// VI (Tiếng Việt · Việt Nam) calculator dictionary — every user-visible string of the shared tool.
//
// ★2026-10-07 신설(vi 계산기 랜딩 · 골격 = app/tr/calculator/dict.ts 10-06 선례 · 뜻 정본 = CALC_DICT_EN).
// 🔴 키워드 실측(2026-10-07 · DFS google_ads/search_volume · location 2704 Vietnam · vi):
//    poker calculator 140 · poker odds calculator 110 · icm poker 110 · poker equity calculator 50 · icm calculator 40 ·
//    texas holdem calculator 10 · tính xác suất poker 10 · 자동완성 = «app tính xác suất poker»·«cách tính xác suất poker»·«phần mềm tính xác suất poker».
//    베트남어 도구 어휘(máy tính poker · tính pot odds · tính equity poker …) = 전부 null.
//    SERP «poker calculator»(VN) top10 = 앱스토어·다운로드 사이트뿐, 베트남어 웹 도구 0.
//    → 머리어 = 영어 «Poker Calculator»(tr·ms와 달리 자국어 머리어가 아니다 — 영어 토큰이 볼륨을 다 가진다) + 베트남어 보조구
//      «máy tính xác suất poker»(그 안에 실측어 «tính xác suất poker»가 그대로 들어 있다 · vi 코퍼스 앵커 texas-holdem-rules-for-beginners.ts:444).
// 용어 = docs/translation-terms-vi.md + lib/posts-vi 코퍼스 실측(10-07): 족보는 hand-rankings 표 형(Mậu Thầu · Một Đôi · Hai Đôi · Sám Cô 21 : Xám 9 ·
//    Sảnh · Thùng · Cù Lũ · Tứ Quý · Thùng Phá Sảnh · Thùng Phá Sảnh Hoàng Gia 10 : Sảnh Thượng 3) · equity 10 · pot odds 12 · outs · stack 49 ·
//    ICM·bubble·payout·shove·call은 tournament-vs-cash-game 글처럼 영어 그대로 · vị trí sớm(EP) · bài tẩy 26 · mù lớn 93.
// 숫자: vi-VN(천단위 «.» · 소수 «,») · 퍼센트는 숫자 뒤 붙여 씀(«81,9%» — 코퍼스 «0,0032%»·«2,60%» 형) → percentPrefix·percentGap 없음. 문체 = bạn.
// 🔴 내부 링크: vi 코퍼스는 8편뿐이고 EN 9슬러그 중 실재 = holdem-tournament-vs-cash-game 하나(+ shortStackLink 대체 = holdem-all-in-rules · tr·fr 선례).
//    quickRef ①~⑤는 link 비움(게이트 F항 · note는 자립 문장으로 끝냈다) · deal.linkLead/link 생략 · /vi/solver·/vi/glossary 없음.
//    related는 /vi/blog/ 슬러그만 받는다(컴포넌트가 /{locale}/blog/{slug}로 만든다) → /vi/hand-chart는 여기 못 넣는다.
import type { CalcDict } from "@/components/calculator/dict";

export const CALC_DICT_VI: CalcDict = {
  numberLocale: "vi-VN",

  seo: {
    title: "Poker Calculator — Máy tính xác suất poker: equity, pot odds",
    description:
      "Poker odds calculator miễn phí, không cần đăng ký: tính xác suất poker, equity giữa các tay bài, pot odds, outs, SPR, M, ICM deal và push/fold — 9 công cụ.",
    path: "/vi/calculator",
  },

  hero: {
    badges: ["Công cụ miễn phí", "Không cần đăng ký"],
    h1: "Poker Calculator",
    h1Sub: "Equity, ICM và pot odds trong một trang",
    lead: "Nhập hai tay bài và xem ai thắng — rồi kiểm tra pot odds, outs, ICM deal, SPR, chỉ số M trong giải đấu và range push/fold. Chín máy tính Hold'em miễn phí, đếm chính xác mọi runout ở những street mà việc đó đủ nhanh.",
    chips: ["🎲 Equity", "🎯 Outs", "💰 Pot Odds", "🃏 Xếp hạng bài", "📊 Bài khởi đầu", "📐 SPR", "🏆 Chỉ số M", "📈 ICM", "⚡ Push/Fold"],
  },

  equity: {
    label: "Equity", sub: "Tay bài vs tay bài",
    hero: "Tay bài của bạn",
    opp: "Đối thủ {n}",
    random: "Tay bài ngẫu nhiên",
    board: "Board",
    pickerHint: "Chọn một ghế hoặc board, rồi chọn lá bài.",
    addPlayer: "+ Thêm đối thủ", removePlayer: "− Bớt đối thủ",
    needTwo: "Mỗi tay bài cần 2 lá (hoặc đặt một đối thủ là tay bài ngẫu nhiên).",
    boardCount: "Để trống board cho preflop, hoặc nhập 3 (flop), 4 (turn) hay 5 (river) lá.",
    th: { player: "Người chơi", hand: "Tay bài", win: "Thắng", tie: "Hòa", equity: "Equity" },
    exactNote: "Chính xác — đã đếm toàn bộ {n} runout có thể.",
    mcNote: "Monte Carlo — {n} runout ngẫu nhiên; kết quả dao động khoảng ±0,3 điểm phần trăm giữa các lần chạy.",
    winner: "{p} thắng với {hand}",
    chop: "Chia pot — {n} tay bài chia đều pot với {hand}",
    showdownNote: "Showdown — board đã đủ, đây là kết quả cuối cùng.",
    presets: [
      { label: "AA vs KK", hands: ["AsAh", "KsKd"] },
      { label: "AKs vs QQ", hands: ["AhKh", "QsQc"] },
      { label: "AKo vs 22", hands: ["AhKd", "2s2c"] },
      { label: "AKo vs AQo", hands: ["AhKd", "AsQc"] },
      { label: "AA vs 87s", hands: ["AsAh", "8d7d"] },
    ],
  },

  tabs: {
    outs: { label: "Outs", sub: "Xác suất draw" },
    pot: { label: "Pot Odds", sub: "Call/fold" },
    hand: { label: "Xếp hạng bài", sub: "Chọn lá bài" },
    starting: { label: "Bài khởi đầu", sub: "Sức mạnh mở bài" },
    spr: { label: "SPR", sub: "Tỷ lệ stack/pot" },
    m: { label: "M giải đấu", sub: "Chỉ số M" },
    icm: { label: "ICM", sub: "Equity tiền thưởng" },
    pushfold: { label: "Push/Fold", sub: "Bảng Nash" },
  },

  workspace: {
    chooseCalculator: "Chọn máy tính",
    resetInputs: "Đặt lại",
    resetAria: "Đặt lại {label}",
    resetMessage: "Đã đặt lại dữ liệu nhập của {label}.",
  },

  cardPicker: {
    clearAll: "Xóa hết",
  },

  outs: {
    drawType: "Loại draw",
    presets: [
      { label: "Tự nhập" },
      { label: "Flush draw", desc: "4 lá cùng chất → cần lá thứ 5 (9 outs, dù có phải nut flush hay không)" },
      { label: "Sảnh hở hai đầu (OESD)", desc: "vd. 5-6-7-8, cần một lá 4 hoặc 9" },
      { label: "Flush + gutshot", desc: "9 flush + 3 gutshot (đã trừ phần trùng)" },
      { label: "Gutshot (sảnh hở giữa)", desc: "vd. 5-6-8-9, chỉ cần một lá 7" },
      { label: "Hai overcard", desc: "2 giá trị cao hơn mọi lá trên board × 3 lá mỗi giá trị — trừ mạnh khi gặp tay đã thành: bắt đôi một overcard vẫn thường thua" },
      { label: "Hai Đôi → Cù Lũ", desc: "vd. A-K trên board A-K-x → còn 2 lá A + 2 lá K" },
      { label: "Một Đôi → Sám Cô", desc: "còn 2 lá cùng giá trị" },
      { label: "Flush + OESD (quái vật)", desc: "9 flush + 8 sảnh (2 lá trùng)" },
    ],
    outsSuffix: " ({n} outs)",
    street: "Street",
    afterFlopBtn: "🃏 Flop → river",
    afterTurnBtn: "🔄 Turn → river",
    flopOneBtn: "🎯 Flop → turn",
    afterFlopOne: "Flop → turn",
    chanceFlopOne: "Xác suất trúng ở lá kế tiếp sau flop",
    outsCount: "Số outs: {v}",
    afterFlop: "Flop → river",
    afterTurn: "Turn → river",
    ruleOf4: "Quy tắc 4",
    ruleOf2: "Quy tắc 2",
    chanceFlop: "Xác suất hoàn thành draw từ flop đến river (cả hai lá — khi all-in)",
    chanceTurn: "Xác suất hoàn thành draw ở river, tính từ turn",
    exact: " (chính xác)",
    ruleMental: "Quy tắc {n} (tính nhẩm):",
    exactNote: "Con số in chữ lớn là giá trị chính xác",
    verdict: { great: "Rất tốt 🔥", good: "Tốt ✅", fair: "Tạm được ⚠️", poor: "Yếu ❌", veryPoor: "Rất yếu 💀" },
  },

  pot: {
    potSize: "Kích thước pot (gồm cả mức bet bạn đang đối mặt)",
    callAmount: "Số tiền bạn cần call",
    potOddsCaption: "Pot odds (equity tối thiểu cần có)",
    orHigher: "— equity cao hơn mức này thì call có lãi",
    equityLabel: "Equity của tay bài: {v}",
    sliderGutshot: "Gutshot (turn) 8,7%",
    sliderFlush: "Flush (turn) 19,6%",
    impliedToggle: "Implied odds {toggle}",
    close: "Đóng ▲",
    add: "Thêm ▼",
    extraWinnings: "Tiền thắng thêm dự kiến (nếu trúng draw): {v}",
    none: "Không",
    impliedCaption: "Implied odds (tính cả tiền thắng thêm)",
    impliedNote: "Equity tối thiểu cần có, tính thêm {n}",
    needImplied: "implied odds {n}%",
    needPot: "pot odds {n}%",
    verdict: {
      call: { title: "Theo (call) — có lãi", body: "Equity của bạn {eq}% > {need} → có lãi về lâu dài" },
      even: { title: "Hòa vốn (EV 0)", body: "Equity của bạn {eq}% = {need} → call không lời cũng không lỗ. Hãy quyết định dựa trên những yếu tố ngoài pot odds, như vị trí và lối chơi của đối thủ" },
      fold: { title: "Nên bỏ bài (fold)", body: "Equity của bạn {eq}% < {need} → lỗ về lâu dài" },
    },
  },

  handEval: {
    pickerLabel: "Chọn lá bài (5–7)",
    emptyTitle: "Chọn từ 5 lá trở lên để đánh giá tay bài",
    emptyHint: "Với 7 lá, tổ hợp 5 lá tốt nhất được tìm tự động",
    bestFrom: "Tay bài tốt nhất từ {n} lá",
    rankNames: [
      "Mậu Thầu", "Một Đôi", "Hai Đôi", "Sám Cô", "Sảnh",
      "Thùng", "Cù Lũ", "Tứ Quý", "Thùng Phá Sảnh", "Thùng Phá Sảnh Hoàng Gia",
    ],
    resultNames: [
      "Mậu Thầu 🃏", "Một Đôi 1️⃣", "Hai Đôi ✌️", "Sám Cô 3️⃣", "Sảnh ➡️",
      "Thùng 🌊", "Cù Lũ 🏠", "Tứ Quý 💎", "Thùng Phá Sảnh 🌟", "Thùng Phá Sảnh Hoàng Gia 👑",
    ],
    axis: ["Mậu Thầu", "Một Đôi", "Thùng", "Tứ Quý", "Royal"],
  },

  starting: {
    pickerLabel: "Chọn 2 lá bài tẩy của bạn",
    emptyPrompt: "Chọn 2 lá bài tẩy của bạn",
    // 폴백 3분기 = EN 09-20 정본(tr·ms 판과 같은 경계): suited — first-in BTN 전부 · CO는 K suited · 둘 다 8 이상 · 54s까지 connector /
    //   offsuit — BTN만, 에이스 아무거나 또는 둘 다 9 이상 / 나머지 fold. 한정어(first-in · suited · BTN만)를 빠뜨리지 마라(브리프 §3-L).
    unknownDesc: "Không có trong bảng mở bài cơ bản",
    unknownAction: "Suited: khi mọi người đã fold đến lượt bạn, từ BTN hãy mở mọi tay suited; từ CO chỉ giữ K suited, hai lá đều từ 8 trở lên (Q8s, 10-8s) và connector đến 54s. Offsuit: chỉ ở BTN — mọi lá A (A9o, A5o), hoặc hai lá đều từ 9 trở lên (K9o, 10-9o). Còn lại (J2o, 93o, 72o): fold",
    tierNames: ["🥇 Tier 1 — Premium", "🥈 Tier 2 — Mạnh", "🥉 Tier 3 — Chơi được", "⚠️ Tier 4 — Cận biên", "🚫 Tier 5 — Yếu"],
    recommendedAction: "Hành động khuyến nghị:",
    axis: ["Premium", "Mạnh", "Chơi được", "Cận biên", "Yếu"],
    summaryTitle: "Tóm tắt các tier",
    summary: [
      { hands: "AA KK QQ JJ 10-10 AKs AKo", action: "Luôn raise" },
      { hands: "AQs AJs A10s KQs KJs 99 88 AQo", action: "Raise ở hầu hết vị trí" },
      { hands: "AJo KQo K10s Q10s QJs J10s 10-9s 77 A9s K9s Q9s J9s", action: "Raise ở vị trí muộn" },
      { hands: "66–22 A8s–A2s KJo QJo A10o–J10o 98s–54s", action: "Chọn lọc ở vị trí muộn" },
      { hands: "các tay offsuit yếu (J2o, 93o, 72o)", action: "Thường fold" },
    ],
    // «오픈 림프로 읽히는 자리» = 선례 로케일과 같은 형(무엇에 대한 call인지 명시 + 오픈 림프 금지) — 브리프 §3-L.
    //   LP = vị trí muộn · EP = vị trí sớm(코퍼스 «vị trí sớm») · first in = 아무도 팟에 안 들어온 상태에서 처음 들어감.
    hands: {
      AA: { desc: "Tay bài mạnh nhất. Raise ở mọi tình huống", action: "Luôn raise/re-raise (3-bet)" },
      KK: { desc: "Chỉ cần dè chừng lá A trên flop", action: "Luôn raise/re-raise" },
      QQ: { desc: "Mạnh hơn JJ, nhưng đừng đánh giá quá cao", action: "Luôn raise; cẩn thận khi stack sâu" },
      JJ: { desc: "Dè chừng overcard trên flop", action: "Raise từ mọi vị trí" },
      "1010": { desc: "Mất giá khi flop ra overcard", action: "Raise từ mọi vị trí — đừng open-limp" },
      AKs: { desc: "Tay draw tốt nhất. Hãy làm pot to lên", action: "Luôn raise/re-raise" },
      AKo: { desc: "Yếu hơn AKs nhưng vẫn là premium", action: "Luôn raise; có thể call một lần re-raise" },
      AQs: { desc: "Tay bài mạnh; giá trị hơn khi có vị trí", action: "Raise từ hầu hết vị trí" },
      AJs: { desc: "Rất tốt ở BTN/CO, yếu từ UTG", action: "Raise ở vị trí giữa/muộn; từ UTG thì raise hoặc fold — không bao giờ limp" },
      A10s: { desc: "Một trong những lá A suited tốt nhất", action: "Raise ở vị trí giữa/muộn; từ UTG thì raise hoặc fold — không bao giờ limp" },
      KQs: { desc: "Tiềm năng ra Thùng cao + draw Sảnh", action: "Raise từ hầu hết vị trí" },
      KJs: { desc: "Tay draw mạnh", action: "Raise ở vị trí muộn; từ vị trí sớm thì raise hoặc fold — không bao giờ limp" },
      "99": { desc: "Đôi trung bình, dè chừng flop có overcard", action: "Raise ở hầu hết vị trí; cẩn thận khi stack sâu" },
      "88": { desc: "Pocket pair có tiềm năng ra set tốt", action: "Raise ở hầu hết vị trí; call một lần raise — không bao giờ open-limp" },
      AQo: { desc: "Offsuit yếu hơn; vị trí rất quan trọng", action: "Raise ở vị trí giữa/muộn; từ UTG thì raise hoặc fold — không bao giờ limp" },
      AJo: { desc: "Yếu ở vị trí sớm, mạnh ở vị trí muộn", action: "Raise ở CO/BTN, cẩn thận ở vị trí sớm" },
      KQo: { desc: "Connector offsuit tốt nhất", action: "Raise ở vị trí muộn; ở vị trí sớm, raise hoặc fold khi chưa ai vào pot, và thường fold khi gặp raise" },
      K10s: { desc: "K suited, mạnh ở vị trí muộn", action: "Raise ở vị trí muộn, fold ở vị trí sớm" },
      QJs: { desc: "Draw mạnh theo cả hai hướng (Sảnh và Thùng)", action: "Raise ở vị trí muộn, giá trị hơn khi stack sâu" },
      J10s: { desc: "Một trong những suited connector tốt nhất", action: "Raise ở vị trí muộn; call một lần raise khi có vị trí" },
      "109s": { desc: "Suited connector mạnh", action: "Raise first in từ vị trí muộn; call một lần raise khi có vị trí" },
      "77": { desc: "Tay đi tìm set, dè chừng overcard", action: "Raise ở vị trí muộn; ở vị trí sớm thì call một lần raise, còn khi first in thì raise hoặc fold — không bao giờ open-limp" },
      A9s: { desc: "A suited có tiềm năng Thùng", action: "Raise ở vị trí muộn" },
      K9s: { desc: "K suited; đôi K có thể bị dominate", action: "Open-raise từ CO/BTN khi mọi người trước bạn đã fold; khi gặp raise, cân nhắc vị trí, giá call và effective stack" },
      Q9s: { desc: "Q suited có tiềm năng Sảnh; dè chừng các lá Q mạnh hơn", action: "Open-raise từ CO/BTN khi mọi người trước bạn đã fold; khi gặp raise, cân nhắc vị trí, giá call và effective stack" },
      J9s: { desc: "Suited one-gapper có tiềm năng Sảnh và Thùng", action: "Open-raise từ CO/BTN khi mọi người trước bạn đã fold; khi gặp raise, cân nhắc vị trí, giá call và effective stack" },
      "66": { desc: "Đi tìm set — cần implied odds", action: "Raise first in từ vị trí muộn; call một lần raise khi cả bạn lẫn người raise đều còn phía sau ít nhất ~15 lần số tiền call" },
      "55": { desc: "Ít giá trị nếu không ra set", action: "Raise first in từ vị trí muộn; ở vị trí muộn, call một lần raise khi cả bạn lẫn người raise đều còn phía sau ít nhất ~15 lần số tiền call" },
      A8s: { desc: "A suited tầm trung", action: "Chơi ở vị trí muộn, fold ở vị trí sớm" },
      A7s: { desc: "A suited tầm trung", action: "Chỉ chơi ở vị trí muộn" },
      A6s: { desc: "A suited tầm trung", action: "Chỉ chơi ở vị trí muộn" },
      A5s: { desc: "Giá trị wheel + chặn lá A; lựa chọn 3-bet bluff được ưa chuộng", action: "Chỉ ở vị trí muộn; implied odds rất quan trọng" },
      A4s: { desc: "A suited có draw wheel", action: "Chỉ ở vị trí muộn" },
      A3s: { desc: "Nut flush draw kèm lá wheel, nhỉnh hơn A2s một bậc", action: "Chỉ ở vị trí muộn" },
      A2s: { desc: "Wheel + nut flush, nhưng yếu", action: "Chỉ ở vị trí muộn" },
      KJo: { desc: "Rủi ro bị dominate; chỉ ở vị trí muộn", action: "Raise ở CO/BTN, fold khi gặp re-raise" },
      QJo: { desc: "Độ liên kết vừa phải; cần vị trí", action: "Chỉ ở vị trí muộn" },
      "98s": { desc: "Suited connector mạnh", action: "Raise first in từ vị trí muộn; call một lần raise khi có vị trí" },
      "87s": { desc: "Suited connector tốt", action: "Raise first in từ vị trí muộn; call một lần raise khi có vị trí" },
      "76s": { desc: "Suited connector", action: "Raise first in từ vị trí muộn; chỉ call raise khi có vị trí và stack sâu" },
      "44": { desc: "Gần như vô giá trị nếu không ra set", action: "Raise first in từ vị trí muộn; ở vị trí muộn, call một lần raise khi cả bạn lẫn người raise đều còn phía sau ít nhất ~15 lần số tiền call" },
      "33": { desc: "Phải đi tìm set; mang tính đầu cơ", action: "Raise first in từ vị trí muộn; ngoài ra chỉ chơi pot nhiều người với stack sâu" },
      "22": { desc: "Pocket pair thấp nhất", action: "Raise first in từ vị trí muộn; ngoài ra chỉ chơi pot nhiều người với stack sâu" },
      K10o: { desc: "K-10 offsuit, yếu", action: "Open-raise từ CO/BTN khi mọi người trước bạn đã fold" },
      Q10o: { desc: "Offsuit liên kết kém", action: "Chỉ ở BTN" },
      J10o: { desc: "Offsuit khá nhưng dễ bị tấn công", action: "Chỉ ở BTN" },
      Q10s: { desc: "Suited broadway mạnh, chơi tốt khi có vị trí", action: "Raise ở vị trí muộn; fold từ vị trí sớm" },
      A10o: { desc: "A offsuit cận biên, dễ bị dominate", action: "Chỉ ở vị trí muộn" },
      "65s": { desc: "Suited connector; cần pot nhiều người/implied odds", action: "Raise first in từ vị trí muộn; chỉ call raise khi có vị trí và stack sâu" },
      "54s": { desc: "Suited connector thấp; mang tính đầu cơ", action: "Raise first in từ vị trí muộn; chỉ call raise khi có vị trí, trong pot nhiều người giá rẻ" },
    },
  },

  spr: {
    effectiveStack: "Effective stack (stack ngắn hơn trong hai stack)",
    potSize: "Kích thước pot hiện tại",
    caption: "SPR (Stack-to-Pot Ratio)",
    stackDivPot: "stack ÷ pot",
    zones: {
      low: {
        label: "SPR thấp (đã cam kết)",
        desc: "Một phần lớn stack đã nằm trong pot. Với top pair top kicker trở lên trên flop khô, hãy lên kế hoạch đưa nốt phần còn lại vào — ở độ sâu này, fold thường là sai lầm lớn hơn. Trên board có đôi, có ba lá cùng chất hoặc ba lá liên tiếp, hay khi gặp hành động mà chỉ set hoặc Sảnh mới làm, một đôi vẫn chỉ là một đôi.",
        actions: [["TPTK+", "Cân nhắc all-in"], ["Draw", "Bắt buộc tính pot odds"], ["Tay yếu", "Fold thận trọng"]],
      },
      mid: {
        label: "SPR trung bình (linh hoạt)",
        desc: "Đây là vùng để chơi các tay mạnh như Hai Đôi trở lên. Bảo vệ stack trở nên quan trọng.",
        actions: [["Hai Đôi+", "Value bet"], ["Một đôi", "Một hai street, rồi kiểm soát pot"], ["Draw", "Semi-bluff khi có fold equity; không có thì bỏ"]],
      },
      high: {
        label: "SPR cao (đang sâu dần)",
        desc: "Stack đang sâu dần. Giá trị tương đối của draw và tay mạnh đã thành tăng lên.",
        actions: [["Set+", "Chơi mạnh"], ["Draw", "Implied odds tăng"], ["Một đôi/TPTK", "Tiếp tục thận trọng"]],
      },
      deep: {
        label: "SPR rất cao (sâu)",
        desc: "Đây là ván deep stack. Vị trí, tiềm năng draw và khả năng đọc range đối thủ rất quan trọng.",
        actions: [["Tay nuts", "Có thể bet lớn"], ["Draw", "Implied odds rất cao"], ["Tay đã thành yếu", "Cẩn thận, dễ bị bluff"]],
      },
    },
    legend: ["Đã cam kết", "Linh hoạt", "Sâu dần", "Sâu"],
  },

  m: {
    inputs: { stack: "Stack của bạn", bb: "Mù lớn (BB)", sb: "Mù nhỏ (SB)", ante: "Ante" },
    players: "Số người ở bàn: {v}",
    headsUp: "2 (heads-up)",
    orbitCaption: "Chi phí một vòng (tổng mù trả trong một vòng)",
    orbitFormula: "BB {bb} + SB {sb} + ante {ante}×{players}",
    mCaption: "Chỉ số M (M của Harrington)",
    zones: {
      dead: { name: "💀 Vùng chết", desc: "Fold equity đã hết — all-in là nước đi duy nhất, nên hãy shove tay tốt nhất bạn thấy trước khi mù đến lượt bạn, và ưu tiên pot chưa ai mở.", action: "All-in ngay" },
      red: { name: "🔴 Vùng đỏ", desc: "Bạn cần double up sớm. Chuyển sang chiến lược push/fold — shove tay tốt, fold phần còn lại.", action: "Push/fold" },
      orange: { name: "🟠 Vùng cam", desc: "Stack đang cạn dần. Thu hẹp range chỉ còn tay mạnh và tìm cơ hội open-shove.", action: "Range chặt" },
      yellow: { name: "🟡 Vùng vàng", desc: "Áp lực đã bắt đầu. Bạn cần chủ động gom chip — chơi hung hãn khi có spot tốt.", action: "Chơi hung hãn" },
      green: { name: "🟢 Vùng xanh", desc: "Stack của bạn thoải mái. Dùng đầy đủ chiến lược — tăng stack bằng lối chơi theo vị trí và bluff.", action: "Chiến lược đầy đủ" },
    },
  },

  icm: {
    introStrong: "ICM (Independent Chip Model)",
    introRest: " quy đổi stack trong giải đấu thành tiền thưởng kỳ vọng theo ICM. Với quyết định call hay fold, hãy nhân giá trị của bạn sau mỗi kết quả có thể (thắng, hòa hoặc thua) với xác suất thực của nó, rồi so tổng đó với giá trị sau khi fold. Bị loại không tự động bằng 0 mà bằng đúng số tiền thưởng thực nhận.",
    numPlayers: "Số người chơi",
    paidPlaces: "Số hạng được trả thưởng",
    stacksTitle: "Stack chip của người chơi",
    total: "tổng {n}",
    decStack: "Giảm stack của người chơi {n}",
    stackInput: "Stack chip của người chơi {n}",
    incStack: "Tăng stack của người chơi {n}",
    prizesTitle: "Tiền thưởng",
    decPrize: "Giảm tiền thưởng hạng {n}",
    prizeInput: "Tiền thưởng hạng {n}",
    incPrize: "Tăng tiền thưởng hạng {n}",
    currencyNote: "Nhập tiền thưởng theo bất kỳ đơn vị tiền tệ nào.",
    resultTitle: "Kết quả ICM",
    th: { player: "Người chơi", chips: "Chip", chipPct: "Chip %", icmValue: "Giá trị ICM", icmPct: "ICM %", diff: "Chênh lệch", chop: "Chip chop" },
    playerCell: "{medal} P{n}",
    diffPlus: "+chênh lệch",
    diffPlusNote: "Theo ICM, phần của bạn trong quỹ thưởng cao hơn phần chip của bạn. Chỉ dấu của chênh lệch thì không cho biết nên call hay fold.",
    diffMinus: "−chênh lệch",
    diffMinusNote: "Theo ICM, phần của bạn trong quỹ thưởng thấp hơn phần chip của bạn. Chỉ dấu của chênh lệch thì không cho biết lối chơi hung hãn có lãi hay không.",
    diffUnit: "điểm",
    empty: "Dùng stack và tiền thưởng dương, xếp tiền thưởng từ cao xuống thấp (được phép bằng nhau).",
  },

  pushfold: {
    ante: "Ante",
    noAnte: "Không ante",
    bbAnteOn: "BB ante BẬT",
    table: "Bàn",
    headsUp: "Heads-Up",
    sixMax: "6-max",
    nineMax: "9-max",
    scenario: "Tình huống",
    sbShove: "SB: shove hoặc fold",
    bbCall: "BB: call khi bị shove",
    position: "Vị trí {hint}",
    firstInHint: "(first-in — mọi người đã fold đến bạn)",
    effectiveStack: "Effective stack: {v}",
    captionHuPush: "Các tay SB shove ở {stack}bb",
    captionHuCall: "Các tay BB call shove ở {stack}bb",
    captionMw: "Shove first-in từ {pos} ở bàn {table}-max, {stack}bb",
    withAnte: " (có ante)",
    combosSuffix: " / {total} combo",
    legendPush: "Push (all-in)",
    legendCall: "Call",
    legendFold: "Fold",
    note: {
      strong1: "Đường chéo = đôi · phía trên bên phải = suited · phía dưới bên trái = offsuit",
      p1: "Bảng được sắp theo ",
      strong2: "giá trị lá bài (rank), không theo sức mạnh",
      p2: ", nên trong một hàng các ô được tô và không tô xen kẽ nhau là bình thường — AQo, KQo và QQ nằm cạnh nhau nhưng không theo thứ tự sức mạnh. A5s có mặt còn A6s thì không cũng là đúng: A5s có thể tạo",
      strong3: "Sảnh wheel (A-2-3-4-5)",
      p3: ", bù lại cho kicker thấp hơn.",
    },
    cellTitle: "{hand} — {action}",
    cell: { push: "push", call: "call", fold: "fold" },
    huNote: {
      strong: "Cân bằng Nash, heads-up (SB vs BB)",
      p1: ": giả định SB chỉ shove hoặc fold. Tùy chọn ante cộng thêm 0,125bb mỗi người (12,5% big blind mỗi người — đúng bằng mức big blind ante quy ra mỗi người ở bàn 8 người; heads-up thì tổng cộng chỉ 0,25bb). Stack càng ngắn, range càng rộng — và dưới ~3-4bb, BB call ",
      em: "rộng hơn",
      p2: " range shove của SB là đúng, vì pot odds.",
    },
    mwNote: {
      strong: "Bảng shove first-in {table}-max",
      p1: ": mọi người phía trước đã fold và bạn chỉ shove hoặc fold. Đây là cân bằng kiểu Nash ",
      strong2: "thuần chip-EV",
      p2: " — range call của những người phía sau được giải đồng thời — và dùng giả định chuẩn rằng pot bị call được phân định heads-up với người call đầu tiên (bỏ qua pot có nhiều người call). Range rộng ra khi phía sau bạn còn ít người hơn (UTG → BTN → SB), khi stack ngắn hơn và khi BẬT ante (0,125bb mỗi người). Vì là thuần chip-EV, range 10bb ở vị trí sớm (UTG/MP) chặt hơn các quy tắc kinh nghiệm phổ biến (khi không có ante, đôi nhỏ thì fold) — thực tế hãy điều chỉnh theo ICM và đối thủ.",
    },
    // 🔴 vi에는 holdem-short-stack 글이 없다 → tr·fr 선례대로 all-in 규칙 글로(shortStackLink는 필수 키).
    readMore: "Để hiểu việc đẩy cả stack vào giữa và pot phụ vận hành ra sao, hãy đọc",
    shortStackLink: { slug: "holdem-all-in-rules", text: "luật all-in và pot phụ (side pot)" },
    readMoreEnd: ".",
  },

  icmGuide: {
    bubble: {
      badge: "Hướng dẫn ICM",
      h2: "Cách dùng máy tính ICM — ví dụ bubble trong 3 phút",
      intro: "Giả sử còn bốn người và ba người được trả thưởng (bubble). Stack là 60.000 / 40.000 / 30.000 / 20.000, tiền thưởng $500 / $300 / $200. Nhập các số này vào máy tính, bạn sẽ thấy phần chip của mỗi người đặt cạnh giá trị tiền thưởng thực (ICM):",
      th: { player: "Người chơi", chipPct: "Chip %", icmPct: "ICM %", diff: "Chênh lệch" },
      rows: [
        { player: "🥇 Chip leader", chip: "40,0%", icm: "33,3%", diff: "-6,7 điểm", up: false },
        { player: "🥈 Thứ 2", chip: "26,7%", icm: "27,2%", diff: "+0,6 điểm", up: true },
        { player: "🥉 Thứ 3", chip: "20,0%", icm: "22,9%", diff: "+2,9 điểm", up: true },
        { player: "Thứ 4 (short stack)", chip: "13,3%", icm: "16,6%", diff: "+3,3 điểm", up: true },
      ],
      keyPoint: {
        text: "Bảng cho thấy {b1}, chênh 6,7 điểm phần trăm; đây không phải ngưỡng call/fold. Stack trung bình thường chịu risk premium lớn nhất, nên chip leader — người có stack lớn hơn (cover được) họ — có thể {b2} khi range cho phép. Short stack nên {b3}. Quyết định phụ thuộc vào stack, cơ cấu trả thưởng và đối thủ, chứ không chỉ vào dấu của chênh lệch.",
        b1: "giá trị ICM của chip leader (33,3%) thấp hơn phần chip của họ (40%)",
        b2: "gây áp lực lên các stack trung bình",
        b3: "chọn lựa kỹ khi call, trừ những stack sắp bị mù ăn hết",
      },
    },
    deal: {
      // 수치 = scripts/calc-icm-example.ts 출력 = EN 그대로(§13). 🔴 vi에 holdem-icm 글이 없어 linkLead/link 생략(tr·fr 선례 · 게이트 F항).
      badge: "Máy tính ICM deal",
      h2: "Máy tính ICM deal — một deal ở final table thực sự đáng bao nhiêu",
      intro: "Còn bốn người và đang bàn chuyện deal. Stack là 450.000 / 250.000 / 180.000 / 120.000 (45% / 25% / 18% / 12%), còn lại $2.300 tiền thưởng, trả $1.000 / $600 / $400 / $300. Nhập các số này vào máy tính ICM ở trên, cột Chip chop sẽ đặt hai con số cạnh nhau:",
      th: { player: "Người chơi", chop: "Chip chop", icm: "ICM deal", diff: "Chênh lệch" },
      rows: [
        { player: "🥇 Chip leader (45%)", chop: "$1.035", icm: "$726", diff: "-$309", up: false },
        { player: "🥈 Thứ 2 (25%)", chop: "$575", icm: "$591", diff: "+$16", up: true },
        { player: "🥉 Thứ 3 (18%)", chop: "$414", icm: "$526", diff: "+$112", up: true },
        { player: "Thứ 4 (12%)", chop: "$276", icm: "$458", diff: "+$182", up: true },
      ],
      summary: {
        text: "Chip chop thô chia theo phần chip và {b1}; ICM deal phản ánh khả năng về đích ở từng hạng của mỗi người và {b2}. Ở ví dụ trên, stack ngắn nhất nhận $276 nếu chia theo chip nhưng $458 theo ICM — {b3}. Hãy tính cả hai con số trước khi thương lượng. Thứ mà các phòng chơi gọi là chip chop thường là save-and-chop — trước hết mọi người được trả mức thưởng kế tiếp (ở đây là $300 của hạng 4), chỉ phần còn lại mới chia theo chip — và cách này cho kết quả gần ICM, chứ không phải kiểu chia thô mà cột này hiển thị. Ngoài ra ICM giả định mọi người ngang tài và bỏ qua việc ai phải đặt mù kế tiếp, nên hãy lường trước việc người có stack lớn sẽ đòi phần chia cao hơn con số ICM của họ.",
        b1: "có lợi cho chip leader",
        b2: "công bằng hơn với short stack",
        b3: "nhiều hơn $182",
      },
    },
  },

  // 빠른 참조 6표 — 🔴 모든 값 = scripts/calc-reference-tables.ts 출력(EN 그대로 · §13) · 구분자만 베트남식 · 퍼센트 기호 뒤.
  //   🔴 link는 lib/posts-vi/에 «실재하는» 슬러그만(게이트 F항) → ①~⑤ 비움, ⑥ tournament-vs-cash-game.
  //   link를 비운 표의 note는 미완 문장으로 끝나면 안 된다 — 자립 문장으로 끝냈다(EN의 «… is in» 꼬리 삭제).
  quickRef: [
    {
      badge: "Tra cứu nhanh",
      h2: "Bảng equity tham khảo — các cặp đối đầu all-in preflop",
      intro: "Equity khi hai tay bài all-in preflop, lấy trung bình trên mọi tổ hợp chất của cặp đối đầu đó (tính sẵn ngoại tuyến: toàn bộ 1.712.304 board cho mỗi tổ hợp). Một tổ hợp chất cụ thể có thể lệch hơn hai điểm phần trăm (A♠K♠ vs Q♠J♠: 66,0%) — hãy nhập đúng lá bài vào máy tính equity ở trên.",
      th: ["Cặp đối đầu", "Tay A", "Tay B", "Hòa"],
      align: ["left", "right", "right", "right"],
      emphasis: 1,
      nowrap: [1, 2, 3],
      rows: [
        ["AA vs KK", "81,9%", "18,1%", "0,5%"],
        ["AA vs AKs", "87,9%", "12,1%", "1,3%"],
        ["AA vs 87s", "77,5%", "22,5%", "0,3%"],
        ["AA vs 72o", "88,2%", "11,8%", "0,4%"],
        ["KK vs AKs", "65,9%", "34,1%", "0,8%"],
        ["QQ vs AKo", "56,8%", "43,2%", "0,4%"],
        ["QQ vs AKs", "54,0%", "46,0%", "0,4%"],
        ["JJ vs TT", "82,0%", "18,0%", "0,4%"],
        ["TT vs A9o", "72,2%", "27,8%", "0,4%"],
        ["TT vs 87s", "80,3%", "19,7%", "0,5%"],
        ["22 vs AKo", "52,6%", "47,4%", "0,6%"],
        ["AKo vs AQo", "74,4%", "25,6%", "4,7%"],
        ["AKs vs QJs", "63,5%", "36,5%", "0,5%"],
        ["AKo vs JTs", "59,5%", "40,5%", "0,5%"],
      ],
      note: "Equity là phần pot trung bình của bạn, tính cả các lần hòa (chia pot). Một đôi gặp hai overcard là thế coin flip kinh điển; một đôi gặp đôi cao hơn là cửa dưới với tỷ lệ khoảng 4,5 : 1.",
    },
    {
      badge: "Tra cứu nhanh",
      h2: "Đôi A gặp tay bài ngẫu nhiên — theo số đối thủ",
      intro: "Tần suất AA thắng khi mọi người all-in preflop với N tay bài ngẫu nhiên (Monte Carlo, 8.000.000 runout mỗi hàng). Hai người call đầu tiên mỗi người lấy đi của đôi A khoảng 10 điểm phần trăm; sau đó mỗi người lấy đi ít hơn.",
      th: ["Đối thủ", "Equity của AA"],
      align: ["left", "right"],
      emphasis: 1,
      nowrap: [1],
      rows: [
        ["1", "85,2%"], ["2", "73,4%"], ["3", "63,8%"], ["4", "55,9%"],
        ["5", "49,2%"], ["6", "43,6%"], ["7", "38,7%"], ["8", "34,6%"],
      ],
      note: "Đó là lý do đôi A muốn pot heads-up: trước năm tay bài ngẫu nhiên, tay khởi đầu mạnh nhất của Hold'em không còn là cửa trên để thắng pot (49,2%, năm người kia chia phần còn lại). Đặt một đối thủ thành “Tay bài ngẫu nhiên” trong máy tính equity để thử bất kỳ tay nào theo cách tương tự (tối đa ba đối thủ).",
    },
    {
      badge: "Tra cứu nhanh",
      h2: "Bảng outs tham khảo — xác suất draw theo số outs",
      intro: "Xác suất draw hoàn thành: flop → river (còn hai lá), flop → turn (chỉ lá kế tiếp) và turn → river (một lá) — giá trị chính xác, đặt cạnh ước lượng của quy tắc 4 và 2. Đếm outs trước, rồi đọc theo hàng ngang.",
      th: ["Outs", "Draw điển hình", "Flop → river", "Flop → turn", "Turn → river", "Quy tắc 4 · 2"],
      align: ["left", "left", "right", "right", "right", "right"],
      emphasis: 2,
      nowrap: [2, 3, 4, 5],
      rows: [
        ["1", "–", "4,3%", "2,1%", "2,2%", "4% · 2%"],
        ["2", "Pocket pair → set", "8,4%", "4,3%", "4,3%", "8% · 4%"],
        ["3", "Một overcard", "12,5%", "6,4%", "6,5%", "12% · 6%"],
        ["4", "Gutshot", "16,5%", "8,5%", "8,7%", "16% · 8%"],
        ["5", "Một Đôi → Hai Đôi hoặc Sám Cô", "20,4%", "10,6%", "10,9%", "20% · 10%"],
        ["6", "Hai overcard", "24,1%", "12,8%", "13,0%", "24% · 12%"],
        ["7", "–", "27,8%", "14,9%", "15,2%", "28% · 14%"],
        ["8", "Sảnh hở hai đầu", "31,5%", "17,0%", "17,4%", "32% · 16%"],
        ["9", "Flush draw", "35,0%", "19,1%", "19,6%", "36% · 18%"],
        ["10", "Gutshot + hai overcard", "38,4%", "21,3%", "21,7%", "40% · 20%"],
        ["11", "Hở hai đầu + một overcard", "41,7%", "23,4%", "23,9%", "44% · 22%"],
        ["12", "Flush draw + gutshot", "45,0%", "25,5%", "26,1%", "48% · 24%"],
        ["13", "–", "48,1%", "27,7%", "28,3%", "52% · 26%"],
        ["14", "Hở hai đầu + hai overcard", "51,2%", "29,8%", "30,4%", "56% · 28%"],
        ["15", "Flush draw + hở hai đầu", "54,1%", "31,9%", "32,6%", "60% · 30%"],
        ["16", "–", "57,0%", "34,0%", "34,8%", "64% · 32%"],
        ["17", "–", "59,8%", "36,2%", "37,0%", "68% · 34%"],
        ["18", "–", "62,4%", "38,3%", "39,1%", "72% · 36%"],
        ["19", "–", "65,0%", "40,4%", "41,3%", "76% · 38%"],
        ["20", "–", "67,5%", "42,6%", "43,5%", "80% · 40%"],
      ],
      note: "Con số hai lá chỉ đúng khi bạn được xem cả hai lá mà không phải trả thêm (all-in). Khi gặp một lần bet ở flop, hãy dùng cột flop → turn: 9 outs = 19,1%. Overcard là loại outs kém tin cậy nhất — trước một tay đã thành, bắt đôi một overcard vẫn thường thua, nên hãy trừ bớt giá trị của chúng.",
    },
    {
      badge: "Tra cứu nhanh",
      h2: "Bảng pot odds tham khảo — equity cần có để call",
      intro: "Khi gặp một mức bet cỡ này vào pot, đây là equity tối thiểu để call hòa vốn: call ÷ (pot sau bet + call). Hiển thị theo hai cách — dạng tỷ lệ và dạng equity tương ứng; máy tính trả về dạng equity. Hãy so với xác suất chính xác của draw trong bảng outs ở trên.",
      th: ["Mức bet", "Tỷ lệ (X : 1)", "Equity cần có"],
      align: ["left", "right", "right"],
      emphasis: 2,
      nowrap: [1, 2],
      rows: [
        ["¼ pot", "5 : 1", "16,7%"],
        ["⅓ pot", "4 : 1", "20,0%"],
        ["½ pot", "3 : 1", "25,0%"],
        ["⅔ pot", "2,5 : 1", "28,6%"],
        ["¾ pot", "2,33 : 1", "30,0%"],
        ["Pot", "2 : 1", "33,3%"],
        ["1,5× pot", "1,67 : 1", "37,5%"],
        ["2× pot", "1,5 : 1", "40,0%"],
        ["3× pot", "1,33 : 1", "42,9%"],
      ],
      note: "Một flush draw (35,0% khi còn hai lá, 19,1% ở lá kế tiếp) chỉ call được mức bet bằng pot ở flop khi đó là all-in. Nếu không, máy tính implied odds — nút bật trong tab pot odds — sẽ cộng thêm số tiền bạn kỳ vọng thắng về sau, với điều kiện đối thủ còn chip phía sau và có tay bài chịu trả tiền; hãy trừ mạnh khi bạn không draw tới nuts.",
    },
    {
      badge: "Tra cứu nhanh",
      h2: "Bảng SPR tham khảo — cần tay bài mạnh đến đâu",
      intro: "SPR = effective stack ÷ pot hiện tại, trong đó effective stack là stack ngắn hơn trong hai stack — toàn bộ số chip mà mỗi người có thể thắng hoặc thua. SPR càng thấp, phần stack đã đưa vào pot càng lớn và bạn có thể đẩy hết stack với tay yếu hơn; SPR càng cao, bạn càng cần tay bài gần nuts mới nên chơi pot lớn. Hãy đọc các vùng này như kế hoạch ở flop: trên board ướt hoặc có đôi, một đôi vẫn chỉ là một đôi.",
      th: ["SPR", "Vùng", "Sức mạnh tay bài · hành động"],
      align: ["left", "left", "left"],
      emphasis: 1,
      rows: [
        ["SPR < 4", "Đã cam kết", "Top pair top kicker trở lên trên flop khô: lên kế hoạch đẩy hết vào — ở độ sâu này, fold thường là sai lầm lớn hơn"],
        ["4 ≤ SPR < 8", "Linh hoạt", "Hai Đôi trở lên để lấy value; một đôi chơi một hai street, rồi kiểm soát pot"],
        ["8 ≤ SPR < 15", "Sâu dần", "Set trở lên chơi để lấy cả stack; draw có thêm implied odds"],
        ["SPR ≥ 15", "Sâu", "Pot lớn chỉ với tay cỡ nuts — tay đã thành yếu là mục tiêu bị bluff"],
      ],
      note: "Máy tính SPR ở trên quy đổi bất kỳ stack và pot nào về một trong bốn vùng này.",
    },
    {
      badge: "Tra cứu nhanh",
      h2: "Máy tính chỉ số M — năm vùng trong giải đấu",
      intro: "M = stack của bạn ÷ chi phí một vòng (mù nhỏ + mù lớn + toàn bộ ante): số vòng bạn trụ được mà không chơi tay nào. Các vùng giả định bàn đủ chín hoặc mười người; khi bàn ít người hơn, hãy nhân M với (số người ÷ 10) trước — Effective M của Harrington — nên M 10 ở final table sáu người chơi giống M 6 (tab “M giải đấu” ở trên hiển thị M thô; bạn tự quy đổi).",
      th: ["Vùng", "M", "Chiến lược"],
      align: ["left", "right", "left"],
      emphasis: 1,
      rows: [
        ["💀 Vùng chết", "< 1", "Fold equity đã hết — shove tay tốt nhất bạn thấy trước khi mù đến lượt bạn, tốt nhất là khi first in"],
        ["🔴 Vùng đỏ", "1–5", "Push/fold: shove tay tốt, fold phần còn lại, sớm double up"],
        ["🟠 Vùng cam", "6–9", "Thu hẹp về tay mạnh và tìm cơ hội open-shove"],
        ["🟡 Vùng vàng", "10–19", "Áp lực đã đến — gom chip hung hãn ở spot tốt"],
        ["🟢 Vùng xanh", "20+", "Stack thoải mái — chiến lược đầy đủ, chơi theo vị trí và bluff"],
      ],
      note: "Vì sao stack trong giải đấu được đo bằng số vòng và mù thay vì bằng chip, xem bài",
      link: { slug: "holdem-tournament-vs-cash-game", text: "Tournament hay Cash Game?" },
      linkTail: "",
    },
  ],

  guide: {
    badge: "Công cụ",
    h2: "Cách dùng 9 máy tính Hold'em",
    cards: [
      { icon: "🎲", title: "Máy tính equity (tay bài vs tay bài)", body: "Nhập 2–4 tay bài và board tùy ý để xem % thắng, % hòa và equity của từng tay. Khi biết hết các tay, flop và turn được đếm chính xác; ở preflop hoặc khi có đối thủ cầm tay ngẫu nhiên, máy lấy mẫu 60.000 runout và ghi rõ điều đó." },
      { icon: "🎯", title: "Máy tính outs", body: "Tính chính xác xác suất draw hoàn thành ở flop hoặc turn. Xem cùng lúc mẹo quy tắc 4 và 2 lẫn giá trị chính xác." },
      { icon: "💰", title: "Pot odds & implied odds", body: "Quyết định call hay fold bằng con số; nút implied odds cộng thêm số tiền bạn kỳ vọng thắng ở các street sau." },
      { icon: "🃏", title: "Đánh giá tay bài", body: "Chọn lá bài để kiểm tra thứ hạng tay bài. Nhập tối đa 7 lá, máy tự tìm tổ hợp 5 lá tốt nhất." },
      { icon: "📊", title: "Sức mạnh bài khởi đầu", body: "Chọn hai lá bài tẩy để xem đó là tay nào trong 169 tay khởi đầu và hành động khuyến nghị theo vị trí." },
      { icon: "📐", title: "SPR (Stack-to-Pot Ratio)", body: "Tỷ lệ stack trên pot cho biết bạn cần tay bài mạnh đến đâu. SPR càng thấp, càng nên cam kết với tay mạnh." },
      { icon: "🏆", title: "Chỉ số M trong giải đấu", body: "M của Harrington đo áp lực lên stack giải đấu của bạn. Chiến lược thay đổi hoàn toàn giữa các vùng xanh/vàng/cam/đỏ/chết." },
      { icon: "📈", title: "Máy tính ICM", body: "Independent Chip Model quy đổi chip giải đấu thành giá trị tiền thưởng thực, kèm cột chip chop bên cạnh — những con số đứng sau quyết định ở bubble và các cuộc thương lượng deal ở final table." },
      { icon: "⚡", title: "Bảng Nash push/fold", body: "Bảng Nash 13×13 cho heads-up, 6-max và 9-max: open-shove với tay nào ở 1–25bb (và ở heads-up, call với tay nào). Không thể thiếu ở giai đoạn cuối giải đấu." },
    ],
  },

  faq: {
    badge: "Hỏi đáp",
    h2: "Hỏi đáp — máy tính ICM và máy tính Hold'em",
    q: "Hỏi: {q}",
  },

  related: {
    badge: "Đọc tiếp",
    h2: "Các hướng dẫn nên đọc khi đã nắm phần tính toán",
    // 🔴 vi 코퍼스 8편 전수(EN 8슬러그는 vi에 0개 실재 · tr·fr 선례: related = 실재 글 전수 · 게이트 F항 min(EN 8, 코퍼스)).
    //    title/desc = 각 글의 title·seoTitle·desc 축어 범위 안(settled §3-A · 창작 금지 · 첫 글자 대문자화만).
    //    /vi/hand-chart는 블로그 슬러그가 아니라서 여기 못 넣는다(컴포넌트가 /vi/blog/{slug}로 만든다).
    links: [
      { slug: "holdem-tournament-vs-cash-game", title: "Tournament hay Cash Game?", desc: "Giá trị chip, blind, bankroll, variance và áp lực ICM" },
      { slug: "holdem-all-in-rules", title: "Luật all-in & side pot", desc: "Table stakes, pot chính, pot phụ (side pot), quyền tố lại và thứ tự showdown" },
      { slug: "holdem-hand-rankings", title: "Thứ hạng tay bài poker", desc: "10 tay bài poker từ mạnh nhất đến yếu nhất, xác suất thực của từng tay" },
      { slug: "holdem-betting-actions", title: "Các hành động cược trong poker", desc: "Check, theo (call), tố (raise) và bỏ bài (fold)" },
      { slug: "holdem-game-order", title: "Trình Tự Chơi Texas Hold'em", desc: "Preflop, flop, turn, river, lật bài" },
      { slug: "holdem-showdown-rules", title: "Luật showdown & muck trong Poker", desc: "Người cược cuối, bài tự nói, slow roll và all-in" },
      { slug: "texas-holdem-rules-for-beginners", title: "Cách chơi Texas Hold'em cho người mới", desc: "Mù, chia chip, thứ hạng bài và bảng tóm tắt in được" },
      { slug: "holdem-blind-meaning", title: "Mù nhỏ và mù lớn trong poker", desc: "Ai đặt, mức cược SB/BB, big blind ante và luật mù khi chơi heads-up" },
    ],
  },
};
