// TR (Türkçe · Türkiye) calculator dictionary — every user-visible string of the shared tool.
//
// ★2026-10-06 신설(tr 클러스터 회차 2 · docs/tr-cluster-plan.md §4 · 정본 골격 = docs/harden-brief/calculator-landing-rewrite.md §1).
// 🔴 키워드 실측(2026-10-06 · DFS google_ads/search_volume · location 2792 Türkiye):
//    poker calculator 40 · poker odds calculator 40 · poker hesaplayıcı 10 · poker hesaplama 10 · poker equity calculator 10 ·
//    icm calculator 10 · poker olasılık/oran/ihtimal hesaplama · pot oranı hesaplama · texas holdem hesaplayıcı = null.
//    → 시장 자체는 입문·족보에 몰려 있고(poker nasıl oynanır 5.400 · poker elleri 2.900) 도구 어휘는 ms형(자국어 미약 · 영어 토큰 생존).
//    머리어 = 터키어 «Poker Hesaplayıcı»(ms·id의 «Kalkulator Poker»와 같은 판단) + 차별화어는 코퍼스 차용어(Odds · Equity · ICM) + «pot oranı».
//    🔴 «pot oranı hesaplama · olasılık hesaplama» 의도는 이 도구가 주인이다(§3) — pot-odds·probability 글(회차 3)은 개념 의도만.
// 용어 = docs/translation-terms-tr.md + lib/posts-tr 코퍼스 실측(10-06): 족보는 코퍼스 표 형(Flush·Full House·Straight Flush·Royal Flush는 영어,
//    Kare·Kent·Üçlü·İki Çift·Çift·Yüksek Kart는 터키어) · çip 57+ : fiş 8(클러스터 표기 = çip) · equity 11 · pot odds 8 · out 3 · turnuva 44 · ödül 6.
// 숫자: tr-TR(천단위 «.» · 소수 «,») · 🔴 퍼센트는 기호가 앞(«%81,9» — 코퍼스 38 : 0) → percentPrefix. 문체 = sen.
// 🔴 내부 링크: tr 코퍼스는 8편뿐이고 EN 9슬러그 중 실재 = holdem-tournament-vs-cash-game 하나(+ shortStackLink 대체 = holdem-all-in-rules · fr 선례).
//    quickRef ①~⑤는 link를 비웠다(게이트 F항) · deal.linkLead/link 생략 · related = 실재 8편 전수.
//    회차 3(pot-odds·probability 글) 뒤에 quickRef ①④·related를 다시 건다.
import type { CalcDict } from "@/components/calculator/dict";

export const CALC_DICT_TR: CalcDict = {
  numberLocale: "tr-TR",
  percentPrefix: true,

  seo: {
    title: "Poker Hesaplayıcı — Odds, Equity, ICM ve Pot Oranı",
    description:
      "Ücretsiz Texas Hold'em hesaplayıcısı: eller arası equity, pot oranı, implied odds, out, el değeri, SPR, M değeri, ICM deal ve chip chop — 9 araç tek sayfada.",
    path: "/tr/calculator",
  },

  hero: {
    badges: ["Ücretsiz araç", "Üyelik yok"],
    h1: "Poker Hesaplayıcı",
    h1Sub: "Equity, ICM ve pot oranı tek yerde",
    lead: "İki eli gir, kimin kazandığını gör — sonra pot oranını, out'ları, ICM deal'ini, SPR'ı, turnuva M değerini ve push/fold range'ini kontrol et. Dokuz ücretsiz Hold'em hesaplayıcısı; yeterince hızlı olduğu her street'te tek tek sayarak kesin hesaplama.",
    chips: ["🎲 Equity", "🎯 Out", "💰 Pot Oranı", "🃏 El Değeri", "📊 Başlangıç Elleri", "📐 SPR", "🏆 M Değeri", "📈 ICM", "⚡ Push/Fold"],
  },

  equity: {
    label: "Equity", sub: "El karşılaştırması",
    hero: "Senin elin",
    opp: "Rakip {n}",
    random: "Rastgele el",
    board: "Board",
    pickerHint: "Bir oyuncu ya da board seç, sonra kartlarını seç.",
    addPlayer: "+ Rakip ekle", removePlayer: "− Rakibi çıkar",
    needTwo: "Her ele 2 kart ver (ya da bir rakibi rastgele el olarak işaretle).",
    boardCount: "Preflop için board'u boş bırak ya da 3 (flop), 4 (turn) veya 5 (river) kart ver.",
    th: { player: "Oyuncu", hand: "El", win: "Kazanma", tie: "Beraberlik", equity: "Equity" },
    exactNote: "Kesin — olası {n} runout'un tamamı tek tek sayıldı.",
    mcNote: "Monte Carlo — {n} rastgele runout; sonuç çalıştırmalar arasında yaklaşık ±0,3 yüzde puan oynar.",
    winner: "{p}, {hand} ile kazanır",
    chop: "Beraberlik — {n} el potu {hand} ile paylaşır",
    showdownNote: "Showdown — board tamamlandı, bu kesin sonuçtur.",
    presets: [
      { label: "AA vs KK", hands: ["AsAh", "KsKd"] },
      { label: "AKs vs QQ", hands: ["AhKh", "QsQc"] },
      { label: "AKo vs 22", hands: ["AhKd", "2s2c"] },
      { label: "AKo vs AQo", hands: ["AhKd", "AsQc"] },
      { label: "AA vs 87s", hands: ["AsAh", "8d7d"] },
    ],
  },

  tabs: {
    outs: { label: "Out", sub: "Draw ihtimali" },
    pot: { label: "Pot Oranı", sub: "Call/fold" },
    hand: { label: "El Değeri", sub: "Kart seç" },
    starting: { label: "Başlangıç Elleri", sub: "Açılış gücü" },
    spr: { label: "SPR", sub: "Stack/pot oranı" },
    m: { label: "Turnuva M", sub: "M değeri" },
    icm: { label: "ICM", sub: "Ödül equity'si" },
    pushfold: { label: "Push/Fold", sub: "Nash tablosu" },
  },

  workspace: {
    chooseCalculator: "Hesaplayıcı seç",
    resetInputs: "Girdileri sıfırla",
    resetAria: "Sıfırla: {label}",
    resetMessage: "{label} girdileri sıfırlandı.",
  },

  cardPicker: {
    clearAll: "Hepsini temizle",
  },

  outs: {
    drawType: "Draw türü",
    presets: [
      { label: "Özel giriş" },
      { label: "Flush draw", desc: "Aynı türden 4 kart → 5.'si lazım (nut flush olsun olmasın 9 out)" },
      { label: "Açık uçlu kent draw'ı (OESD)", desc: "ör. 5-6-7-8, 4 ya da 9 lazım" },
      { label: "Flush + gutshot kombosu", desc: "9 flush + 3 gutshot (çakışanlar çıkarıldı)" },
      { label: "Gutshot kent", desc: "ör. 5-6-8-9, yalnızca 7 lazım" },
      { label: "İki overcard", desc: "Board'daki her karttan yüksek 2 değer × 3'er — hazır ele karşı ciddi indir: bir overcard'ı eşlemek bile çoğu zaman yine kaybeder" },
      { label: "İki Çift → Full House", desc: "ör. A-K-x board'da A-K → kalan 2 as + 2 papaz" },
      { label: "Çift → Üçlü", desc: "o değerden kalan 2 kart" },
      { label: "Flush + OESD (canavar)", desc: "9 flush + 8 kent (2'si çakışır)" },
    ],
    outsSuffix: " ({n} out)",
    street: "Street",
    afterFlopBtn: "🃏 Flop → river",
    afterTurnBtn: "🔄 Turn → river",
    flopOneBtn: "🎯 Flop → turn",
    afterFlopOne: "Flop → turn",
    chanceFlopOne: "Flop'tan sonraki tek kartta tutma ihtimali",
    outsCount: "Out sayısı: {v}",
    afterFlop: "Flop → river",
    afterTurn: "Turn → river",
    ruleOf4: "4 kuralı",
    ruleOf2: "2 kuralı",
    chanceFlop: "Flop'tan river'a kadar draw'ın tamamlanma ihtimali (iki kart da — all-in)",
    chanceTurn: "Turn'den sonra, river'da draw'ın tamamlanma ihtimali",
    exact: " (kesin)",
    ruleMental: "{n} kuralı (kafadan hesap):",
    exactNote: "Büyük puntoyla gösterilen sayı kesin değerdir",
    verdict: { great: "Harika 🔥", good: "İyi ✅", fair: "Orta ⚠️", poor: "Zayıf ❌", veryPoor: "Çok zayıf 💀" },
  },

  pot: {
    potSize: "Pot büyüklüğü (karşılaştığın bet dahil)",
    callAmount: "Call tutarın",
    potOddsCaption: "Pot oranı (gereken minimum equity)",
    orHigher: "— elinin equity'si bundan yüksekse call kârlıdır",
    equityLabel: "Elinin equity'si: {v}",
    sliderGutshot: "Gutshot (turn) %8,7",
    sliderFlush: "Flush (turn) %19,6",
    impliedToggle: "Implied odds {toggle}",
    close: "Kapat ▲",
    add: "Ekle ▼",
    extraWinnings: "Ek beklenen kazanç (draw tutarsa): {v}",
    none: "Yok",
    impliedCaption: "Implied odds (ek kazançla)",
    impliedNote: "{n} ek kazançla hesaplanan gereken minimum equity",
    needImplied: "implied odds %{n}",
    needPot: "pot oranı %{n}",
    verdict: {
      call: { title: "Call (kârlı)", body: "Elinin equity'si %{eq} > {need} → uzun vadede kâr" },
      even: { title: "Başabaş (EV 0)", body: "Elinin equity'si %{eq} = {need} → call ne kazandırır ne kaybettirir. Pozisyon ve rakibin tarzı gibi pot oranı dışındaki etkenlere göre karar ver" },
      fold: { title: "Fold önerilir", body: "Elinin equity'si %{eq} < {need} → uzun vadede zarar" },
    },
  },

  handEval: {
    pickerLabel: "Kart seç (5–7)",
    emptyTitle: "Eli değerlendirmek için 5 ya da daha fazla kart seç",
    emptyHint: "7 kartla en iyi 5 kartlık kombinasyon otomatik bulunur",
    bestFrom: "{n} karttan en iyi el",
    rankNames: [
      "Yüksek Kart", "Çift", "İki Çift", "Üçlü", "Kent",
      "Flush", "Full House", "Kare", "Straight Flush", "Royal Flush",
    ],
    resultNames: [
      "Yüksek Kart 🃏", "Çift 1️⃣", "İki Çift ✌️", "Üçlü 3️⃣", "Kent ➡️",
      "Flush 🌊", "Full House 🏠", "Kare 💎", "Straight Flush 🌟", "Royal Flush 👑",
    ],
    axis: ["Yüksek Kart", "Çift", "Flush", "Kare", "Royal"],
  },

  starting: {
    pickerLabel: "Elindeki 2 kartı seç",
    emptyPrompt: "Elindeki 2 kartı seç",
    // 폴백 3분기 = EN 09-20 정본(ms 판과 같은 경계): suited — first-in BTN 전부 · CO는 K suited · 둘 다 8 이상 · 54s까지 connector /
    //   offsuit — BTN만, 에이스 아무거나 또는 둘 다 9 이상 / 나머지 fold. 한정어(first-in · suited · BTN만)를 빠뜨리지 마라(브리프 §3-L).
    unknownDesc: "Temel açılış tablosunda yok",
    unknownAction: "Suited: herkes sana kadar fold ettiyse BTN'den her suited eli aç; CO'dan suited papazlar, iki kartı da 8 ve üstü olanlar (Q8s, 10-8s) ve 54s'e kadar connector'larla sınırla. Offsuit: yalnızca BTN — herhangi bir as (A9o, A5o) ya da iki kartı da 9 ve üstü (K9o, 10-9o). Gerisi (J2o, 93o, 72o): fold",
    tierNames: ["🥇 Tier 1 — Premium", "🥈 Tier 2 — Güçlü", "🥉 Tier 3 — Oynanabilir", "⚠️ Tier 4 — Sınırda", "🚫 Tier 5 — Zayıf"],
    recommendedAction: "Önerilen hamle:",
    axis: ["Premium", "Güçlü", "Oynanabilir", "Sınırda", "Zayıf"],
    summaryTitle: "El tier özeti",
    summary: [
      { hands: "AA KK QQ JJ 10-10 AKs AKo", action: "Her zaman raise" },
      { hands: "AQs AJs A10s KQs KJs 99 88 AQo", action: "Çoğu pozisyondan raise" },
      { hands: "AJo KQo K10s Q10s QJs J10s 10-9s 77 A9s K9s Q9s J9s", action: "Geç pozisyondan raise" },
      { hands: "66–22 A8s–A2s KJo QJo A10o–J10o 98s–54s", action: "Geç pozisyonda seçici" },
      { hands: "zayıf offsuit eller (J2o, 93o, 72o)", action: "Genelde fold" },
    ],
    // «오픈 림프로 읽히는 자리» = 선례 8로케일과 같은 형(무엇에 대한 call인지 명시 + 오픈 림프 금지) — 브리프 §3-L.
    hands: {
      AA: { desc: "En iyi el. Her spotta raise", action: "Her zaman raise/re-raise (3-bet)" },
      KK: { desc: "Flop'ta yalnızca asa dikkat", action: "Her zaman raise/re-raise" },
      QQ: { desc: "JJ'den güçlü ama fazla değer biçme", action: "Her zaman raise; derin stack'te dikkatli ol" },
      JJ: { desc: "Flop'taki overcard'lara dikkat", action: "Her pozisyondan raise" },
      "1010": { desc: "Flop'ta overcard gelince değer kaybeder", action: "Her pozisyondan raise — open-limp yapma" },
      AKs: { desc: "En iyi draw eli. Potu büyüt", action: "Her zaman raise/re-raise" },
      AKo: { desc: "AKs'ten zayıf ama yine premium", action: "Her zaman raise; re-raise'e call edilebilir" },
      AQs: { desc: "Güçlü el; pozisyonda daha değerli", action: "Çoğu pozisyondan raise" },
      AJs: { desc: "BTN/CO'da harika, UTG'den zayıf", action: "Orta/geç pozisyonda raise; UTG'den raise ya da fold — limp yapma" },
      A10s: { desc: "En iyi suited aslardan", action: "Orta/geç pozisyonda raise; UTG'den raise ya da fold — limp yapma" },
      KQs: { desc: "Yüksek flush potansiyeli + kent draw'ı", action: "Çoğu pozisyondan raise" },
      KJs: { desc: "Güçlü draw eli", action: "Geç pozisyonda raise; erken pozisyondan raise ya da fold — limp yapma" },
      "99": { desc: "Orta çift, overcard'lı flop'lara dikkat", action: "Çoğu pozisyondan raise; derin stack'te dikkatli ol" },
      "88": { desc: "Set potansiyeli iyi bir pocket pair", action: "Çoğu pozisyondan raise; raise'e call — open-limp yapma" },
      AQo: { desc: "Offsuit daha zayıf; pozisyon önemli", action: "Orta/geç pozisyonda raise; UTG'den raise ya da fold — limp yapma" },
      AJo: { desc: "Erken pozisyonda zayıf, geç pozisyonda güçlü", action: "CO/BTN'de raise, erken pozisyonda dikkatli ol" },
      KQo: { desc: "En iyi offsuit connector", action: "Geç pozisyonda raise; erken pozisyonda, henüz kimse girmediyse raise ya da fold, raise'e karşı genelde fold" },
      K10s: { desc: "Suited papaz, geç pozisyonda güçlü", action: "Geç pozisyonda raise, erken pozisyonda fold" },
      QJs: { desc: "Hem kent hem flush draw'ı yapabilen güçlü el", action: "Geç pozisyonda raise, derin stack'te daha değerli" },
      J10s: { desc: "En iyi suited connector'lardan", action: "Geç pozisyonda raise; pozisyonun varsa tek raise'e call" },
      "109s": { desc: "Güçlü suited connector", action: "Geç pozisyondan first in raise; pozisyonla tek raise'e call" },
      "77": { desc: "Set avı eli, overcard'lara dikkat", action: "Geç pozisyonda raise; erken pozisyonda raise'e call, first in isen raise ya da fold — open-limp yapma" },
      A9s: { desc: "Flush potansiyelli suited as", action: "Geç pozisyonda raise" },
      K9s: { desc: "Suited papaz; papaz çifti domine olabilir", action: "Senden öncekiler fold ettiyse CO/BTN'den open-raise; raise'e karşı pozisyonu, fiyatı ve efektif stack'i tart" },
      Q9s: { desc: "Kent potansiyelli suited kız; kicker'ı güçlü Q'lara dikkat", action: "Senden öncekiler fold ettiyse CO/BTN'den open-raise; raise'e karşı pozisyonu, fiyatı ve efektif stack'i tart" },
      J9s: { desc: "Kent ve flush potansiyelli suited one-gapper", action: "Senden öncekiler fold ettiyse CO/BTN'den open-raise; raise'e karşı pozisyonu, fiyatı ve efektif stack'i tart" },
      "66": { desc: "Set avı; implied odds gerekir", action: "Geç pozisyondan first in raise; ikiniz de (sen ve raise yapan) arkada en az call'un ~15 katı çip tutuyorsanız raise'e call" },
      "55": { desc: "Set olmadan değeri az", action: "Geç pozisyondan first in raise; ikiniz de (sen ve raise yapan) arkada en az call'un ~15 katı çip tutuyorsanız geç pozisyonda tek raise'e call" },
      A8s: { desc: "Orta suited as", action: "Geç pozisyonda oyna, erken pozisyonda fold" },
      A7s: { desc: "Orta suited as", action: "Yalnızca geç pozisyonda oyna" },
      A6s: { desc: "Orta suited as", action: "Yalnızca geç pozisyonda oyna" },
      A5s: { desc: "Wheel değeri + as bloğu; gözde 3-bet blöfü", action: "Yalnızca geç pozisyon; implied odds önemli" },
      A4s: { desc: "Wheel draw'lı suited as", action: "Yalnızca geç pozisyon" },
      A3s: { desc: "Wheel kartı + nut flush draw, A2s'in bir basamak üstü", action: "Yalnızca geç pozisyon" },
      A2s: { desc: "Wheel + nut flush, ama zayıf", action: "Yalnızca geç pozisyon" },
      KJo: { desc: "Domine olma riski; yalnızca geç pozisyon", action: "CO/BTN'de raise, re-raise gelirse fold" },
      QJo: { desc: "Orta bağlantı; pozisyon ister", action: "Yalnızca geç pozisyon" },
      "98s": { desc: "Güçlü suited connector", action: "Geç pozisyondan first in raise; pozisyonla raise'e call" },
      "87s": { desc: "İyi suited connector", action: "Geç pozisyondan first in raise; pozisyonla raise'e call" },
      "76s": { desc: "Suited connector", action: "Geç pozisyondan first in raise; raise'e yalnızca pozisyon ve derin stack'le call" },
      "44": { desc: "Set olmadan neredeyse değersiz", action: "Geç pozisyondan first in raise; ikiniz de (sen ve raise yapan) arkada en az call'un ~15 katı çip tutuyorsanız geç pozisyonda tek raise'e call" },
      "33": { desc: "Set avlamalı; spekülatif", action: "Geç pozisyondan first in raise; onun dışında yalnızca derin stack'li multiway potlar" },
      "22": { desc: "En düşük pocket pair", action: "Geç pozisyondan first in raise; onun dışında yalnızca derin stack'li multiway potlar" },
      K10o: { desc: "K-10 offsuit, zayıf", action: "Senden öncekiler fold ettiyse CO/BTN'den open-raise" },
      Q10o: { desc: "Bağlantısı zayıf offsuit", action: "Yalnızca BTN" },
      J10o: { desc: "Fena olmayan ama kolay saldırılan offsuit", action: "Yalnızca BTN" },
      Q10s: { desc: "Güçlü suited broadway, pozisyonda iyi oynar", action: "Geç pozisyonda raise; erken pozisyondan fold" },
      A10o: { desc: "Sınırda offsuit as, kolay domine olur", action: "Yalnızca geç pozisyon" },
      "65s": { desc: "Suited connector; multiway/implied odds ister", action: "Geç pozisyondan first in raise; raise'e yalnızca pozisyon ve derin stack'le call" },
      "54s": { desc: "Düşük suited connector; spekülatif", action: "Geç pozisyondan first in raise; raise'e yalnızca pozisyonla ve ucuz multiway potta call" },
    },
  },

  spr: {
    effectiveStack: "Efektif stack (iki stack'ten kısa olanı)",
    potSize: "Mevcut pot büyüklüğü",
    caption: "SPR (Stack-to-Pot Ratio)",
    stackDivPot: "stack ÷ pot",
    zones: {
      low: {
        label: "Düşük SPR (bağlanmış)",
        desc: "Stack'in epey büyük bir kısmı zaten pota girdi. Kuru flop'ta top pair top kicker ya da daha iyisiyle kalanını da sokmayı planla — bu derinlikte fold çoğu zaman daha büyük hatadır. Eşli board'da, üç aynı türde ya da üç ardışık kartlı board'da veya yalnızca set ya da kentin yapabileceği aksiyona karşı tek çift yine tek çifttir.",
        actions: [["TPTK+", "All-in'i düşün"], ["Draw", "Pot oranını mutlaka hesapla"], ["Zayıf el", "Dikkatle fold"]],
      },
      mid: {
        label: "Orta SPR (esnek)",
        desc: "İki Çift ve üstü güçlü ellerle oynama bölgesi. Stack'ini korumak önem kazanır.",
        actions: [["İki Çift+", "Value bet"], ["Tek çift", "Bir iki street, sonra pot kontrolü"], ["Draw", "Fold equity varsa semi-blöf; yoksa bırak"]],
      },
      high: {
        label: "Yüksek SPR (derinleşiyor)",
        desc: "Stack'ler derinleşiyor. Draw'ların ve güçlü hazır ellerin göreli değeri artar.",
        actions: [["Set+", "Güçlü oyna"], ["Draw", "Implied odds artar"], ["Tek çift/TPTK", "Dikkatle devam et"]],
      },
      deep: {
        label: "Çok yüksek SPR (derin)",
        desc: "Bu bir derin stack oyunu. Pozisyon, draw potansiyeli ve rakibin range'ini okumak çok önemli.",
        actions: [["Nut el", "Büyük bet atabilirsin"], ["Draw", "Implied odds çok yüksek"], ["Zayıf hazır el", "Dikkat, kolay blöf yer"]],
      },
    },
    legend: ["Bağlanmış", "Esnek", "Derinleşiyor", "Derin"],
  },

  m: {
    inputs: { stack: "Senin stack'in", bb: "Big blind", sb: "Small blind", ante: "Ante" },
    players: "Masadaki oyuncu: {v}",
    headsUp: "2 (heads-up)",
    orbitCaption: "Bir tur maliyeti (bir turda ödenen blind'lar)",
    orbitFormula: "BB {bb} + SB {sb} + ante {ante}×{players}",
    mCaption: "M değeri (Harrington M)",
    zones: {
      dead: { name: "💀 Ölü bölge", desc: "Fold equity tükendi — tek hamle all-in, bu yüzden blindler gelmeden eline gelen en iyi eli shove et ve henüz kimsenin açmadığı potları tercih et.", action: "Hemen all-in" },
      red: { name: "🔴 Kırmızı bölge", desc: "Acilen double up yapman lazım. Push/fold stratejisine geç — iyi elleri shove et, gerisini fold et.", action: "Push/fold" },
      orange: { name: "🟠 Turuncu bölge", desc: "Stack'in eriyor. Range'ini yalnızca güçlü ellere daralt ve open-shove fırsatı kolla.", action: "Sıkı range" },
      yellow: { name: "🟡 Sarı bölge", desc: "Baskı hissediliyor. Aktif çip toplaman gerek — iyi spot gelince agresif oyna.", action: "Agresif oyna" },
      green: { name: "🟢 Yeşil bölge", desc: "Stack'in rahat. Stratejinin tamamını kullan — pozisyon oyunu ve blöfle stack'ini büyüt.", action: "Tam strateji" },
    },
  },

  icm: {
    introStrong: "ICM (Independent Chip Model)",
    introRest: ", turnuva stack'lerini ICM'e göre beklenen ödül parasına çevirir. Call mu fold mu seçmek için olası her sonuçtan (kazanma, beraberlik ya da kaybetme) sonraki değerini gerçek olasılığıyla çarp, toplamı fold sonrası değerle karşılaştır. Elendiğinde otomatik sıfır değil, gerçekten alınan ödülü say.",
    numPlayers: "Oyuncu sayısı",
    paidPlaces: "Ödül alan sıralar",
    stacksTitle: "Oyuncu çip stack'leri",
    total: "toplam {n}",
    decStack: "{n}. oyuncunun stack'ini azalt",
    stackInput: "{n}. oyuncunun çip stack'i",
    incStack: "{n}. oyuncunun stack'ini artır",
    prizesTitle: "Ödüller",
    decPrize: "{n}. sıra ödülünü azalt",
    prizeInput: "{n}. sıra ödülü",
    incPrize: "{n}. sıra ödülünü artır",
    currencyNote: "Ödül tutarlarını herhangi bir para biriminde gir.",
    resultTitle: "ICM sonucu",
    th: { player: "Oyuncu", chips: "Çip", chipPct: "Çip %", icmValue: "ICM değeri", icmPct: "ICM %", diff: "Fark", chop: "Chip chop" },
    playerCell: "{medal} P{n}",
    diffPlus: "+fark",
    diffPlusNote: "ICM'e göre ödül havuzundaki payın çip payından yüksek. Farkın işareti tek başına call mı fold mu yapacağını belirlemez.",
    diffMinus: "−fark",
    diffMinusNote: "ICM'e göre ödül havuzundaki payın çip payından düşük. Farkın işareti tek başına agresyonun kârlı olup olmadığını belirlemez.",
    diffUnit: "puan",
    empty: "Pozitif stack ve ödüller kullan, ödülleri en yüksekten en düşüğe sırala; eşit ödüller serbest.",
  },

  pushfold: {
    ante: "Ante",
    noAnte: "Ante yok",
    bbAnteOn: "BB ante AÇIK",
    table: "Masa",
    headsUp: "Heads-Up",
    sixMax: "6-max",
    nineMax: "9-max",
    scenario: "Senaryo",
    sbShove: "SB: shove ya da fold",
    bbCall: "BB: shove'a call",
    position: "Pozisyon {hint}",
    firstInHint: "(first-in — herkes sana kadar fold etti)",
    effectiveStack: "Efektif stack: {v}",
    captionHuPush: "SB'nin {stack}bb'de shove ettiği eller",
    captionHuCall: "BB'nin {stack}bb'de shove'a call ettiği eller",
    // 🔴 «{pos}'dan» 금지 — 접미사가 포지션마다 갈린다(CO'dan · BTN'den). 괄호로 뺐다.
    captionMw: "{table}-max masada first-in shove ({pos}), {stack}bb",
    withAnte: " (ante ile)",
    combosSuffix: " / {total} kombo",
    legendPush: "Push (all-in)",
    legendCall: "Call",
    legendFold: "Fold",
    note: {
      strong1: "Köşegen = çift · sağ üst = suited · sol alt = offsuit",
      p1: "Tablo ",
      strong2: "güce göre değil, kart değerine (rank) göre",
      p2: " dizildi; bu yüzden bir satırda işaretli ve işaretsiz hücrelerin sırayla gelmesi normaldir — AQo, KQo ve QQ yan yanadır ama güç sırasında değildir. A5s'in girip A6s'in girmemesi de doğrudur: A5s",
      strong3: "wheel kenti (A-2-3-4-5)",
      p3: " yapabilir; bu da kicker'ının daha düşük olmasını telafi eder.",
    },
    cellTitle: "{hand} — {action}",
    cell: { push: "push", call: "call", fold: "fold" },
    huNote: {
      strong: "Nash dengesi, heads-up (SB vs BB)",
      p1: ": SB'nin ya shove ya fold yaptığı varsayılır. Ante ayarı oyuncu başına 0,125bb ekler (oyuncu başına big blind'ın %12,5'i — 8 kişilik masada big blind ante'nin değeri; heads-up'ta toplam yalnızca 0,25bb). Stack kısaldıkça range genişler — ve ~3-4bb'nin altında BB'nin pot oranı yüzünden SB'nin shove range'inden ",
      em: "daha geniş",
      p2: " call etmesi doğrudur.",
    },
    mwNote: {
      strong: "{table}-max first-in shove tablosu",
      p1: ": önündeki herkes fold etti ve sen ya shove ya fold yapıyorsun. Bu, ",
      strong2: "saf chip-EV",
      p2: " Nash tarzı bir dengedir — arkadaki oyuncuların call range'leri aynı anda çözülür — ve call edilen potun ilk caller'a karşı heads-up sonuçlandığı standart varsayımını kullanır (birden fazla caller'lı potlar hesaba katılmaz). Arkanda daha az oyuncu kaldıkça (UTG → BTN → SB), stack kısaldıkça ve ante AÇIK olduğunda (oyuncu başına 0,125bb) range genişler. Saf chip-EV olduğu için erken pozisyondan (UTG/MP) 10bb range'i, yaygın genel kuraldan (ante yokken küçük çiftler fold) daha sıkı çıkar — gerçek oyunda ICM'e ve rakiplere göre ayarla.",
    },
    // 🔴 tr에는 holdem-short-stack 글이 없다 → fr 선례대로 all-in 규칙 글로(shortStackLink는 필수 키).
    readMore: "Stack'in tamamını ortaya sürmenin ve yan potların nasıl işlediğini öğrenmek için",
    shortStackLink: { slug: "holdem-all-in-rules", text: "all-in ve yan pot kuralları rehberimize" },
    readMoreEnd: " göz at.",
  },

  icmGuide: {
    bubble: {
      badge: "ICM rehberi",
      h2: "ICM hesaplayıcısı nasıl kullanılır — 3 dakikalık bubble örneği",
      intro: "Dört oyuncu kaldı ve üçü ödül alıyor (bubble). Stack'ler 60.000 / 40.000 / 30.000 / 20.000, ödüller $500 / $300 / $200. Bu sayıları hesaplayıcıya girersen her oyuncunun çip payını gerçek ödül değeriyle (ICM) yan yana görürsün:",
      th: { player: "Oyuncu", chipPct: "Çip %", icmPct: "ICM %", diff: "Fark" },
      rows: [
        { player: "🥇 Chip leader", chip: "%40,0", icm: "%33,3", diff: "-6,7 puan", up: false },
        { player: "🥈 2.", chip: "%26,7", icm: "%27,2", diff: "+0,6 puan", up: true },
        { player: "🥉 3.", chip: "%20,0", icm: "%22,9", diff: "+2,9 puan", up: true },
        { player: "4. (kısa stack)", chip: "%13,3", icm: "%16,6", diff: "+3,3 puan", up: true },
      ],
      keyPoint: {
        text: "Tablo {b1} gösteriyor, fark 6,7 yüzde puan; bu bir call/fold eşiği değildir. Risk primini çoğu zaman en çok orta stack'ler taşır; bu yüzden onları kapsayan leader, range izin veriyorsa {b2}. Kısa stack {b3}. Karar farkın işaretine değil; stack'lere, ödüllere ve rakiplere bağlıdır.",
        b1: "chip leader'ın ICM değerinin (%33,3) çip payından (%40) düşük olduğunu",
        b2: "orta stack'lere baskı kurabilir",
        b3: "blindlerin neredeyse bitirdiği stack'ler dışında call'larını özenle seçmeli",
      },
    },
    deal: {
      // 수치 = scripts/calc-icm-example.ts 출력 = EN 그대로(§13). 🔴 tr에 holdem-icm 글이 없어 linkLead/link 생략(fr 선례 · 게이트 F항).
      badge: "ICM deal hesaplayıcısı",
      h2: "ICM deal hesaplayıcısı — final table'da bir deal gerçekte ne eder",
      intro: "Dört oyuncu kaldı ve deal konuşuluyor. Stack'ler 450.000 / 250.000 / 180.000 / 120.000 (%45 / %25 / %18 / %12), kalan ödül $2.300; ödemeler $1.000 / $600 / $400 / $300. Bu sayıları yukarıdaki ICM hesaplayıcısına gir; Chip chop sütunu iki sayıyı yan yana koyar:",
      th: { player: "Oyuncu", chop: "Chip chop", icm: "ICM deal", diff: "Fark" },
      rows: [
        { player: "🥇 Chip leader (%45)", chop: "$1.035", icm: "$726", diff: "-$309", up: false },
        { player: "🥈 2. (%25)", chop: "$575", icm: "$591", diff: "+$16", up: true },
        { player: "🥉 3. (%18)", chop: "$414", icm: "$526", diff: "+$112", up: true },
        { player: "4. (%12)", chop: "$276", icm: "$458", diff: "+$182", up: true },
      ],
      summary: {
        text: "Ham chip chop çip payına göre böler ve {b1}; ICM deal ise her oyuncunun her sırada bitirme ihtimalini yansıtır ve {b2}. Yukarıda en kısa stack çipe göre $276, ICM'e göre $458 alıyor — {b3}. Pazarlığa oturmadan önce iki sayıyı da hesapla. İnsanların chip chop dediği şey çoğu zaman aslında save-and-chop'tur — önce herkese sıradaki ödül ödenir (burada 4. sıranın $300'ü), yalnızca kalan kısım çipe göre bölünür — ve bu, bu sütunun gösterdiği ham bölüşüme değil ICM'e yakın düşer. ICM ayrıca herkesin eşit yetenekte olduğunu varsayar ve sıradaki blindi kimin ödeyeceğini hesaba katmaz; büyük stack'lerin ICM rakamının üstünde pazarlık etmesini bekle.",
        b1: "chip leader'ı kayırır",
        b2: "kısa stack'lere daha adildir",
        b3: "$182 daha fazla",
      },
    },
  },

  // 빠른 참조 6표 — 🔴 모든 값 = scripts/calc-reference-tables.ts 출력(EN 그대로 · §13) · 구분자만 터키식 · 퍼센트 기호 앞.
  //   🔴 link는 lib/posts-tr/에 «실재하는» 슬러그만(게이트 F항) → ①~⑤ 비움, ⑥만 holdem-tournament-vs-cash-game.
  //   link를 비운 표의 note는 «…ada dalam»식 미완 문장으로 끝나면 안 된다 — 자립 문장으로 끝냈다.
  quickRef: [
    {
      badge: "Hızlı referans",
      h2: "Equity referans tablosu — preflop all-in eşleşmeleri",
      intro: "İki el preflop all-in olduğunda equity; o eşleşmenin tüm tür kombinasyonlarının ortalaması (çevrim dışı önceden hesaplandı: her biri için 1.712.304 board'un tamamı). Belirli bir tür kombinasyonu iki yüzde puandan fazla sapabilir (A♠K♠ vs Q♠J♠: %66,0) — tam kartları yukarıdaki equity hesaplayıcısına gir.",
      th: ["Eşleşme", "El A", "El B", "Beraberlik"],
      align: ["left", "right", "right", "right"],
      emphasis: 1,
      nowrap: [1, 2, 3],
      rows: [
        ["AA vs KK", "%81,9", "%18,1", "%0,5"],
        ["AA vs AKs", "%87,9", "%12,1", "%1,3"],
        ["AA vs 87s", "%77,5", "%22,5", "%0,3"],
        ["AA vs 72o", "%88,2", "%11,8", "%0,4"],
        ["KK vs AKs", "%65,9", "%34,1", "%0,8"],
        ["QQ vs AKo", "%56,8", "%43,2", "%0,4"],
        ["QQ vs AKs", "%54,0", "%46,0", "%0,4"],
        ["JJ vs TT", "%82,0", "%18,0", "%0,4"],
        ["TT vs A9o", "%72,2", "%27,8", "%0,4"],
        ["TT vs 87s", "%80,3", "%19,7", "%0,5"],
        ["22 vs AKo", "%52,6", "%47,4", "%0,6"],
        ["AKo vs AQo", "%74,4", "%25,6", "%4,7"],
        ["AKs vs QJs", "%63,5", "%36,5", "%0,5"],
        ["AKo vs JTs", "%59,5", "%40,5", "%0,5"],
      ],
      note: "Equity, beraberlikler (chop) dahil pottan ortalama payındır. Bir çift iki overcard'a karşı klasik bir yazı turadır; bir çift daha yüksek bir çifte karşı yaklaşık 4,5'e 1 underdog'dur.",
    },
    {
      badge: "Hızlı referans",
      h2: "Pocket as rastgele ellere karşı — rakip sayısına göre",
      intro: "Herkes preflop all-in olduğunda AA'nın N rastgele ele karşı kazanma sıklığı (Monte Carlo, satır başına 8.000.000 runout). İlk iki caller asları ayrı ayrı yaklaşık 10 yüzde puan düşürür; sonrasında her biri daha az düşürür.",
      th: ["Rakip", "AA equity'si"],
      align: ["left", "right"],
      emphasis: 1,
      nowrap: [1],
      rows: [
        ["1", "%85,2"], ["2", "%73,4"], ["3", "%63,8"], ["4", "%55,9"],
        ["5", "%49,2"], ["6", "%43,6"], ["7", "%38,7"], ["8", "%34,6"],
      ],
      note: "Asların heads-up pot istemesinin sebebi bu: beş rastgele ele karşı Hold'em'in en iyi başlangıç elinin equity'si %50'nin altına düşer (%49,2; kalanını diğer beşi paylaşır). Herhangi bir eli aynı şekilde test etmek için equity hesaplayıcısında bir rakibi «Rastgele el» yap (en fazla üç rakip alır).",
    },
    {
      badge: "Hızlı referans",
      h2: "Out referans tablosu — out sayısına göre draw ihtimali",
      intro: "Draw'ının tamamlanma ihtimali: flop → river (iki kart gelecek), flop → turn (yalnızca sıradaki kart) ve turn → river (tek kart) — kesin değerler, 4 ve 2 kuralı tahminiyle yan yana. Önce out'larını say, sonra satırı soldan sağa oku.",
      th: ["Out", "Tipik draw", "Flop → river", "Flop → turn", "Turn → river", "4 · 2 kuralı"],
      align: ["left", "left", "right", "right", "right", "right"],
      emphasis: 2,
      nowrap: [2, 3, 4, 5],
      rows: [
        ["1", "–", "%4,3", "%2,1", "%2,2", "%4 · %2"],
        ["2", "Pocket pair → set", "%8,4", "%4,3", "%4,3", "%8 · %4"],
        ["3", "Tek overcard", "%12,5", "%6,4", "%6,5", "%12 · %6"],
        ["4", "Gutshot kent", "%16,5", "%8,5", "%8,7", "%16 · %8"],
        ["5", "Çift → İki Çift ya da Üçlü", "%20,4", "%10,6", "%10,9", "%20 · %10"],
        ["6", "İki overcard", "%24,1", "%12,8", "%13,0", "%24 · %12"],
        ["7", "–", "%27,8", "%14,9", "%15,2", "%28 · %14"],
        ["8", "Açık uçlu kent", "%31,5", "%17,0", "%17,4", "%32 · %16"],
        ["9", "Flush draw", "%35,0", "%19,1", "%19,6", "%36 · %18"],
        ["10", "Gutshot + iki overcard", "%38,4", "%21,3", "%21,7", "%40 · %20"],
        ["11", "Açık uçlu + tek overcard", "%41,7", "%23,4", "%23,9", "%44 · %22"],
        ["12", "Flush draw + gutshot", "%45,0", "%25,5", "%26,1", "%48 · %24"],
        ["13", "–", "%48,1", "%27,7", "%28,3", "%52 · %26"],
        ["14", "Açık uçlu + iki overcard", "%51,2", "%29,8", "%30,4", "%56 · %28"],
        ["15", "Flush draw + açık uçlu", "%54,1", "%31,9", "%32,6", "%60 · %30"],
        ["16", "–", "%57,0", "%34,0", "%34,8", "%64 · %32"],
        ["17", "–", "%59,8", "%36,2", "%37,0", "%68 · %34"],
        ["18", "–", "%62,4", "%38,3", "%39,1", "%72 · %36"],
        ["19", "–", "%65,0", "%40,4", "%41,3", "%76 · %38"],
        ["20", "–", "%67,5", "%42,6", "%43,5", "%80 · %40"],
      ],
      note: "İki kartlık değer yalnızca iki kartı da ek ödeme yapmadan göreceksen (all-in) geçerlidir. Flop'ta bir bet'e karşıysan flop → turn sütununu kullan: 9 out = %19,1. Overcard'lar en az güvenilir out'lardır — hazır ele karşı birini eşlemek çoğu zaman yine kaybeder, değerlerini indir.",
    },
    {
      badge: "Hızlı referans",
      h2: "Pot oranı referans tablosu — call için gereken equity",
      intro: "Pota bu büyüklükte bir bet'le karşılaştığında call'ın başabaş olması için gereken minimum equity: call ÷ (bet sonrası pot + call). İki biçimde gösterilir — oran olarak ve gerektirdiği equity olarak; hesaplayıcı equity biçimini verir. Yukarıdaki out tablosunda draw'ının kesin ihtimaliyle karşılaştır.",
      th: ["Bet büyüklüğü", "Oran (X : 1)", "Gereken equity"],
      align: ["left", "right", "right"],
      emphasis: 2,
      nowrap: [1, 2],
      rows: [
        ["¼ pot", "5 : 1", "%16,7"],
        ["⅓ pot", "4 : 1", "%20,0"],
        ["½ pot", "3 : 1", "%25,0"],
        ["⅔ pot", "2,5 : 1", "%28,6"],
        ["¾ pot", "2,33 : 1", "%30,0"],
        ["Pot", "2 : 1", "%33,3"],
        ["1,5× pot", "1,67 : 1", "%37,5"],
        ["2× pot", "1,5 : 1", "%40,0"],
        ["3× pot", "1,33 : 1", "%42,9"],
      ],
      note: "Bir flush draw (iki kart gelecekken %35,0, sıradaki kartta %19,1) flop'ta pot büyüklüğündeki bet'e yalnızca all-in'ken call eder. Aksi hâlde implied odds hesaplayıcısı — pot oranı sekmesindeki düğme — sonradan kazanmayı beklediğin parayı ekler; yeter ki rakibin arkada çipi ve ödeyecek bir eli olsun. Nut'a draw etmiyorsan ciddi indir.",
    },
    {
      badge: "Hızlı referans",
      h2: "SPR referans tablosu — ne kadar güçlü bir el gerekir",
      intro: "SPR = efektif stack ÷ mevcut pot; efektif stack iki stack'ten kısa olanıdır — iki oyuncunun da kazanıp kaybedebileceği her şey. Değer düştükçe stack o kadar bağlanmıştır ve stack'i daha zayıf bir elle sokabilirsin; yükseldikçe büyük pot için nut'a o kadar yakın olman gerekir. Bu bölgeleri flop planı olarak oku: ıslak ya da eşli board'da tek çift yine tek çifttir.",
      th: ["SPR", "Bölge", "El gücü · hamle"],
      align: ["left", "left", "left"],
      emphasis: 1,
      rows: [
        ["SPR < 4", "Bağlanmış", "Kuru flop'ta top pair top kicker ya da daha iyisi: hepsini sokmayı planla — bu derinlikte fold çoğu zaman daha büyük hatadır"],
        ["4 ≤ SPR < 8", "Esnek", "Value için İki Çift ya da daha iyisi; tek çiftle bir iki street oyna, sonra pot kontrolüne geç"],
        ["8 ≤ SPR < 15", "Derinleşiyor", "Set ve üstü stack için oynar; draw'lar implied odds kazanır"],
        ["SPR ≥ 15", "Derin", "Büyük pot yalnızca nut sınıfı ellerle — zayıf hazır eller blöf hedefi olur"],
      ],
      note: "Yukarıdaki «SPR» sekmesi herhangi bir stack ve potu bu dört bölgeden birine çevirir.",
    },
    {
      badge: "Hızlı referans",
      h2: "M değeri hesaplayıcısı — turnuvanın beş bölgesi",
      intro: "M = stack'in ÷ bir tur maliyeti (small blind + big blind + tüm ante'ler): hiç el oynamadan kaç tur dayanabileceğin. Bölgeler dokuz ya da on kişilik tam masayı varsayar; masa kısaldığında önce M'yi (oyuncu sayısı ÷ 10) ile çarp — Harrington'ın Efektif M'si — yani altı kişilik final table'da M 10, 6 gibi oynar (yukarıdaki «Turnuva M» sekmesi ham M'yi gösterir; çevirmeyi kendin yap).",
      th: ["Bölge", "M", "Strateji"],
      align: ["left", "right", "left"],
      emphasis: 1,
      rows: [
        ["💀 Ölü bölge", "< 1", "Fold equity tükendi — blindler gelmeden eline gelen en iyi eli shove et, tercihen first in"],
        ["🔴 Kırmızı bölge", "1–5", "Push/fold: iyi elleri shove et, gerisini fold et, acilen double up"],
        ["🟠 Turuncu bölge", "6–9", "Range'ini güçlü ellere daralt ve open-shove fırsatı kolla"],
        ["🟡 Sarı bölge", "10–19", "Baskı hissediliyor — iyi spotlarda agresif çip topla"],
        ["🟢 Yeşil bölge", "20+", "Stack rahat — tam strateji, pozisyon oyunu ve blöf"],
      ],
      note: "Turnuva stack'lerinin neden çiple değil tur ve blindle ölçüldüğünü anlatan yazı:",
      link: { slug: "holdem-tournament-vs-cash-game", text: "Turnuva mı cash game mi?" },
      linkTail: "",
    },
  ],

  guide: {
    badge: "Araçlar",
    h2: "9 Hold'em hesaplayıcısı nasıl kullanılır",
    cards: [
      { icon: "🎲", title: "Equity hesaplayıcı (el karşılaştırması)", body: "2–4 el ve istediğin board'u gir; her elin kazanma %'si, beraberlik %'si ve equity'si çıksın. Tüm eller biliniyorsa flop ve turn tek tek kesin sayılır; preflop'ta ya da rastgele elli rakipte 60.000 runout örneklenir ve bu belirtilir." },
      { icon: "🎯", title: "Out hesaplayıcı", body: "Draw'ının flop'ta ya da turn'de tamamlanma ihtimalini kesin hesaplar. 4 ve 2 kuralı kestirmesini ve kesin değeri birlikte gör." },
      { icon: "💰", title: "Pot oranı ve implied odds", body: "Call mu fold mu, hesapla karar ver; implied odds düğmesi sonraki street'lerde kazanmayı beklediğin parayı ekler." },
      { icon: "🃏", title: "El değerlendirici", body: "Kartları seç, el sıralamasını kontrol et. 7 karta kadar gir, en iyi 5 kartlık kombinasyonu otomatik bulsun." },
      { icon: "📊", title: "Başlangıç eli gücü", body: "Elindeki iki kartı seç; 169 başlangıç elinden hangisi olduğunu ve pozisyona göre önerilen hamleyi gör." },
      { icon: "📐", title: "SPR (Stack-to-Pot Ratio)", body: "Stack'in pota oranı ne kadar güçlü bir el gerektiğini söyler. SPR düştükçe güçlü elle bağlanmak o kadar mantıklıdır." },
      { icon: "🏆", title: "Turnuva M değeri", body: "Harrington M, turnuva stack'indeki baskıyı ölçer. Yeşil/sarı/turuncu/kırmızı/ölü bölgeler arasında stratejin tamamen değişir." },
      { icon: "📈", title: "ICM hesaplayıcı", body: "Independent Chip Model turnuva çiplerini gerçek ödül değerine çevirir, yanında chip chop sütunu da var — bubble kararlarının ve final table deal pazarlığının arkasındaki sayılar." },
      { icon: "⚡", title: "Nash push/fold tablosu", body: "Heads-up, 6-max ve 9-max için 13×13 Nash tablosu: 1–25bb'de hangi ellerle open-shove (heads-up'ta ayrıca hangi ellerle call). Turnuvanın son aşamaları için şart." },
    ],
  },

  faq: {
    badge: "SSS",
    h2: "SSS — ICM hesaplayıcı ve Hold'em hesaplayıcıları",
    q: "S. {q}",
  },

  related: {
    badge: "Sıradaki okuma",
    h2: "Hesaplar oturduktan sonra okunacak rehberler",
    // 🔴 tr 코퍼스 8편 전수(EN 8슬러그는 tr에 0개 실재 · fr 선례: related = 실재 글 전수 · 게이트 F항 min(EN 8, 코퍼스)).
    //    title/desc = 각 글의 title·seoTitle·desc 축어 범위 안(settled §3-A · 창작 금지).
    links: [
      { slug: "holdem-tournament-vs-cash-game", title: "Turnuva mı cash game mi?", desc: "Fiş değeri, blind yapısı, bankroll ve ICM baskısı" },
      { slug: "holdem-all-in-rules", title: "All-in ve yan pot kuralları", desc: "Table stakes, ana pot, yan pot ve showdown" },
      { slug: "holdem-hand-rankings", title: "Poker el sıralaması", desc: "En güçlüden en zayıfa 10 poker eli, olasılıklarla" },
      { slug: "holdem-betting-actions", title: "Poker bahis hareketleri", desc: "Check, call, raise, fold ve min-raise kuralı" },
      { slug: "texas-holdem-rules-for-beginners", title: "Poker nasıl oynanır?", desc: "Texas Hold'em kuralları, sıfırdan" },
      { slug: "holdem-blind-meaning", title: "Small ve big blind", desc: "Kim koyar, SB ve BB tutarları, big blind ante" },
      { slug: "holdem-showdown-rules", title: "Showdown ve muck kuralları", desc: "Kartı önce kim açar?" },
      { slug: "holdem-game-order", title: "Hold'em el sırası", desc: "Preflop, flop, turn, river, showdown" },
    ],
  },
};
