// `/es/calculator` 사전 — 공용 `components/calculator/calculator-tool.tsx`가 이 객체 하나로 화면 전체를 그린다.
// ★2026-09-17 신설. 용어 출처(우선순위 순): `docs/translation-terms-es.md` → `lib/posts-es/holdem-glossary.ts`
//   → `lib/posts-es/{holdem-icm,holdem-outs,holdem-pot-odds,holdem-short-stack,holdem-starting-hands-chart}.ts` 실제 표기.
// 🔴 숫자 형식 = EN 그대로(`1,326` · `23.1%` · `$1,500`) → `numberLocale: "en-US"`.
//    근거: es 코퍼스 60편 실측 — 천단위 콤마 1,421곳 vs 점 178곳(그중 65곳은 wsop-2026 가이드 한 편) ·
//    소수점 `.` 1,738곳 vs `,` 10곳 · translation-terms-es.md 「★MANTENER EL FORMATO DE EN TAL CUAL」.
//    통화도 `holdem-icm.ts` L72·L137 그대로 맨 `$`(US$ 0건).
// 🔴 족보 이름은 glossary L138-139 + translation-terms 「TRAMPAS」: Color=flush · Escalera=straight ·
//    Póker=four of a kind · Full=full house. 영어권 관용어(outs·pot odds·equity·ICM·SPR·push/fold·shove·
//    stack·all-in·chip chop·coin flip)는 코퍼스가 원어 그대로 쓰므로 번역하지 않는다.
// 🔴 산문은 «póker»(1,278곳), 검색 표면(title/desc)은 «poker»(솔버 랜딩·seoTitle 관례) — 섞임이 의도다.
import type { CalcDict } from "@/components/calculator/dict";

export const CALC_DICT_ES: CalcDict = {
  numberLocale: "en-US",

  seo: {
    title: "Calculadora de probabilidades de poker — outs, pot odds e ICM",
    description:
      "Calculadora de poker gratis: outs, pot odds, evaluador de manos, manos iniciales, SPR, M de torneo, ICM y tabla push/fold de Nash — 8 herramientas en una.",
    path: "/es/calculator",
  },

  hero: {
    badges: ["Herramienta gratis", "En tiempo real"],
    h1: "Calculadora de probabilidades",
    h1Sub: "Todos los números del Hold'em en un solo lugar",
    lead: "Outs · pot odds · evaluador de manos · fuerza de la mano inicial · SPR · M de torneo · ICM · tabla push/fold de Nash — las matemáticas que necesitas en la mesa, al instante.",
    chips: ["🎯 Outs", "💰 Pot odds", "🃏 Jerarquía", "📊 Mano inicial", "📐 SPR", "🏆 Valor M", "📈 ICM", "⚡ Push/fold"],
  },

  tabs: {
    outs: { label: "Outs", sub: "Odds del proyecto" },
    pot: { label: "Pot odds", sub: "Pagar o foldear" },
    hand: { label: "Jerarquía", sub: "Elige cartas" },
    starting: { label: "Mano inicial", sub: "Fuerza preflop" },
    spr: { label: "SPR", sub: "Stack / bote" },
    m: { label: "M de torneo", sub: "Valor M" },
    icm: { label: "ICM", sub: "Equity en premios" },
    pushfold: { label: "Push/fold", sub: "Tabla de Nash" },
  },

  workspace: {
    chooseCalculator: "Elige una calculadora",
    resetInputs: "Reiniciar valores",
    resetAria: "Reiniciar {label}",
    resetMessage: "Valores de {label} reiniciados.",
  },

  cardPicker: {
    clearAll: "Borrar todo",
  },

  outs: {
    drawType: "Tipo de proyecto",
    presets: [
      { label: "Valor personalizado" },
      { label: "Proyecto de color al nuts", desc: "4 cartas de un palo → falta la 5.ª" },
      { label: "Escalera abierta (OESD)", desc: "p. ej. 5-6-7-8, sirve un 4 o un 9" },
      { label: "Color + gutshot (combo)", desc: "9 de color + 3 de gutshot (solapamiento descontado)" },
      { label: "Gutshot (escalera interior)", desc: "p. ej. 5-6-8-9, solo sirve un 7" },
      { label: "Dos sobrecartas", desc: "2 valores altos que no están en la mesa × 3 cada uno" },
      { label: "Doble pareja → full", desc: "p. ej. A-K en mesa A-K-x → quedan 2 ases + 2 reyes" },
      { label: "Pareja → trío", desc: "quedan 2 cartas de ese valor" },
      { label: "Color + OESD (monstruo)", desc: "9 de color + 8 de escalera (2 repetidas)" },
    ],
    outsSuffix: " ({n} outs)",
    street: "Calle",
    afterFlopBtn: "🃏 Tras el flop",
    afterTurnBtn: "🔄 Tras el turn",
    outsCount: "Número de outs: {v}",
    afterFlop: "Tras el flop",
    afterTurn: "Tras el turn",
    ruleOf4: "Regla del 4",
    ruleOf2: "Regla del 2",
    chanceFlop: "Probabilidad de completar tras el flop",
    chanceTurn: "Probabilidad de completar tras el turn",
    exact: " (exacto)",
    ruleMental: "Regla del {n} (cálculo mental):",
    exactNote: "El valor de arriba es la cifra exacta",
    verdict: { great: "Excelente 🔥", good: "Bueno ✅", fair: "Regular ⚠️", poor: "Malo ❌", veryPoor: "Muy malo 💀" },
  },

  pot: {
    potSize: "Tamaño actual del bote",
    callAmount: "Cantidad a pagar (call)",
    potOddsCaption: "Pot odds (equity mínima necesaria)",
    orHigher: "o más hace rentable el call",
    equityLabel: "Equity de tu mano: {v}",
    sliderGutshot: "Gutshot 8.7%",
    sliderFlush: "Color 19%",
    impliedToggle: "Odds implícitas {toggle}",
    close: "Cerrar ▲",
    add: "Agregar ▼",
    extraWinnings: "Ganancia extra esperada (si ligas): {v}",
    none: "Ninguna",
    impliedCaption: "Odds implícitas (con la ganancia extra)",
    impliedNote: "Equity mínima necesaria contando {n} extra",
    needImplied: "odds implícitas {n}%",
    needPot: "pot odds {n}%",
    verdict: {
      call: { title: "Call (rentable)", body: "Tu equity {eq}% > {need} → rentable a largo plazo" },
      even: { title: "Punto de equilibrio (EV 0)", body: "Tu equity {eq}% = {need} → pagar ni gana ni pierde. Decide por factores fuera de las pot odds, como la posición y las tendencias del rival" },
      fold: { title: "Mejor foldear", body: "Tu equity {eq}% < {need} → pierde a largo plazo" },
    },
  },

  handEval: {
    pickerLabel: "Elige las cartas (5–7)",
    emptyTitle: "Elige 5 cartas o más para evaluar la mano",
    emptyHint: "Con 7 cartas, la mejor combinación de 5 se encuentra sola",
    bestFrom: "Mejor mano con {n} cartas",
    rankNames: [
      "Carta alta", "Pareja", "Doble pareja", "Trío", "Escalera",
      "Color", "Full", "Póker", "Escalera de color", "Escalera real",
    ],
    resultNames: [
      "Carta alta 🃏", "Pareja 1️⃣", "Doble pareja ✌️", "Trío 3️⃣", "Escalera ➡️",
      "Color 🌊", "Full 🏠", "Póker 💎", "Escalera de color 🌟", "Escalera real 👑",
    ],
    axis: ["Carta alta", "Pareja", "Color", "Póker", "Real"],
  },

  starting: {
    pickerLabel: "Elige tus 2 cartas de mano",
    emptyPrompt: "Elige tus 2 cartas de mano",
    unknownDesc: "Mano muy débil",
    unknownAction: "Normalmente fold",
    tierNames: ["🥇 Nivel 1 — Premium", "🥈 Nivel 2 — Fuerte", "🥉 Nivel 3 — Jugable", "⚠️ Nivel 4 — Marginal", "🚫 Nivel 5 — Débil"],
    recommendedAction: "Acción recomendada:",
    axis: ["Premium", "Fuerte", "Jugable", "Marginal", "Débil"],
    summaryTitle: "Resumen por niveles",
    summary: [
      { hands: "AA KK QQ JJ 10-10 AKs AKo", action: "Subir siempre" },
      { hands: "AQs AJs A10s KQs KJs 99 88 AQo", action: "Subir desde casi cualquier posición" },
      { hands: "AJo KQo K10s QJs J10s 10-9s 77 A9s", action: "Subir en posición tardía" },
      { hands: "66–55 A8s–A2s KJo QJo conectores del mismo palo", action: "Con selección en posición tardía" },
      { hands: "44–22 manos débiles de distinto palo", action: "Normalmente fold" },
    ],
    hands: {
      AA: { desc: "La mejor mano. Sube en cualquier spot", action: "Subir/resubir siempre (3-bet)" },
      KK: { desc: "Solo vigila que no salga un as en el flop", action: "Subir/resubir siempre" },
      QQ: { desc: "Más fuerte que JJ, pero no la sobrevalores", action: "Subir siempre; cuidado con stacks profundos" },
      JJ: { desc: "Vigila las sobrecartas en el flop", action: "Subir desde cualquier posición" },
      "1010": { desc: "Pierde valor cuando el flop trae sobrecartas", action: "Subir en posición media/tardía, en temprana plantéate pagar" },
      AKs: { desc: "La mejor mano con proyecto. Construye el bote", action: "Subir/resubir siempre" },
      AKo: { desc: "Más débil que AKs, pero sigue siendo premium", action: "Subir siempre; puede pagar una resubida" },
      AQs: { desc: "Mano fuerte; vale más en posición", action: "Subir desde casi cualquier posición" },
      AJs: { desc: "Muy buena en BTN/CO, floja desde UTG", action: "Subir en posición media/tardía, en temprana plantéate pagar" },
      A10s: { desc: "Uno de los mejores ases del mismo palo", action: "Subir en posición tardía, pagar en temprana" },
      KQs: { desc: "Potencial de color alto + escalera", action: "Subir desde casi cualquier posición" },
      KJs: { desc: "Mano fuerte con proyectos", action: "Subir en posición tardía, pagar en temprana" },
      "99": { desc: "Par medio, vigila los flops con sobrecartas", action: "Subir desde casi cualquier posición; cuidado con stacks profundos" },
      "88": { desc: "Par servido con buen potencial de set", action: "Subir en posición tardía, en temprana plantéate pagar" },
      AQo: { desc: "Más floja de distinto palo; la posición importa", action: "Subir en posición media/tardía" },
      AJo: { desc: "Floja en posición temprana, fuerte en tardía", action: "Subir en CO/BTN, cuidado en temprana" },
      KQo: { desc: "El mejor conector de distinto palo", action: "Subir en posición tardía, pagar/fold en temprana" },
      K10s: { desc: "Rey del mismo palo, fuerte en posición tardía", action: "Subir en tardía, fold en temprana" },
      QJs: { desc: "Proyectos fuertes por los dos lados", action: "Subir en tardía, vale más con stacks profundos" },
      J10s: { desc: "Uno de los mejores conectores del mismo palo", action: "Subir en tardía, pagar en temprana con pot odds" },
      "109s": { desc: "Conector del mismo palo fuerte", action: "Subir/pagar en posición tardía" },
      "77": { desc: "Mano para buscar set, vigila las sobrecartas", action: "Subir en tardía, pagar en temprana" },
      A9s: { desc: "As del mismo palo con potencial de color", action: "Subir en posición tardía" },
      "66": { desc: "Para buscar set; necesita pot odds", action: "Pagar/subir en tardía, mejor en botes multiway" },
      "55": { desc: "Poco valor sin ligar set", action: "Pagar en tardía, en botes con una sola subida" },
      A8s: { desc: "As medio del mismo palo", action: "Jugar en tardía, fold en temprana" },
      A7s: { desc: "As medio del mismo palo", action: "Solo en posición tardía" },
      A6s: { desc: "As medio del mismo palo", action: "Solo en posición tardía" },
      A5s: { desc: "Rueda + bloqueador de as; un 3-bet de farol favorito", action: "Solo en tardía; las odds implícitas importan" },
      A4s: { desc: "As del mismo palo con proyecto de rueda", action: "Solo en posición tardía" },
      A3s: { desc: "El fondo de los ases del mismo palo", action: "Solo BTN/SB" },
      A2s: { desc: "Rueda + color al nuts, pero débil", action: "Solo BTN" },
      KJo: { desc: "Riesgo de dominación; solo en tardía", action: "Subir en CO/BTN, fold ante una resubida" },
      QJo: { desc: "Conectividad moderada; necesita posición", action: "Solo en posición tardía" },
      "98s": { desc: "Conector del mismo palo fuerte", action: "Pagar/subir en posición tardía" },
      "87s": { desc: "Buen conector del mismo palo", action: "Pagar en posición tardía" },
      "76s": { desc: "Conector del mismo palo", action: "Pagar en tardía con pot odds" },
      "44": { desc: "Casi sin valor si no liga set", action: "Pagar solo con pot odds baratas" },
      "33": { desc: "Tiene que buscar set; especulativa", action: "Botes multiway, solo calls baratos" },
      "22": { desc: "El par servido más bajo", action: "Botes multiway, solo calls baratos" },
      K10o: { desc: "K-10 de distinto palo, débil", action: "De vez en cuando desde el BTN" },
      Q10o: { desc: "Poca conectividad y distinto palo", action: "Solo BTN" },
      J10o: { desc: "Aceptable de distinto palo, pero vulnerable", action: "De vez en cuando desde el BTN" },
      Q10s: { desc: "Broadway del mismo palo fuerte, juega bien en posición", action: "Subir en tardía, pagar en temprana con pot odds" },
      A10o: { desc: "As marginal de distinto palo, fácil de dominar", action: "Solo en posición tardía" },
      "65s": { desc: "Conector del mismo palo; quiere botes multiway y odds implícitas", action: "Pagar en posición tardía" },
      "54s": { desc: "Conector bajo del mismo palo; especulativo", action: "Pagar en tardía, botes multiway baratos" },
    },
  },

  spr: {
    effectiveStack: "Stack efectivo (el tuyo)",
    potSize: "Tamaño actual del bote",
    caption: "SPR (Stack-to-Pot Ratio)",
    stackDivPot: "stack ÷ bote",
    zones: {
      low: {
        label: "SPR bajo (comprometido)",
        desc: "Una gran parte del bote ya está dentro. Con pareja máxima y kicker máximo o mejor, plantéate ir all-in — foldear aquí puede ser un error.",
        actions: [["TPTK+", "Plantéate el all-in"], ["Proyectos", "Pot odds obligatorias"], ["Manos débiles", "Foldea con cuidado"]],
      },
      mid: {
        label: "SPR medio (flexible)",
        desc: "Es la zona para jugar manos fuertes como doble pareja o mejor. Proteger tu stack empieza a importar.",
        actions: [["Doble pareja+", "Apuesta de valor"], ["Una pareja", "Juégala según la lectura"], ["Proyectos", "Pesa riesgo y recompensa"]],
      },
      high: {
        label: "SPR alto (stacks profundos)",
        desc: "Los stacks empiezan a ser profundos. Los proyectos y las manos hechas fuertes ganan valor relativo.",
        actions: [["Set+", "Juega fuerte"], ["Proyectos", "Suben las odds implícitas"], ["Una pareja/TPTK", "Avanza con cuidado"]],
      },
      deep: {
        label: "SPR muy alto (deep)",
        desc: "Es una partida de stacks profundos. La posición, el potencial del proyecto y leer el rango del rival importan mucho.",
        actions: [["Los nuts", "Puedes apostar grande"], ["Proyectos", "Odds implícitas altísimas"], ["Manos hechas débiles", "Cuidado, vulnerables a faroles"]],
      },
    },
    legend: ["Comprometido", "Flexible", "Casi profundo", "Profundo"],
  },

  m: {
    inputs: { stack: "Tu stack", bb: "Ciega grande", sb: "Ciega pequeña", ante: "Ante" },
    players: "Jugadores en la mesa: {v}",
    headsUp: "2 (mano a mano)",
    orbitCaption: "Costo por órbita (ciegas por vuelta)",
    orbitFormula: "BB {bb} + SB {sb} + ante {ante}×{players}",
    mCaption: "Valor M (la M de Harrington)",
    zones: {
      dead: { name: "💀 Zona muerta", desc: "Tienes que ir all-in ya. No hay margen para esperar una mano mejor — mete todo con la mejor mano que te llegue.", action: "All-in ya" },
      red: { name: "🔴 Zona roja", desc: "Necesitas doblarte pronto. Juega push/fold — shove con tus buenas manos y fold con el resto.", action: "Push/fold" },
      orange: { name: "🟠 Zona naranja", desc: "Tu stack se está encogiendo. Cierra tu rango a manos fuertes y busca hacer open-shove.", action: "Rango cerrado" },
      yellow: { name: "🟡 Zona amarilla", desc: "Empieza la presión. Tienes que acumular fichas de forma activa — juega agresivo cuando aparezcan buenos spots.", action: "Juega agresivo" },
      green: { name: "🟢 Zona verde", desc: "Tienes un stack cómodo. Usa todo tu repertorio — haz crecer tu stack con juego posicional y faroles.", action: "Estrategia completa" },
    },
  },

  icm: {
    introStrong: "El ICM (Independent Chip Model)",
    introRest: " es la forma de calcular el valor real en dinero de tus fichas de torneo. Hasta el valor ICM del chip leader es menor que su porcentaje de fichas, mientras que los stacks cortos valen más que el suyo. Úsalo para decidir call o fold en la mesa final y en la burbuja.",
    numPlayers: "Número de jugadores",
    paidPlaces: "Puestos pagados",
    stacksTitle: "Stacks de los jugadores",
    total: "total {n}",
    decStack: "Reducir el stack del jugador {n}",
    stackInput: "Stack del jugador {n}",
    incStack: "Aumentar el stack del jugador {n}",
    prizesTitle: "Premios",
    decPrize: "Reducir el premio del puesto {n}",
    prizeInput: "Premio del puesto {n}",
    incPrize: "Aumentar el premio del puesto {n}",
    currencyNote: "Escribe los premios en la moneda que quieras.",
    resultTitle: "Resultado ICM",
    th: { player: "Jugador", chips: "Fichas", chipPct: "% fichas", icmValue: "Valor ICM", icmPct: "ICM %", diff: "Dif." },
    playerCell: "{medal} J{n}",
    diffPlus: "+dif.",
    diffPlusNote: "Valor ICM por encima del % de fichas → zona de protección del stack corto, evita los coin flips",
    diffMinus: "−dif.",
    diffMinusNote: "Valor ICM por debajo del % de fichas → la agresión del chip leader rinde más",
    empty: "Pon stacks y premios mayores que cero para ver el resultado ICM.",
  },

  pushfold: {
    ante: "Ante",
    noAnte: "Sin ante",
    bbAnteOn: "BB ante activado",
    table: "Mesa",
    headsUp: "Heads-up",
    sixMax: "6-max",
    nineMax: "9-max",
    scenario: "Escenario",
    sbShove: "SB: shove o fold",
    bbCall: "BB: pagar un shove",
    position: "Posición {hint}",
    firstInHint: "(first-in — todos foldearon hasta ti)",
    effectiveStack: "Stack efectivo: {v}",
    captionHuPush: "Manos con las que la SB va de shove a {stack}bb",
    captionHuCall: "Manos con las que la BB paga un shove a {stack}bb",
    captionMw: "Shove first-in desde {pos} en mesa {table}-max, {stack}bb",
    withAnte: " (con ante)",
    combosSuffix: " / {total} combos",
    legendPush: "Push (all-in)",
    legendCall: "Call",
    legendFold: "Fold",
    note: {
      strong1: "Diagonal = pares · arriba a la derecha = mismo palo · abajo a la izquierda = distinto palo",
      p1: "La tabla está ordenada por ",
      strong2: "valor de las cartas, no por fuerza",
      p2: ", así que es normal que en una misma fila se alternen celdas marcadas y sin marcar — AQo, KQo y QQ están juntas pero no en orden de fuerza. Que A5s entre y A6s no también es correcto: A5s forma la",
      strong3: "escalera de rueda (A-2-3-4-5)",
      p3: ", y eso pesa más que el kicker inferior.",
    },
    cellTitle: "{hand} — {action}",
    cell: { push: "push", call: "call", fold: "fold" },
    huNote: {
      strong: "Equilibrio de Nash, mano a mano (SB vs BB)",
      p1: ": se asume que la SB solo hace shove o fold. La opción de ante suma 0.125bb por jugador (equivalente a un big blind ante, ≈12.5%). Los rangos se amplían cuanto más cortos son los stacks — y por debajo de ~3-4bb la BB paga correctamente ",
      em: "más amplio",
      p2: " de lo que la SB hace shove, por las pot odds.",
    },
    mwNote: {
      strong: "Tabla de shove first-in en mesa {table}-max",
      p1: ": todos los de delante han foldeado y tú haces shove o fold. Es un equilibrio tipo Nash de ",
      strong2: "chip EV puro",
      p2: " — los rangos de call de los jugadores que quedan detrás se resuelven a la vez — con la aproximación estándar de que un bote pagado se resuelve mano a mano contra el primero que paga (se ignoran los botes con varios calls). Los rangos se amplían cuantos menos jugadores quedan detrás de ti (UTG → BTN → SB), cuanto más cortos son los stacks y con los antes activados (0.125bb por jugador). Como es chip EV puro, los rangos de 10bb desde posición temprana (UTG/MP) salen más cerrados que las reglas populares (los pares bajos foldean) — en la práctica, ajusta por ICM y por los rivales.",
    },
    readMore: "Para los fundamentos del juego con stack corto, lee nuestra",
    shortStackLink: { slug: "holdem-short-stack", text: "guía de estrategia short stack" },
    readMoreEnd: ".",
  },

  icmGuide: {
    bubble: {
      badge: "Guía ICM",
      h2: "Cómo usar la calculadora de ICM — un ejemplo de burbuja en 3 minutos",
      intro: "Supón que quedan cuatro jugadores y cobran tres (la burbuja). Los stacks son 60,000 / 40,000 / 30,000 / 20,000 y los premios, $500 / $300 / $200. Mételos en la calculadora y obtienes el porcentaje de fichas de cada jugador frente a su valor real en premios (ICM):",
      th: { player: "Jugador", chipPct: "% fichas", icmPct: "ICM %", diff: "Dif." },
      rows: [
        { player: "🥇 Chip leader", chip: "40.0%", icm: "33.3%", diff: "-6.7 pts", up: false },
        { player: "🥈 2.º", chip: "26.7%", icm: "27.2%", diff: "+0.6 pts", up: true },
        { player: "🥉 3.º", chip: "20.0%", icm: "22.9%", diff: "+2.9 pts", up: true },
        { player: "4.º (stack corto)", chip: "13.3%", icm: "16.6%", diff: "+3.3 pts", up: true },
      ],
      keyPoint: {
        text: "La clave: {b1} por 6.7 puntos. Como ganar solo paga el premio del 1.º, el líder gana menos valor en premios con un coin flip de lo que sugiere su cantidad de fichas. Por eso en la burbuja el líder debería {b2}, mientras que el stack corto (13.3% de fichas → 16.6% ICM) vale más que sus fichas y debería {b3} para proteger ese valor de supervivencia.",
        b1: "el valor ICM del chip leader (33.3%) es menor que su porcentaje de fichas (40%)",
        b2: "presionar a los stacks cortos",
        b3: "evitar calls all-in innecesarios",
      },
    },
    deal: {
      badge: "Reparto de premios",
      h2: "Acuerdo por ICM vs chip chop — cómo repartir la bolsa de premios",
      intro: "Ahora quedan tres jugadores y están negociando un acuerdo. Con stacks del 50% / 30% / 20% y $1,500 de premios por repartir, los dos métodos reparten de forma muy distinta:",
      th: { player: "Jugador", chop: "Chip chop", icm: "Acuerdo ICM", diff: "Dif." },
      rows: [
        { player: "🥇 Chip leader (50%)", chop: "$750", icm: "$618", diff: "-$132", up: false },
        { player: "🥈 2.º (30%)", chop: "$450", icm: "$485", diff: "+$35", up: true },
        { player: "🥉 Stack corto (20%)", chop: "$300", icm: "$397", diff: "+$97", up: true },
      ],
      summary: {
        text: "El chip chop reparte según el porcentaje de fichas y {b1}; el acuerdo por ICM refleja las probabilidades de terminar en cada puesto y es {b2}. Arriba, el stack corto se lleva $300 con un chip chop pero unos $397 con un acuerdo por ICM — {b3}. Pide un acuerdo por ICM cuando vas corto; propón un chip chop cuando eres el líder.",
        b1: "favorece al chip leader",
        b2: "más justo con los stacks cortos",
        b3: "$97 más",
      },
    },
  },

  guide: {
    badge: "Herramientas",
    h2: "Cómo usar las 8 calculadoras de Hold'em",
    cards: [
      { title: "Calculadora de outs", body: "Calcula con precisión la probabilidad de que tu proyecto entre en el flop o en el turn. Ves a la vez el atajo de la regla del 2 y 4 y la cifra exacta." },
      { title: "Pot odds y odds implícitas", body: "Decide con matemáticas si pagar o foldear. Cuando el rival tiene un stack profundo, agrega las odds implícitas para una decisión más precisa." },
      { title: "Evaluador de manos", body: "Elige cartas para ver qué mano tienes según la jerarquía. Mete hasta 7 cartas y encuentra sola la mejor combinación de 5." },
      { title: "Fuerza de la mano inicial", body: "Elige tus dos cartas de mano para ver cuál de las 169 manos es y la acción recomendada según la posición." },
      { title: "SPR (Stack-to-Pot Ratio)", body: "La relación entre stack y bote te dice cuánta mano necesitas. Cuanto más bajo el SPR, más favorece comprometerse con una mano fuerte." },
      { title: "M de torneo", body: "La M de Harrington mide la presión sobre tu stack de torneo. Tu estrategia cambia por completo entre las zonas verde, amarilla, naranja, roja y muerta." },
      { title: "Calculadora de ICM", body: "El Independent Chip Model convierte las fichas de torneo en valor real en premios — imprescindible para decidir call o fold y para negociar acuerdos en la burbuja y en la mesa final." },
      { title: "Tabla push/fold de Nash", body: "Una tabla 13×13 mano a mano calculada a partir del equilibrio de Nash: con qué manos hacer open-shove y con cuáles pagar de 1 a 25bb. Imprescindible en las fases finales de un torneo." },
    ],
  },

  faq: {
    badge: "FAQ",
    h2: "Preguntas frecuentes sobre la calculadora de ICM y de Hold'em",
    q: "Q. {q}",
  },

  related: {
    badge: "Profundiza",
    h2: "Guías para leer cuando los números ya te cuadren",
    links: [
      { slug: "holdem-tournament", title: "Cómo funcionan los torneos de póker", desc: "ICM, la burbuja y la mesa final" },
      { slug: "holdem-equity", title: "El equity en el póker explicado", desc: "% de victoria, fold equity y realización" },
      { slug: "holdem-pot-odds", title: "Cómo calcular las pot odds", desc: "Convierte cada call o fold en matemáticas" },
      { slug: "holdem-outs", title: "Cómo contar outs", desc: "Outs por proyecto y la regla del 2 y 4" },
      { slug: "holdem-probability", title: "Probabilidades en el póker", desc: "Los números clave detrás de cada mano" },
      { slug: "holdem-starting-hands-chart", title: "Tabla de manos iniciales", desc: "Qué manos jugar según la posición" },
    ],
  },
};
