// `/pt/calculator` 사전 — `components/calculator/dict.ts`의 `CalcDict`를 pt-BR로 채운 것.
// ★2026-09-17 신설. 공용 컴포넌트 `components/calculator/calculator-tool.tsx`가 이 객체 하나로 화면 전체를 그린다.
// 용어 출처(우선순위 순): `docs/translation-terms-pt.md` → `lib/posts-pt/holdem-glossary.ts` →
//   `lib/posts-pt/holdem-outs.ts`·`holdem-pot-odds.ts`·`holdem-icm.ts`·`holdem-short-stack.ts`·`holdem-hand-rankings.ts`.
// 판단: ① outs·pot odds·equity·ICM·SPR·push/fold·all-in·draw·flush·kicker·stack은 코퍼스대로 영어 유지
//       ② call→pagar · raise→aumentar · pot→pote · check→dar check(translation-terms-pt «용어» 절)
//       ③ 숫자는 브라질식(천단위 `.` · 소수 `,`) — numberLocale "pt-BR" · 통화는 §13 보존을 위해 `$` 유지(holdem-icm.ts 동일)
//       ④ 족보 이름은 `holdem-hand-rankings.ts` tldr 축어(Carta Alta … Royal Flush)
import type { CalcDict } from "@/components/calculator/dict";

export const CALC_DICT_PT: CalcDict = {
  numberLocale: "pt-BR",

  seo: {
    title: "Calculadora de probabilidades de poker — outs, pot odds e ICM",
    description: "Calculadora de poker grátis: outs, pot odds, ranking de mãos, mão inicial, SPR, M-ratio de torneio, ICM e tabela push/fold de Nash — 8 ferramentas em uma.",
    path: "/pt/calculator",
  },

  hero: {
    badges: ["Ferramenta grátis", "Em tempo real"],
    h1: "Calculadora de probabilidades de poker",
    h1Sub: "Todos os números do Hold'em em um só lugar",
    lead: "Outs · pot odds · ranking de mãos · força da mão inicial · SPR · M-ratio de torneio · ICM · tabela push/fold de Nash — a conta que você precisa na mesa, na hora.",
    chips: ["🎯 Outs", "💰 Pot Odds", "🃏 Ranking de mãos", "📊 Mão inicial", "📐 SPR", "🏆 M-ratio", "📈 ICM", "⚡ Push/Fold"],
  },

  tabs: {
    outs: { label: "Outs", sub: "Odds de draw" },
    pot: { label: "Pot Odds", sub: "Pagar/foldar" },
    hand: { label: "Ranking de mãos", sub: "Escolha as cartas" },
    starting: { label: "Mão inicial", sub: "Força de abertura" },
    spr: { label: "SPR", sub: "Stack/pote" },
    m: { label: "M de torneio", sub: "M-ratio" },
    icm: { label: "ICM", sub: "Equity de premiação" },
    pushfold: { label: "Push/Fold", sub: "Tabela de Nash" },
  },

  workspace: {
    chooseCalculator: "Escolha uma calculadora",
    resetInputs: "Limpar valores",
    resetAria: "Limpar {label}",
    resetMessage: "Valores de {label} limpos.",
  },

  cardPicker: {
    clearAll: "Limpar tudo",
  },

  outs: {
    drawType: "Tipo de draw",
    presets: [
      { label: "Valor personalizado" },
      { label: "Nut flush draw", desc: "4 cartas do mesmo naipe → falta a 5ª" },
      { label: "Straight draw aberto (OESD)", desc: "ex.: 5-6-7-8, precisa de um 4 ou de um 9" },
      { label: "Flush + gutshot (combo)", desc: "9 de flush + 3 de gutshot (sem a carta repetida)" },
      { label: "Gutshot (sequência interna)", desc: "ex.: 5-6-8-9, precisa só de um 7" },
      { label: "Duas overcards", desc: "2 valores altos fora do board × 3 cartas cada" },
      { label: "Dois pares → full house", desc: "ex.: A-K num board A-K-x → sobram 2 ases + 2 reis" },
      { label: "Par → trinca", desc: "sobram 2 cartas do mesmo valor" },
      { label: "Flush + OESD (monstro)", desc: "9 de flush + 8 de sequência (2 repetidas)" },
    ],
    outsSuffix: " ({n} outs)",
    street: "Street",
    afterFlopBtn: "🃏 Depois do flop",
    afterTurnBtn: "🔄 Depois do turn",
    outsCount: "Número de outs: {v}",
    afterFlop: "Depois do flop",
    afterTurn: "Depois do turn",
    ruleOf4: "Regra do 4",
    ruleOf2: "Regra do 2",
    chanceFlop: "Chance de completar depois do flop",
    chanceTurn: "Chance de completar depois do turn",
    exact: " (exato)",
    ruleMental: "Regra do {n} (conta de cabeça):",
    exactNote: "O valor acima é o número exato",
    verdict: { great: "Ótimo 🔥", good: "Bom ✅", fair: "Razoável ⚠️", poor: "Fraco ❌", veryPoor: "Muito fraco 💀" },
  },

  pot: {
    potSize: "Tamanho atual do pote",
    callAmount: "Valor que você precisa pagar",
    potOddsCaption: "Pot odds (equity mínima necessária)",
    orHigher: "ou mais torna o call lucrativo",
    equityLabel: "Equity da sua mão: {v}",
    sliderGutshot: "Gutshot 8,7%",
    sliderFlush: "Flush 19%",
    impliedToggle: "Implied odds {toggle}",
    close: "Fechar ▲",
    add: "Adicionar ▼",
    extraWinnings: "Ganho extra esperado (se acertar): {v}",
    none: "Nenhum",
    impliedCaption: "Implied odds (com o ganho extra)",
    impliedNote: "Equity mínima necessária, contando {n} a mais",
    needImplied: "implied odds de {n}%",
    needPot: "pot odds de {n}%",
    verdict: {
      call: { title: "Pague (lucrativo)", body: "Sua equity de {eq}% > {need} → lucrativo no longo prazo" },
      even: { title: "Empate (EV 0)", body: "Sua equity de {eq}% = {need} → pagar não ganha nem perde. Decida por fatores fora das pot odds, como posição e tendências do adversário" },
      fold: { title: "Fold recomendado", body: "Sua equity de {eq}% < {need} → perde no longo prazo" },
    },
  },

  handEval: {
    pickerLabel: "Selecione as cartas (5–7)",
    emptyTitle: "Escolha 5 cartas ou mais para avaliar a mão",
    emptyHint: "Com 7 cartas, a melhor combinação de 5 é encontrada automaticamente",
    bestFrom: "Melhor mão com {n} cartas",
    rankNames: [
      "Carta Alta", "Par", "Dois Pares", "Trinca", "Sequência",
      "Flush", "Full House", "Quadra", "Straight Flush", "Royal Flush",
    ],
    resultNames: [
      "Carta Alta 🃏", "Par 1️⃣", "Dois Pares ✌️", "Trinca 3️⃣", "Sequência ➡️",
      "Flush 🌊", "Full House 🏠", "Quadra 💎", "Straight Flush 🌟", "Royal Flush 👑",
    ],
    axis: ["Carta Alta", "Par", "Flush", "Quadra", "Royal"],
  },

  starting: {
    pickerLabel: "Selecione suas 2 cartas fechadas",
    emptyPrompt: "Escolha suas 2 cartas fechadas",
    unknownDesc: "Mão muito fraca",
    unknownAction: "Geralmente fold",
    tierNames: ["🥇 Tier 1 — Premium", "🥈 Tier 2 — Forte", "🥉 Tier 3 — Jogável", "⚠️ Tier 4 — Marginal", "🚫 Tier 5 — Fraca"],
    recommendedAction: "Ação recomendada:",
    axis: ["Premium", "Forte", "Jogável", "Marginal", "Fraca"],
    summaryTitle: "Resumo por tier",
    summary: [
      { hands: "AA KK QQ JJ 10-10 AKs AKo", action: "Sempre aumente" },
      { hands: "AQs AJs A10s KQs KJs 99 88 AQo", action: "Aumente da maioria das posições" },
      { hands: "AJo KQo K10s QJs J10s 10-9s 77 A9s", action: "Aumente de posição tardia" },
      { hands: "66–55 A8s–A2s KJo QJo suited connectors", action: "Seletivo em LP" },
      { hands: "44–22 mãos offsuit fracas", action: "Geralmente fold" },
    ],
    hands: {
      AA: { desc: "A melhor mão. Aumente em qualquer spot", action: "Sempre aumente/re-aumente (3-bet)" },
      KK: { desc: "Só fique de olho num ás no flop", action: "Sempre aumente/re-aumente" },
      QQ: { desc: "Mais forte que JJ, mas não supervalorize", action: "Sempre aumente; cuidado com stacks profundos" },
      JJ: { desc: "Cuidado com overcards no flop", action: "Aumente de qualquer posição" },
      "1010": { desc: "Perde valor quando vêm overcards no flop", action: "Aumente de MP/LP, considere pagar em EP" },
      AKs: { desc: "A melhor mão de draw. Construa o pote", action: "Sempre aumente/re-aumente" },
      AKo: { desc: "Mais fraca que AKs, mas ainda premium", action: "Sempre aumente; pode pagar um re-aumento" },
      AQs: { desc: "Mão forte; vale mais em posição", action: "Aumente da maioria das posições" },
      AJs: { desc: "Ótima no BTN/CO, fraca do UTG", action: "Aumente de MP/LP, considere pagar em EP" },
      A10s: { desc: "Um dos melhores ases suited", action: "Aumente em LP, pague em EP" },
      KQs: { desc: "Potencial de flush alto + straight draw", action: "Aumente da maioria das posições" },
      KJs: { desc: "Mão de draw forte", action: "Aumente em LP, pague em EP" },
      "99": { desc: "Par médio, cuidado com flops de overcards", action: "Aumente da maioria das posições; cuidado deep" },
      "88": { desc: "Pocket pair com bom potencial de set", action: "Aumente em LP, considere pagar em EP" },
      AQo: { desc: "Offsuit mais fraco; a posição importa", action: "Aumente de posição média/tardia" },
      AJo: { desc: "Fraca em EP, forte em LP", action: "Aumente do CO/BTN, cuidado em EP" },
      KQo: { desc: "O melhor conector offsuit", action: "Aumente em LP, pague/folde em EP" },
      K10s: { desc: "Rei suited, forte em LP", action: "Aumente em LP, folde em EP" },
      QJs: { desc: "Draws fortes dos dois lados", action: "Aumente em LP, vale mais com stacks profundos" },
      J10s: { desc: "Um dos melhores suited connectors", action: "Aumente em LP, pague em EP pelas pot odds" },
      "109s": { desc: "Suited connector forte", action: "Aumente/pague em LP" },
      "77": { desc: "Mão de set mining, cuidado com overcards", action: "Aumente em LP, pague em EP" },
      A9s: { desc: "Ás suited com potencial de flush", action: "Aumente em LP" },
      "66": { desc: "Set mining; precisa de pot odds", action: "Pague/aumente em LP, melhor em pote multiway" },
      "55": { desc: "Pouco valor sem um set", action: "Pague em LP, em potes de um aumento só" },
      A8s: { desc: "Ás suited médio", action: "Jogue em LP, folde em EP" },
      A7s: { desc: "Ás suited médio", action: "Só em LP" },
      A6s: { desc: "Ás suited médio", action: "Só em LP" },
      A5s: { desc: "Wheel + valor de bloqueio do ás; blefe de 3-bet favorito", action: "Só em LP; as implied odds importam" },
      A4s: { desc: "Ás suited com draw de wheel", action: "Só em LP" },
      A3s: { desc: "O fundo dos ases suited", action: "Só no BTN/SB" },
      A2s: { desc: "Wheel + nut flush, mas fraca", action: "Só no BTN" },
      KJo: { desc: "Risco de dominação; só em LP", action: "Aumente do CO/BTN, folde a um re-aumento" },
      QJo: { desc: "Conectividade moderada; precisa de posição", action: "Só em LP" },
      "98s": { desc: "Suited connector forte", action: "Pague/aumente em LP" },
      "87s": { desc: "Bom suited connector", action: "Pague em LP" },
      "76s": { desc: "Suited connector", action: "Pague em LP pelas pot odds" },
      "44": { desc: "Quase nenhum valor sem um set", action: "Pague só com pot odds baratas" },
      "33": { desc: "Precisa de set mining; especulativa", action: "Potes multiway, só calls baratos" },
      "22": { desc: "O menor pocket pair", action: "Potes multiway, só calls baratos" },
      K10o: { desc: "K-10 offsuit, fraca", action: "De vez em quando do BTN" },
      Q10o: { desc: "Offsuit de pouca conectividade", action: "Só no BTN" },
      J10o: { desc: "Offsuit razoável, mas vulnerável", action: "De vez em quando do BTN" },
      Q10s: { desc: "Broadway suited forte, joga bem em posição", action: "Aumente em LP, pague em EP pelas pot odds" },
      A10o: { desc: "Ás offsuit marginal, fácil de ser dominado", action: "Só em LP" },
      "65s": { desc: "Suited connector; quer multiway/implied odds", action: "Pague em LP" },
      "54s": { desc: "Suited connector baixo; especulativo", action: "Pague em LP, potes multiway baratos" },
    },
  },

  spr: {
    effectiveStack: "Stack efetivo (o seu)",
    potSize: "Tamanho atual do pote",
    caption: "SPR (Stack-to-Pot Ratio)",
    stackDivPot: "stack ÷ pote",
    zones: {
      low: {
        label: "SPR baixo (comprometido)",
        desc: "Boa parte do pote já está no meio. Com top pair top kicker ou melhor, considere ir de all-in — foldar aqui pode ser um erro.",
        actions: [["TPTK+", "Considere o all-in"], ["Draws", "Pot odds são obrigatórias"], ["Mãos fracas", "Folde com cuidado"]],
      },
      mid: {
        label: "SPR médio (flexível)",
        desc: "É a zona para jogar mãos fortes como dois pares ou melhor. Proteger o stack passa a importar.",
        actions: [["Dois pares+", "Aposte por valor"], ["Um par", "Jogue pela leitura"], ["Draws", "Pese risco e recompensa"]],
      },
      high: {
        label: "SPR alto (ficando deep)",
        desc: "Os stacks estão ficando profundos. Draws e mãos feitas fortes sobem de valor relativo.",
        actions: [["Set+", "Jogue forte"], ["Draws", "As implied odds sobem"], ["Um par/TPTK", "Siga com cautela"]],
      },
      deep: {
        label: "SPR muito alto (deep)",
        desc: "É um jogo de stacks profundos. Posição, potencial de draw e leitura do range do adversário pesam muito.",
        actions: [["Mãos nut", "Pode apostar grande"], ["Draws", "Implied odds altíssimas"], ["Mãos feitas fracas", "Cuidado, vulneráveis a blefes"]],
      },
    },
    legend: ["Comprometido", "Flexível", "Ficando deep", "Deep"],
  },

  m: {
    inputs: { stack: "Seu stack", bb: "Big blind", sb: "Small blind", ante: "Ante" },
    players: "Jogadores na mesa: {v}",
    headsUp: "2 (heads-up)",
    orbitCaption: "Custo da órbita (blinds por volta)",
    orbitFormula: "BB {bb} + SB {sb} + ante {ante}×{players}",
    mCaption: "M-ratio (o M de Harrington)",
    zones: {
      dead: { name: "💀 Zona morta", desc: "Você precisa ir de all-in imediatamente. Não dá para esperar uma mão melhor — dê shove com a melhor mão que aparecer.", action: "All-in agora" },
      red: { name: "🔴 Zona vermelha", desc: "Você precisa dobrar logo. Use push/fold — dê shove com as mãos boas e folde o resto.", action: "Push/fold" },
      orange: { name: "🟠 Zona laranja", desc: "Seu stack está encolhendo. Feche o range só para mãos fortes e procure spots de open-shove.", action: "Range fechado" },
      yellow: { name: "🟡 Zona amarela", desc: "A pressão chegou. Você precisa acumular fichas ativamente — jogue agressivo quando aparecerem bons spots.", action: "Jogue agressivo" },
      green: { name: "🟢 Zona verde", desc: "Você tem um stack confortável. Use o repertório inteiro — cresça o stack com jogo de posição e blefes.", action: "Estratégia completa" },
    },
  },

  icm: {
    introStrong: "ICM (Independent Chip Model)",
    introRest: " é a forma de calcular o valor real em dinheiro das suas fichas de torneio. Até o chip leader tem um valor de ICM menor que a sua fatia de fichas, enquanto os short stacks valem mais do que a deles. Use para decisões de pagar/foldar na final table e na bolha.",
    numPlayers: "Número de jogadores",
    paidPlaces: "Posições pagas",
    stacksTitle: "Stacks dos jogadores",
    total: "total {n}",
    decStack: "Diminuir o stack do jogador {n}",
    stackInput: "Stack do jogador {n}",
    incStack: "Aumentar o stack do jogador {n}",
    prizesTitle: "Prêmios",
    decPrize: "Diminuir o prêmio do {n}º lugar",
    prizeInput: "Prêmio do {n}º lugar",
    incPrize: "Aumentar o prêmio do {n}º lugar",
    currencyNote: "Digite os prêmios em qualquer moeda.",
    resultTitle: "Resultado do ICM",
    th: { player: "Jogador", chips: "Fichas", chipPct: "% de fichas", icmValue: "Valor ICM", icmPct: "% ICM", diff: "Dif." },
    playerCell: "{medal} J{n}",
    diffPlus: "+dif.",
    diffPlusNote: "Valor de ICM acima da fatia de fichas → zona de proteção do short stack, evite coin flips",
    diffMinus: "−dif.",
    diffMinusNote: "Valor de ICM abaixo da fatia de fichas → a agressão do chip leader rende mais",
    empty: "Defina stacks e prêmios acima de zero para ver o resultado do ICM.",
  },

  pushfold: {
    ante: "Ante",
    noAnte: "Sem ante",
    bbAnteOn: "BB ante ON",
    table: "Mesa",
    headsUp: "Heads-Up",
    sixMax: "6-max",
    nineMax: "9-max",
    scenario: "Cenário",
    sbShove: "SB: shove ou fold",
    bbCall: "BB: pagar um shove",
    position: "Posição {hint}",
    firstInHint: "(first-in — todos foldaram até você)",
    effectiveStack: "Stack efetivo: {v}",
    captionHuPush: "Mãos com que o SB dá shove com {stack}bb",
    captionHuCall: "Mãos com que o BB paga um shove com {stack}bb",
    captionMw: "Shove first-in do {pos} numa mesa {table}-max, {stack}bb",
    withAnte: " (com ante)",
    combosSuffix: " / {total} combos",
    legendPush: "Push (all-in)",
    legendCall: "Call",
    legendFold: "Fold",
    note: {
      strong1: "Diagonal = pares · canto superior direito = suited · canto inferior esquerdo = offsuit",
      p1: "A grade está ordenada por ",
      strong2: "valor da carta, não por força",
      p2: ", então é normal que células marcadas e não marcadas se alternem na mesma linha — AQo, KQo e QQ ficam lado a lado, mas não em ordem de força. A5s entrar enquanto A6s fica de fora também está certo: A5s faz a",
      strong3: "sequência wheel (A-2-3-4-5)",
      p3: ", o que compensa o kicker mais baixo.",
    },
    cellTitle: "{hand} — {action}",
    cell: { push: "push", call: "call", fold: "fold" },
    huNote: {
      strong: "Equilíbrio de Nash, heads-up (SB vs BB)",
      p1: ": assume-se que o SB só dá shove ou folda. A opção de ante acrescenta 0,125bb por jogador (o equivalente a um big blind ante, ≈12,5%). Os ranges abrem conforme os stacks encurtam — e abaixo de ~3-4bb o BB paga corretamente ",
      em: "mais largo",
      p2: " do que o SB dá shove, por causa das pot odds.",
    },
    mwNote: {
      strong: "Tabela de shove first-in {table}-max",
      p1: ": todo mundo na sua frente foldou e você só dá shove ou folda. É um equilíbrio no estilo Nash de ",
      strong2: "chip EV puro",
      p2: " — os ranges de call dos jogadores atrás são resolvidos ao mesmo tempo — usando a aproximação padrão de que um pote pago se resolve heads-up contra o primeiro caller (potes com vários callers são ignorados). Os ranges abrem conforme sobram menos jogadores atrás de você (UTG → BTN → SB), conforme os stacks encurtam e com antes ON (0,125bb por jogador). Por ser chip EV puro, os ranges de 10bb das posições iniciais (UTG/MP) saem mais fechados do que as regras de bolso populares (pares pequenos foldam) — na prática, ajuste para ICM e para os adversários.",
    },
    readMore: "Para os fundamentos de short stack, leia o nosso",
    shortStackLink: { slug: "holdem-short-stack", text: "guia de estratégia de short stack" },
    readMoreEnd: ".",
  },

  icmGuide: {
    bubble: {
      badge: "Guia de ICM",
      h2: "Como usar a calculadora de ICM — um exemplo de bolha em 3 minutos",
      intro: "Digamos que sobram quatro jogadores e três são pagos (a bolha). Os stacks são 60.000 / 40.000 / 30.000 / 20.000 e os prêmios são $500 / $300 / $200. Coloque isso na calculadora e você tem a fatia de fichas de cada jogador contra o valor real dele em premiação (ICM):",
      th: { player: "Jogador", chipPct: "% de fichas", icmPct: "% ICM", diff: "Dif." },
      rows: [
        { player: "🥇 Chip leader", chip: "40,0%", icm: "33,3%", diff: "-6,7 pts", up: false },
        { player: "🥈 2º", chip: "26,7%", icm: "27,2%", diff: "+0,6 pt", up: true },
        { player: "🥉 3º", chip: "20,0%", icm: "22,9%", diff: "+2,9 pts", up: true },
        { player: "4º (short stack)", chip: "13,3%", icm: "16,6%", diff: "+3,3 pts", up: true },
      ],
      keyPoint: {
        text: "O ponto central: {b1} em 6,7 pontos. Como ganhar só paga o prêmio de 1º lugar, o leader ganha menos valor em premiação num coin flip do que a contagem de fichas sugere. Então, na bolha, o leader deve {b2}, enquanto o short stack (13,3% das fichas → 16,6% de ICM) vale mais do que as suas fichas e deve {b3} para proteger esse valor de sobrevivência.",
        b1: "o valor de ICM do chip leader (33,3%) é menor que a sua fatia de fichas (40%)",
        b2: "pressionar os short stacks",
        b3: "evitar calls de all-in desnecessários",
      },
    },
    deal: {
      badge: "Divisão da premiação",
      h2: "ICM deal vs chip chop — como dividir a premiação",
      intro: "Agora sobram três jogadores e eles discutem um deal. Com stacks de 50% / 30% / 20% e $1.500 de premiação restante, os dois métodos dividem de forma bem diferente:",
      th: { player: "Jogador", chop: "Chip chop", icm: "ICM deal", diff: "Dif." },
      rows: [
        { player: "🥇 Chip leader (50%)", chop: "$750", icm: "$618", diff: "-$132", up: false },
        { player: "🥈 2º (30%)", chop: "$450", icm: "$485", diff: "+$35", up: true },
        { player: "🥉 Short stack (20%)", chop: "$300", icm: "$397", diff: "+$97", up: true },
      ],
      summary: {
        text: "O chip chop divide pela fatia de fichas e {b1}; o ICM deal reflete as probabilidades de colocação e é {b2}. Acima, o short stack recebe $300 num chip chop, mas cerca de $397 num ICM deal — {b3}. Se você está short, peça um ICM deal; se você é o leader, proponha um chip chop.",
        b1: "favorece o chip leader",
        b2: "mais justo com os short stacks",
        b3: "$97 a mais",
      },
    },
  },

  guide: {
    badge: "Ferramentas",
    h2: "Como usar as 8 calculadoras de Hold'em",
    cards: [
      { title: "Calculadora de outs", body: "Calcula com precisão a chance de o seu draw completar no flop ou no turn. Veja ao mesmo tempo o atalho da regra do 4 e do 2 e o número exato." },
      { title: "Pot odds e implied odds", body: "Decida entre pagar ou foldar com matemática. Quando o adversário está deep, adicione as implied odds para uma decisão mais precisa." },
      { title: "Ranking de mãos", body: "Escolha as cartas para conferir a força da mão. Digite até 7 cartas e ela encontra a melhor combinação de 5 automaticamente." },
      { title: "Força da mão inicial", body: "Escolha suas duas cartas fechadas para ver qual das 169 mãos ela é e a ação recomendada por posição." },
      { title: "SPR (Stack-to-Pot Ratio)", body: "A relação entre stack e pote diz quão forte a sua mão precisa ser. Quanto menor o SPR, mais vale se comprometer com uma mão forte." },
      { title: "M-ratio de torneio", body: "O M de Harrington mede a pressão sobre o seu stack no torneio. A estratégia muda por completo entre as zonas verde/amarela/laranja/vermelha/morta." },
      { title: "Calculadora de ICM", body: "O Independent Chip Model converte fichas de torneio em valor real de premiação — essencial para decisões de pagar/foldar e para negociar deals na bolha e na final table." },
      { title: "Tabela push/fold de Nash", body: "Uma tabela 13×13 de heads-up calculada a partir do equilíbrio de Nash: com que mãos dar open-shove e com quais pagar de 1 a 25bb. Indispensável nas fases finais de torneio." },
    ],
  },

  faq: {
    badge: "FAQ",
    h2: "Perguntas frequentes sobre a calculadora de ICM e de Hold'em",
    q: "P. {q}",
  },

  related: {
    badge: "Aprofunde",
    h2: "Guias para ler quando a conta fizer sentido",
    links: [
      { slug: "holdem-tournament", title: "Estratégia de torneio", desc: "ICM, a bolha e o jogo na final table" },
      { slug: "holdem-equity", title: "Equity no poker explicada", desc: "Win %, fold equity e realização" },
      { slug: "holdem-pot-odds", title: "Como calcular pot odds", desc: "Transforme o pagar/foldar em conta" },
      { slug: "holdem-outs", title: "Como contar outs", desc: "Outs por draw e a regra do 2 e 4" },
      { slug: "holdem-probability", title: "Odds e probabilidade no poker", desc: "Os números centrais por trás de cada mão" },
      { slug: "holdem-starting-hands-chart", title: "Tabela de mãos iniciais", desc: "Quais mãos jogar por posição" },
    ],
  },
};
