// AUTO-GENERATED by scripts/gen-pushfold.mjs — 직접 수정 금지 (재생성: node scripts/gen-pushfold.mjs)
// 헤즈업(SB vs BB) 내시 균형 푸시/폴드 차트 데이터.
// 계산 방법: 169×169 프리플랍 올인 에퀴티(몬테카를로 300,000 샘플/매치업,
// lib/poker-eval.ts 평가기와 교차 검증) → fictitious play로 SB 푸시/BB 콜 균형 수렴.
// 칩EV 모델: SB 폴드 = S-0.5-a, 푸시 후 BB 폴드 = S+1+a, 콜 = 2S×eq (S=유효스택 bb, a=앤티/인).
// 앤티 ON = 플레이어당 0.125bb (BB 앤티 1bb ≈ 12.5%/인 환산).
//
// 핸드 인덱스: 13×13 그리드, index = row*13+col, row/col = A,K,Q,J,T,9,8,7,6,5,4,3,2.
// 대각선 = 페어, col > row = 수티드, col < row = 오프수트.
// 마스크 인코딩: 169비트 → 43 hex nibble, bit i = (hex[i>>2] >> (i&3)) & 1.

export const PF_STACK_MIN = 1;
export const PF_STACK_MAX = 25;
export const PF_STACK_STEP = 0.5;

// D[anteIdx][stackIdx] = "pushHex|callHex" (anteIdx 0 = 앤티 없음, 1 = 앤티 ON)
const D: [string[], string[]] = [
  [
    "ffffffffffffffffffffffffffffffffffffffffff1|ffffffffffffffffffffffffffffffffffffffffff1",
    "fffffffffffffffffffffffffffffffffffffffff31|ffffffffffffffffffffffffffffffffffffffffff1",
    "fffffffffffffffffffffffffffffffffffbf14f301|ffffffffffffffffffffffffffffffffffffffffff1",
    "fffffffffffffffffffffffff7fffefddf0bf14f101|ffffffffffffffffffffffffffffffffffffffffff1",
    "ffffffffffffffffffffff9ff3fffe7cd70bf04f101|fffffffffffffffffffffffffffffffffffff9ff301",
    "fffffffffffffffffffdff9ff3fffe7cd70b704f001|fffffffffffffffffffffffff7fffefff78bf04f101",
    "fffffffffffffffffffdff9ff3fffe3cd30b704f001|fffffffffffffffffffdff9ff3ff7e3cd309704f001",
    "fffffffffffffffffffdff9ff3fffe1cd30b704f001|ffffffffffffffffff7cff8ff1f13e1cc3093047001",
    "fffffffffffffffffffcff9ff3fffe1cd30b7047001|fffffffffffffff7ef7cf78fd0f01e14c1093047001",
    "fffffffffffffffffffcff9ff3fdfe1cd10b3047001|fffffffffffffff1ef3cf78f40701e04c1093047001",
    "fffffffffffffffffffcff9ff3fcfe1cd10b3047001|ffffffffffff3ff1ef1cf38740701e04c1091043001",
    "fffffffffffffffffffcff9ff3fcfe0cd10b3047001|ffffffffffff1ff0ef1c738340701e04c0091043001",
    "ffffffffffffffffef7cff9ff37cfe0cd10b3047001|ffffffffffff0ff0ef1c318340701604c0091043001",
    "ffffffffffffffffef7cff9ff3787e0cd10b3043001|fffffffffbf70f70ef0c318340301604c0091043001",
    "fffffffffffffff7ef7cff9ff3787e0cd00b1043001|fffffffff9f70f70ef0c118340301604c0091043001",
    "fffffffffffffff7ef7cff9ff3787e0cd00b1043001|fffffffff8f70f70e50c118140301604c0091041001",
    "ffffffffffff7ff7ef7cff9bf3787e0cd00b1043001|ffffffff78f30f70e50c118140301604c0090041001",
    "ffffffffffff7ff7ef7cff93f378760cd0091043001|ffffffff78f30f30e50c11814030160440090041001",
    "ffffffffffff7ff7ef7cff93f338760cd0091043001|ffffffff38f30f30e40c01814030160440090041001",
    "ffffffffffff7ff7ef7cff81f338760cd0091043001|ffffffff38f30f30e40c01814030120440090041001",
    "ffffffffffff3ff3ef7cff81e330760cd0091043001|ffffffdf18f10f30e40c01814030120440090041001",
    "ffffffffffff3ff3ef7cff81e330760cd0091043001|ffffffcf18f10f10e40c01814010120440090041001",
    "ffffffffffff3ff3ef7cff81e330760cd0091041001|ffffffcf18f10f10640c01814010120440090041001",
    "ffffffffffff3ff1ef7cff81e330760cd0090041001|fffff7cf18f10f10640c01804010120440090041001",
    "fffffffffbff3ff1ef7cff81e330760cc0090041001|fffff7cf18f10710640c01804010120440090041001",
    "fffffffffbff1ff1ef7cef81e330760c40090041001|fffff3cf08f00710640c01804010120440090041001",
    "fffffffff9ff1ff1ef7ccf81e130760c40090041001|fffff3cf08f00710640401804010120440090041001",
    "fffffffff9ff1ff1ef3ccf81e130720c40090041001|fffff1cf08f00710640401804010120440090041001",
    "fffffffff9ff1ff1ef3ccf81c130720c40090041001|fffff1cf08f00710640401804010120440090041001",
    "fffffffff9ff1ff1ef3ccf81c110720c40090041001|fffff0cf08f00310640401804010120440090041000",
    "fffffffff9ff1ff1ef3ccf81c110720c40090041001|fffff0cf08f00310640401804010120440090040000",
    "fffffffff8ff0ff1ef3ccf80c110320c40090041001|fffff0c708f00310640401804010120440090040000",
    "fffffffff8ff0ff1ef3ccf80c110320c40090041001|fffff0c708f00310640401804010120440010040000",
    "fffffffff8ff0ff1ef3ccf80c110320c40090041001|fffff0c708f00310240401804010120440010040000",
    "fffffffff8f70ff1ef3c8f80c110320c40090041001|ffff70c708f00310240401804010120440010040000",
    "fffffffff8f70ff1ef348f80c110320c40090041001|ffff70c708700310240401804010120440010040000",
    "fffffffff8f70ff1ef348f80c110320c40090041001|ffff70c708700310240401804010120400010040000",
    "ffffffdff8f70ff1ef348780c110320c40090041001|ffff70c708700310240401804010120400010040000",
    "ffffffdff8f70ff1ef348780c110320c40090041001|ffff70c708500310240401804010120400010040000",
    "ffffffcff8f70ff1ef340780c110320c40090041001|ffff70c708500310240401804010120400010040000",
    "ffffffcff8f70ff1ef340780c110320c40090041001|ffff70c708500310240401804010100400010040000",
    "ffffffcff8f70ff1ef340780c110320c40090041001|ffff70c708500310240401804010100400010040000",
    "ffffffcff8f70ff1ef340780c110320c40090041001|ffff70c708500310240401804000100400010040000",
    "ffffffcff8f70ff1ef340780c110320c40090041001|ffff70c308500310240401804000100400010040000",
    "ffffffcff8f70ff1ef340780c110320440090041001|ffff30c308500310240401804000100400010000000",
    "ffffffcff8f70ff1ef340780c110320440090041001|fffe30c308500110240401804000100400010000000",
    "ffffffcff8f70ff1af340780c010320440090041001|fffe30c308500110240401804000100400010000000",
    "ffffffcf78f70ff0af340780c010320440090041001|fffe30c308500110240401804000100400010000000",
    "ffffffcf78f70ff02f340780c010320440090041001|ff7e30c308500110240401804000100400010000000",
  ],
  [
    "ffffffffffffffffffffffffffffffffffffffffff1|ffffffffffffffffffffffffffffffffffffffffff1",
    "ffffffffffffffffffffffffffffffffffffffffff1|ffffffffffffffffffffffffffffffffffffffffff1",
    "fffffffffffffffffffffffffffffffffffffffff01|ffffffffffffffffffffffffffffffffffffffffff1",
    "fffffffffffffffffffffffffffffffffffbf14f301|ffffffffffffffffffffffffffffffffffffffffff1",
    "fffffffffffffffffffffffff7fffeffdf0bf14f101|ffffffffffffffffffffffffffffffffffffffffff1",
    "ffffffffffffffffffffff9ff3fffeffd70bf04f101|fffffffffffffffffffffffffffffffffffff1df301",
    "ffffffffffffffffffffff9ff3fffe7ed70bf04f001|fffffffffffffffffffffffff7fffefff70bf04f101",
    "ffffffffffffffffffffff9ff3fffe7ed70b704f001|ffffffffffffffffffffff9ff3ff7e3cd309704f001",
    "fffffffffffffffffffdff9ff3fffe3ed30b704f001|ffffffffffffffffff7cff8ff1f33e1cc309704f001",
    "fffffffffffffffffffdff9ff3fffe1ed30b704f001|ffffffffffffffffef7cff8ff1f03e14c3093047001",
    "fffffffffffffffffffdff9ff3fffe1ed30b7047001|fffffffffffffff7ef3cf78fc0f01e14c1093047001",
    "fffffffffffffffffffcff9ff3fdfe1ed30b3047001|fffffffffffffff1ef3cf78f40701e04c1093047001",
    "fffffffffffffffffffcff9ff3fcfe1ed10b3047001|ffffffffffff3ff1ef1cf38740701e04c1091043001",
    "fffffffffffffffffffcff9ff3fcfe0ed10b3047001|ffffffffffff1ff0ef1c738740701e04c0091043001",
    "ffffffffffffffffeffcff9ff37cfe0ed10b3047001|ffffffffffff1ff0ef1c318340701e04c0091043001",
    "ffffffffffffffffef7cff9ff378fe0cd10b3043001|fffffffffbf70ff0ef0c318340701604c0091043001",
    "ffffffffffffffffef7cff9ff378fe0cd10b1043001|fffffffffbf70f70ef0c118340301604c0091043001",
    "fffffffffffffff7ef7cff9ff378fe0cd10b1043001|fffffffff9f70f70ef0c118140301604c0091043001",
    "fffffffffffffff7ef7cff9ff378fe0cd00b1043001|fffffffff8f70f70e50c118140301604c0091041001",
    "fffffffffffffff7ef7cff9bf3787e0cd00b1043001|fffffffff8f30f70e50c118140301604c0090041001",
    "ffffffffffff7ff7ef7cff93f378760cd00b1043001|ffffffff78f30f30e50c11814030160440090041001",
    "ffffffffffff7ff7ef7cff93f378760cd00b1043001|ffffffff78f30f30e40c11814030160440090041001",
    "ffffffffffff7ff7ef7cff93f338760cd0091043001|ffffffff38f30f30e40c01814030160440090041001",
    "ffffffffffff7ff7ef7cff81f338760cd0091043001|ffffffff18f10f30e40c01814030120440090041001",
    "ffffffffffff3ff3ef7cff81e338760cd0091043001|ffffffdf18f10f30e40c01814010120440090041001",
    "ffffffffffff3ff3ef7cff81e330760cd0091043001|ffffffcf18f10f10e40c01814010120440090041001",
    "ffffffffffff3ff3ef7cff81e330760cd0091041001|ffffffcf18f10f10640c01814010120440090041001",
    "ffffffffffff3ff1ef7cff81e330760cd0090041001|fffff7cf18f10f10640c01814010120440090041001",
    "fffffffffbff3ff1ef7cff81e330760cd0090041001|fffff7cf18f10f10640c01804010120440090041001",
    "fffffffffbff3ff1ef7cef81e330760cd0090041001|fffff7cf08f10710640c01804010120440090041001",
    "fffffffffbff1ff1ef7cef81e130760c40090041001|fffff3cf08f00710640c01804010120440090041001",
    "fffffffff9ff1ff1ef7cef81e130760c40090041001|fffff3cf08f00710640401804010120440090041001",
    "fffffffff9ff1ff1ef7ccf81e130720c40090041001|fffff1cf08f00710640401804010120440090041001",
    "fffffffff9ff1ff1ef3ccf81c130720c40090041001|fffff1cf08f00710640401804010120440090041001",
    "fffffffff9ff1ff1ef3ccf81c110720c40090041001|fffff0cf08f00310640401804010120440090041000",
    "fffffffff9ff1ff1ef3ccf81c110720c40090041001|fffff0cf08f00310640401804010120440090041000",
    "fffffffff9ff1ff1ef3ccf81c110720c40090041001|fffff0cf08f00310640401804010120440090040000",
    "fffffffff8ff0ff1ef3ccf80c110320c40090041001|fffff0c708f00310640401804010120440090040000",
    "fffffffff8ff0ff1ef3ccf80c110320c40090041001|fffff0c708f00310640401804010120440010040000",
    "fffffffff8ff0ff1ef3ccf80c110320c40090041001|fffff0c708f00310240401804010120440010040000",
    "fffffffff8ff0ff1ef3ccf80c110320c40090041001|ffff70c708f00310240401804010120440010040000",
    "fffffffff8ff0ff1ef34cf80c110320c40090041001|ffff70c708700310240401804010120440010040000",
    "fffffffff8ff0ff1ef34cf80c110320c40090041001|ffff70c708700310240401804010120400010040000",
    "ffffffdff8f70ff1ef348780c110320c40090041001|ffff70c708700310240401804010120400010040000",
    "ffffffdff8f70ff1ef348780c110320c40090041001|ffff70c708500310240401804010120400010040000",
    "ffffffdff8f70ff1ef348780c110320c40090041001|ffff70c708500310240401804010120400010040000",
    "ffffffcff8f70ff1ef340780c110320c40090041001|ffff70c708500310240401804010120400010040000",
    "ffffffcff8f70ff0ef340780c110320c40090041001|ffff70c708500310240401804010100400010040000",
    "ffffffcff8f70ff06f340780c110320c40090041001|ffff70c708500310240401804010100400010040000",
  ],
];

function hexToMask(h: string): boolean[] {
  const m: boolean[] = new Array(169);
  for (let i = 0; i < 169; i++) m[i] = ((parseInt(h[i >> 2], 16) >> (i & 3)) & 1) === 1;
  return m;
}

/** 스택(bb)·앤티 설정에 해당하는 SB 푸시 / BB 콜 마스크(169칸, 그리드 순서) */
export function pfLookup(stack: number, ante: boolean): { push: boolean[]; call: boolean[] } {
  const idx = Math.min(
    Math.max(Math.round((stack - PF_STACK_MIN) / PF_STACK_STEP), 0),
    Math.round((PF_STACK_MAX - PF_STACK_MIN) / PF_STACK_STEP)
  );
  const [ph, ch] = D[ante ? 1 : 0][idx].split("|");
  return { push: hexToMask(ph), call: hexToMask(ch) };
}
