/**
 * 대회 일정 데이터 (단일 정본)
 *
 * ★ 이 파일이 유일한 대회 데이터 소스다.
 *   - `/tournaments` 페이지 카드
 *   - Event JSON-LD (구조화 데이터)
 *   둘 다 여기서 읽는다. 예전처럼 두 군데에 날짜를 따로 적어 어긋나는 일이 없어야 한다.
 *
 * ★ status는 직접 적지 않는다. startDate/endDate에서 자동 계산된다.
 *   (2026-07-28에 "WSOP 진행중" 배너가 13일간 묵어 있던 사고의 구조적 방지)
 *
 * ★ 값의 출처·원문 인용·검증 등급은 `docs/tournament-spine.md`에 있다.
 *   값을 고치기 전에 반드시 그 문서의 정본 URL을 먼저 열어볼 것.
 *
 * 검증 등급(sourceTier)
 *   'A' — 작성자가 직접 정본을 열어 원문 확인
 *   'B' — 조사관이 정본 원문 인용 확보 (작성자 미대조)
 *   'C' — 2차 출처(취재매체)만. 정본에 해당 정보 없음
 */

export type TournamentType = "domestic" | "international";
export type TournamentStatus = "upcoming" | "ongoing" | "ended";
export type SourceTier = "A" | "B" | "C";

export interface Tournament {
  id: string;
  name: string;
  /** 다국어 페이지용 영문 대회명. 라틴 표기가 12개 언어의 공통 베이스가 된다 */
  nameEn: string;
  type: TournamentType;

  /** ISO 'YYYY-MM-DD'. null이면 상시 개최(status는 항상 ongoing) */
  startDate: string | null;
  endDate: string | null;
  /** 날짜 옆에 덧붙일 부가 설명. 예: "(ME 파이널 8/3~5)" */
  dateNote?: string;
  /** 날짜가 없는 상시 대회의 표시 문구 */
  dateLabelOverride?: string;

  /** 카드 표시용 장소 문자열 */
  location: string;
  /** JSON-LD용 */
  city: string;
  /** ISO 2자리 국가코드 (다국어 확장 시 비자 레이어 조인 키) */
  country: string;
  venue: string;

  /** 카드 표시용 바이인 문자열 */
  buyin: string;

  emoji: string;
  color: string;
  note?: string;
  highlight?: boolean;
  /** 우리 블로그 상세 가이드 */
  blogLink?: string;

  /**
   * ★ 독자에게 링크할 URL.
   * "클릭했을 때 우리 데이터와 같은 내용을 보는 페이지"여야 한다.
   * 공식 사이트라도 낡은 페이지면 링크하지 않는다. (docs/tournament-spine.md §2-1)
   */
  sourceUrl: string | null;
  sourceTier: SourceTier | null;
  /** 'YYYY-MM-DD' — 이 값을 마지막으로 원문 확인한 날 */
  verifiedAt: string | null;

  /** JSON-LD organizer */
  organizer?: { name: string; url: string };
  /** JSON-LD description. 없으면 스키마에서 제외 */
  schemaDescription?: string;
}

/* ────────────────────────────────────────────────────────────
   상태 계산 — 날짜에서 자동 도출. 손으로 적지 않는다.
   ──────────────────────────────────────────────────────────── */

export function computeStatus(t: Tournament, todayISO: string): TournamentStatus {
  // ★ 날짜가 아직 안 나온 대회는 "진행중"이 아니라 "예정"이다.
  //    예전엔 ongoing을 반환해서, 날짜 미발표 대회가 6개 언어 전부에서
  //    "진행중 + 연중 + 날짜 미발표"라는 자기모순 카드로 나갔다.
  if (!t.startDate || !t.endDate) return "upcoming"; // 상시 개최
  if (todayISO < t.startDate) return "upcoming";
  if (todayISO > t.endDate) return "ended";
  return "ongoing";
}

export const STATUS_LABEL: Record<TournamentStatus, string> = {
  upcoming: "예정",
  ongoing: "진행중",
  ended: "종료",
};

/** '2026.08.07~08.16' 형태로 표시 문자열 생성 */
export function formatDateRange(t: Tournament): string {
  if (t.dateLabelOverride) return t.dateLabelOverride;
  if (!t.startDate || !t.endDate) return "";
  const [sy, sm, sd] = t.startDate.split("-");
  const [ey, em, ed] = t.endDate.split("-");
  const base =
    sy === ey ? `${sy}.${sm}.${sd}~${em}.${ed}` : `${sy}.${sm}.${sd}~${ey}.${em}.${ed}`;
  return t.dateNote ? `${base} ${t.dateNote}` : base;
}

/** 카드 상단 월 배지 */
export function formatMonthBadge(t: Tournament): string {
  if (!t.startDate) return "일정 미정";
  const sm = Number(t.startDate.slice(5, 7));
  if (!t.endDate) return `${sm}월`;
  const em = Number(t.endDate.slice(5, 7));
  return sm === em ? `${sm}월` : `${sm}~${em}월`;
}

/* ────────────────────────────────────────────────────────────
   대회 목록
   ★ 순서는 신경 쓰지 말고 추가할 것. 아래에서 시작일 오름차순으로 자동 정렬한다.
     (손으로 순서를 맞추면 반드시 어긋난다 — 실제로 한 번 어긋났다)
   ──────────────────────────────────────────────────────────── */

const RAW_TOURNAMENTS: Tournament[] = [
  {
    id: "kpc-jeju",
    name: "KPC x LPT Series 2026",
    nameEn: "KPC x LPT Series 2026",
    type: "domestic",
    startDate: "2026-01-03",
    endDate: "2026-01-18",
    location: "한국 제주 (LES A Casino)",
    city: "Jeju",
    country: "KR",
    venue: "LES A Casino",
    buyin: "₩90만~",
    emoji: "🃏",
    color: "bg-primary/20 text-primary border-primary/40",
    note: "KPC x LPT 시리즈 + 킹 포커 시리즈 합동 개최",
    // koreapokercup.com은 526 SSL로 다운. KPC 산하 브랜드 부문 kpclive.com에 일정이 게시돼 있다.
    // (개런티·이벤트 수는 공식 미기재 → 적지 않는다)
    sourceUrl: "https://www.kpclive.com/ko-KR",
    sourceTier: "A",
    verifiedAt: "2026-07-29",
  },
  {
    id: "aspt-korea",
    name: "ASPT Korea 2026",
    nameEn: "ASPT Korea 2026",
    type: "domestic",
    startDate: "2026-01-23",
    endDate: "2026-02-01",
    // ⚠️ 공식 페이지(aspt.world)에 베뉴 표기가 없다. 추측으로 채우지 않는다.
    location: "한국 (베뉴 공식 미기재)",
    city: "Incheon",
    country: "KR",
    venue: "공식 미기재",
    buyin: "메인 ₩150만",
    emoji: "🏙️",
    color: "bg-blue-500/15 text-blue-400 border-blue-500/30",
    note: "90개+ 토너먼트 · 메인이벤트 Day 1A 바이인 1,500,000",
    sourceUrl: "https://aspt.world/events/aspt-korea-2026/",
    sourceTier: "A",
    verifiedAt: "2026-07-29",
  },
  {
    id: "apt-jeju-classic",
    name: "APT 제주 클래식 2026",
    nameEn: "APT Jeju Classic 2026",
    type: "domestic",
    startDate: "2026-01-30",
    endDate: "2026-02-08",
    location: "한국 제주 (신화월드 LES A)",
    city: "Jeju",
    country: "KR",
    venue: "LES A Casino, Jeju Shinhwa World",
    buyin: "메인 ₩230만",
    emoji: "🌴",
    color: "bg-emerald-500/15 text-emerald-400 border-emerald-500/30",
    note: "한국 개최 국제 대회 사상 최대 — 1,718 엔트리 (종전 1,693 경신)",
    sourceUrl:
      "https://www.theasianpokertour.com/series/apt-jeju-classic-south-korea-2026/events",
    sourceTier: "A",
    verifiedAt: "2026-07-29",
    organizer: { name: "Asian Poker Tour", url: "https://www.theasianpokertour.com" },
  },
  {
    id: "ept-paris",
    name: "EPT 파리 2026",
    nameEn: "EPT Paris 2026",
    type: "international",
    startDate: "2026-02-18",
    endDate: "2026-03-01",
    location: "프랑스 파리 (Le Palais des Congrès)",
    city: "Paris",
    country: "FR",
    venue: "Le Palais des Congrès",
    buyin: "€825~€100,000",
    emoji: "🇫🇷",
    color: "bg-indigo-500/15 text-indigo-400 border-indigo-500/30",
    note: "메인이벤트 €5,300 (2/23~3/1)",
    sourceUrl: "https://www.pokerstarslive.com/ept/paris/",
    sourceTier: "A",
    verifiedAt: "2026-07-29",
  },
  {
    id: "triton-jeju-1",
    name: "Triton 제주 2026 (ONE + SHR)",
    nameEn: "Triton Jeju 2026 (ONE + SHR)",
    type: "domestic",
    startDate: "2026-03-05",
    endDate: "2026-04-01",
    location: "한국 제주 (LES A Casino)",
    city: "Jeju",
    country: "KR",
    venue: "LES A Casino, Jeju Shinhwa World",
    buyin: "$2,000~$150,000",
    emoji: "💎",
    color: "bg-purple-500/15 text-purple-400 border-purple-500/30",
    note: "ONE 3/5~15 + Super High Roller Series 3/15~4/1 · SHRS 타이틀 스폰서 Jupiter Exchange",
    // ⚠️ 종료된 대회라 공식 페이지에서 전체 스케줄이 내려갔다(결과 3건만 노출).
    //    날짜·바이인 범위는 조사관 확인분 — 작성자 직접 대조 미완료
    sourceUrl: "https://tritonpokerseries.com/en-US/events/Triton_SHRS_Jeju_S5",
    sourceTier: "B",
    verifiedAt: "2026-07-29",
  },
  {
    id: "wsope",
    name: "WSOP Europe 2026",
    nameEn: "WSOP Europe 2026",
    type: "international",
    // ★ 정정: 종료일 04.10 → 04.12 / 베뉴 King's Resort Rozvadov → Hilton Prague
    startDate: "2026-03-31",
    endDate: "2026-04-12",
    location: "체코 프라하 (Hilton Prague)",
    city: "Prague",
    country: "CZ",
    venue: "Hilton Prague (King's Casino Prague 운영)",
    buyin: "€5,300 (메인)",
    emoji: "🇨🇿",
    color: "bg-red-500/15 text-red-400 border-red-500/30",
    note: "로즈바도프 King's Resort를 떠나 프라하 힐튼으로 이전 · 브레이슬릿 15개",
    sourceUrl: "https://www.wsop.com/tournaments/2026-wsop-europe/",
    sourceTier: "A",
    verifiedAt: "2026-07-29",
  },
  {
    id: "ajpc-incheon-1",
    name: "AJPC 사무라이 서킷 인천 1차",
    nameEn: "AJPC Samurai Circuit Incheon #1",
    type: "domestic",
    startDate: "2026-04-10",
    endDate: "2026-04-19",
    // 공식(samurai.ajpc.jp)은 지역·날짜만 표기하고 베뉴는 적지 않는다
    location: "한국 인천",
    city: "Incheon",
    country: "KR",
    venue: "공식 미기재",
    buyin: "다양",
    emoji: "⛩️",
    color: "bg-rose-500/15 text-rose-400 border-rose-500/30",
    sourceUrl: "https://samurai.ajpc.jp/en/",
    sourceTier: "A",
    verifiedAt: "2026-07-29",
  },
  {
    id: "apt-taipei",
    name: "APT Taipei 2026",
    nameEn: "APT Taipei 2026",
    type: "international",
    startDate: "2026-04-22",
    endDate: "2026-05-03",
    location: "대만 타이베이 (Red Space + Asia Poker Arena)",
    city: "Taipei",
    country: "TW",
    venue: "Red Space 多元商務空間 / Asia Poker Arena",
    buyin: "TWD 3,000~800,000",
    emoji: "🇹🇼",
    color: "bg-cyan-500/15 text-cyan-400 border-cyan-500/30",
    note: "메인 #54 TWD 55,000 / TWD 70,000,000 GTD · 투어 20년 역사상 최대 비(非)챔피언십 페스티벌 (26,009 엔트리)",
    sourceUrl: "https://www.theasianpokertour.com/series/apt-taipei-taiwan-2026/events",
    sourceTier: "A",
    verifiedAt: "2026-07-29",
  },
  {
    id: "ept-montecarlo",
    name: "EPT 몬테카를로 2026",
    nameEn: "EPT Monte-Carlo 2026",
    type: "international",
    startDate: "2026-04-30",
    endDate: "2026-05-10",
    location: "모나코 (Sporting Monte-Carlo)",
    city: "Monte Carlo",
    country: "MC",
    venue: "Sporting Monte-Carlo",
    buyin: "€1,650~€250,000",
    emoji: "🎰",
    color: "bg-amber-500/15 text-amber-400 border-amber-500/30",
    note: "메인이벤트 €5,300 (5/4~10) · €250,000 슈퍼 하이롤러 편성",
    sourceUrl: "https://www.pokerstarslive.com/ept/montecarlo/",
    sourceTier: "A",
    verifiedAt: "2026-07-29",
  },
  {
    id: "ajpc-taipei",
    name: "AJPC 사무라이 서킷 타이베이",
    nameEn: "AJPC Samurai Circuit Taipei",
    type: "international",
    startDate: "2026-05-11",
    endDate: "2026-05-18",
    // 공식은 지역·날짜만 표기하고 베뉴는 적지 않는다
    location: "대만 타이베이",
    city: "Taipei",
    country: "TW",
    venue: "공식 미기재",
    buyin: "다양",
    emoji: "⛩️",
    color: "bg-rose-500/15 text-rose-400 border-rose-500/30",
    sourceUrl: "https://samurai.ajpc.jp/en/",
    sourceTier: "A",
    verifiedAt: "2026-07-29",
  },
  {
    id: "triton-montenegro",
    name: "Triton SHR 몬테네그로 2026",
    nameEn: "Triton SHR Montenegro 2026",
    type: "international",
    startDate: "2026-05-13",
    endDate: "2026-05-28",
    location: "몬테네그로 부드바 (Maestral Resort)",
    city: "Budva",
    country: "ME",
    venue: "Maestral Resort & Casino, Pržno",
    buyin: "$25,000~$200,000",
    emoji: "💎",
    color: "bg-purple-500/15 text-purple-400 border-purple-500/30",
    note: "$200K Invitational 상금풀 $27.4M · 메인이벤트 우승 Danny Tang $3,522,000",
    // ⚠️ 종료된 대회라 공식 페이지에서 이벤트 목록이 내려갔다.
    //    날짜·베뉴·바이인은 조사관 확인분 — 작성자 직접 대조 미완료
    sourceUrl: "https://tritonpokerseries.com/en-US/events/Triton_SHRS_Montenegro_S5",
    sourceTier: "B",
    verifiedAt: "2026-07-29",
  },
  {
    id: "gop-incheon-1",
    name: "GOP 인천 2026 (The Prophecy Unfolds)",
    nameEn: "GOP Incheon 2026 (The Prophecy Unfolds)",
    type: "domestic",
    startDate: "2026-05-15",
    endDate: "2026-05-24",
    location: "한국 인천 (파라다이스 시티)",
    city: "Incheon",
    country: "KR",
    venue: "Paradise City Casino",
    buyin: "메인 ₩220만",
    emoji: "⚡",
    color: "bg-violet-500/15 text-violet-400 border-violet-500/30",
    note: "메인이벤트 개런티 ₩7억 (시리즈 총액 아님)",
    sourceUrl: "https://godsofpoker.com/series/incheon-2026",
    sourceTier: "A",
    verifiedAt: "2026-07-29",
  },
  {
    id: "holdem-masters-7",
    name: "제7회 홀덤 마스터스",
    nameEn: "7th Holdem Masters",
    type: "domestic",
    startDate: "2026-05-29",
    endDate: "2026-08-02",
    location: "한국 서울 (야자수 서울센터)",
    city: "Seoul",
    country: "KR",
    venue: "야자수 서울센터",
    buyin: "초대권 전용 (현금 바이인 없음)",
    emoji: "👑",
    color: "bg-yellow-500/15 text-yellow-400 border-yellow-500/30",
    note: "종료 · 총상금 15억 GTD · 챔피언스 우승 강경식(2억) · 챌린저스 우승 이준우(1억)",
    highlight: true,
    blogLink: "/blog/holdem-masters-7th-guide",
    sourceUrl: "https://wpl.winjoygame.com/holdem-masters/hall-7",
    sourceTier: "A",
    verifiedAt: "2026-08-06",
    organizer: { name: "WeLive", url: "https://wpl.winjoygame.com" },
    schemaDescription:
      "후원 WPL · 주관 WeLive · 협력 YAJASU. 총상금 15억원 보장, 초대권 전용 참가.",
  },
  {
    id: "wsop-2026",
    name: "제57회 WSOP 2026",
    nameEn: "57th WSOP 2026",
    type: "international",
    startDate: "2026-05-26",
    endDate: "2026-08-05",
    dateNote: "(ME 파이널 8/3~5)",
    location: "미국 라스베이거스 (Horseshoe & Paris)",
    city: "Las Vegas",
    country: "US",
    venue: "Horseshoe Las Vegas / Paris Las Vegas",
    buyin: "$300~$250,000",
    emoji: "🏆",
    color: "bg-yellow-500/15 text-yellow-400 border-yellow-500/30",
    note: "브레이슬릿 100개는 7/15 종료 · 메인이벤트 파이널 테이블만 8/3~5 (ESPN)",
    highlight: true,
    blogLink: "/blog/wsop-2026-tournament-guide",
    sourceUrl:
      "https://www.wsop.com/tournaments/2026-57th-annual-world-series-of-poker/",
    sourceTier: "A",
    verifiedAt: "2026-07-29",
    organizer: { name: "WSOP", url: "https://www.wsop.com" },
    schemaDescription:
      "세계 최대 홀덤 대회. 브레이슬릿 100개 5/26~7/15, 메인이벤트 9,208 엔트리·상금풀 $85,634,400, 파이널 테이블 8/3~5 ESPN 중계.",
  },
  {
    id: "kpc-king-july",
    name: "K Poker Cup + King Poker Cup 2026",
    nameEn: "K Poker Cup + King Poker Cup 2026",
    type: "domestic",
    startDate: "2026-07-25",
    endDate: "2026-08-10",
    location: "한국 제주 (LES A Casino)",
    city: "Jeju",
    country: "KR",
    venue: "LES A Casino",
    buyin: "~₩700만 (하이롤러)",
    emoji: "🃏",
    color: "bg-primary/20 text-primary border-primary/40",
    note: "17일 페스티벌 · 총 20억 GTD · 7/25~8/4 K Poker Cup → 8/3부터 King Poker Cup(메인 11억 GTD)",
    highlight: true,
    sourceUrl: "https://www.kpclive.com/ko-KR",
    sourceTier: "A",
    verifiedAt: "2026-07-29",
    organizer: { name: "K Poker Cup", url: "https://www.kpclive.com" },
    schemaDescription:
      "제주 LES A Casino에서 열리는 17일 포커 페스티벌. 총 20억원 보장, King Poker Cup 메인이벤트 11억 GTD.",
  },
  {
    id: "apt-incheon",
    name: "APT 인천 2026",
    nameEn: "APT Incheon 2026",
    type: "domestic",
    startDate: "2026-08-07",
    endDate: "2026-08-16",
    location: "한국 인천 (파라다이스 시티)",
    city: "Incheon",
    country: "KR",
    venue: "Paradise City Casino",
    buyin: "메인 ₩250만",
    emoji: "🇰🇷",
    color: "bg-primary/20 text-primary border-primary/40",
    note: "총 40억원+ 보장 · 메인이벤트 8/9~15 (15억 GTD) · APTC 시트 9석",
    highlight: true,
    blogLink: "/blog/apt-incheon-2026-guide",
    sourceUrl:
      "https://www.theasianpokertour.com/series/apt-incheon-south-korea-2026/events",
    sourceTier: "A",
    verifiedAt: "2026-07-29",
    organizer: { name: "Asian Poker Tour", url: "https://www.theasianpokertour.com" },
    schemaDescription:
      "아시아 최대 홀덤 투어 APT의 2026 인천 스톱. 파라다이스 시티 개최, 총 40억원+ 보장, 메인이벤트 15억 GTD.",
  },
  {
    id: "ept-barcelona",
    name: "EPT 바르셀로나 2026",
    nameEn: "EPT Barcelona 2026",
    type: "international",
    startDate: "2026-08-16",
    endDate: "2026-08-29",
    location: "스페인 바르셀로나 (Casino Barcelona)",
    city: "Barcelona",
    country: "ES",
    venue: "Casino Barcelona",
    buyin: "€825~€100,000",
    emoji: "🇪🇸",
    color: "bg-orange-500/15 text-orange-400 border-orange-500/30",
    note: "듀얼 페스티벌 — PokerStars Open ME €1,650 (8/16~22) → EPT ME €5,300 (8/22~29)",
    sourceUrl: "https://www.pokerstarslive.com/ept/barcelona/",
    blogLink: "/blog/ept-barcelona-2026-guide",
    sourceTier: "A",
    verifiedAt: "2026-07-29",
  },
  {
    id: "gop-manila",
    name: "GOP Manila 2026 (The Arena of Champions)",
    nameEn: "GOP Manila 2026 (The Arena of Champions)",
    type: "international",
    startDate: "2026-08-21",
    endDate: "2026-08-30",
    location: "필리핀 마닐라 (City of Dreams)",
    city: "Manila",
    country: "PH",
    venue: "City of Dreams Manila",
    buyin: "₱11,000~₱682,500",
    emoji: "🇵🇭",
    color: "bg-sky-500/15 text-sky-400 border-sky-500/30",
    note: "시리즈 개런티 ₱60,000,000 · 메인이벤트 ₱30M GTD",
    sourceUrl: "https://godsofpoker.com/series/manila-2026",
    sourceTier: "A",
    verifiedAt: "2026-07-29",
  },
  {
    id: "ajpc-incheon-2",
    name: "AJPC 사무라이 서킷 인천 2차",
    nameEn: "AJPC Samurai Circuit Incheon #2",
    type: "domestic",
    startDate: "2026-08-21",
    endDate: "2026-08-30",
    location: "한국 인천",
    city: "Incheon",
    country: "KR",
    venue: "미정 (공식 미기재)",
    buyin: "다양",
    emoji: "⛩️",
    color: "bg-rose-500/15 text-rose-400 border-rose-500/30",
    sourceUrl: "https://samurai.ajpc.jp/en/",
    sourceTier: "A",
    verifiedAt: "2026-07-29",
  },
  {
    id: "holdem-masters-8",
    name: "제8회 홀덤 마스터스",
    nameEn: "8th Holdem Masters",
    type: "domestic",
    startDate: "2026-08-03",
    endDate: "2026-10-05",
    location: "한국 서울 (야자수 서울센터)",
    city: "Seoul",
    country: "KR",
    venue: "야자수 서울센터",
    buyin: "초대권 전용",
    emoji: "👑",
    color: "bg-yellow-500/15 text-yellow-400 border-yellow-500/30",
    note: "메인이벤트 18억 + NLH 딥스택 5개(각 4천만) · DAY1 28회 8/21~10/2 · FINAL 10/5",
    highlight: true,
    sourceUrl: "https://wpl.winjoygame.com/holdem-masters-8",
    sourceTier: "A",
    verifiedAt: "2026-08-31",
    organizer: { name: "WeLive", url: "https://wpl.winjoygame.com" },
    schemaDescription:
      "제8회 홀덤 마스터스. WPL 메인이벤트 DAY3 & FINAL 상금 18억원, NLH 딥스택 5개 각 4천만원. DAY1 플라이트 28회(8/21~10/2), FINAL 10/5. 초대권 전용 참가.",
  },
  {
    /**
     * ★ 바이인 범위는 2026-08-31에 «₩350K~₩5M»에서 넓혔다. **이전 값이 틀렸던 게 아니다** —
     *   07-29엔 `/appt/korea/schedule/`이 빈 표로 렌더돼(스파인 §APPT 「내부 모순」 행)
     *   랜딩의 Key Events 8개만 근거였고, 그 8개 안에서는 ₩350K~₩5M이 맞았다.
     *   그 뒤 전체 스케줄이 공개됐다("The full schedule is now available").
     * ★ 실측(Playwright DOM): 이벤트 **#0~#67 결번 0** · 12일 전부 렌더 · 페이지네이션 없음.
     *   최소 = `#0 FLIPS to Main Event MEGA Qualifier - 1 in 7` **₩50,000**(9/9 · 1,000 스택),
     *   최대 = `#43 APPT Super High Roller` **₩10,000,000**(9/10 Day1 · 9/11 Final · 250,000 스택).
     * 🔴 «Key Events만 보고 범위를 좁히지 마라» — 본문 탭 파싱은 #0을 놓친다
     *   (이벤트 번호가 0이고 Reg.Close 칸이 비어 있다). 심판은 `select#buy-in-filter`의 24종 열거다.
     */
    id: "appt-korea",
    name: "APPT 코리아 2026",
    nameEn: "APPT Korea 2026",
    type: "domestic",
    startDate: "2026-09-03",
    endDate: "2026-09-14",
    location: "한국 인천 (파라다이스 시티)",
    city: "Incheon",
    country: "KR",
    venue: "Paradise City",
    buyin: "₩5만~₩1,000만",
    emoji: "♠️",
    color: "bg-teal-500/15 text-teal-400 border-teal-500/30",
    note: "메인이벤트 9/10~14 — ₩180만 바이인 · ₩10억 GTD · 전 68이벤트",
    highlight: true,
    blogLink: "/blog/appt-korea-2026-guide",
    sourceUrl: "https://www.pokerstarslive.com/appt/korea/",
    sourceTier: "A",
    verifiedAt: "2026-08-31",
    organizer: { name: "PokerStars LIVE", url: "https://www.pokerstarslive.com/appt/" },
    schemaDescription:
      "PokerStars APPT의 2026 한국 스톱. 파라다이스 시티 인천 개최, 메인이벤트 ₩10억 보장.",
  },
  {
    id: "triton-jeju-2",
    name: "Triton SHR 제주 II 2026",
    nameEn: "Triton SHR Jeju II 2026",
    type: "domestic",
    startDate: "2026-09-04",
    endDate: "2026-09-17",
    location: "한국 제주 (LES A Casino)",
    city: "Seogwipo",
    country: "KR",
    venue: "LES A Casino, Jeju Shinhwa World",
    buyin: "$15,000~$200,000",
    emoji: "💎",
    color: "bg-purple-500/15 text-purple-400 border-purple-500/30",
    note: "14개 하이롤러 · 새틀라이트 없음(추천제) · $200K Invitational 9/12~14",
    sourceUrl: "https://tritonpokerseries.com/en-US/events/Triton_SHRS_Jeju_II_S5",
    sourceTier: "A",
    verifiedAt: "2026-08-31",
    organizer: { name: "Triton Poker Series", url: "https://tritonpokerseries.com" },
    schemaDescription:
      "Triton Super High Roller Series 제주 2차. 14개 하이롤러 토너먼트, 바이인 $15,000~$200,000.",
  },
  {
    id: "gop-taipei-2",
    name: "GOP Taipei II (The Trial of Wisdom)",
    nameEn: "GOP Taipei II (The Trial of Wisdom)",
    type: "international",
    startDate: "2026-09-18",
    endDate: "2026-09-27",
    location: "대만 타이베이 (CTP Asia Poker Arena)",
    city: "Taipei",
    country: "TW",
    venue: "CTP Asia Poker Arena",
    buyin: "다양",
    emoji: "🇹🇼",
    color: "bg-cyan-500/15 text-cyan-400 border-cyan-500/30",
    sourceUrl: "https://godsofpoker.com/series/taipei-2026-ii",
    sourceTier: "A",
    verifiedAt: "2026-07-29",
  },
  {
    id: "apt-jeju-fall",
    name: "APT 제주 2026 (가을)",
    nameEn: "APT Jeju 2026 (Fall)",
    type: "domestic",
    startDate: "2026-09-25",
    endDate: "2026-10-07",
    location: "한국 제주 (신화월드 LES A)",
    city: "Jeju",
    country: "KR",
    venue: "LES A Casino, Jeju Shinhwa World",
    buyin: "메인 ₩270만",
    emoji: "🌴",
    color: "bg-emerald-500/15 text-emerald-400 border-emerald-500/30",
    /**
     * ★ 이벤트 수 136 → **135** (2026-08-31 라이브 실측). 07-29 판정이 틀렸던 게 아니라
     *   **편성에서 하나가 빠졌다** — 발표 시점엔 136이 맞았다(poker.org
     *   "136 trophy events over 13 days" + 우리 07-29 실측).
     * ★ 실측 3중 확인: 번호 열거 `#1~#135` · **결번 0** · `#0` 없음(APPT엔 있었다) ·
     *   활성 필터 0 · 마지막 행이 `#135 Hyper Turbo - High Roller`(그 뒤는 푸터).
     * 🔴 **종목 분해는 여기 적지 않는다.** 내 재분류로는 NLH 91 / 기타 44가 나오지만
     *   `#71 Atomic Pineapple` 같은 자리에서 APT 공식 분류를 재현하지 못한다
     *   = «내 기준의 값»이라 발행 부적합. 글의 「90+46」을 고치려면 공식 분류 근거부터 찾아라.
     * ⚠️ 개막(9/25) 전 또 바뀔 수 있다 — `docs/update-calendar.md`에 재확인 등재.
     */
    note: "135개 이벤트 · 메인이벤트 22억 GTD · APTC 시트 12석",
    highlight: true,
    blogLink: "/blog/apt-jeju-2026-fall-guide",
    sourceUrl: "https://www.theasianpokertour.com/series/apt-jeju-south-korea-2026/events",
    sourceTier: "A",
    verifiedAt: "2026-08-31",
    organizer: { name: "Asian Poker Tour", url: "https://www.theasianpokertour.com" },
    schemaDescription:
      "APT의 2026 제주 가을 스톱. 135개 이벤트, 메인이벤트 22억원 보장.",
  },
  {
    id: "gop-incheon-2",
    name: "GOP Incheon II (The Labyrinth Trail)",
    nameEn: "GOP Incheon II (The Labyrinth Trail)",
    type: "domestic",
    startDate: "2026-10-30",
    endDate: "2026-11-08",
    location: "한국 인천 (파라다이스 시티)",
    city: "Incheon",
    country: "KR",
    venue: "Paradise City Casino",
    buyin: "다양",
    emoji: "⚡",
    color: "bg-violet-500/15 text-violet-400 border-violet-500/30",
    note: "같은 기간 영종도에서 WPT Seoul도 동시 개최 (베뉴 다름)",
    /**
     * 🔴 sourceUrl을 `/series/incheon-2026-ii` → `/series`로 바꿨다(2026-08-31).
     *   그 URL은 **`/news/gods-of-poker-incheon`으로 리다이렉트**되는데 그 기사(1/4 게시)에는
     *   **날짜가 한 줄도 없다** → 독자가 우리 카드의 10/30~11/8을 확인할 수 없다
     *   (스파인 §2-1 「링크 금지 = 독자가 우리 글과 다른 내용을 보게 됨」과 같은 계급).
     *   `/series` 목록은 `OCT 30-NOV 8, 2026 / GOP INCHEON 2026 II / THELABYRINTHTRAIL`을
     *   그대로 띄운다. 형제 `gop-jeju`가 이미 `/series`를 쓰고 있어 표기도 통일된다.
     *   ⚠️ 공식 자체가 이 두 시리즈만 `/news/`로 링크한다(타이베이는 `/series/taipei-2026-ii`).
     */
    sourceUrl: "https://godsofpoker.com/series",
    sourceTier: "A",
    verifiedAt: "2026-08-31",
  },
  {
    id: "wpt-seoul",
    name: "WPT Seoul 2026",
    nameEn: "WPT Seoul 2026",
    type: "domestic",
    startDate: "2026-10-30",
    endDate: "2026-11-09",
    location: "한국 인천 영종도 (INSPIRE)",
    city: "Incheon",
    country: "KR",
    venue: "YY Poker Club, INSPIRE Entertainment Resort",
    buyin: "₩30만~₩800만",
    emoji: "🌟",
    color: "bg-fuchsia-500/15 text-fuchsia-400 border-fuchsia-500/30",
    note: "46개 이벤트 · 메인 11/5~9 (₩175만, 10억 GTD) · 70테이블 신설 포커룸",
    highlight: true,
    // ⚠️ worldpokertour.com은 Cloudflare 403이라 독자도 못 열 수 있음
    //    → INSPIRE 공식 보도자료를 정본으로 승격 (docs/tournament-spine.md §2-1)
    sourceUrl: "https://prtimes.jp/main/html/rd/p/000000091.000128436.html",
    sourceTier: "A",
    verifiedAt: "2026-08-31",
    organizer: { name: "World Poker Tour", url: "https://www.worldpokertour.com" },
    schemaDescription:
      "WPT가 INSPIRE 엔터테인먼트 리조트에서 처음 개최하는 대회. 46개 이벤트, 메인이벤트 ₩10억 보장.",
  },
  {
    id: "apt-championship",
    name: "APT 챔피언십 2026",
    nameEn: "APT Championships 2026",
    type: "international",
    // 정본 시리즈 페이지 헤더는 "12 Nov to 29 Nov". 11/12 첫 이벤트(#1000 Event 0)는
    // "restricted to casino employees and poker industry persons only" — 일반 참가자는 11/13부터.
    // 원칙(정본 우선)에 따라 11-12를 쓰고 note로 구분한다.
    startDate: "2026-11-12",
    endDate: "2026-11-29",
    location: "대만 타이베이 (Red Space + Asia Poker Arena)",
    city: "Taipei",
    country: "TW",
    venue: "Red Space 多元商務空間 / Asia Poker Arena",
    buyin: "TWD 3,300~1,500,000",
    emoji: "👑",
    color: "bg-yellow-500/15 text-yellow-400 border-yellow-500/30",
    note: "210개 트로피 이벤트 · 메인 #14 TWD 311.9K / TWD 165,000,000 GTD (11/23~) · 11/12는 업계 관계자 전용, 일반 참가자는 11/13부터",
    sourceUrl: "https://www.theasianpokertour.com/series/apt-championship-taipei-2026",
    sourceTier: "A",
    verifiedAt: "2026-07-29",
  },
  {
    id: "wsop-paradise",
    name: "WSOP Paradise 2026",
    nameEn: "WSOP Paradise 2026",
    type: "international",
    /**
     * ★ 시작일 이력: 12.01 → (07-29) 12.03 → **(08-31) 12.02**.
     *   07-29 주석은 «12.03이 공식 대회 페이지 기준»이라 적었는데, 2026-08-31 실측에서
     *   **같은 페이지가 두 층 모두 12/02**였다: 헤더 `Dec 02 2026 - Dec 17 2026` +
     *   일정표 첫 행 `Dec 02 WED 11:00 AM — Event #1 Flight A`. `/schedule/` 목록도 동일.
     *   🔴 되돌리지 마라 — 세 출처(대회 페이지 헤더·일정표 첫 행·스케줄 목록)가 12/02로 일치한다.
     * ★ 바이인도 07-29의 «미발표»에서 갱신됐다(그때는 참이었다). 실측 = 이벤트 **#1~#20 결번 0**,
     *   최소 `#1 $2,750 NLH WSOP Circuit Championship Mystery Bounty`,
     *   최대 `#5 $250,000 NLH Super High Roller Invitational`.
     */
    startDate: "2026-12-02",
    endDate: "2026-12-17",
    location: "바하마 나소 (Baha Mar)",
    city: "Nassau",
    country: "BS",
    venue: "Baha Mar Resort",
    buyin: "$2,750~$250,000",
    emoji: "🏝️",
    color: "bg-teal-500/15 text-teal-400 border-teal-500/30",
    note: "Atlantis에서 Baha Mar로 이전 · 전 20이벤트 공개",
    // ⚠️ wsop.com/paradise/ 랜딩은 아직 2025년 정보(Atlantis) 표시 → 대회 페이지로 링크
    sourceUrl: "https://www.wsop.com/tournaments/2026-wsop-paradise/",
    sourceTier: "A",
    verifiedAt: "2026-08-31",
  },
  {
    id: "ept-prague",
    name: "EPT 프라하 2026",
    nameEn: "EPT Prague 2026",
    type: "international",
    startDate: "2026-12-02",
    endDate: "2026-12-13",
    location: "체코 프라하 (Hilton Prague)",
    city: "Prague",
    country: "CZ",
    venue: "Hilton Hotel Prague",
    buyin: "€1,650~€5,300",
    emoji: "🇨🇿",
    color: "bg-red-500/15 text-red-400 border-red-500/30",
    note: "듀얼 페스티벌 — PokerStars Open ME €1,650 (12/2~7) → EPT ME €5,300 (12/7~13)",
    sourceUrl: "https://www.pokerstarslive.com/ept/prague/",
    sourceTier: "A",
    verifiedAt: "2026-07-29",
  },
  {
    id: "gop-jeju",
    name: "GOP Jeju 2026 (The Olympus Return)",
    nameEn: "GOP Jeju 2026 (The Olympus Return)",
    type: "domestic",
    startDate: "2026-12-04",
    endDate: "2026-12-13",
    location: "한국 제주 (신화월드 LES A)",
    city: "Jeju",
    country: "KR",
    venue: "LES A Casino, Jeju Shinhwa World",
    buyin: "다양",
    emoji: "⚡",
    color: "bg-violet-500/15 text-violet-400 border-violet-500/30",
    sourceUrl: "https://godsofpoker.com/series",
    sourceTier: "A",
    verifiedAt: "2026-08-31",
  },
  /* ── 🇯🇵 일본 JOPT — 한국에서 2~3시간, 아시아 최대급 필드 ────────── */
  {
    id: "jopt-fukuoka-1",
    name: "JOPT 2026 Fukuoka #01",
    nameEn: "JOPT 2026 Fukuoka #01",
    type: "international",
    startDate: "2026-07-30",
    endDate: "2026-08-02",
    location: "일본 후쿠오카 (UNITEDLAB)",
    city: "Fukuoka",
    country: "JP",
    venue: "UNITEDLAB, Daimyo",
    buyin: "¥2,000~¥300,000",
    emoji: "🇯🇵",
    color: "bg-rose-500/15 text-rose-400 border-rose-500/30",
    note: "JOPT 사상 첫 후쿠오카 개최 · 메인이벤트 ¥15,000,000 GTD",
    blogLink: "/blog/japan-poker-tournaments-guide",
    sourceUrl: "https://japanopenpoker.com/events/",
    sourceTier: "A",
    verifiedAt: "2026-08-31",
  },
  {
    id: "jopt-sapporo-2",
    name: "JOPT 2026 Sapporo #02",
    nameEn: "JOPT 2026 Sapporo #02",
    type: "international",
    startDate: "2026-09-18",
    endDate: "2026-09-23",
    location: "일본 삿포로",
    city: "Sapporo",
    country: "JP",
    venue: "サッポロファクトリーホール",
    buyin: "¥3,000~¥200,000",
    emoji: "🇯🇵",
    color: "bg-rose-500/15 text-rose-400 border-rose-500/30",
    blogLink: "/blog/japan-poker-tournaments-guide",
    sourceUrl: "https://japanopenpoker.com/events/",
    sourceTier: "A",
    verifiedAt: "2026-08-31",
  },
  {
    id: "jopt-tokyo-3",
    name: "JOPT 2026 Tokyo #03",
    nameEn: "JOPT 2026 Tokyo #03",
    type: "international",
    startDate: "2026-10-08",
    endDate: "2026-10-12",
    location: "일본 도쿄 (베르사르 다카다노바바)",
    city: "Tokyo",
    country: "JP",
    venue: "ベルサール高田馬場, 新宿区",
    // 「다양」 → 「미발표」 (2026-08-31). `events…/2026-tokyo-03`이 **404** = Players Guide 미공개다.
    // 「다양」은 «여러 가격대가 공개돼 있다»로 읽혀 미공개 상태를 가린다(스파인 §3-2 판정법).
    buyin: "미발표",
    emoji: "🇯🇵",
    color: "bg-rose-500/15 text-rose-400 border-rose-500/30",
    blogLink: "/blog/japan-poker-tournaments-guide",
    sourceUrl: "https://japanopenpoker.com/events/",
    sourceTier: "A",
    verifiedAt: "2026-08-31",
  },
  {
    id: "jopt-osaka-2",
    name: "JOPT 2026 Osaka #02",
    nameEn: "JOPT 2026 Osaka #02",
    type: "international",
    startDate: "2026-10-29",
    endDate: "2026-11-03",
    location: "일본 오사카 (도지마 리버 포럼)",
    city: "Osaka",
    country: "JP",
    venue: "堂島リバーフォーラム",
    // 「다양」 → 「미발표」 (2026-08-31). `events…/2026-osaka-02` **404** — 스파인 §3-2가
    // 이미 「이벤트별 바이인 ==미공개== (2026-07-30)」이라 적어 둔 것과 표기를 맞췄다.
    buyin: "미발표",
    emoji: "🇯🇵",
    color: "bg-rose-500/15 text-rose-400 border-rose-500/30",
    blogLink: "/blog/japan-poker-tournaments-guide",
    sourceUrl: "https://japanopenpoker.com/events/",
    sourceTier: "A",
    verifiedAt: "2026-08-31",
  },
  {
    id: "jopt-tokyo-2027-1",
    name: "JOPT 2027 Tokyo #01",
    nameEn: "JOPT 2027 Tokyo #01",
    type: "international",
    startDate: "2026-12-24",
    endDate: "2027-01-03",
    location: "일본 도쿄 (베르사르 다카다노바바)",
    city: "Tokyo",
    country: "JP",
    venue: "ベルサール高田馬場, 新宿区",
    buyin: "다양",
    emoji: "🇯🇵",
    color: "bg-rose-500/15 text-rose-400 border-rose-500/30",
    note: "연말연시 개최 — 2027 시즌 개막전",
    blogLink: "/blog/japan-poker-tournaments-guide",
    sourceUrl: "https://japanopenpoker.com/events/",
    sourceTier: "A",
    verifiedAt: "2026-08-31",
  },
  /* ★ 아래 2건은 2026-08-31 스파인 재대조에서 편입했다.
     `japanopenpoker.com/events/`의 **Upcoming Events**에 공식 게시돼 있는데
     우리 보드에만 없었다(JOPT 5건은 날짜·바이인 결함 0 — 빠진 것은 이 둘뿐).
     🔴 바이인은 둘 다 «미발표»다: 판정법은 스파인 §3-2 「JOPT는 정보를 두 곳에 낸다」 —
     `events.japanopenpoker.com/<연>-<도시>-<번호>`가 200이면 공개, 404면 미공개.
     실측 = `2027-osaka-01` **404** · `2027-fukuoka-01` **404**(대조군 `2026-sapporo-02`는 200). */
  {
    id: "jopt-osaka-2027-1",
    name: "JOPT 2027 Osaka #01",
    nameEn: "JOPT 2027 Osaka #01",
    type: "international",
    startDate: "2027-03-18",
    endDate: "2027-03-22",
    // ⚠️ 공식 Upcoming 표기가 도시명 「Osaka」뿐이다 — 회장명이 없다.
    //    2025·2026 Osaka는 전부 堂島リバーフォーラム였지만 **추측으로 채우지 않는다**(스파인 §1).
    location: "일본 오사카 (회장 공식 미기재)",
    city: "Osaka",
    country: "JP",
    venue: "공식 미기재",
    buyin: "미발표",
    emoji: "🇯🇵",
    color: "bg-rose-500/15 text-rose-400 border-rose-500/30",
    note: "회장·이벤트별 바이인 모두 공식 미발표 — 확정되면 갱신",
    blogLink: "/blog/japan-poker-tournaments-guide",
    sourceUrl: "https://japanopenpoker.com/events/",
    sourceTier: "A",
    verifiedAt: "2026-08-31",
  },
  {
    id: "jopt-fukuoka-2027-1",
    name: "JOPT 2027 Fukuoka #01",
    nameEn: "JOPT 2027 Fukuoka #01",
    type: "international",
    startDate: "2027-05-27",
    endDate: "2027-05-30",
    location: "일본 후쿠오카 (UNITEDLAB)",
    city: "Fukuoka",
    country: "JP",
    venue: "UNITEDLAB, Daimyo",
    buyin: "미발표",
    emoji: "🇯🇵",
    color: "bg-rose-500/15 text-rose-400 border-rose-500/30",
    note: "2026년 첫 후쿠오카 개최에 이은 2회차 — 같은 회장(UNITEDLAB)",
    blogLink: "/blog/japan-poker-tournaments-guide",
    sourceUrl: "https://japanopenpoker.com/events/",
    sourceTier: "A",
    verifiedAt: "2026-08-31",
  },
  /* ★ 아래 2건은 2026-09-01 «일본 2시장차» 회차에서 편입했다.
     일본은 투어가 여럿이라 JOPT 하나로는 국내 축을 못 덮는다(뱅크 §6-C).
     조달 판정을 통과한 것은 이 둘뿐이다 — JAPAN POKER FESTIVAL(일정이 2024/11에 멈춤)·
     Top of Poker(과거 결과만)·poker-vertex(투어가 아니라 개별 포커룸)는 제외했다.
     🔴 판정 기준은 «사이트가 열리나»가 아니라 «미래 일정을 내나»다(플레이북 규율 2). */
  {
    id: "ajpc-2026",
    name: "AJPC 2026 전일본 포커 선수권",
    nameEn: "AJPC 2026 All Japan Poker Championship",
    type: "international",
    startDate: "2026-09-20",
    endDate: "2026-09-22",
    location: "일본 도쿄 (EBiS303)",
    city: "Tokyo",
    country: "JP",
    // 공식이 회장을 「EBiS303」까지만 적는다. 소재지 주소는 기재가 없어 채우지 않는다.
    venue: "EBiS303",
    // 「ENTRY FEE 完全無料 / オンライン予選から決勝大会まで、無料で日本一を目指せます」(공식 축어)
    buyin: "무료",
    emoji: "🇯🇵",
    color: "bg-rose-500/15 text-rose-400 border-rose-500/30",
    note: "온라인 예선(POKER+) 3단계를 통과하면 본선 Day1 티켓 — 예선부터 결승까지 참가비 무료",
    blogLink: "/blog/japan-poker-tournaments-guide",
    sourceUrl: "https://www.ajpc.jp/ajpc2026overview/",
    sourceTier: "A",
    verifiedAt: "2026-09-01",
    organizer: { name: "All Japan Poker Championship", url: "https://www.ajpc.jp/" },
  },
  {
    id: "nippon-series-go-nagasaki-2026",
    name: "GO by NIPPON SERIES 나가사키 2026",
    nameEn: "GO by NIPPON SERIES Nagasaki 2026",
    type: "international",
    startDate: "2026-09-04",
    endDate: "2026-09-06",
    location: "일본 나가사키 (데지마 메세)",
    city: "Nagasaki",
    country: "JP",
    venue: "出島メッセ長崎",
    // 19개 이벤트 전수 실측(2026-09-01). 최저 #1 Warm-up ¥5,000 · 최고 ¥20,000(메인·Draw Mix·
    // 7-Game·KIHARA). 전 이벤트에 참가수수료 ¥1,000(2drinks)이 붙는다.
    buyin: "¥5,000~¥20,000",
    emoji: "🇯🇵",
    color: "bg-rose-500/15 text-rose-400 border-rose-500/30",
    note: "19개 이벤트 · 메인이벤트 ¥20,000(+¥1,000) 프라이즈 2,500,000 · 전국을 도는 지방창생형",
    blogLink: "/blog/japan-poker-tournaments-guide",
    sourceUrl: "https://nippon-series.jp/event-go-nagasaki",
    sourceTier: "A",
    verifiedAt: "2026-09-01",
    organizer: { name: "一般社団法人Poker Nippon Series", url: "https://nippon-series.jp/" },
  },

  /* ── 🇵🇭 마닐라 (Okada) — PokerStars Live 아시아 거점 ────────── */
  {
    id: "appt-manila",
    name: "APPT Manila 2026",
    nameEn: "APPT Manila 2026",
    type: "international",
    startDate: "2026-07-28",
    endDate: "2026-08-10",
    location: "필리핀 마닐라 (Okada Manila)",
    city: "Parañaque",
    country: "PH",
    venue: "Cove Manila, Okada Manila",
    buyin: "₱9,000~₱300,000",
    emoji: "🇵🇭",
    color: "bg-sky-500/15 text-sky-400 border-sky-500/30",
    note: "총 ₱132M+ 보장 · 메인이벤트 8/6~10 (₱80,000 / ₱60M GTD)",
    sourceUrl: "https://www.pokerstarslive.com/appt/manila/",
    sourceTier: "A",
    verifiedAt: "2026-07-29",
    organizer: { name: "PokerStars LIVE", url: "https://www.pokerstarslive.com/appt/" },
    schemaDescription:
      "PokerStars APPT의 2026 마닐라 스톱. Okada Manila 개최, 총 ₱132M 보장.",
  },
  {
    id: "manila-super-series-24",
    name: "Manila Super Series 24",
    nameEn: "Manila Super Series 24",
    type: "international",
    startDate: "2026-09-18",
    endDate: "2026-09-27",
    location: "필리핀 마닐라 (Okada Manila)",
    city: "Parañaque",
    country: "PH",
    venue: "Okada Manila",
    buyin: "공식 미기재",
    emoji: "🇵🇭",
    color: "bg-sky-500/15 text-sky-400 border-sky-500/30",
    sourceUrl: "https://www.pokerstarslive.com/appt/",
    sourceTier: "A",
    verifiedAt: "2026-07-29",
  },
  {
    id: "appt-manila-championship",
    name: "APPT Manila Championship",
    nameEn: "APPT Manila Championship",
    type: "international",
    startDate: "2026-10-08",
    endDate: "2026-10-19",
    location: "필리핀 마닐라 (Okada Manila)",
    city: "Parañaque",
    country: "PH",
    venue: "Coral Lounge, Okada Manila",
    buyin: "₱3,500~₱500,000",
    emoji: "🇵🇭",
    color: "bg-sky-500/15 text-sky-400 border-sky-500/30",
    note: "APPT 시즌 피날레 · 총 ₱116.75M 보장 · 메인 10/15~19 (₱165,000 / ₱60M GTD)",
    sourceUrl: "https://www.pokerstarslive.com/appt/manilachampionship/",
    sourceTier: "A",
    verifiedAt: "2026-07-29",
  },
  {
    id: "manila-megastack-25",
    name: "Manila Megastack 25",
    nameEn: "Manila Megastack 25",
    type: "international",
    startDate: "2026-11-28",
    endDate: "2026-12-07",
    location: "필리핀 마닐라 (Okada Manila)",
    city: "Parañaque",
    country: "PH",
    venue: "Okada Manila",
    buyin: "공식 미기재",
    emoji: "🇵🇭",
    color: "bg-sky-500/15 text-sky-400 border-sky-500/30",
    sourceUrl: "https://www.pokerstarslive.com/appt/",
    sourceTier: "A",
    verifiedAt: "2026-07-29",
  },

  /* ── 🇻🇳 베트남 — 가성비 원정지 ────────── */
  {
    id: "usop-vietnam-2",
    name: "USOP Vietnam 2026 (하롱베이)",
    nameEn: "USOP Vietnam 2026 (Ha Long Bay)",
    type: "international",
    startDate: "2026-08-27",
    endDate: "2026-09-09",
    location: "베트남 하롱베이 (InterContinental)",
    city: "Ha Long",
    country: "VN",
    venue: "InterContinental Halong Resort",
    buyin: "₫2,300,000~₫152,000,000",
    emoji: "🇻🇳",
    color: "bg-lime-500/15 text-lime-400 border-lime-500/30",
    note: "90개+ 이벤트 · 메인이벤트 9/5~9 (₫30,000,000 / ₫30 Billion GTD)",
    sourceUrl:
      "https://userieschampionship.com/tournament/vietnam-series-2026-halong-v2/",
    sourceTier: "A",
    verifiedAt: "2026-07-29",
  },

  /* ── 🇦🇺 호주 ────────── */
  {
    id: "wpt-australia",
    name: "WPT Australia 2026",
    nameEn: "WPT Australia 2026",
    type: "international",
    startDate: "2026-09-10",
    endDate: "2026-09-30",
    location: "호주 시드니 (The Star Sydney)",
    city: "Sydney",
    country: "AU",
    venue: "The Star Sydney",
    buyin: "AUD $1,150~$5,000",
    emoji: "🇦🇺",
    color: "bg-blue-500/15 text-blue-400 border-blue-500/30",
    note: "36개 이벤트 · Prime Championship AUD $1,500 + Championship AUD $5,000",
    sourceUrl: "https://www.starpoker.com.au/wpt-australia",
    blogLink: "/blog/wpt-australia-2026-guide",
    sourceTier: "A",
    verifiedAt: "2026-07-29",
  },

  /* ── 🇨🇾 북키프로스 Triton ────────── */
  {
    id: "triton-one-cyprus",
    name: "Triton ONE 북키프로스 2026",
    nameEn: "Triton ONE North Cyprus 2026",
    type: "international",
    startDate: "2026-11-04",
    endDate: "2026-11-15",
    location: "북키프로스 키레니아 (Merit Royal Diamond)",
    city: "Kyrenia",
    country: "CY",
    venue: "Merit Royal Diamond Hotel & Casino",
    buyin: "공식 미기재",
    emoji: "💎",
    color: "bg-purple-500/15 text-purple-400 border-purple-500/30",
    // ⚠️ Triton 공식 이벤트 페이지가 "Coming Soon" 상태라 상세 미공개. 날짜는 2차 출처 확인분
    sourceUrl: "https://tritonpokerseries.com/en-US/events",
    sourceTier: "B",
    verifiedAt: "2026-07-29",
  },
  {
    id: "triton-shrs-cyprus",
    name: "Triton SHR 북키프로스 2026",
    nameEn: "Triton SHR North Cyprus 2026",
    type: "international",
    startDate: "2026-11-15",
    endDate: "2026-11-28",
    location: "북키프로스 키레니아 (Merit Royal Diamond)",
    city: "Kyrenia",
    country: "CY",
    venue: "Merit Royal Diamond Hotel & Casino",
    buyin: "$25,000~$150,000",
    emoji: "💎",
    color: "bg-purple-500/15 text-purple-400 border-purple-500/30",
    note: "Triton ONE 종료 직후 연속 개최 — 시즌 최종 스톱",
    // ⚠️ 공식 이벤트 페이지 "Coming Soon". 바이인 범위는 2차 출처 확인분
    sourceUrl: "https://tritonpokerseries.com/en-US/events",
    sourceTier: "B",
    verifiedAt: "2026-07-29",
  },

  /* ── 🇹🇼 대만 CTP Asia Poker Arena — 연 10회 이상 돌아가는 아시아 허브 ──────────
     2026-08-31 보강: `ctpclub.app/en/festivals`(주최 클럽의 공식 목록)를 Playwright DOM으로
     긁어 2026년 페스티벌 19건을 전수 대조했다. 아래 6건이 우리 스파인에 없었다.
     날짜·베뉴·바이인은 **CTP 목록이 아니라 각 주최사 자기 사이트**에서 다시 확인했다
     (보드 히어로가 "每一場都是從主辦方官網上直接確認的"라고 약속하고 있다).
     그 대조에서 **CTP 목록이 주최사와 어긋나는 자리가 나왔다** — ZSOP 항목 주석 참조. */
  {
    /**
     * 2026 대만 개막 시리즈. 값은 `godsofpoker.com/series/taipei-2026` 원문에서 직접 읽었다:
     * 헤더 `JAN 8-18, 2026` / `Asia Poker Arena` / `42 MILLION Series Guarantee` / `95 Total Events`.
     * 바이인은 스케줄의 `Buy-in:` 라벨 128건을 파싱한 실측 범위다(새틀라이트 포함).
     */
    id: "gop-taipei-1",
    name: "Gods of Poker Taipei 2026 — The Titan Assembly",
    nameEn: "Gods of Poker Taipei 2026 — The Titan Assembly",
    type: "international",
    startDate: "2026-01-08",
    endDate: "2026-01-18",
    location: "대만 타이베이 (Asia Poker Arena)",
    city: "Taipei",
    country: "TW",
    venue: "Asia Poker Arena",
    buyin: "NT$2,500~NT$330,000",
    emoji: "🇹🇼",
    color: "bg-cyan-500/15 text-cyan-400 border-cyan-500/30",
    note: "95개 이벤트 · 시리즈 개런티 NT$42,000,000 — 2026 대만 시즌 개막전",
    sourceUrl: "https://godsofpoker.com/series/taipei-2026",
    sourceTier: "A",
    verifiedAt: "2026-08-31",
  },
  {
    /**
     * ★ 2026-08-31 편입. 08-31 (5) 회차가 «베뉴·도시 미확정»을 이유로 보류했던 건인데,
     *   **레포 관례상 그건 보류 사유가 아니다** — `aspt-korea`·`ajpc-incheon-1`·`ajpc-incheon-2`가
     *   이미 `venue: "공식 미기재"`로 편입돼 있다([[absence-may-be-the-standard]]).
     *   보류하면 대만 시즌에 **1/22~2/9 공백**이 남는다(앞 `gop-taipei-1` 1/18 종료 →
     *   뒤 `ps-championship-3-taipei` 2/26 개막).
     *
     * ★ 날짜는 1차 확인됐다 — `ctpclub.app/en/festivals/tmt-19` 헤더
     *   **`January 22, 2026 - February 9, 2026`**(Playwright 렌더 후 DOM).
     * 🔴 **그 페이지의 Schedule 탭은 지금도 `"No events scheduled for this day."`다.**
     *   이벤트·바이인·베뉴가 전부 공식 미기재 → **추측으로 채우지 않았다**(스파인 §1).
     * 🔴 `archive.ctpclub.app`도 확인했으나 **TMT 17회까지의 우승자 기록만** 있고
     *   19회 문서는 없다(사이트 자체가 © 2025 · 「第十九屆」 검색 0건). 이 경로는 닫혔다.
     * ⚠️ `city`는 JSON-LD 필수 필드라 채웠지만 **1차 근거가 없는 값**이다 —
     *   TMT 18·20·Championship이 전부 타이베이라는 전례에 따른 것이고,
     *   2차(somuchpoker)는 오히려 **`* multiple venues *`**라고 적는다.
     *   그래서 **카드에 보이는 `location`에는 도시를 단정하지 않았다.** 확인되면 정정할 것.
     */
    id: "tmt-19",
    name: "Taiwan Millions Tournament TMT 19",
    nameEn: "Taiwan Millions Tournament TMT 19",
    type: "international",
    startDate: "2026-01-22",
    endDate: "2026-02-09",
    location: "대만 (개최 지점 공식 미기재)",
    city: "Taipei",
    country: "TW",
    venue: "공식 미기재",
    buyin: "공식 미기재",
    emoji: "🇹🇼",
    color: "bg-cyan-500/15 text-cyan-400 border-cyan-500/30",
    note: "CTP 주최 TMT 19 — 일정·베뉴 외 상세는 공식 미기재",
    sourceUrl: "https://ctpclub.app/en/festivals/tmt-19",
    sourceTier: "A",
    verifiedAt: "2026-08-31",
  },
  {
    /**
     * `playersseries.com` 원문: `26 Feb – 10 Mar 2026` / `ASIA POKER ARENA, TAIPEI` /
     * `EVENTS 102` / `TOTAL PRIZE POOL NT$93.7M` / ME 우승 `Ki Young Kim NT$3,010,000`.
     * ★ 바이인 파싱 주의 — 이 사이트는 `Buy-in:` 라벨이 없고 «Levels N min» 다음 줄이 바이인이다.
     *   그 뒤의 NT$는 우승 상금이라 라벨 없이 긁으면 섞인다. 구조 앵커로 뽑았고,
     *   최솟값 «1»로 잡히던 건은 `NT$1.5M GTD`(개런티)의 오탐이라 제외했다.
     * ★ 우승자 한글 표기는 어떤 출처에도 없다 — TMT 20 `Park Daeyoung` 선례대로 로마자 유지.
     */
    id: "ps-championship-3-taipei",
    name: "PS Championship III Taipei 2026",
    nameEn: "PS Championship III Taipei 2026",
    type: "international",
    startDate: "2026-02-26",
    endDate: "2026-03-10",
    location: "대만 타이베이 (Asia Poker Arena)",
    city: "Taipei",
    country: "TW",
    venue: "Asia Poker Arena",
    buyin: "NT$2,500~NT$120,000",
    emoji: "🇹🇼",
    color: "bg-cyan-500/15 text-cyan-400 border-cyan-500/30",
    note: "102개 이벤트 · 총 상금풀 NT$93,700,000 · 메인이벤트 우승 Ki Young Kim NT$3,010,000",
    sourceUrl: "https://www.playersseries.com/series/psc3-taipei-2026",
    sourceTier: "A",
    verifiedAt: "2026-08-31",
  },
  {
    /**
     * 🔴 **CTP 목록과 주최사가 갈린 자리** — CTP는 `Mar 03 — Mar 23`이라고 적어 뒀지만
     * 주최사 `zodiacseriesofpoker.com` 헤더는 `12 - 23 MAR, 2026`이고 스케줄 첫날도 MAR 12다.
     * **주최사를 채택했다**(§12-B: 집계 요약이 아니라 원문).
     * 원문: `NT$ 60,000,000 GTD` / `Asia Poker Arena, Taipei`.
     * 바이인은 `Buy-in:` 라벨 103건 실측.
     */
    id: "zsop-horse-awakens",
    name: "Zodiac Series of Poker: The Horse Awakens",
    nameEn: "Zodiac Series of Poker: The Horse Awakens",
    type: "international",
    startDate: "2026-03-12",
    endDate: "2026-03-23",
    location: "대만 타이베이 (Asia Poker Arena)",
    city: "Taipei",
    country: "TW",
    venue: "Asia Poker Arena",
    buyin: "NT$1,900~NT$150,000",
    emoji: "🇹🇼",
    color: "bg-cyan-500/15 text-cyan-400 border-cyan-500/30",
    note: "시리즈 개런티 NT$60,000,000 — 2026 ZSOP 상반기 시리즈",
    sourceUrl: "https://zodiacseriesofpoker.com/series/the-horse-awakens",
    sourceTier: "A",
    verifiedAt: "2026-08-31",
  },
  {
    /**
     * `acepokerleague.com/event/?series_id=27` 원문: `APL TAIPEI 2026` /
     * `Total Prize: 50,000,000 TWD GTD` / `venue : Asia Poker Arena`.
     * ★ 3/28에 `#49 Mini Main Event [Overseas Day-1 PMANG]` 해외 Day-1이 하나 먼저 열렸다.
     *   그건 별도 플라이트라 시리즈 본편(4/3~4/12)을 시작일로 잡고 dateNote로 표기한다.
     * ★ 바이인은 «NT$X(내역 - 수수료)» 꼴만 센 실측 100건이다.
     *   괄호 없이 긁으면 `Prize: NT$1,700,000 GTD`가 바이인으로 섞인다(실제로 섞였다).
     */
    id: "apl-taipei",
    name: "Ace Poker League: APL Taipei 2026",
    nameEn: "Ace Poker League: APL Taipei 2026",
    type: "international",
    startDate: "2026-04-03",
    endDate: "2026-04-12",
    // 🔴 dateNote를 쓰지 마라 — `localizedDateRange`가 이 값을 **번역 없이 그대로** 붙인다.
    //    한국어를 넣으면 6개 다국어 페이지 본문에 한국어가 그대로 나간다(실제로 나갔다).
    //    `note`는 NOTES[locale] 사전을 타서 안전하므로 3/28 정보는 그쪽에 넣었다.
    location: "대만 타이베이 (Asia Poker Arena)",
    city: "Taipei",
    country: "TW",
    venue: "Asia Poker Arena",
    buyin: "NT$2,000~NT$100,000",
    emoji: "🇹🇼",
    color: "bg-cyan-500/15 text-cyan-400 border-cyan-500/30",
    note: "시리즈 개런티 NT$50,000,000 · 3/28에 해외 Day-1(PMANG) 별도 플라이트",
    sourceUrl: "https://acepokerleague.com/event/?series_id=27",
    sourceTier: "A",
    verifiedAt: "2026-08-31",
  },
  {
    /**
     * APC는 자체 공식 사이트가 없다. 그래서 개최 베뉴인 CTP의 공식 페스티벌 목록이 정본이고
     * (`ctpclub.app/en/festivals`에 `Asia Poker Championship: Taipei II 2026 May 05 — May 10, 2026`),
     * 베뉴 표기 `CTP Asia Poker Arena / Taiwan, Taipei City`는 CTP가 링크하는 somuchpoker에서 확인했다.
     * ★ 바이인은 CTP 목록에 없다 → `공식 미기재`. 같은 시리즈 `apc-taipei-4`와 동일한 취급이다.
     */
    id: "apc-taipei-2",
    name: "Asia Poker Championship Taipei II",
    nameEn: "Asia Poker Championship Taipei II",
    type: "international",
    startDate: "2026-05-05",
    endDate: "2026-05-10",
    location: "대만 타이베이 (CTP Asia Poker Arena)",
    city: "Taipei",
    country: "TW",
    venue: "CTP Asia Poker Arena",
    buyin: "공식 미기재",
    emoji: "🇹🇼",
    color: "bg-cyan-500/15 text-cyan-400 border-cyan-500/30",
    sourceUrl: "https://ctpclub.app/en/festivals",
    sourceTier: "A",
    verifiedAt: "2026-08-31",
  },
  {
    /**
     * `wpg.poker/event/wpg-taiwan-2026/` 원문: `23 May to 31 May` / `Venue Asia Poker Arena` /
     * `TWD 24 Million` / `58 TOTAL EVENTS`.
     * 바이인은 May 23~31 **날짜 탭 9개를 전부 클릭**해 모은 실측 범위다(한 탭만 보면 3K~77K로 좁게 잡힌다).
     * 프리롤 새틀(`Cap 200`)과 새틀 통과분(`Qualified`)은 바이인이 아니라 제외했다.
     * ★ ME 1위 상금은 **공식 TWD 1,600,000 ↔ somuchpoker TWD 1,437,000으로 충돌**하고
     *   딜 여부가 공식에 없다(docs/tournament-spine.md) → note에 쓰지 않는다.
     */
    id: "wpg-taiwan",
    name: "World Poker Games: Taiwan 2026",
    nameEn: "World Poker Games: Taiwan 2026",
    type: "international",
    startDate: "2026-05-23",
    endDate: "2026-05-31",
    location: "대만 타이베이 (Asia Poker Arena)",
    city: "Taipei",
    country: "TW",
    venue: "Asia Poker Arena",
    buyin: "TWD 2,100~TWD 77,000",
    emoji: "🇹🇼",
    color: "bg-cyan-500/15 text-cyan-400 border-cyan-500/30",
    note: "58개 이벤트 · 시리즈 개런티 TWD 24,000,000 — 주최 WPG Asia × CTP",
    sourceUrl: "https://wpg.poker/event/wpg-taiwan-2026/",
    sourceTier: "A",
    verifiedAt: "2026-08-31",
  },
  {
    id: "tmt-20",
    name: "Taiwan Millions Tournament TMT 20",
    nameEn: "Taiwan Millions Tournament TMT 20",
    type: "international",
    startDate: "2026-07-08",
    endDate: "2026-08-03",
    location: "대만 타이베이 (REDSPACE → Asia Poker Arena)",
    city: "Taipei",
    country: "TW",
    venue: "REDSPACE 多元商務空間 / Asia Poker Arena",
    buyin: "NT$200~NT$150,000",
    emoji: "🇹🇼",
    color: "bg-cyan-500/15 text-cyan-400 border-cyan-500/30",
    note: "메인이벤트 9,094 엔트리 — TMT 역대 최다 · 상금풀 NTD 66,786,336",
    sourceUrl: "https://ctpclub.app/en/festivals/tmt-20",
    sourceTier: "A",
    verifiedAt: "2026-07-29",
  },
  /**
   * ❌ apc-taipei-3 (Asia Poker Championship Taipei III · 2026-08-05~08-10) — 2026-08-31 삭제.
   *
   * **취소된 대회다. 되살리지 마라.**
   *  - 1차: `ctpclub.app/en/festivals`(주최 클럽 CTP)의 2026 목록에서 사라졌다.
   *    같은 자리(5월)에 있는 것은 **APC Taipei II**(05.05~05.10)이고, III는 어느 구획에도 없다.
   *    이 목록은 종료 대회를 지우지 않는다(TMT 20·WPG 5월분이 그대로 남아 있다)
   *    → «지나가서 빠진 것»이 아니라 «편성에서 빠진 것»이다.
   *  - 2차 축어: somuchpoker `[CANCELLED] APC Taipei III 2026`(2026.08.20 갱신) —
   *    "has been officially cancelled. Organizers confirmed the series will not proceed
   *     on these dates, and the event has been removed from the venue's active schedule."
   *  - 선례: WSOP Super Circuit Cyprus 취소분(docs/tournament-spine.md) — «게시 금지».
   *
   * 이 항목은 카드뿐 아니라 **Event JSON-LD로도 나가고 있었다**(7로케일 + KO).
   */
  {
    id: "ps-championship-4-taipei",
    name: "PS Championship IV Taipei 2026",
    nameEn: "PS Championship IV Taipei 2026",
    type: "international",
    startDate: "2026-08-19",
    endDate: "2026-08-31",
    location: "대만 타이베이 (CTP Asia Poker Arena)",
    city: "Taipei",
    country: "TW",
    venue: "CTP Asia Poker Arena",
    buyin: "프리롤~NT$120,000",
    emoji: "🇹🇼",
    color: "bg-cyan-500/15 text-cyan-400 border-cyan-500/30",
    note: "104개 이벤트 · 총 NTD 39,000,000+ 보장 · 메인 NTD 15,000,000 GTD",
    sourceUrl: "https://ctpclub.app/en/festivals",
    sourceTier: "A",
    verifiedAt: "2026-07-29",
  },
  {
    /**
     * 🔴 **2026-08-31 정정: 시작일 09-04 → 09-03.** 주최사 `zodiacseriesofpoker.com`을 직접 열었다.
     *  - 헤더 `3 - 15 SEPT, 2026` · 스케줄 첫 날짜 앵커 `SEP 3, 2026`(그날 S1·Z1 등 이벤트 편성)
     *  - CTP 목록도 `Sep 03`이다. 즉 **09-04를 쓰던 우리만 하루 늦었다.**
     *  - 🔴 스파인의 「somuchpoker 09.03은 오류」 메모는 **반대로 우리 쪽이 틀린 것**이었다(같이 정정).
     *
     * ⚠ **1차 출처 자기모순**([[primary-source-self-contradiction]]): 헤더는 `3 - 15`인데
     *   스케줄 날짜 앵커는 SEP 3~14 **12일뿐이고 SEP 15는 어디에도 없다**.
     *   9/14가 `Z8 - Zodiac Horse Main Event Final Day`라 시리즈는 그날 끝난다.
     *   → **엔트리 열거를 채택해 endDate는 09-14 유지.** 헤더 15는 주최사 표기 오차로 본다.
     */
    id: "zsop-final-horse",
    name: "Zodiac Series of Poker: The Final Horse",
    nameEn: "Zodiac Series of Poker: The Final Horse",
    type: "international",
    startDate: "2026-09-03",
    endDate: "2026-09-14",
    location: "대만 타이베이 (Asia Poker Arena)",
    city: "Taipei",
    country: "TW",
    venue: "Asia Poker Arena",
    buyin: "NT$2,000~NT$100,000",
    emoji: "🇹🇼",
    color: "bg-cyan-500/15 text-cyan-400 border-cyan-500/30",
    note: "시리즈 개런티 NT$23,456,789 · 메인이벤트 파이널데이 9/14",
    sourceUrl: "https://zodiacseriesofpoker.com/series/the-final-horse",
    sourceTier: "A",
    verifiedAt: "2026-08-31",
  },
  {
    /**
     * ★ 2026-08-31 갱신 — 「공식 미기재」였는데 **주최사 공식에 전부 공개돼 있었다.**
     *   07-29엔 CTP 목록(`ctpclub.app/en/festivals`)만 근거였다. 주최사 공식은 **`hpc.poker`**이고
     *   거기에 5일 전 일정·바이인·구조·베뉴가 다 있다 → sourceUrl을 주최사로 올렸다.
     * ★ 실측(날짜 탭 **5개를 전부 클릭**해 수집 · 이벤트 29건):
     *   최소 **NT$3,500**(BIG O·Fixed Limit Triple Draw·獵殺AJ·Bomb Pot·Hyper Turbo 등 다수) ·
     *   최대 **NT$33,000**(`SPARROW CUP HIGH ROLLER`) · 메인이벤트 **NT$6,000,000 GTD**
     *   (Day 1 진출률별로 NT$8,000/10% · NT$14,000/17.5% · NT$20,000/25% 세 갈래).
     * 🔴 **오탐 3종을 배제했다** — ① `Rebuy NT$500`·`NT$800`은 «MAIN EVENT **FREEROLL**
     *   SATELLITE»의 리바이라 바이인이 아니다(APPT `#53 Employees`의 `- / Re Entry`와 같은 계급)
     *   ② `6`은 `NT$6M GTD` ③ `30`은 `MIN CASH NT$30K`의 파편.
     * 🔴 **첫 탭만 보면 범위가 틀린다** — DOM에 첫날(9.30)만 있고 나머지 4일은 클릭해야 로드된다.
     *   최대값 NT$33,000은 **둘째 탭(10.01)에서만** 나온다. 어제 WPG 교훈과 같은 자리.
     * 🪶 6월 판(`Harbour Poker Cup 2026-1` 06.17~21)은 **여전히 편입 불가**다 —
     *   `hpc.poker`가 «현재 판만» 띄우는 구조라 1차가 부존재하고, CTP 목록에만 남아 있다.
     */
    id: "harbour-poker-cup-2",
    name: "Harbour Poker Cup II 2026",
    nameEn: "Harbour Poker Cup II 2026",
    type: "international",
    startDate: "2026-09-30",
    endDate: "2026-10-04",
    location: "대만 타이베이 (CTP Asia Poker Arena)",
    city: "Taipei",
    country: "TW",
    venue: "CTP Asia Poker Arena",
    buyin: "NT$3,500~NT$33,000",
    emoji: "🇹🇼",
    color: "bg-cyan-500/15 text-cyan-400 border-cyan-500/30",
    note: "메인이벤트 NT$6,000,000 GTD — Day 1 진출률 10%·17.5%·25% 세 갈래",
    sourceUrl: "https://hpc.poker/",
    sourceTier: "A",
    verifiedAt: "2026-08-31",
  },
  {
    id: "tmt-championship",
    name: "Taiwan Millions Tournament Championship 2026",
    nameEn: "Taiwan Millions Tournament Championship 2026",
    type: "international",
    startDate: "2026-10-16",
    endDate: "2026-10-26",
    location: "대만 타이베이 (CTP Asia Poker Arena)",
    city: "Taipei",
    country: "TW",
    venue: "CTP Asia Poker Arena",
    buyin: "공식 미기재",
    emoji: "🇹🇼",
    color: "bg-cyan-500/15 text-cyan-400 border-cyan-500/30",
    note: "NTD 30,000,000 GTD (귀속 대상 공식 미기재)",
    sourceUrl: "https://ctpclub.app/en/festivals",
    sourceTier: "A",
    verifiedAt: "2026-07-29",
  },
  {
    id: "apc-taipei-4",
    name: "Asia Poker Championship Taipei IV 2026",
    nameEn: "Asia Poker Championship Taipei IV 2026",
    type: "international",
    startDate: "2026-12-02",
    endDate: "2026-12-13",
    location: "대만 타이베이 (CTP Asia Poker Arena)",
    city: "Taipei",
    country: "TW",
    venue: "CTP Asia Poker Arena",
    buyin: "공식 미기재",
    emoji: "🇹🇼",
    color: "bg-cyan-500/15 text-cyan-400 border-cyan-500/30",
    sourceUrl: "https://ctpclub.app/en/festivals",
    sourceTier: "A",
    verifiedAt: "2026-07-29",
  },
  {
    id: "ola-poker-tour-taipei",
    name: "OLA Poker Tour: Taipei",
    nameEn: "OLA Poker Tour: Taipei",
    type: "international",
    startDate: "2026-12-16",
    endDate: "2026-12-21",
    location: "대만 타이베이 (CTP Asia Poker Arena)",
    city: "Taipei",
    country: "TW",
    venue: "CTP Asia Poker Arena",
    buyin: "공식 미기재",
    emoji: "🇹🇼",
    color: "bg-cyan-500/15 text-cyan-400 border-cyan-500/30",
    // ⚠️ 공식 목록의 명칭이 "OLA Poker Tour: Taipei 2025"인데 날짜는 2026년이다(주최측 표기 오류로 보임)
    note: "공식 목록 명칭에 연도가 2025로 표기돼 있으나 일정은 2026년",
    sourceUrl: "https://ctpclub.app/en/festivals",
    sourceTier: "A",
    verifiedAt: "2026-07-29",
  },

  /* ── 🇨🇾 북키프로스 Merit — 하이롤러 씬의 유럽 거점 ────────── */
  {
    id: "merit-noir",
    name: "NOIR Poker Series",
    nameEn: "NOIR Poker Series",
    type: "international",
    startDate: "2026-07-27",
    endDate: "2026-08-06",
    location: "북키프로스 키레니아 (Merit Royal Diamond)",
    city: "Kyrenia",
    country: "CY",
    venue: "Merit Royal Diamond Hotel Casino & Spa",
    buyin: "$330~$7,500",
    emoji: "🃏",
    color: "bg-slate-500/15 text-slate-400 border-slate-500/30",
    note: "Merit 첫 NOIR 시리즈 · 총 $6,000,000+ 보장 · 메인 $5,500 (8/2~6, $3M GTD)",
    sourceUrl: "https://meritpoker.com/event/noir-series-27-jul-6-aug/",
    sourceTier: "A",
    verifiedAt: "2026-07-29",
  },
  {
    id: "merit-onyx-aug",
    name: "Onyx High Roller Series (8월)",
    nameEn: "Onyx High Roller Series (August)",
    type: "international",
    startDate: "2026-08-07",
    endDate: "2026-08-16",
    location: "북키프로스 키레니아 (Merit Royal Diamond)",
    city: "Kyrenia",
    country: "CY",
    venue: "Merit Royal Diamond Hotel Casino & Spa",
    buyin: "$10,400~$50,500",
    emoji: "🃏",
    color: "bg-slate-500/15 text-slate-400 border-slate-500/30",
    note: "메인이벤트 $25,500 / $5M GTD · Premiere $10,400 / $5M GTD",
    // meritpoker.com의 8월 Onyx 페이지는 NOIR 콘텐츠를 표시하는 오염 상태 → Onyx 자체 사이트로 링크
    sourceUrl: "https://onyxclub.com/events/high-roller-series-aug-26/",
    sourceTier: "A",
    verifiedAt: "2026-07-29",
  },
  {
    id: "mediterranean-poker-party",
    name: "Mediterranean Poker Party",
    nameEn: "Mediterranean Poker Party",
    type: "international",
    startDate: "2026-09-17",
    endDate: "2026-09-27",
    location: "북키프로스 (Merit Poker)",
    city: "Kyrenia",
    country: "CY",
    venue: "Merit Poker",
    buyin: "공식 미기재",
    emoji: "🃏",
    color: "bg-slate-500/15 text-slate-400 border-slate-500/30",
    // 투어 자체 사이트(medpokerparty.com)는 2025년판만 게시돼 있어 Merit 캘린더를 정본으로 삼는다
    sourceUrl: "https://meritpoker.com/tournaments/",
    sourceTier: "A",
    verifiedAt: "2026-07-29",
  },

  /* ── 🌍 WSOP Circuit 국제 스톱 ────────── */
  {
    id: "wsopc-tallinn",
    name: "WSOP Circuit 탈린",
    nameEn: "WSOP Circuit Tallinn",
    type: "international",
    startDate: "2026-07-24",
    endDate: "2026-08-02",
    location: "에스토니아 탈린 (Olympic Park Casino)",
    city: "Tallinn",
    country: "EE",
    venue: "Olympic Park Casino",
    buyin: "공식 미기재",
    emoji: "🔵",
    color: "bg-blue-500/15 text-blue-400 border-blue-500/30",
    note: "링 이벤트 12개 · 메인 €1,500 / €1M GTD",
    sourceUrl: "https://www.wsop.com/circuit/",
    sourceTier: "A",
    verifiedAt: "2026-07-29",
  },
  {
    id: "wsopc-bratislava",
    name: "WSOP Circuit 브라티슬라바",
    nameEn: "WSOP Circuit Bratislava",
    type: "international",
    startDate: "2026-07-31",
    endDate: "2026-08-11",
    location: "슬로바키아 브라티슬라바 (Card Casino)",
    city: "Bratislava",
    country: "SK",
    venue: "Card Casino",
    buyin: "공식 미기재",
    emoji: "🔵",
    color: "bg-blue-500/15 text-blue-400 border-blue-500/30",
    sourceUrl: "https://www.wsop.com/circuit/",
    sourceTier: "A",
    verifiedAt: "2026-07-29",
  },
  {
    id: "wsopc-canada-super",
    name: "WSOP Super Circuit 캐나다",
    nameEn: "WSOP Super Circuit Canada",
    type: "international",
    startDate: "2026-08-26",
    endDate: "2026-09-12",
    location: "캐나다 퀘벡 (Playground)",
    city: "Kahnawake",
    country: "CA",
    venue: "Playground",
    buyin: "공식 미기재",
    emoji: "🔵",
    color: "bg-blue-500/15 text-blue-400 border-blue-500/30",
    note: "슈퍼 서킷 — 정규 서킷과 별도 브랜드",
    sourceUrl: "https://www.wsop.com/circuit/",
    sourceTier: "A",
    verifiedAt: "2026-08-31",
  },
  {
    id: "wsopc-mexico",
    name: "WSOP Circuit 멕시코시티",
    nameEn: "WSOP Circuit Mexico City",
    type: "international",
    startDate: "2026-08-31",
    endDate: "2026-09-11",
    location: "멕시코 멕시코시티 (Barceló Santa Fe)",
    city: "Mexico City",
    country: "MX",
    venue: "Barceló México Santa Fe Hotel",
    buyin: "$300~$3,000",
    emoji: "🔵",
    color: "bg-blue-500/15 text-blue-400 border-blue-500/30",
    note: "링 이벤트 12개 · 메인 $1,700 (Big Bola Casinos 주최)",
    sourceUrl: "https://www.wsop.com/circuit/",
    sourceTier: "A",
    verifiedAt: "2026-08-31",
  },
  {
    id: "wsopc-paris",
    name: "WSOP Circuit 파리",
    nameEn: "WSOP Circuit Paris",
    type: "international",
    startDate: "2026-09-01",
    endDate: "2026-09-14",
    location: "프랑스 파리 (Partouche Casino Club)",
    city: "Paris",
    country: "FR",
    venue: "Partouche Casino Club",
    buyin: "공식 미기재",
    emoji: "🔵",
    color: "bg-blue-500/15 text-blue-400 border-blue-500/30",
    sourceUrl: "https://www.wsop.com/circuit/",
    sourceTier: "A",
    verifiedAt: "2026-08-31",
  },
  {
    id: "wsopc-liechtenstein",
    name: "WSOP Circuit 리히텐슈타인",
    nameEn: "WSOP Circuit Liechtenstein",
    type: "international",
    startDate: "2026-09-10",
    endDate: "2026-09-22",
    location: "리히텐슈타인 감프린 (Grand Casino)",
    city: "Gamprin",
    country: "LI",
    venue: "Grand Casino Liechtenstein",
    buyin: "공식 미기재",
    emoji: "🔵",
    color: "bg-blue-500/15 text-blue-400 border-blue-500/30",
    note: "연 2회 개최 중 2차",
    sourceUrl: "https://www.wsop.com/circuit/",
    sourceTier: "A",
    verifiedAt: "2026-08-31",
  },
  {
    id: "wsopc-malta",
    name: "WSOP Circuit 몰타",
    nameEn: "WSOP Circuit Malta",
    type: "international",
    startDate: "2026-09-25",
    endDate: "2026-10-05",
    location: "몰타 세인트줄리안 (Casino Malta)",
    city: "St. Julian's",
    country: "MT",
    venue: "Casino Malta",
    buyin: "공식 미기재",
    emoji: "🔵",
    color: "bg-blue-500/15 text-blue-400 border-blue-500/30",
    sourceUrl: "https://www.wsop.com/circuit/",
    sourceTier: "A",
    verifiedAt: "2026-08-31",
  },
  {
    id: "wsopc-calgary",
    name: "WSOP Circuit 캘거리",
    nameEn: "WSOP Circuit Calgary",
    type: "international",
    startDate: "2026-09-30",
    endDate: "2026-10-12",
    location: "캐나다 캘거리 (Deerfoot Inn)",
    city: "Calgary",
    country: "CA",
    venue: "Deerfoot Inn & Casino",
    buyin: "공식 미기재",
    emoji: "🔵",
    color: "bg-blue-500/15 text-blue-400 border-blue-500/30",
    sourceUrl: "https://www.wsop.com/circuit/",
    sourceTier: "A",
    verifiedAt: "2026-08-31",
  },
  {
    id: "wsopc-madrid",
    name: "WSOP Circuit 마드리드",
    nameEn: "WSOP Circuit Madrid",
    type: "international",
    startDate: "2026-10-23",
    endDate: "2026-11-02",
    location: "스페인 마드리드 (Casino Gran Vía)",
    city: "Madrid",
    country: "ES",
    venue: "Casino Gran Via",
    buyin: "공식 미기재",
    emoji: "🔵",
    color: "bg-blue-500/15 text-blue-400 border-blue-500/30",
    sourceUrl: "https://www.wsop.com/circuit/",
    sourceTier: "A",
    verifiedAt: "2026-08-31",
  },
  {
    id: "wsopc-playground-nov",
    name: "WSOP Circuit 플레이그라운드 (11월)",
    nameEn: "WSOP Circuit Playground (November)",
    type: "international",
    startDate: "2026-11-02",
    endDate: "2026-11-17",
    location: "캐나다 퀘벡 (Playground)",
    city: "Kahnawake",
    country: "CA",
    venue: "Playground",
    buyin: "공식 미기재",
    emoji: "🔵",
    color: "bg-blue-500/15 text-blue-400 border-blue-500/30",
    note: "3월·8월에 이은 연 3회차",
    sourceUrl: "https://www.wsop.com/circuit/",
    sourceTier: "A",
    verifiedAt: "2026-08-31",
  },
  {
    id: "wsopc-panama",
    name: "WSOP Circuit 파나마시티",
    nameEn: "WSOP Circuit Panama City",
    type: "international",
    startDate: "2026-11-05",
    endDate: "2026-11-15",
    location: "파나마 파나마시티",
    city: "Panama City",
    country: "PA",
    venue: "공식 미기재",
    buyin: "공식 미기재",
    emoji: "🔵",
    color: "bg-blue-500/15 text-blue-400 border-blue-500/30",
    sourceUrl: "https://www.wsop.com/circuit/",
    sourceTier: "A",
    verifiedAt: "2026-08-31",
  },
  {
    id: "wsopc-middelkerke",
    name: "WSOP Circuit 미델케르케",
    nameEn: "WSOP Circuit Middelkerke",
    type: "international",
    startDate: "2026-11-06",
    endDate: "2026-11-15",
    location: "벨기에 미델케르케 (Casino Middelkerke)",
    city: "Middelkerke",
    country: "BE",
    venue: "Casino Middelkerke Betfirst by Partouche",
    buyin: "공식 미기재",
    emoji: "🔵",
    color: "bg-blue-500/15 text-blue-400 border-blue-500/30",
    sourceUrl: "https://www.wsop.com/circuit/",
    sourceTier: "A",
    verifiedAt: "2026-08-31",
  },
  {
    id: "wsopc-sanremo",
    name: "WSOP Circuit 산레모",
    nameEn: "WSOP Circuit Sanremo",
    type: "international",
    startDate: "2026-11-20",
    endDate: "2026-11-30",
    location: "이탈리아 산레모 (Casino Sanremo)",
    city: "Sanremo",
    country: "IT",
    venue: "Casino Sanremo",
    buyin: "공식 미기재",
    emoji: "🔵",
    color: "bg-blue-500/15 text-blue-400 border-blue-500/30",
    sourceUrl: "https://www.wsop.com/circuit/",
    sourceTier: "A",
    verifiedAt: "2026-08-31",
  },

  /* ── 🇬🇧🇪🇸🇮🇪 partypoker Tour — UK 5 · 스페인 4 · 아일랜드 1 ────────── */
  {
    id: "pp-sheffield",
    name: "partypoker Tour 셰필드",
    nameEn: "partypoker Tour Sheffield",
    type: "international",
    startDate: "2026-01-27",
    endDate: "2026-02-01",
    location: "영국 셰필드 (Genting Casino)",
    city: "Sheffield",
    country: "GB",
    venue: "Genting Casino Sheffield",
    buyin: "£150~£1,000",
    emoji: "🎲",
    color: "bg-orange-500/15 text-orange-400 border-orange-500/30",
    sourceUrl: "https://www.partypoker.com/en/poker/p/party-poker-tour-2026/index",
    sourceTier: "A",
    verifiedAt: "2026-07-29",
  },
  {
    id: "pp-seville",
    name: "partypoker Tour 세비야",
    nameEn: "partypoker Tour Seville",
    type: "international",
    startDate: "2026-03-16",
    endDate: "2026-03-22",
    location: "스페인 세비야 (Casino Admiral)",
    city: "Seville",
    country: "ES",
    venue: "Casino Admiral Seville",
    buyin: "€150~€1,000",
    emoji: "🎲",
    color: "bg-orange-500/15 text-orange-400 border-orange-500/30",
    sourceUrl: "https://www.partypoker.com/en/poker/p/party-poker-tour-2026/index",
    sourceTier: "A",
    verifiedAt: "2026-07-29",
  },
  {
    id: "pp-madrid",
    name: "partypoker Tour 마드리드",
    nameEn: "partypoker Tour Madrid",
    type: "international",
    startDate: "2026-05-11",
    endDate: "2026-05-17",
    location: "스페인 마드리드 (Casino Gran Vía)",
    city: "Madrid",
    country: "ES",
    venue: "Casino Gran Vía Madrid",
    buyin: "€150~€1,000",
    emoji: "🎲",
    color: "bg-orange-500/15 text-orange-400 border-orange-500/30",
    sourceUrl: "https://www.partypoker.com/en/poker/p/party-poker-tour-2026/index",
    sourceTier: "A",
    verifiedAt: "2026-07-29",
  },
  {
    id: "pp-manchester",
    name: "partypoker Tour 맨체스터",
    nameEn: "partypoker Tour Manchester",
    type: "international",
    startDate: "2026-06-13",
    endDate: "2026-06-21",
    location: "영국 맨체스터 (Manchester235)",
    city: "Manchester",
    country: "GB",
    venue: "Manchester235 Poker Room & Casino",
    buyin: "£150~£1,000",
    emoji: "🎲",
    color: "bg-orange-500/15 text-orange-400 border-orange-500/30",
    sourceUrl: "https://www.partypoker.com/en/poker/p/party-poker-tour-2026/index",
    sourceTier: "A",
    verifiedAt: "2026-07-29",
  },
  {
    id: "pp-london-jul",
    name: "partypoker Tour 런던 (7월)",
    nameEn: "partypoker Tour London (July)",
    type: "international",
    startDate: "2026-07-04",
    endDate: "2026-07-12",
    location: "영국 런던 (Genting Stratford)",
    city: "London",
    country: "GB",
    venue: "Genting Casino Stratford",
    buyin: "£150~£1,000",
    emoji: "🎲",
    color: "bg-orange-500/15 text-orange-400 border-orange-500/30",
    note: "21개 이벤트",
    sourceUrl: "https://www.partypoker.com/en/poker/p/party-poker-tour-2026/index",
    sourceTier: "A",
    verifiedAt: "2026-07-29",
  },
  {
    id: "pp-glasgow",
    name: "partypoker Tour 글래스고",
    nameEn: "partypoker Tour Glasgow",
    type: "international",
    startDate: "2026-08-03",
    endDate: "2026-08-09",
    location: "영국 글래스고 (Alea Casino)",
    city: "Glasgow",
    country: "GB",
    venue: "Alea Casino Glasgow",
    buyin: "£150~£1,000",
    emoji: "🎲",
    color: "bg-orange-500/15 text-orange-400 border-orange-500/30",
    note: "메인이벤트 £500 (£445+£55) / £100,000 GTD",
    sourceUrl: "https://www.partypoker.com/en/poker/p/party-poker-tour-2026/index",
    sourceTier: "A",
    verifiedAt: "2026-07-29",
  },
  {
    id: "pp-castellon",
    name: "partypoker Tour 카스테욘",
    nameEn: "partypoker Tour Castellón",
    type: "international",
    startDate: "2026-10-05",
    endDate: "2026-10-11",
    location: "스페인 카스테욘",
    city: "Castellón",
    country: "ES",
    venue: "공식 미기재",
    buyin: "€150~€1,000",
    emoji: "🎲",
    color: "bg-orange-500/15 text-orange-400 border-orange-500/30",
    sourceUrl: "https://www.partypoker.com/en/poker/p/party-poker-tour-2026/index",
    sourceTier: "A",
    verifiedAt: "2026-07-29",
  },
  {
    id: "pp-cork",
    name: "partypoker Tour 코크",
    nameEn: "partypoker Tour Cork",
    type: "international",
    startDate: "2026-11-09",
    endDate: "2026-11-15",
    location: "아일랜드 코크 (Macau Casino)",
    city: "Cork",
    country: "IE",
    venue: "Macau Casino Complex, 16 St. Patricks Quay",
    buyin: "€150~€1,000",
    emoji: "🎲",
    color: "bg-orange-500/15 text-orange-400 border-orange-500/30",
    note: "메인 €500 / €100,000 GTD · 투어 유일의 아일랜드 스톱",
    sourceUrl: "https://www.partypoker.com/en/poker/p/party-poker-tour-2026/index",
    sourceTier: "A",
    verifiedAt: "2026-07-29",
  },
  {
    id: "pp-murcia",
    name: "partypoker Tour 무르시아",
    nameEn: "partypoker Tour Murcia",
    type: "international",
    startDate: "2026-11-30",
    endDate: "2026-12-06",
    location: "스페인 무르시아",
    city: "Murcia",
    country: "ES",
    venue: "공식 미기재",
    buyin: "€150~€1,000",
    emoji: "🎲",
    color: "bg-orange-500/15 text-orange-400 border-orange-500/30",
    sourceUrl: "https://www.partypoker.com/en/poker/p/party-poker-tour-2026/index",
    sourceTier: "A",
    verifiedAt: "2026-07-29",
  },
  {
    id: "pp-london-dec",
    name: "partypoker Tour 런던 (12월)",
    nameEn: "partypoker Tour London (December)",
    type: "international",
    startDate: "2026-12-12",
    endDate: "2026-12-20",
    location: "영국 런던",
    city: "London",
    country: "GB",
    venue: "공식 미기재",
    buyin: "£150~£1,000",
    emoji: "🎲",
    color: "bg-orange-500/15 text-orange-400 border-orange-500/30",
    note: "시즌 최종 스톱",
    sourceUrl: "https://www.partypoker.com/en/poker/p/party-poker-tour-2026/index",
    sourceTier: "A",
    verifiedAt: "2026-07-29",
  },

  /* ── 🇧🇷 BSOP (브라질) — 20주년 시즌 ────────── */
  {
    id: "bsop-winter",
    name: "BSOP Winter",
    nameEn: "BSOP Winter",
    type: "international",
    startDate: "2026-07-21",
    endDate: "2026-07-30",
    location: "브라질 상파울루 (WTC Sheraton)",
    city: "São Paulo",
    country: "BR",
    venue: "Golden Hall, WTC Sheraton",
    buyin: "R$500~R$100,000",
    emoji: "🇧🇷",
    color: "bg-green-500/15 text-green-400 border-green-500/30",
    note: "메인이벤트 1,315 엔트리 · 상금풀 R$5.1M 초과",
    sourceUrl: "https://bsop.com.br/proximas-etapas/",
    sourceTier: "A",
    verifiedAt: "2026-07-29",
  },
  {
    id: "bsop-floripa",
    name: "BSOP Floripa",
    nameEn: "BSOP Floripa",
    type: "international",
    startDate: "2026-09-04",
    endDate: "2026-09-08",
    location: "브라질 플로리아노폴리스 (Costão do Santinho)",
    city: "Florianópolis",
    country: "BR",
    venue: "Costão do Santinho",
    buyin: "R$500~R$25,000",
    emoji: "🇧🇷",
    color: "bg-green-500/15 text-green-400 border-green-500/30",
    note: "26개 토너먼트 (새틀라이트 제외)",
    sourceUrl: "https://bsop.com.br/proximas-etapas/",
    sourceTier: "A",
    verifiedAt: "2026-07-29",
  },
  {
    id: "bsop-millions",
    name: "BSOP Millions",
    nameEn: "BSOP Millions",
    type: "international",
    startDate: "2026-11-13",
    endDate: "2026-11-28",
    location: "브라질 상파울루 (WTC Sheraton)",
    city: "São Paulo",
    country: "BR",
    venue: "WTC Sheraton",
    buyin: "공식 미기재",
    emoji: "🇧🇷",
    color: "bg-green-500/15 text-green-400 border-green-500/30",
    note: "라틴아메리카 최대 포커 이벤트 (주최측 자체 표현)",
    sourceUrl: "https://bsop.com.br/proximas-etapas/",
    sourceTier: "A",
    verifiedAt: "2026-07-29",
  },
  {
    id: "bsop-summer-2027",
    name: "BSOP Summer 2027",
    nameEn: "BSOP Summer 2027",
    type: "international",
    startDate: "2027-01-22",
    endDate: "2027-01-30",
    location: "브라질 바이아 (Costa do Sauípe)",
    city: "Mata de São João",
    country: "BR",
    venue: "Sauípe Resorts",
    buyin: "공식 미기재",
    emoji: "🇧🇷",
    color: "bg-green-500/15 text-green-400 border-green-500/30",
    sourceUrl: "https://bsop.com.br/proximas-etapas/",
    sourceTier: "A",
    verifiedAt: "2026-07-29",
  },

  /* ── 🇦🇷 CAP (아르헨티나) — 15주년 시즌 ────────── */
  {
    id: "cap-5-santarosa",
    name: "CAP 5° Fecha 산타로사",
    nameEn: "CAP 5° Fecha Santa Rosa",
    type: "international",
    startDate: "2026-08-19",
    endDate: "2026-08-24",
    location: "아르헨티나 산타로사 (Casino Club)",
    city: "Santa Rosa",
    country: "AR",
    venue: "Casino Club Santa Rosa",
    buyin: "USD 100~1,000",
    emoji: "🇦🇷",
    color: "bg-sky-500/15 text-sky-400 border-sky-500/30",
    note: "메인이벤트 USD 500",
    sourceUrl: "https://capoker.com.ar/calendario-2026/",
    sourceTier: "A",
    verifiedAt: "2026-07-29",
  },
  {
    id: "cap-6-iguazu",
    name: "CAP 6° Fecha 이과수",
    nameEn: "CAP 6° Fecha Puerto Iguazú",
    type: "international",
    startDate: "2026-09-16",
    endDate: "2026-09-21",
    location: "아르헨티나 푸에르토이과수 (City Center)",
    city: "Puerto Iguazú",
    country: "AR",
    venue: "City Center Iguazú",
    buyin: "공식 미기재",
    emoji: "🇦🇷",
    color: "bg-sky-500/15 text-sky-400 border-sky-500/30",
    sourceUrl: "https://capoker.com.ar/calendario-2026/",
    sourceTier: "A",
    verifiedAt: "2026-07-29",
  },
  {
    id: "cap-7-buenosaires",
    name: "CAP 7° Fecha 부에노스아이레스",
    nameEn: "CAP 7° Fecha Buenos Aires",
    type: "international",
    startDate: "2026-10-03",
    endDate: "2026-10-11",
    location: "아르헨티나 부에노스아이레스 (Casino BA)",
    city: "Buenos Aires",
    country: "AR",
    venue: "Casino Buenos Aires",
    buyin: "공식 미기재",
    emoji: "🇦🇷",
    color: "bg-sky-500/15 text-sky-400 border-sky-500/30",
    sourceUrl: "https://capoker.com.ar/calendario-2026/",
    sourceTier: "A",
    verifiedAt: "2026-07-29",
  },
  {
    id: "cap-8-rosario",
    name: "CAP 8° Fecha 로사리오",
    nameEn: "CAP 8° Fecha Rosario",
    type: "international",
    startDate: "2026-12-12",
    endDate: "2026-12-20",
    location: "아르헨티나 로사리오 (City Center)",
    city: "Rosario",
    country: "AR",
    venue: "City Center Rosario",
    buyin: "공식 미기재",
    emoji: "🇦🇷",
    color: "bg-sky-500/15 text-sky-400 border-sky-500/30",
    note: "시즌 최종전",
    sourceUrl: "https://capoker.com.ar/calendario-2026/",
    sourceTier: "A",
    verifiedAt: "2026-07-29",
  },

  /* ── ♠️ PokerStars Live 기타 ────────── */
  {
    id: "maryland-state",
    name: "Maryland State Poker Championship",
    nameEn: "Maryland State Poker Championship",
    type: "international",
    startDate: "2026-08-26",
    endDate: "2026-09-07",
    location: "미국 메릴랜드 (Live! Casino)",
    city: "Hanover",
    country: "US",
    venue: "Live! Casino & Hotel Maryland",
    buyin: "공식 미기재",
    emoji: "♠️",
    color: "bg-teal-500/15 text-teal-400 border-teal-500/30",
    note: "16개 트로피 이벤트 · 총 $1,000,000+ 보장 · 메인 $500K GTD",
    sourceUrl: "https://www.pokerstarslive.com/maryland-state-poker-championship/",
    sourceTier: "A",
    verifiedAt: "2026-08-31",
  },
  {
    id: "bpc-megastack",
    name: "BPC Megastack Edition",
    nameEn: "BPC Megastack Edition",
    type: "international",
    startDate: "2026-09-17",
    endDate: "2026-09-27",
    location: "벨기에 나뮈르 (Circus Casino Resort)",
    city: "Namur",
    country: "BE",
    venue: "Circus Casino Resort Namur",
    buyin: "€400~",
    emoji: "♠️",
    color: "bg-teal-500/15 text-teal-400 border-teal-500/30",
    note: "메인이벤트 €400 / €300,000 GTD",
    sourceUrl: "https://www.pokerstarslive.com/sponsored/belgianpokerchallenge/",
    sourceTier: "A",
    verifiedAt: "2026-07-29",
  },
  {
    id: "ps-open-aix",
    name: "PokerStars Open 엑상프로방스",
    nameEn: "PokerStars Open Aix-en-Provence",
    type: "international",
    startDate: "2026-11-02",
    endDate: "2026-11-08",
    location: "프랑스 엑상프로방스 (Pasino GRAND)",
    city: "Aix-en-Provence",
    country: "FR",
    venue: "Pasino GRAND Partouche",
    buyin: "€1,100~",
    emoji: "♠️",
    color: "bg-teal-500/15 text-teal-400 border-teal-500/30",
    note: "메인이벤트 €1,100 / €1,000,000 GTD",
    sourceUrl: "https://www.pokerstarslive.com/pokerstarsopen/aixenprovence/",
    sourceTier: "A",
    verifiedAt: "2026-07-29",
  },
  /* ── 🇺🇸 WSOP Circuit 미국 스톱 (하반기) ────────── */
  {
    id: "wsopc-cherokee-aug",
    name: "WSOP Circuit 체로키 (8월)",
    nameEn: "WSOP Circuit Cherokee (August)",
    type: "international",
    startDate: "2026-08-06",
    endDate: "2026-08-17",
    location: "미국 NC (Harrah's Cherokee)",
    city: "Cherokee",
    country: "US",
    venue: "Harrah's Cherokee",
    buyin: "공식 미기재",
    emoji: "🇺🇸",
    color: "bg-blue-500/15 text-blue-400 border-blue-500/30",
    sourceUrl: "https://www.wsop.com/schedule/",
    sourceTier: "A",
    verifiedAt: "2026-07-29",
  },
  {
    id: "wsopc-atlantic-city",
    name: "WSOP Circuit 애틀랜틱시티",
    nameEn: "WSOP Circuit Atlantic City",
    type: "international",
    startDate: "2026-08-13",
    endDate: "2026-08-24",
    location: "미국 NJ (Harrah's Atlantic City)",
    city: "Atlantic City",
    country: "US",
    venue: "Harrah's Atlantic City",
    buyin: "공식 미기재",
    emoji: "🇺🇸",
    color: "bg-blue-500/15 text-blue-400 border-blue-500/30",
    sourceUrl: "https://www.wsop.com/schedule/",
    sourceTier: "A",
    verifiedAt: "2026-07-29",
  },
  {
    id: "wsopc-tunica",
    name: "WSOP Circuit 튜니카",
    nameEn: "WSOP Circuit Tunica",
    type: "international",
    startDate: "2026-08-20",
    endDate: "2026-08-31",
    location: "미국 MS (Horseshoe Tunica)",
    city: "Robinsonville",
    country: "US",
    venue: "Horseshoe Tunica",
    buyin: "공식 미기재",
    emoji: "🇺🇸",
    color: "bg-blue-500/15 text-blue-400 border-blue-500/30",
    sourceUrl: "https://www.wsop.com/schedule/",
    sourceTier: "A",
    verifiedAt: "2026-08-31",
  },
  {
    id: "wsopc-tulsa",
    name: "WSOP Circuit 털사",
    nameEn: "WSOP Circuit Tulsa",
    type: "international",
    startDate: "2026-08-26",
    endDate: "2026-09-07",
    location: "미국 OK (Hard Rock Tulsa)",
    city: "Catoosa",
    country: "US",
    venue: "Hard Rock Tulsa",
    buyin: "공식 미기재",
    emoji: "🇺🇸",
    color: "bg-blue-500/15 text-blue-400 border-blue-500/30",
    sourceUrl: "https://www.wsop.com/schedule/",
    sourceTier: "A",
    verifiedAt: "2026-08-31",
  },
  {
    id: "wsopc-virginia",
    name: "WSOP Circuit 버지니아",
    nameEn: "WSOP Circuit Virginia",
    type: "international",
    startDate: "2026-09-03",
    endDate: "2026-09-14",
    location: "미국 VA (Caesars Virginia)",
    city: "Danville",
    country: "US",
    venue: "Caesars Virginia",
    buyin: "공식 미기재",
    emoji: "🇺🇸",
    color: "bg-blue-500/15 text-blue-400 border-blue-500/30",
    sourceUrl: "https://www.wsop.com/schedule/",
    sourceTier: "A",
    verifiedAt: "2026-08-31",
  },
  {
    id: "wsopc-austin",
    name: "WSOP Circuit 오스틴",
    nameEn: "WSOP Circuit Austin",
    type: "international",
    startDate: "2026-09-10",
    endDate: "2026-09-21",
    location: "미국 TX (Texas Card House)",
    city: "Austin",
    country: "US",
    venue: "Texas Card House",
    buyin: "공식 미기재",
    emoji: "🇺🇸",
    color: "bg-blue-500/15 text-blue-400 border-blue-500/30",
    sourceUrl: "https://www.wsop.com/schedule/",
    sourceTier: "A",
    verifiedAt: "2026-08-31",
  },
  {
    id: "wsopc-council-bluffs",
    name: "WSOP Circuit 카운슬블러프스",
    nameEn: "WSOP Circuit Council Bluffs",
    type: "international",
    startDate: "2026-09-17",
    endDate: "2026-09-28",
    location: "미국 IA (Horseshoe Council Bluffs)",
    city: "Council Bluffs",
    country: "US",
    venue: "Horseshoe Council Bluffs",
    buyin: "공식 미기재",
    emoji: "🇺🇸",
    color: "bg-blue-500/15 text-blue-400 border-blue-500/30",
    sourceUrl: "https://www.wsop.com/schedule/",
    sourceTier: "A",
    verifiedAt: "2026-08-31",
  },
  {
    id: "wsopc-thunder-valley",
    name: "WSOP Circuit 썬더밸리",
    nameEn: "WSOP Circuit Thunder Valley",
    type: "international",
    startDate: "2026-09-24",
    endDate: "2026-10-05",
    location: "미국 CA (Thunder Valley Casino Resort)",
    city: "Lincoln",
    country: "US",
    venue: "Thunder Valley Casino Resort",
    buyin: "공식 미기재",
    emoji: "🇺🇸",
    color: "bg-blue-500/15 text-blue-400 border-blue-500/30",
    sourceUrl: "https://www.wsop.com/schedule/",
    sourceTier: "A",
    verifiedAt: "2026-08-31",
  },
  {
    id: "wsopc-pompano",
    name: "WSOP Circuit 폼파노비치",
    nameEn: "WSOP Circuit Pompano Beach",
    type: "international",
    startDate: "2026-10-01",
    endDate: "2026-10-12",
    location: "미국 FL (Harrah's Pompano Beach)",
    city: "Pompano Beach",
    country: "US",
    venue: "Harrah's Pompano Beach",
    buyin: "공식 미기재",
    emoji: "🇺🇸",
    color: "bg-blue-500/15 text-blue-400 border-blue-500/30",
    sourceUrl: "https://www.wsop.com/schedule/",
    sourceTier: "A",
    verifiedAt: "2026-08-31",
  },
  {
    id: "wsopc-turning-stone",
    name: "WSOP Circuit 터닝스톤",
    nameEn: "WSOP Circuit Turning Stone",
    type: "international",
    startDate: "2026-10-15",
    endDate: "2026-10-26",
    location: "미국 NY (Turning Stone Resort Casino)",
    city: "Verona",
    country: "US",
    venue: "Turning Stone Resort Casino",
    buyin: "공식 미기재",
    emoji: "🇺🇸",
    color: "bg-blue-500/15 text-blue-400 border-blue-500/30",
    sourceUrl: "https://www.wsop.com/schedule/",
    sourceTier: "A",
    verifiedAt: "2026-08-31",
  },
  {
    id: "wsopc-lake-tahoe",
    name: "WSOP Circuit 레이크타호",
    nameEn: "WSOP Circuit Lake Tahoe",
    type: "international",
    startDate: "2026-10-22",
    endDate: "2026-11-02",
    location: "미국 NV (Caesars Republic Lake Tahoe)",
    city: "Stateline",
    country: "US",
    venue: "Caesars Republic Lake Tahoe",
    buyin: "공식 미기재",
    emoji: "🇺🇸",
    color: "bg-blue-500/15 text-blue-400 border-blue-500/30",
    sourceUrl: "https://www.wsop.com/schedule/",
    sourceTier: "A",
    verifiedAt: "2026-08-31",
  },
  {
    id: "wsopc-southern-indiana",
    name: "WSOP Circuit 서던인디애나",
    nameEn: "WSOP Circuit Southern Indiana",
    type: "international",
    startDate: "2026-10-22",
    endDate: "2026-11-02",
    location: "미국 IN (Caesars Southern Indiana)",
    city: "Elizabeth",
    country: "US",
    venue: "Caesars Southern Indiana",
    buyin: "공식 미기재",
    emoji: "🇺🇸",
    color: "bg-blue-500/15 text-blue-400 border-blue-500/30",
    sourceUrl: "https://www.wsop.com/schedule/",
    sourceTier: "A",
    verifiedAt: "2026-08-31",
  },
  {
    id: "wsopc-choctaw",
    name: "WSOP Circuit 초크토",
    nameEn: "WSOP Circuit Choctaw Durant",
    type: "international",
    startDate: "2026-10-28",
    endDate: "2026-11-09",
    location: "미국 OK (Choctaw Casino Resort)",
    city: "Durant",
    country: "US",
    venue: "Choctaw Casino Resort",
    buyin: "공식 미기재",
    emoji: "🇺🇸",
    color: "bg-blue-500/15 text-blue-400 border-blue-500/30",
    sourceUrl: "https://www.wsop.com/schedule/",
    sourceTier: "A",
    verifiedAt: "2026-08-31",
  },
  {
    id: "wsopc-toledo",
    name: "WSOP Circuit 톨레도",
    nameEn: "WSOP Circuit Toledo",
    type: "international",
    startDate: "2026-10-29",
    endDate: "2026-11-09",
    location: "미국 OH (The Reserve Poker Club)",
    city: "Toledo",
    country: "US",
    venue: "The Reserve Poker Club",
    buyin: "공식 미기재",
    emoji: "🇺🇸",
    color: "bg-blue-500/15 text-blue-400 border-blue-500/30",
    sourceUrl: "https://www.wsop.com/schedule/",
    sourceTier: "A",
    verifiedAt: "2026-08-31",
  },
  {
    id: "wsopc-talking-stick",
    name: "WSOP Circuit 토킹스틱",
    nameEn: "WSOP Circuit Talking Stick",
    type: "international",
    startDate: "2026-11-05",
    endDate: "2026-11-16",
    location: "미국 AZ (Talking Stick Resort)",
    city: "Scottsdale",
    country: "US",
    venue: "Talking Stick Resort",
    buyin: "공식 미기재",
    emoji: "🇺🇸",
    color: "bg-blue-500/15 text-blue-400 border-blue-500/30",
    sourceUrl: "https://www.wsop.com/schedule/",
    sourceTier: "A",
    verifiedAt: "2026-08-31",
  },
  {
    id: "wsopc-grand-victoria",
    name: "WSOP Circuit 그랜드빅토리아",
    nameEn: "WSOP Circuit Grand Victoria",
    type: "international",
    startDate: "2026-11-05",
    endDate: "2026-11-16",
    location: "미국 IL (Grand Victoria Casino)",
    city: "Elgin",
    country: "US",
    venue: "Grand Victoria Casino",
    buyin: "공식 미기재",
    emoji: "🇺🇸",
    color: "bg-blue-500/15 text-blue-400 border-blue-500/30",
    sourceUrl: "https://www.wsop.com/schedule/",
    sourceTier: "A",
    verifiedAt: "2026-08-31",
  },
  {
    id: "wsopc-new-orleans",
    name: "WSOP Circuit 뉴올리언스",
    nameEn: "WSOP Circuit New Orleans",
    type: "international",
    startDate: "2026-11-12",
    endDate: "2026-11-23",
    location: "미국 LA (Caesars New Orleans)",
    city: "New Orleans",
    country: "US",
    venue: "Caesars New Orleans",
    buyin: "공식 미기재",
    emoji: "🇺🇸",
    color: "bg-blue-500/15 text-blue-400 border-blue-500/30",
    sourceUrl: "https://www.wsop.com/schedule/",
    sourceTier: "A",
    verifiedAt: "2026-08-31",
  },
  {
    id: "wsopc-cherokee-nov",
    name: "WSOP Circuit 체로키 (11월)",
    nameEn: "WSOP Circuit Cherokee (November)",
    type: "international",
    startDate: "2026-11-26",
    endDate: "2026-12-07",
    location: "미국 NC (Harrah's Cherokee)",
    city: "Cherokee",
    country: "US",
    venue: "Harrah's Cherokee",
    buyin: "공식 미기재",
    emoji: "🇺🇸",
    color: "bg-blue-500/15 text-blue-400 border-blue-500/30",
    sourceUrl: "https://www.wsop.com/schedule/",
    sourceTier: "A",
    verifiedAt: "2026-08-31",
  },

  {
    id: "wpt-world-championship",
    name: "WPT 월드 챔피언십",
    nameEn: "WPT World Championship",
    type: "international",
    // ★ 2026년 날짜는 공식 미발표. (12/2~12/22는 2025년 날짜이므로 쓰지 않는다)
    startDate: null,
    endDate: null,
    dateLabelOverride: "2026.12 예정 (날짜 미발표)",
    location: "미국 라스베이거스 (Wynn)",
    city: "Las Vegas",
    country: "US",
    venue: "Wynn Las Vegas",
    buyin: "미발표",
    emoji: "🌎",
    color: "bg-blue-500/15 text-blue-400 border-blue-500/30",
    note: "2026년 일정 미발표 — 베뉴(Wynn) 공식 포커 페이지에도 WPT 언급이 없다",
    // ⚠️ 링크할 정본이 없다. worldpokertour.com은 Cloudflare 403이고,
    //    Wynn 공식 포커 페이지에는 WPT 관련 내용이 전혀 없어 링크하면 독자를 오도한다.
    sourceUrl: null,
    sourceTier: null,
    verifiedAt: "2026-08-31",
  },

  /* ════════════════════════════════════════════════════════════
     DACH (독일·오스트리아·스위스) — 2026-08-10 신설.

     ★왜 지금 넣나: `/de/tournaments`를 열었는데 보드에 DE/AT/CH 개최분이
       0건이었다. 독일어 검색 수요의 핵심은 지역·일정이다
       (poker turnier münchen 590/LDA4 · nrw 320/4 · in der nähe 140/9 —
        docs/keyword-bank/de-core-volumes.md 시드⑫).
     ★전 값은 주최사 공식 페이지 원문에서 직접 추출했다. 열거·개수는
       DOM 스크레이프/PDF 파싱으로 «직접 셌다»(§12-B). 근거·축어·미확인 목록은
       **docs/dach-tournaments-2026.md**에 있다 — 수정 전 반드시 그 파일을 볼 것.
     🔴 **독일 안에는 큰 페스티벌이 없다.** 「독일 브랜드」 대회는 전부 체코
       King's에서 열린다(country: "CZ"). Spielbank Berlin Summer Cup은 7월에
       끝났고 Schenefeld·Hamburg는 다일간 시리즈가 아예 없다(주간 상시뿐).
     🔴 **germanpokertours.de를 출처로 쓰지 마라** — 주최사가 아니라 여행 패키지
       사업자이고, 거기 날짜는 «여행 기간»이라 대회 기간과 다르다.
     ════════════════════════════════════════════════════════════ */

  // ── King's Resort Rozvadov (CZ) — 독일 브랜드 5종 ──
  {
    id: "kings-gpt-sep",
    name: "GPT 저먼 포커 투어",
    nameEn: "GPT German Poker Tour",
    type: "international",
    startDate: "2026-09-01",
    endDate: "2026-09-06",
    location: "체코 로즈바도프 (King's Resort)",
    city: "Rozvadov",
    country: "CZ",
    venue: "King's Resort Rozvadov",
    buyin: "€25~€190",
    emoji: "🇩🇪",
    color: "bg-amber-500/15 text-amber-400 border-amber-500/30",
    note: "메인 €140+€50 바운티 / €300,000 GTD · 22개 이벤트",
    sourceUrl: "https://kings-resort.com/poker",
    sourceTier: "A",
    verifiedAt: "2026-08-10",
    // ⚠ schemaDescription을 달지 않는다 — 한국어로 적으면 SCHEMA_DESC_<locale>에
    //    항목이 없는 언어에서 JSON-LD에 한글이 그대로 나간다(2026-08-10 실측: 61→144).
    //    6개 로케일 설명을 다 쓸 때 함께 넣을 것.
  },
  {
    id: "kings-km-epc",
    name: "킹스 밀리언 유러피언 포커 챔피언십",
    nameEn: "King's Million European Poker Championship",
    type: "international",
    startDate: "2026-09-16",
    endDate: "2026-10-06",
    location: "체코 로즈바도프 (King's Resort)",
    city: "Rozvadov",
    country: "CZ",
    venue: "King's Resort Rozvadov",
    buyin: "€40~€3,000",
    emoji: "👑",
    color: "bg-amber-500/15 text-amber-400 border-amber-500/30",
    // ⚠ 슈퍼 메인(€1,150)과 미니 메인(€250)은 별개 이벤트다. 혼동 주의.
    note: "슈퍼 메인 €1,150 / €5M GTD · 페스티벌 €10,000,000 GTD · 118개 이벤트",
    highlight: true,
    sourceUrl: "https://kings-resort.com/poker",
    sourceTier: "A",
    verifiedAt: "2026-08-10",
  },
  {
    id: "kings-gpd-oct",
    name: "저먼 포커 데이즈 미스터리 바운티",
    nameEn: "German Poker Days \"Mystery Bounty\"",
    type: "international",
    startDate: "2026-10-07",
    endDate: "2026-10-11",
    location: "체코 로즈바도프 (King's Resort)",
    city: "Rozvadov",
    country: "CZ",
    venue: "King's Resort Rozvadov",
    buyin: "€35~€199",
    emoji: "🇩🇪",
    color: "bg-amber-500/15 text-amber-400 border-amber-500/30",
    note: "메인 €124+€75 바운티 / €300,000 GTD · 18개 이벤트",
    sourceUrl: "https://kings-resort.com/poker",
    sourceTier: "A",
    verifiedAt: "2026-08-10",
  },
  {
    id: "kings-gpm-nov",
    name: "저먼 포커 마스터스 €1MILLION",
    nameEn: "German Poker Masters €1MILLION",
    type: "international",
    startDate: "2026-11-20",
    endDate: "2026-11-30",
    location: "체코 로즈바도프 (King's Resort)",
    city: "Rozvadov",
    country: "CZ",
    venue: "King's Resort Rozvadov",
    buyin: "€35~€600",
    emoji: "🇩🇪",
    color: "bg-amber-500/15 text-amber-400 border-amber-500/30",
    note: "메인 €285 / €1,000,000 GTD · 49개 이벤트",
    highlight: true,
    sourceUrl: "https://kings-resort.com/poker",
    sourceTier: "A",
    verifiedAt: "2026-08-10",
  },
  {
    id: "kings-gpd-dec",
    name: "저먼 포커 데이즈 (12월)",
    nameEn: "German Poker Days (December)",
    type: "international",
    startDate: "2026-12-02",
    endDate: "2026-12-06",
    location: "체코 로즈바도프 (King's Resort)",
    city: "Rozvadov",
    country: "CZ",
    venue: "King's Resort Rozvadov",
    buyin: "€35~€199",
    emoji: "🇩🇪",
    color: "bg-amber-500/15 text-amber-400 border-amber-500/30",
    // ⚠ 페스티벌 개런티 €400,000과 메인이벤트 개런티 €300,000은 다른 값이다.
    note: "메인 €199 / 메인 €300,000 GTD · 페스티벌 €400,000 GTD · 19개 이벤트",
    sourceUrl: "https://kings-resort.com/poker",
    sourceTier: "A",
    verifiedAt: "2026-08-10",
  },

  // ── CAPT (Casinos Austria Poker Tour) — 잔여 5개 스톱 ──
  {
    id: "capt-graz",
    name: "CAPT 그라츠",
    nameEn: "CAPT Graz",
    type: "international",
    startDate: "2026-09-22",
    endDate: "2026-09-27",
    location: "오스트리아 그라츠 (Casino Graz)",
    city: "Graz",
    country: "AT",
    venue: "Casino Graz",
    buyin: "€36~€550",
    emoji: "🇦🇹",
    color: "bg-rose-500/15 text-rose-400 border-rose-500/30",
    note: "메인 €500+50 · 10개 이벤트 (최저 €30+6 새틀라이트)",
    sourceUrl: "https://www.casinos.at/spiel/poker/capt",
    sourceTier: "A",
    verifiedAt: "2026-08-10",
  },
  {
    id: "capt-seefeld-oct",
    name: "CAPT 제펠트 (10월)",
    nameEn: "CAPT Seefeld (October)",
    type: "international",
    startDate: "2026-10-07",
    endDate: "2026-10-11",
    location: "오스트리아 제펠트 (Casino Seefeld)",
    city: "Seefeld",
    country: "AT",
    venue: "Casino Seefeld",
    buyin: "€1,100",
    emoji: "🇦🇹",
    color: "bg-rose-500/15 text-rose-400 border-rose-500/30",
    // ⚠ 2차 출처가 "1.–11. Oktober"라 적었으나 공식은 7.-11.10.이다(나흘 차이).
    note: "메인 €1,000+100",
    sourceUrl: "https://www.casinos.at/spiel/poker/capt",
    sourceTier: "A",
    verifiedAt: "2026-08-10",
  },
  {
    id: "capt-bregenz-oct",
    name: "CAPT 브레겐츠 (10월)",
    nameEn: "CAPT Bregenz (October)",
    type: "international",
    startDate: "2026-10-15",
    endDate: "2026-10-25",
    location: "오스트리아 브레겐츠 (Casino Bregenz)",
    city: "Bregenz",
    country: "AT",
    venue: "Casino Bregenz",
    buyin: "€1,100",
    emoji: "🇦🇹",
    color: "bg-rose-500/15 text-rose-400 border-rose-500/30",
    // ⚠ 공식 «자체» 모순: 개요는 15.-25.10., 상세는 13.-25.10.이라 적는다.
    //    같은 상세가 "elf Tage(11일)"라 쓰는데 15→25가 정확히 11일이라 개요를 채택했다.
    //    13일은 새틀라이트 주간 포함으로 보인다. 단정 서술 금지.
    note: "메인 €1,100 · Bodensee Hold'em Trophy €30,000 GTD",
    sourceUrl: "https://www.casinos.at/spiel/poker/capt",
    sourceTier: "A",
    verifiedAt: "2026-08-10",
  },
  {
    id: "capt-innsbruck-nov",
    name: "CAPT 인스브루크 (11월)",
    nameEn: "CAPT Innsbruck (November)",
    type: "international",
    startDate: "2026-11-02",
    endDate: "2026-11-08",
    location: "오스트리아 인스브루크 (Casino Innsbruck)",
    city: "Innsbruck",
    country: "AT",
    venue: "Casino Innsbruck",
    buyin: "€1,100",
    emoji: "🇦🇹",
    color: "bg-rose-500/15 text-rose-400 border-rose-500/30",
    note: "메인 €1,000+100 — 인스브루크 사상 첫 €1,100 메인이벤트",
    sourceUrl: "https://www.casinos.at/spiel/poker/capt",
    sourceTier: "A",
    verifiedAt: "2026-08-10",
  },
  {
    id: "capt-million-baden",
    name: "CAPT 밀리언 바덴",
    nameEn: "CAPT Million Baden",
    type: "international",
    startDate: "2026-11-19",
    endDate: "2026-11-30",
    // ⚠ 오스트리아 Baden(빈 근교)이다. 스위스 Baden(CH-5400)과 다른 도시다.
    location: "오스트리아 바덴 (Casino Baden)",
    city: "Baden",
    country: "AT",
    venue: "Casino Baden",
    buyin: "€550",
    emoji: "🇦🇹",
    color: "bg-rose-500/15 text-rose-400 border-rose-500/30",
    note: "CAPT 시즌 피날레 · 메인 €500+50 / €1,000,000 GTD",
    highlight: true,
    sourceUrl: "https://www.casinos.at/spiel/poker/capt",
    sourceTier: "A",
    verifiedAt: "2026-08-10",
  },

  // ── 스위스 — Grand Casino Luzern (PCSM) ──
  // 🔴 Grand Casino Baden은 «넣지 않는다» — 2026-05-31을 마지막으로 포커를 중단했다
  //    (증축 공사, 재개 시점 미공개). 공식 축어는 docs/dach-tournaments-2026.md §3.
  {
    id: "pcso-40-luzern",
    name: "제40회 포커 서클 스위스 오픈",
    nameEn: "40th Poker Circle Swiss Open",
    type: "international",
    startDate: "2026-09-30",
    endDate: "2026-10-04",
    location: "스위스 루체른 (Grand Casino Luzern)",
    city: "Luzern",
    country: "CH",
    venue: "Grand Casino Luzern",
    // 월별 캘린더 PDF가 당월분만 발행돼 이 회차 바이인은 아직 없다. 추정하지 않는다.
    buyin: "공식 미기재",
    emoji: "🇨🇭",
    color: "bg-red-500/15 text-red-400 border-red-500/30",
    sourceUrl: "https://www.grandcasinoluzern.ch/en/play/poker-circle",
    sourceTier: "A",
    verifiedAt: "2026-08-10",
  },
  {
    id: "pcsm-autumn-luzern",
    name: "포커 서클 오텀 스페셜",
    nameEn: "Poker Circle Autumn Special",
    type: "international",
    startDate: "2026-11-26",
    endDate: "2026-11-29",
    location: "스위스 루체른 (Grand Casino Luzern)",
    city: "Luzern",
    country: "CH",
    venue: "Grand Casino Luzern",
    buyin: "공식 미기재",
    emoji: "🇨🇭",
    color: "bg-red-500/15 text-red-400 border-red-500/30",
    sourceUrl: "https://www.grandcasinoluzern.ch/en/play/poker-circle",
    sourceTier: "A",
    verifiedAt: "2026-08-10",
  },
  {
    id: "pcsm-championship-luzern",
    name: "PCSM 챔피언십 위크",
    nameEn: "PCSM Championship Week",
    type: "international",
    startDate: "2026-12-16",
    endDate: "2026-12-20",
    location: "스위스 루체른 (Grand Casino Luzern)",
    city: "Luzern",
    country: "CH",
    venue: "Grand Casino Luzern",
    buyin: "CHF 880",
    emoji: "🇨🇭",
    color: "bg-red-500/15 text-red-400 border-red-500/30",
    note: "PCSM 시즌 하이라이트 · 메인 CHF 800+80",
    sourceUrl: "https://www.grandcasinoluzern.ch/en/play/poker-circle",
    sourceTier: "A",
    verifiedAt: "2026-08-10",
  },
];

/**
 * 시작일 오름차순 정렬. 날짜 없는 상시 대회(HPL 등)는 맨 뒤.
 * 배열에 추가할 때 위치를 신경 쓸 필요가 없다.
 */
export const TOURNAMENTS: Tournament[] = [...RAW_TOURNAMENTS].sort((a, b) => {
  if (!a.startDate && !b.startDate) return 0;
  if (!a.startDate) return 1;
  if (!b.startDate) return -1;
  return a.startDate < b.startDate ? -1 : a.startDate > b.startDate ? 1 : 0;
});

/** id 중복은 React key 충돌을 일으키므로 빌드 시점에 잡는다 */
{
  const seen = new Set<string>();
  for (const t of RAW_TOURNAMENTS) {
    if (seen.has(t.id)) throw new Error(`[tournaments] id 중복: "${t.id}"`);
    seen.add(t.id);
  }
}

/* ────────────────────────────────────────────────────────────
   Event JSON-LD 자동 생성
   ★ 예전엔 3개를 손으로 적었으나 실제로는 렌더조차 되지 않았다.
     이제 데이터에서 자동 생성하고, 종료된 대회는 제외한다.
   ──────────────────────────────────────────────────────────── */

export function buildEventSchemas(todayISO: string) {
  return TOURNAMENTS.filter(
    (t) =>
      t.startDate &&
      t.endDate &&
      t.schemaDescription && // 설명이 준비된 것만
      computeStatus(t, todayISO) !== "ended", // 끝난 행사는 구조화 데이터에서 제외
  ).map((t) => ({
    "@context": "https://schema.org",
    "@type": "Event",
    name: t.name,
    description: t.schemaDescription,
    startDate: t.startDate,
    endDate: t.endDate,
    eventStatus: "https://schema.org/EventScheduled",
    eventAttendanceMode: "https://schema.org/OfflineEventAttendanceMode",
    location: {
      "@type": "Place",
      name: t.venue,
      address: {
        "@type": "PostalAddress",
        addressLocality: t.city,
        addressCountry: t.country,
      },
    },
    ...(t.organizer && {
      organizer: { "@type": "Organization", name: t.organizer.name, url: t.organizer.url },
    }),
    ...(t.sourceUrl && { url: t.sourceUrl }),
  }));
}
