import type { CalcDict } from "@/components/calculator/dict";

// hi 계산기 사전 — 데바나가리 산문 + 라틴 포커 용어(코퍼스 하우스 스타일 · docs/translation-terms-hi.md).
// 족보 이름은 라틴 정본(Royal Flush … High Card) · «패»는 हैंड · 2인칭 आप체.
// numberLocale: 코퍼스가 서양식 묶음(100,000 · 212,175)과 라틴 숫자를 쓰므로 en-US(hi-IN/en-IN은 lakh 묶음 1,00,000).
export const CALC_DICT_HI: CalcDict = {
  numberLocale: "en-US",

  seo: {
    title: "Poker Odds Calculator — outs, pot odds, हैंड रैंकिंग, SPR और ICM",
    description: "मुफ़्त Hold'em कैलकुलेटर: outs व draw odds, pot odds, हैंड रैंकिंग, starting hand, SPR, tournament M value, ICM और push/fold Nash चार्ट — 8 कैलकुलेटर एक जगह।",
    path: "/hi/calculator",
  },

  hero: {
    badges: ["पूरी तरह मुफ़्त", "तुरंत परिणाम"],
    h1: "Poker Odds Calculator",
    h1Sub: "Hold'em की हर गणना एक ही जगह",
    lead: "Outs · pot odds · हैंड रैंकिंग · starting hand की ताक़त · SPR · tournament M value · ICM · Nash push/fold चार्ट — टेबल पर जिस गणित की ज़रूरत है, वह तुरंत पाएँ।",
    chips: ["🎯 Outs", "💰 Pot Odds", "🃏 हैंड रैंकिंग", "📊 Starting Hand", "📐 SPR", "🏆 M Value", "📈 ICM", "⚡ Push/Fold"],
  },

  tabs: {
    outs: { label: "Outs", sub: "Draw के odds" },
    pot: { label: "Pot Odds", sub: "Call या fold" },
    hand: { label: "हैंड रैंकिंग", sub: "कार्ड चुनें" },
    starting: { label: "Starting Hand", sub: "Open की ताक़त" },
    spr: { label: "SPR", sub: "Stack/pot अनुपात" },
    m: { label: "Tournament M", sub: "M value" },
    icm: { label: "ICM", sub: "Prize equity" },
    pushfold: { label: "Push/Fold", sub: "Nash चार्ट" },
  },

  workspace: {
    chooseCalculator: "कैलकुलेटर चुनें",
    resetInputs: "इनपुट रीसेट करें",
    resetAria: "{label} रीसेट करें",
    resetMessage: "{label} के इनपुट रीसेट हो गए।",
  },

  cardPicker: {
    clearAll: "सब साफ़ करें",
  },

  outs: {
    drawType: "Draw का प्रकार",
    presets: [
      { label: "अपना इनपुट" },
      { label: "Nut flush draw", desc: "एक suit के 4 कार्ड → 5वाँ चाहिए" },
      { label: "Open-ended straight draw (OESD)", desc: "जैसे 5-6-7-8, 4 या 9 चाहिए" },
      { label: "Flush + gutshot combo", desc: "9 flush + 3 gutshot (दोहराव हटाकर)" },
      { label: "Gutshot straight", desc: "जैसे 5-6-8-9, सिर्फ़ 7 चाहिए" },
      { label: "दो overcards", desc: "बोर्ड पर न आए 2 ऊँचे rank × 3-3 कार्ड" },
      { label: "Two pair → full house", desc: "जैसे A-K-x बोर्ड पर A-K → 2 ace और 2 king बचे" },
      { label: "One pair → trips", desc: "उस rank के 2 कार्ड बचे हैं" },
      { label: "Flush + OESD (monster)", desc: "9 flush + 8 straight (2 दोहराव)" },
    ],
    outsSuffix: " ({n} outs)",
    street: "Street",
    afterFlopBtn: "🃏 Flop के बाद",
    afterTurnBtn: "🔄 Turn के बाद",
    outsCount: "Outs की संख्या: {v}",
    afterFlop: "Flop के बाद",
    afterTurn: "Turn के बाद",
    ruleOf4: "Rule of 4",
    ruleOf2: "Rule of 2",
    chanceFlop: "Flop के बाद पूरा होने की संभावना",
    chanceTurn: "Turn के बाद पूरा होने की संभावना",
    exact: " (सटीक)",
    ruleMental: "Rule of {n} (मन में हिसाब):",
    exactNote: "ऊपर का मान सटीक आँकड़ा है",
    verdict: { great: "बहुत अच्छा 🔥", good: "अच्छा ✅", fair: "ठीक-ठाक ⚠️", poor: "कमज़ोर ❌", veryPoor: "बहुत कमज़ोर 💀" },
  },

  pot: {
    potSize: "अभी pot का आकार",
    callAmount: "आपके call की रकम",
    potOddsCaption: "Pot odds (कम से कम ज़रूरी equity)",
    orHigher: "या इससे ज़्यादा हो तो call फ़ायदेमंद है",
    equityLabel: "आपके हैंड की equity: {v}",
    sliderGutshot: "Gutshot 8.7%",
    sliderFlush: "Flush 19%",
    impliedToggle: "Implied odds {toggle}",
    close: "बंद करें ▲",
    add: "जोड़ें ▼",
    extraWinnings: "हिट होने पर अपेक्षित अतिरिक्त जीत: {v}",
    none: "कुछ नहीं",
    impliedCaption: "Implied odds (अतिरिक्त जीत के साथ)",
    impliedNote: "{n} अतिरिक्त गिनकर कम से कम ज़रूरी equity",
    needImplied: "implied odds {n}%",
    needPot: "pot odds {n}%",
    verdict: {
      call: { title: "Call (फ़ायदेमंद)", body: "आपकी equity {eq}% > {need} → लंबे समय में फ़ायदा" },
      even: { title: "Break-even (EV 0)", body: "आपकी equity {eq}% = {need} → call से न फ़ायदा, न नुकसान। फ़ैसला pot odds से बाहर की बातों पर करें, जैसे position और विरोधी की आदतें" },
      fold: { title: "Fold की सलाह", body: "आपकी equity {eq}% < {need} → लंबे समय में नुकसान" },
    },
  },

  handEval: {
    pickerLabel: "कार्ड चुनें (5–7)",
    emptyTitle: "हैंड जाँचने के लिए 5 या ज़्यादा कार्ड चुनें",
    emptyHint: "7 कार्ड होने पर सबसे अच्छा 5-कार्ड संयोजन अपने आप मिल जाता है",
    bestFrom: "{n} कार्ड में से सबसे अच्छा हैंड",
    rankNames: [
      "High Card", "One Pair", "Two Pair", "Three of a Kind", "Straight",
      "Flush", "Full House", "Four of a Kind", "Straight Flush", "Royal Flush",
    ],
    resultNames: [
      "High Card 🃏", "One Pair 1️⃣", "Two Pair ✌️", "Three of a Kind 3️⃣", "Straight ➡️",
      "Flush 🌊", "Full House 🏠", "Four of a Kind 💎", "Straight Flush 🌟", "Royal Flush 👑",
    ],
    axis: ["High Card", "One Pair", "Flush", "Quads", "Royal"],
  },

  starting: {
    pickerLabel: "अपने 2 hole कार्ड चुनें",
    emptyPrompt: "अपने 2 hole कार्ड चुनें",
    unknownDesc: "बहुत कमज़ोर हैंड",
    unknownAction: "आम तौर पर fold",
    tierNames: ["🥇 Tier 1 — Premium", "🥈 Tier 2 — मज़बूत", "🥉 Tier 3 — खेलने लायक", "⚠️ Tier 4 — Marginal", "🚫 Tier 5 — कमज़ोर"],
    recommendedAction: "सुझाई गई कार्रवाई:",
    axis: ["Premium", "मज़बूत", "खेलने लायक", "Marginal", "कमज़ोर"],
    summaryTitle: "हैंड tier का सार",
    summary: [
      { hands: "AA KK QQ JJ 10-10 AKs AKo", action: "हमेशा raise" },
      { hands: "AQs AJs A10s KQs KJs 99 88 AQo", action: "ज़्यादातर positions से raise" },
      { hands: "AJo KQo K10s QJs J10s 10-9s 77 A9s", action: "Late position से raise" },
      { hands: "66–55 A8s–A2s KJo QJo suited connectors", action: "LP में चुनकर खेलें" },
      { hands: "44–22 कमज़ोर offsuit हैंड", action: "आम तौर पर fold" },
    ],
    hands: {
      AA: { desc: "सबसे अच्छा हैंड। हर स्पॉट में raise करें", action: "हमेशा raise/re-raise (3-bet)" },
      KK: { desc: "बस flop पर ace से सावधान रहें", action: "हमेशा raise/re-raise" },
      QQ: { desc: "JJ से मज़बूत, पर ज़्यादा भाव न दें", action: "हमेशा raise; deep होने पर सावधान" },
      JJ: { desc: "Flop पर overcards से सावधान रहें", action: "किसी भी position से raise" },
      "1010": { desc: "Flop पर overcards आने से कीमत घटती है", action: "Mid/late से raise, EP में call पर विचार" },
      AKs: { desc: "सबसे अच्छा drawing हैंड। Pot बड़ा करें", action: "हमेशा raise/re-raise" },
      AKo: { desc: "AKs से कमज़ोर, पर फिर भी premium", action: "हमेशा raise; re-raise पर call कर सकते हैं" },
      AQs: { desc: "मज़बूत हैंड; position में ज़्यादा कीमती", action: "ज़्यादातर positions से raise" },
      AJs: { desc: "BTN/CO पर बढ़िया, UTG से कमज़ोर", action: "Mid/late से raise, EP में call पर विचार" },
      A10s: { desc: "सबसे अच्छे suited aces में से एक", action: "LP में raise, EP में call" },
      KQs: { desc: "ऊँचे flush + straight draw की संभावना", action: "ज़्यादातर positions से raise" },
      KJs: { desc: "मज़बूत drawing हैंड", action: "LP में raise, EP में call" },
      "99": { desc: "मध्यम pair, overcard वाले flop से सावधान", action: "ज़्यादातर positions से raise; deep में सावधान" },
      "88": { desc: "अच्छी set संभावना वाला pocket pair", action: "LP में raise, EP में call पर विचार" },
      AQo: { desc: "कमज़ोर offsuit; position मायने रखता है", action: "Mid/late position से raise" },
      AJo: { desc: "EP में कमज़ोर, LP में मज़बूत", action: "CO/BTN से raise, EP में सावधान" },
      KQo: { desc: "सबसे अच्छा offsuit connector", action: "LP में raise, EP में call/fold" },
      K10s: { desc: "Suited king, LP में मज़बूत", action: "LP में raise, EP में fold" },
      QJs: { desc: "मज़बूत two-way draws", action: "LP में raise, deep होने पर ज़्यादा कीमती" },
      J10s: { desc: "सबसे अच्छे suited connectors में से एक", action: "LP में raise, EP में pot odds पर call" },
      "109s": { desc: "मज़बूत suited connector", action: "LP में raise/call" },
      "77": { desc: "Set-mining हैंड, overcards से सावधान", action: "LP में raise, EP में call" },
      A9s: { desc: "Flush की संभावना वाला suited ace", action: "LP में raise" },
      "66": { desc: "Set-mining; pot odds चाहिए", action: "LP में call/raise, multiway में सबसे अच्छा" },
      "55": { desc: "Set के बिना कम कीमत", action: "LP में call, single-raised pots" },
      A8s: { desc: "मध्यम suited ace", action: "LP में खेलें, EP में fold" },
      A7s: { desc: "मध्यम suited ace", action: "सिर्फ़ LP में खेलें" },
      A6s: { desc: "मध्यम suited ace", action: "सिर्फ़ LP में खेलें" },
      A5s: { desc: "Wheel + ace-blocker की कीमत; पसंदीदा 3-bet bluff", action: "सिर्फ़ LP; implied odds मायने रखते हैं" },
      A4s: { desc: "Wheel draw वाला suited ace", action: "सिर्फ़ LP" },
      A3s: { desc: "Suited aces में सबसे नीचे", action: "सिर्फ़ BTN/SB" },
      A2s: { desc: "Wheel + nut flush, पर कमज़ोर", action: "सिर्फ़ BTN" },
      KJo: { desc: "Domination का ख़तरा; सिर्फ़ LP", action: "CO/BTN से raise, re-raise पर fold" },
      QJo: { desc: "मध्यम connectivity; position चाहिए", action: "सिर्फ़ LP" },
      "98s": { desc: "मज़बूत suited connector", action: "LP में call/raise" },
      "87s": { desc: "अच्छा suited connector", action: "LP में call" },
      "76s": { desc: "Suited connector", action: "LP में pot odds पर call" },
      "44": { desc: "Set के बिना लगभग कोई कीमत नहीं", action: "सिर्फ़ कम pot odds पर call" },
      "33": { desc: "Set-mine करना होगा; speculative", action: "Multiway pots, सिर्फ़ सस्ते call" },
      "22": { desc: "सबसे छोटा pocket pair", action: "Multiway pots, सिर्फ़ सस्ते call" },
      K10o: { desc: "K-10 offsuit, कमज़ोर", action: "कभी-कभी BTN से" },
      Q10o: { desc: "कम connectivity वाला offsuit", action: "सिर्फ़ BTN" },
      J10o: { desc: "ठीक-ठाक offsuit, पर असुरक्षित", action: "कभी-कभी BTN से" },
      Q10s: { desc: "मज़बूत suited broadway, position में अच्छा खेलता है", action: "LP में raise, EP में pot odds पर call" },
      A10o: { desc: "Marginal offsuit ace, domination का ख़तरा", action: "सिर्फ़ LP" },
      "65s": { desc: "Suited connector; multiway/implied odds चाहिए", action: "LP में call" },
      "54s": { desc: "छोटा suited connector; speculative", action: "LP में call, सस्ते multiway pots" },
    },
  },

  spr: {
    effectiveStack: "Effective stack (आपका)",
    potSize: "अभी pot का आकार",
    caption: "SPR (Stack-to-Pot Ratio)",
    stackDivPot: "stack ÷ pot",
    zones: {
      low: {
        label: "कम SPR (committed)",
        desc: "Pot का बड़ा हिस्सा पहले ही अंदर है। Top pair top kicker या उससे बेहतर हैंड हो तो all-in पर विचार करें — यहाँ fold करना गलती हो सकती है।",
        actions: [["TPTK+", "All-in पर विचार करें"], ["Draws", "Pot odds ज़रूरी हैं"], ["कमज़ोर हैंड", "सावधानी से fold"]],
      },
      mid: {
        label: "मध्यम SPR (लचीला)",
        desc: "यह two pair या उससे बेहतर जैसे मज़बूत हैंड खेलने का ज़ोन है। अपना stack बचाना अहम हो जाता है।",
        actions: [["Two pair+", "Value bet"], ["One pair", "परिस्थिति देखकर खेलें"], ["Draws", "जोखिम और इनाम तौलें"]],
      },
      high: {
        label: "ऊँचा SPR (गहरा होता हुआ)",
        desc: "Stacks गहरे हो रहे हैं। Draws और मज़बूत बने हुए हैंड की तुलनात्मक कीमत बढ़ती है।",
        actions: [["Set+", "मज़बूती से खेलें"], ["Draws", "Implied odds बढ़ते हैं"], ["One pair/TPTK", "सावधानी से आगे बढ़ें"]],
      },
      deep: {
        label: "बहुत ऊँचा SPR (deep)",
        desc: "यह deep-stack खेल है। Position, draw की संभावना और विरोधी की range पढ़ना बहुत मायने रखता है।",
        actions: [["Nut हैंड", "बड़ा bet कर सकते हैं"], ["Draws", "बहुत ऊँचे implied odds"], ["कमज़ोर बने हुए हैंड", "सावधान, bluff का शिकार हो सकते हैं"]],
      },
    },
    legend: ["Committed", "लचीला", "गहरा होता हुआ", "Deep"],
  },

  m: {
    inputs: { stack: "आपका stack", bb: "Big blind", sb: "Small blind", ante: "Ante" },
    players: "टेबल पर खिलाड़ी: {v}",
    headsUp: "2 (heads-up)",
    orbitCaption: "Orbit की लागत (एक चक्कर के blinds)",
    orbitFormula: "BB {bb} + SB {sb} + ante {ante}×{players}",
    mCaption: "M value (Harrington का M)",
    zones: {
      dead: { name: "💀 Dead zone", desc: "आपको तुरंत all-in जाना होगा। बेहतर हैंड का इंतज़ार करने की गुंजाइश नहीं है — जो सबसे अच्छा हैंड मिले, उसी से shove करें।", action: "अभी all-in" },
      red: { name: "🔴 Red zone", desc: "आपको जल्द double up करना होगा। Push/fold रणनीति अपनाएँ — अच्छे हैंड से shove करें, बाक़ी fold करें।", action: "Push/fold" },
      orange: { name: "🟠 Orange zone", desc: "आपका stack घट रहा है। Range को सिर्फ़ मज़बूत हैंड तक सीमित रखें और open-shove के मौक़े देखें।", action: "Tight range" },
      yellow: { name: "🟡 Yellow zone", desc: "दबाव बढ़ रहा है। आपको सक्रिय होकर chips जुटाने होंगे — अच्छे स्पॉट मिलें तो आक्रामक खेलें।", action: "आक्रामक खेलें" },
      green: { name: "🟢 Green zone", desc: "आपके पास आरामदायक stack है। पूरी रणनीति का इस्तेमाल करें — position play और bluff से stack बढ़ाएँ।", action: "पूरी रणनीति" },
    },
  },

  icm: {
    introStrong: "ICM (Independent Chip Model)",
    introRest: " आपके tournament chips की असली नकद कीमत निकालने का तरीका है। Chip leader की ICM value भी उसके chip share से कम होती है, जबकि short stacks की कीमत उनके chips से ज़्यादा। Final table और bubble पर call/fold के फ़ैसलों में इसका इस्तेमाल करें।",
    numPlayers: "खिलाड़ियों की संख्या",
    paidPlaces: "Paid places (ITM)",
    stacksTitle: "खिलाड़ियों के chip stacks",
    total: "कुल {n}",
    decStack: "खिलाड़ी {n} का stack घटाएँ",
    stackInput: "खिलाड़ी {n} का chip stack",
    incStack: "खिलाड़ी {n} का stack बढ़ाएँ",
    prizesTitle: "Prizes",
    decPrize: "स्थान {n} का prize घटाएँ",
    prizeInput: "स्थान {n} का prize",
    incPrize: "स्थान {n} का prize बढ़ाएँ",
    currencyNote: "Prize की रकम किसी भी currency में भरें।",
    resultTitle: "ICM परिणाम",
    th: { player: "खिलाड़ी", chips: "Chips", chipPct: "Chip %", icmValue: "ICM value", icmPct: "ICM %", diff: "अंतर" },
    playerCell: "{medal} P{n}",
    diffPlus: "+अंतर",
    diffPlusNote: "ICM value chip share से ऊपर → short-stack बचाव ज़ोन, coin flip से बचें",
    diffMinus: "−अंतर",
    diffMinusNote: "ICM value chip share से नीचे → chip leader की आक्रामकता का फ़ायदा ज़्यादा",
    empty: "ICM परिणाम देखने के लिए stacks और prizes शून्य से ऊपर रखें।",
  },

  pushfold: {
    ante: "Ante",
    noAnte: "बिना ante",
    bbAnteOn: "BB ante ON",
    table: "टेबल",
    headsUp: "Heads-Up",
    sixMax: "6-max",
    nineMax: "9-max",
    scenario: "स्थिति",
    sbShove: "SB: shove या fold",
    bbCall: "BB: shove पर call",
    position: "Position {hint}",
    firstInHint: "(first-in — आपके सामने सब fold)",
    effectiveStack: "Effective stack: {v}",
    captionHuPush: "{stack}bb पर SB जिन हैंड से shove करता है",
    captionHuCall: "{stack}bb पर BB जिन हैंड से shove call करता है",
    captionMw: "{table}-max टेबल पर {pos} से first-in shove, {stack}bb",
    withAnte: " (ante के साथ)",
    combosSuffix: " / {total} combos",
    legendPush: "Push (all-in)",
    legendCall: "Call",
    legendFold: "Fold",
    note: {
      strong1: "तिरछी रेखा = pairs · ऊपर दाईं ओर = suited · नीचे बाईं ओर = offsuit",
      p1: "ग्रिड ",
      strong2: "rank के क्रम में है, ताक़त के नहीं",
      p2: ", इसलिए एक ही पंक्ति में highlight वाले और बिना highlight वाले खाने बारी-बारी दिखना सामान्य है — AQo, KQo और QQ पास-पास हैं, पर ताक़त के क्रम में नहीं। A5s का शामिल होना और A6s का बाहर रहना भी सही है: A5s से ",
      strong3: "wheel straight (A-2-3-4-5)",
      p3: " बनता है, जो कम kicker से ज़्यादा मायने रखता है।",
    },
    cellTitle: "{hand} — {action}",
    cell: { push: "push", call: "call", fold: "fold" },
    huNote: {
      strong: "Nash equilibrium, heads-up (SB बनाम BB)",
      p1: ": माना गया है कि SB या तो shove करता है या fold। Ante सेटिंग हर खिलाड़ी के लिए 0.125bb जोड़ती है (big-blind ante के बराबर, ≈12.5%)। Stack जितना छोटा, ranges उतनी चौड़ी — और ~3-4bb से नीचे BB सही तौर पर SB के shove से ",
      em: "ज़्यादा चौड़ी",
      p2: " range से call करता है, pot odds की वजह से।",
    },
    mwNote: {
      strong: "{table}-max first-in shove चार्ट",
      p1: ": आपके सामने सब fold कर चुके हैं और आप या तो shove करते हैं या fold। यह ",
      strong2: "शुद्ध chip-EV",
      p2: " वाला Nash-शैली का equilibrium है — पीछे बैठे खिलाड़ियों की calling ranges एक साथ solve होती हैं — इस मानक अनुमान के साथ कि call हुआ pot पहले caller के साथ heads-up तय होता है (कई callers वाले pot नहीं गिने जाते)। आपके पीछे जितने कम खिलाड़ी बचते हैं (UTG → BTN → SB), stack जितना छोटा होता है और ante ON (हर खिलाड़ी 0.125bb) होने पर ranges चौड़ी होती हैं। शुद्ध chip-EV होने से early position (UTG/MP) की 10bb ranges लोकप्रिय अंगूठे के नियमों से tight निकलती हैं (छोटे pairs fold) — असल खेल में ICM और विरोधियों के हिसाब से समायोजन करें।",
    },
    readMore: "Tournament में stack के दबाव और ICM की बुनियाद के लिए हमारी",
    shortStackLink: { slug: "holdem-tournament-vs-cash-game", text: "tournament बनाम cash game गाइड" },
    readMoreEnd: " पढ़ें।",
  },

  icmGuide: {
    bubble: {
      badge: "ICM गाइड",
      h2: "ICM कैलकुलेटर कैसे इस्तेमाल करें — 3 मिनट का bubble उदाहरण",
      intro: "मान लीजिए चार खिलाड़ी बचे हैं और तीन को prize मिलेगा (bubble)। Stacks 60,000 / 40,000 / 30,000 / 20,000 हैं और prizes $500 / $300 / $200। इन्हें कैलकुलेटर में भरें, और हर खिलाड़ी का chip share बनाम उसकी असली prize value (ICM) सामने आ जाती है:",
      th: { player: "खिलाड़ी", chipPct: "Chip %", icmPct: "ICM %", diff: "अंतर" },
      rows: [
        { player: "🥇 Chip leader", chip: "40.0%", icm: "33.3%", diff: "-6.7 अंक", up: false },
        { player: "🥈 दूसरा", chip: "26.7%", icm: "27.2%", diff: "+0.6 अंक", up: true },
        { player: "🥉 तीसरा", chip: "20.0%", icm: "22.9%", diff: "+2.9 अंक", up: true },
        { player: "चौथा (short stack)", chip: "13.3%", icm: "16.6%", diff: "+3.3 अंक", up: true },
      ],
      keyPoint: {
        text: "अहम बात: {b1}, यानी 6.7 अंक कम। जीतने पर भी सिर्फ़ पहले स्थान का prize मिलता है, इसलिए coin flip से leader को उतनी prize value नहीं मिलती जितनी chip count से लगती है। इसलिए bubble पर leader को {b2}, जबकि short stack (13.3% chips → 16.6% ICM) की कीमत उसके chips से ज़्यादा है और survival की इस कीमत को बचाने के लिए उसे {b3}।",
        b1: "chip leader की ICM value (33.3%) उसके chip share (40%) से कम है",
        b2: "short stacks पर दबाव बनाना चाहिए",
        b3: "गैर-ज़रूरी all-in call से बचना चाहिए",
      },
    },
    deal: {
      badge: "Prize का बँटवारा",
      h2: "ICM deal बनाम chip chop — prize pool का बँटवारा",
      intro: "अब तीन खिलाड़ी बचे हैं और deal पर बात हो रही है। Stacks 50% / 30% / 20% हैं और $1,500 का prize money बचा है — दोनों तरीक़े बहुत अलग बँटवारा देते हैं:",
      th: { player: "खिलाड़ी", chop: "Chip chop", icm: "ICM deal", diff: "अंतर" },
      rows: [
        { player: "🥇 Chip leader (50%)", chop: "$750", icm: "$618", diff: "-$132", up: false },
        { player: "🥈 दूसरा (30%)", chop: "$450", icm: "$485", diff: "+$35", up: true },
        { player: "🥉 Short stack (20%)", chop: "$300", icm: "$397", diff: "+$97", up: true },
      ],
      summary: {
        text: "Chip chop chip share के हिसाब से बाँटता है और {b1}; ICM deal हर स्थान पर finish करने की संभावनाओं को दर्शाता है और {b2}। ऊपर short stack को chip chop में $300 मिलते हैं, लेकिन ICM deal में लगभग $397 — {b3}। Short हों तो ICM deal माँगें; leader हों तो chip chop का प्रस्ताव रखें।",
        b1: "chip leader के पक्ष में जाता है",
        b2: "short stacks के लिए ज़्यादा fair है",
        b3: "$97 ज़्यादा",
      },
    },
  },

  guide: {
    badge: "कैलकुलेटर",
    h2: "8 Hold'em कैलकुलेटर कैसे इस्तेमाल करें",
    cards: [
      { title: "Outs कैलकुलेटर", body: "Flop या turn पर आपका draw पूरा होने की संभावना सटीक निकालता है। Rule of 4 और 2 का shortcut और सटीक आँकड़ा, दोनों एक साथ देखें।" },
      { title: "Pot odds और implied odds", body: "Call या fold का फ़ैसला गणित से लें। विरोधी deep हो तो ज़्यादा सटीक फ़ैसले के लिए implied odds जोड़ें।" },
      { title: "हैंड रैंकिंग जाँच", body: "कार्ड चुनकर हैंड की रैंक देखें। 7 कार्ड तक भरें, यह सबसे अच्छा 5-कार्ड संयोजन अपने आप ढूँढ लेता है।" },
      { title: "Starting hand की ताक़त", body: "अपने दो hole कार्ड चुनें और देखें कि 169 हैंड में यह कौन-सा है और position के हिसाब से सुझाई गई कार्रवाई क्या है।" },
      { title: "SPR (Stack-to-Pot Ratio)", body: "Stack और pot का अनुपात बताता है कि आपको कितना मज़बूत हैंड चाहिए। SPR जितना कम, मज़बूत हैंड से commit होना उतना सही।" },
      { title: "Tournament M value", body: "Harrington का M आपके tournament stack पर दबाव मापता है। Green/yellow/orange/red/dead ज़ोन के साथ आपकी रणनीति पूरी तरह बदल जाती है।" },
      { title: "ICM कैलकुलेटर", body: "Independent Chip Model tournament chips को असली prize money की कीमत में बदलता है — bubble और final table पर call/fold के फ़ैसलों और deal की बातचीत के लिए ज़रूरी।" },
      { title: "Nash push/fold चार्ट", body: "Nash equilibrium से निकाला गया 13×13 heads-up चार्ट: 1–25bb पर किन हैंड से open-shove करें और किनसे call। Tournament के आख़िरी चरण के लिए ज़रूरी।" },
    ],
  },

  faq: {
    badge: "FAQ",
    h2: "ICM कैलकुलेटर और Hold'em कैलकुलेटर — अक्सर पूछे जाने वाले सवाल",
    q: "Q. {q}",
  },

  related: {
    badge: "और गहराई में",
    h2: "गणित समझ आ जाए, तो ये गाइड पढ़ें",
    links: [
      { slug: "holdem-tournament-vs-cash-game", title: "Tournament या cash game", desc: "ICM, bubble और chip value का फ़र्क़" },
      { slug: "texas-holdem-rules-for-beginners", title: "टेक्सस होल्डम कैसे खेलें", desc: "नियम, chips और pot odds का पहला उदाहरण" },
      { slug: "3bet-pot-bet-sizing", title: "3-bet pot में bet sizing", desc: "Draws की कीमत और एक कार्ड के odds" },
      { slug: "holdem-hand-rankings", title: "पोकर हैंड रैंकिंग", desc: "सबसे मज़बूत से सबसे कमज़ोर तक, संभावनाओं के साथ" },
      { slug: "holdem-all-in-rules", title: "All-in नियम और side pot", desc: "Shove के बाद आप क्या जीत सकते हैं" },
      { slug: "holdem-blind-meaning", title: "Blinds क्या होते हैं", desc: "SB, BB, ante और orbit की लागत" },
    ],
  },
};
