// `/id/calculator` 사전 — 공용 계산기(`components/calculator/calculator-tool.tsx`)의 인니어 문자열.
//
// ★2026-09-17 신설. 정본 = `components/calculator/dict.ts`의 CALC_DICT_EN(키 전부 동일 · 자리표시자 동일).
// 용어 출처(우선순위 순): `docs/keyword-bank/id-posting-reference.md` §5·§5-A(코퍼스 실측 판정) →
//   `docs/translation-terms-id.md` → `lib/posts-id/*.ts` 실제 어법(outs 249 · pot odds 168 · equity 533 ·
//   ICM 189 · SPR 63 · push/fold 29 · short stack 92 · chip chop 12 · ICM deal 13 · 족보 영어 표기).
// 판단:
//   · 영어 차용어 유지 = outs · pot odds · implied odds · equity · ICM · SPR · push/fold · shove · draw ·
//     board · range · stack · 족보 10종(Royal Flush … High Card) — 코퍼스 다수파. 억지 번역이 결함.
//   · 홀카드 = «kartu tertutup»(94 vs hole card 26) · 스타팅핸드 = «starting hand»(77 vs tangan awal 24) ·
//     승률 = «peluang»(180 vs probabilitas 47) · 포지션 = «posisi awal/akhir»(positions 글의 EP/LP 병기 그대로).
//   · 숫자 = 인니식(천단위 `.` · 소수 `,` · `%` 앞 공백 없음) → numberLocale "id-ID" · 고정 문자열도 동일 규칙.
//   · M 존 이름 = short-stack 글의 «Hijau · Kuning · Oranye · Merah · Mati» 승계.
//   · 2인칭 = Anda 고정(코퍼스 3,340:0).
import type { CalcDict } from "@/components/calculator/dict";

export const CALC_DICT_ID: CalcDict = {
  numberLocale: "id-ID",

  seo: {
    title: "Kalkulator Odds Poker — Outs, Pot Odds, Urutan Kartu, SPR & ICM",
    description: "Kalkulator poker gratis: outs & peluang draw, pot odds, penilai hand, starting hand, SPR, nilai M turnamen, ICM, dan chart push/fold Nash — 8 alat dalam satu.",
    path: "/id/calculator",
  },

  hero: {
    badges: ["Alat gratis", "Hasil seketika"],
    h1: "Kalkulator Odds Poker",
    h1Sub: "Semua angka Hold'em di satu tempat",
    lead: "Outs · pot odds · penilai hand · kekuatan starting hand · SPR · nilai M turnamen · ICM · chart push/fold Nash — matematika yang Anda butuhkan di meja, seketika.",
    chips: ["🎯 Outs", "💰 Pot Odds", "🃏 Urutan Kartu", "📊 Starting Hand", "📐 SPR", "🏆 Nilai M", "📈 ICM", "⚡ Push/Fold"],
  },

  tabs: {
    outs: { label: "Outs", sub: "Peluang draw" },
    pot: { label: "Pot Odds", sub: "Call/fold" },
    hand: { label: "Urutan Kartu", sub: "Pilih kartu" },
    starting: { label: "Starting Hand", sub: "Kekuatan open" },
    spr: { label: "SPR", sub: "Rasio stack/pot" },
    m: { label: "M Turnamen", sub: "Nilai M" },
    icm: { label: "ICM", sub: "Equity hadiah" },
    pushfold: { label: "Push/Fold", sub: "Chart Nash" },
  },

  workspace: {
    chooseCalculator: "Pilih kalkulator",
    resetInputs: "Reset input",
    resetAria: "Reset {label}",
    resetMessage: "Input {label} sudah direset.",
  },

  cardPicker: {
    clearAll: "Hapus semua",
  },

  outs: {
    drawType: "Jenis draw",
    presets: [
      { label: "Input manual" },
      { label: "Nut flush draw", desc: "4 kartu satu jenis → butuh kartu ke-5" },
      { label: "Open-ended straight draw (OESD)", desc: "mis. 5-6-7-8, butuh 4 atau 9" },
      { label: "Kombo flush + gutshot", desc: "9 flush + 3 gutshot (tumpang tindih sudah dikurangi)" },
      { label: "Gutshot straight", desc: "mis. 5-6-8-9, hanya butuh 7" },
      { label: "Dua overcard", desc: "2 nilai tinggi yang tidak ada di board × 3 kartu tiap nilai" },
      { label: "Two pair → full house", desc: "mis. A-K di board A-K-x → tersisa 2 As + 2 King" },
      { label: "One pair → trips", desc: "tersisa 2 kartu dengan nilai itu" },
      { label: "Flush + OESD (monster)", desc: "9 flush + 8 straight (2 tumpang tindih)" },
    ],
    outsSuffix: " ({n} outs)",
    street: "Street",
    afterFlopBtn: "🃏 Setelah flop",
    afterTurnBtn: "🔄 Setelah turn",
    outsCount: "Jumlah outs: {v}",
    afterFlop: "Setelah flop",
    afterTurn: "Setelah turn",
    ruleOf4: "Aturan 4",
    ruleOf2: "Aturan 2",
    chanceFlop: "Peluang jadi setelah flop",
    chanceTurn: "Peluang jadi setelah turn",
    exact: " (persis)",
    ruleMental: "Aturan {n} (hitung cepat):",
    exactNote: "Angka di atas adalah nilai persisnya",
    verdict: { great: "Bagus sekali 🔥", good: "Bagus ✅", fair: "Lumayan ⚠️", poor: "Buruk ❌", veryPoor: "Sangat buruk 💀" },
  },

  pot: {
    potSize: "Ukuran pot saat ini",
    callAmount: "Jumlah call Anda",
    potOddsCaption: "Pot odds (equity minimum yang dibutuhkan)",
    orHigher: "atau lebih membuat call menguntungkan",
    equityLabel: "Equity hand Anda: {v}",
    sliderGutshot: "Gutshot 8,7%",
    sliderFlush: "Flush 19%",
    impliedToggle: "Implied odds {toggle}",
    close: "Tutup ▲",
    add: "Tambah ▼",
    extraWinnings: "Perkiraan kemenangan tambahan (jika kena): {v}",
    none: "Tidak ada",
    impliedCaption: "Implied odds (dengan kemenangan tambahan)",
    impliedNote: "Equity minimum yang dibutuhkan, dengan tambahan {n}",
    needImplied: "implied odds {n}%",
    needPot: "pot odds {n}%",
    verdict: {
      call: { title: "Call (menguntungkan)", body: "Equity Anda {eq}% > {need} → untung dalam jangka panjang" },
      even: { title: "Break-even (EV 0)", body: "Equity Anda {eq}% = {need} → call tidak untung dan tidak rugi. Putuskan dari faktor di luar pot odds, seperti posisi dan kecenderungan lawan" },
      fold: { title: "Disarankan fold", body: "Equity Anda {eq}% < {need} → rugi dalam jangka panjang" },
    },
  },

  handEval: {
    pickerLabel: "Pilih kartu (5–7)",
    emptyTitle: "Pilih 5 kartu atau lebih untuk menilai hand",
    emptyHint: "Dengan 7 kartu, kombinasi 5 kartu terbaik dicari otomatis",
    bestFrom: "Hand terbaik dari {n} kartu",
    rankNames: [
      "High Card", "One Pair", "Two Pair", "Three of a Kind", "Straight",
      "Flush", "Full House", "Four of a Kind", "Straight Flush", "Royal Flush",
    ],
    resultNames: [
      "High Card 🃏", "One Pair 1️⃣", "Two Pair ✌️", "Three of a Kind 3️⃣", "Straight ➡️",
      "Flush 🌊", "Full House 🏠", "Four of a Kind 💎", "Straight Flush 🌟", "Royal Flush 👑",
    ],
    axis: ["High Card", "One Pair", "Flush", "Quads", "Royal"],
  },

  starting: {
    pickerLabel: "Pilih 2 kartu tertutup Anda",
    emptyPrompt: "Pilih 2 kartu tertutup Anda",
    unknownDesc: "Hand sangat lemah",
    unknownAction: "Biasanya fold",
    tierNames: ["🥇 Tier 1 — Premium", "🥈 Tier 2 — Kuat", "🥉 Tier 3 — Bisa dimainkan", "⚠️ Tier 4 — Marginal", "🚫 Tier 5 — Lemah"],
    recommendedAction: "Aksi yang disarankan:",
    axis: ["Premium", "Kuat", "Bisa dimainkan", "Marginal", "Lemah"],
    summaryTitle: "Ringkasan tier hand",
    summary: [
      { hands: "AA KK QQ JJ 10-10 AKs AKo", action: "Selalu raise" },
      { hands: "AQs AJs A10s KQs KJs 99 88 AQo", action: "Raise dari hampir semua posisi" },
      { hands: "AJo KQo K10s QJs J10s 10-9s 77 A9s", action: "Raise dari posisi akhir" },
      { hands: "66–55 A8s–A2s KJo QJo suited connector", action: "Selektif di posisi akhir" },
      { hands: "44–22 hand offsuit lemah", action: "Biasanya fold" },
    ],
    hands: {
      AA: { desc: "Hand terbaik. Raise di setiap spot", action: "Selalu raise/re-raise (3-bet)" },
      KK: { desc: "Hanya waspadai As di flop", action: "Selalu raise/re-raise" },
      QQ: { desc: "Lebih kuat dari JJ, tapi jangan dinilai berlebihan", action: "Selalu raise; hati-hati saat deep" },
      JJ: { desc: "Waspadai overcard di flop", action: "Raise dari posisi mana pun" },
      "1010": { desc: "Nilainya turun saat overcard muncul di flop", action: "Raise di posisi tengah/akhir, pertimbangkan call di posisi awal" },
      AKs: { desc: "Drawing hand terbaik. Bangun pot", action: "Selalu raise/re-raise" },
      AKo: { desc: "Lebih lemah dari AKs tapi tetap premium", action: "Selalu raise; boleh call re-raise" },
      AQs: { desc: "Hand kuat; lebih bernilai saat in position", action: "Raise dari hampir semua posisi" },
      AJs: { desc: "Bagus di BTN/CO, lemah dari UTG", action: "Raise di posisi tengah/akhir, pertimbangkan call di posisi awal" },
      A10s: { desc: "Salah satu suited ace teratas", action: "Raise di posisi akhir, call di posisi awal" },
      KQs: { desc: "Potensi flush tinggi + straight draw", action: "Raise dari hampir semua posisi" },
      KJs: { desc: "Drawing hand yang kuat", action: "Raise di posisi akhir, call di posisi awal" },
      "99": { desc: "Pair sedang, waspadai flop dengan overcard", action: "Raise dari hampir semua posisi; hati-hati saat deep" },
      "88": { desc: "Pocket pair dengan potensi set yang bagus", action: "Raise di posisi akhir, pertimbangkan call di posisi awal" },
      AQo: { desc: "Versi offsuit lebih lemah; posisi menentukan", action: "Raise di posisi tengah/akhir" },
      AJo: { desc: "Lemah di posisi awal, kuat di posisi akhir", action: "Raise di CO/BTN, hati-hati di posisi awal" },
      KQo: { desc: "Connector offsuit teratas", action: "Raise di posisi akhir, call/fold di posisi awal" },
      K10s: { desc: "Suited king, kuat di posisi akhir", action: "Raise di posisi akhir, fold di posisi awal" },
      QJs: { desc: "Draw dua arah yang kuat", action: "Raise di posisi akhir, lebih bernilai saat deep" },
      J10s: { desc: "Salah satu suited connector terbaik", action: "Raise di posisi akhir, call di posisi awal sesuai pot odds" },
      "109s": { desc: "Suited connector yang kuat", action: "Raise/call di posisi akhir" },
      "77": { desc: "Hand set mining, waspadai overcard", action: "Raise di posisi akhir, call di posisi awal" },
      A9s: { desc: "Suited ace dengan potensi flush", action: "Raise di posisi akhir" },
      "66": { desc: "Set mining; butuh pot odds", action: "Call/raise di posisi akhir, paling bagus multiway" },
      "55": { desc: "Nilainya kecil tanpa set", action: "Call di posisi akhir, pot single-raised" },
      A8s: { desc: "Suited ace menengah", action: "Mainkan di posisi akhir, fold di posisi awal" },
      A7s: { desc: "Suited ace menengah", action: "Hanya di posisi akhir" },
      A6s: { desc: "Suited ace menengah", action: "Hanya di posisi akhir" },
      A5s: { desc: "Nilai wheel + blocker As; 3-bet bluff favorit", action: "Hanya di posisi akhir; implied odds menentukan" },
      A4s: { desc: "Suited ace dengan wheel draw", action: "Hanya di posisi akhir" },
      A3s: { desc: "Suited ace paling bawah", action: "Hanya BTN/SB" },
      A2s: { desc: "Wheel + nut flush, tapi lemah", action: "Hanya BTN" },
      KJo: { desc: "Risiko domination; hanya posisi akhir", action: "Raise di CO/BTN, fold ke re-raise" },
      QJo: { desc: "Konektivitas sedang; butuh posisi", action: "Hanya di posisi akhir" },
      "98s": { desc: "Suited connector yang kuat", action: "Call/raise di posisi akhir" },
      "87s": { desc: "Suited connector yang bagus", action: "Call di posisi akhir" },
      "76s": { desc: "Suited connector", action: "Call di posisi akhir sesuai pot odds" },
      "44": { desc: "Hampir tanpa nilai tanpa set", action: "Call hanya saat pot odds murah" },
      "33": { desc: "Harus set mining; spekulatif", action: "Pot multiway, call murah saja" },
      "22": { desc: "Pocket pair terendah", action: "Pot multiway, call murah saja" },
      K10o: { desc: "K-10 offsuit, lemah", action: "Sesekali dari BTN" },
      Q10o: { desc: "Offsuit dengan konektivitas rendah", action: "Hanya BTN" },
      J10o: { desc: "Offsuit yang lumayan tapi rentan", action: "Sesekali dari BTN" },
      Q10s: { desc: "Suited broadway yang kuat, enak dimainkan in position", action: "Raise di posisi akhir, call di posisi awal sesuai pot odds" },
      A10o: { desc: "Ace offsuit marginal, rawan domination", action: "Hanya di posisi akhir" },
      "65s": { desc: "Suited connector; butuh multiway/implied odds", action: "Call di posisi akhir" },
      "54s": { desc: "Suited connector rendah; spekulatif", action: "Call di posisi akhir, pot multiway yang murah" },
    },
  },

  spr: {
    effectiveStack: "Stack efektif (milik Anda)",
    potSize: "Ukuran pot saat ini",
    caption: "SPR (Stack-to-Pot Ratio)",
    stackDivPot: "stack ÷ pot",
    zones: {
      low: {
        label: "SPR rendah (committed)",
        desc: "Sebagian besar pot sudah masuk. Dengan top pair top kicker atau lebih baik, pertimbangkan all-in — fold di sini bisa jadi kesalahan.",
        actions: [["TPTK+", "Pertimbangkan all-in"], ["Draw", "Pot odds wajib dihitung"], ["Hand lemah", "Fold dengan hati-hati"]],
      },
      mid: {
        label: "SPR sedang (fleksibel)",
        desc: "Ini zona untuk memainkan hand kuat seperti two pair atau lebih baik. Melindungi stack Anda mulai penting.",
        actions: [["Two pair+", "Value bet"], ["One pair", "Mainkan sesuai feel"], ["Draw", "Timbang risiko vs imbalan"]],
      },
      high: {
        label: "SPR tinggi (mulai deep)",
        desc: "Stack mulai deep. Draw dan hand jadi yang kuat naik nilai relatifnya.",
        actions: [["Set+", "Mainkan kuat"], ["Draw", "Implied odds naik"], ["One pair/TPTK", "Lanjutkan dengan hati-hati"]],
      },
      deep: {
        label: "SPR sangat tinggi (deep)",
        desc: "Ini permainan deep stack. Posisi, potensi draw, dan membaca range lawan sangat menentukan.",
        actions: [["Hand nut", "Bisa bet besar"], ["Draw", "Implied odds sangat tinggi"], ["Hand jadi yang lemah", "Hati-hati, rentan terhadap bluff"]],
      },
    },
    legend: ["Committed", "Fleksibel", "Mulai deep", "Deep"],
  },

  m: {
    inputs: { stack: "Stack Anda", bb: "Big blind", sb: "Small blind", ante: "Ante" },
    players: "Pemain di meja: {v}",
    headsUp: "2 (heads-up)",
    orbitCaption: "Biaya orbit (blind per putaran)",
    orbitFormula: "BB {bb} + SB {sb} + ante {ante}×{players}",
    mCaption: "Nilai M (M Harrington)",
    zones: {
      dead: { name: "💀 Zona mati", desc: "Anda harus all-in sekarang juga. Tidak ada ruang untuk menunggu hand yang lebih baik — shove hand terbaik yang Anda dapat.", action: "All-in sekarang" },
      red: { name: "🔴 Zona merah", desc: "Anda harus segera double up. Pakai strategi push/fold — shove hand bagus Anda, fold sisanya.", action: "Push/fold" },
      orange: { name: "🟠 Zona oranye", desc: "Stack Anda menyusut. Ketatkan range ke hand kuat saja dan cari peluang open-shove.", action: "Range ketat" },
      yellow: { name: "🟡 Zona kuning", desc: "Tekanan mulai terasa. Anda harus aktif mengumpulkan chip — main agresif saat spot bagus muncul.", action: "Main agresif" },
      green: { name: "🟢 Zona hijau", desc: "Stack Anda nyaman. Pakai seluruh strategi — besarkan stack lewat permainan posisi dan bluff.", action: "Strategi penuh" },
    },
  },

  icm: {
    introStrong: "ICM (Independent Chip Model)",
    introRest: " adalah cara menghitung nilai uang sebenarnya dari chip turnamen Anda. Nilai ICM chip leader pun lebih rendah daripada persentase chipnya, sedangkan short stack bernilai lebih dari persentase chipnya. Pakai untuk keputusan call/fold di meja final dan di bubble.",
    numPlayers: "Jumlah pemain",
    paidPlaces: "Posisi yang dibayar",
    stacksTitle: "Stack chip pemain",
    total: "total {n}",
    decStack: "Kurangi stack pemain {n}",
    stackInput: "Stack chip pemain {n}",
    incStack: "Tambah stack pemain {n}",
    prizesTitle: "Hadiah",
    decPrize: "Kurangi hadiah posisi {n}",
    prizeInput: "Hadiah posisi {n}",
    incPrize: "Tambah hadiah posisi {n}",
    currencyNote: "Masukkan jumlah hadiah dalam satuan mata uang apa pun.",
    resultTitle: "Hasil ICM",
    th: { player: "Pemain", chips: "Chip", chipPct: "Chip %", icmValue: "Nilai ICM", icmPct: "ICM %", diff: "Selisih" },
    playerCell: "{medal} P{n}",
    diffPlus: "+selisih",
    diffPlusNote: "Nilai ICM di atas persentase chip → zona perlindungan short stack, hindari coin flip",
    diffMinus: "−selisih",
    diffMinusNote: "Nilai ICM di bawah persentase chip → agresi chip leader lebih menguntungkan",
    empty: "Isi stack dan hadiah di atas nol untuk melihat hasil ICM.",
  },

  pushfold: {
    ante: "Ante",
    noAnte: "Tanpa ante",
    bbAnteOn: "BB ante ON",
    table: "Meja",
    headsUp: "Heads-Up",
    sixMax: "6-max",
    nineMax: "9-max",
    scenario: "Skenario",
    sbShove: "SB: shove atau fold",
    bbCall: "BB: call shove",
    position: "Posisi {hint}",
    firstInHint: "(first-in — semua fold ke Anda)",
    effectiveStack: "Stack efektif: {v}",
    captionHuPush: "Hand yang di-shove SB pada {stack}bb",
    captionHuCall: "Hand yang dipakai BB untuk call shove pada {stack}bb",
    captionMw: "Shove first-in dari {pos} di meja {table}-max, {stack}bb",
    withAnte: " (dengan ante)",
    combosSuffix: " / {total} combo",
    legendPush: "Push (all-in)",
    legendCall: "Call",
    legendFold: "Fold",
    note: {
      strong1: "Diagonal = pair · kanan atas = suited · kiri bawah = offsuit",
      p1: "Grid diurutkan berdasarkan ",
      strong2: "nilai kartu, bukan kekuatan",
      p2: ", jadi sel yang disorot dan tidak disorot berselang-seling dalam satu baris itu wajar — AQo, KQo, dan QQ bersebelahan tetapi tidak berurutan menurut kekuatan. A5s masuk sementara A6s tidak juga benar: A5s membentuk",
      strong3: "wheel straight (A-2-3-4-5)",
      p3: ", yang lebih berharga daripada kicker yang sedikit lebih tinggi.",
    },
    cellTitle: "{hand} — {action}",
    cell: { push: "push", call: "call", fold: "fold" },
    huNote: {
      strong: "Keseimbangan Nash, heads-up (SB vs BB)",
      p1: ": SB diasumsikan hanya shove atau fold. Pengaturan ante menambah 0,125bb per pemain (setara big blind ante, ≈12,5%). Range melebar saat stack makin pendek — dan di bawah ~3-4bb BB justru benar call ",
      em: "lebih lebar",
      p2: " daripada range shove SB, karena pot odds.",
    },
    mwNote: {
      strong: "Chart shove first-in {table}-max",
      p1: ": semua pemain di depan sudah fold dan Anda hanya shove atau fold. Ini keseimbangan ala Nash ",
      strong2: "murni chip-EV",
      p2: " — range call para pemain di belakang dihitung serentak — dengan pendekatan standar bahwa pot yang di-call diselesaikan heads-up melawan pemanggil pertama (pot dengan lebih dari satu pemanggil diabaikan). Range melebar saat pemain di belakang Anda makin sedikit (UTG → BTN → SB), saat stack makin pendek, dan saat ante ON (0,125bb per pemain). Karena murni chip-EV, range 10bb dari posisi awal (UTG/MP) keluar lebih ketat daripada patokan umum (pair kecil fold) — sesuaikan dengan ICM dan lawan dalam praktik.",
    },
    readMore: "Untuk dasar-dasar short stack, baca",
    shortStackLink: { slug: "holdem-short-stack", text: "panduan strategi short stack" },
    readMoreEnd: " kami.",
  },

  icmGuide: {
    bubble: {
      badge: "Panduan ICM",
      h2: "Cara memakai kalkulator ICM — contoh bubble 3 menit",
      intro: "Misalkan tersisa empat pemain dan tiga yang dibayar (bubble). Stack-nya 60.000 / 40.000 / 30.000 / 20.000 dan hadiahnya $500 / $300 / $200. Masukkan ke kalkulator, dan Anda mendapat persentase chip tiap pemain dibandingkan nilai hadiah sebenarnya (ICM):",
      th: { player: "Pemain", chipPct: "Chip %", icmPct: "ICM %", diff: "Selisih" },
      rows: [
        { player: "🥇 Chip leader", chip: "40,0%", icm: "33,3%", diff: "-6,7 poin", up: false },
        { player: "🥈 Ke-2", chip: "26,7%", icm: "27,2%", diff: "+0,6 poin", up: true },
        { player: "🥉 Ke-3", chip: "20,0%", icm: "22,9%", diff: "+2,9 poin", up: true },
        { player: "Ke-4 (short stack)", chip: "13,3%", icm: "16,6%", diff: "+3,3 poin", up: true },
      ],
      keyPoint: {
        text: "Intinya: {b1} sebesar 6,7 poin. Karena menang hanya membayar hadiah juara 1, nilai hadiah yang didapat leader dari sebuah coin flip lebih kecil daripada yang ditunjukkan jumlah chipnya. Jadi di bubble, leader sebaiknya {b2}, sedangkan short stack (13,3% chip → 16,6% ICM) bernilai lebih dari chipnya dan sebaiknya {b3} untuk melindungi nilai bertahan itu.",
        b1: "nilai ICM chip leader (33,3%) lebih rendah daripada persentase chipnya (40%)",
        b2: "menekan short stack",
        b3: "menghindari call all-in yang tidak perlu",
      },
    },
    deal: {
      badge: "Pembagian hadiah",
      h2: "ICM deal vs chip chop — membagi prize pool",
      intro: "Sekarang tersisa tiga pemain dan mereka membahas deal. Dengan stack 50% / 30% / 20% dan sisa hadiah $1.500, kedua metode membagi dengan sangat berbeda:",
      th: { player: "Pemain", chop: "Chip chop", icm: "ICM deal", diff: "Selisih" },
      rows: [
        { player: "🥇 Chip leader (50%)", chop: "$750", icm: "$618", diff: "-$132", up: false },
        { player: "🥈 Ke-2 (30%)", chop: "$450", icm: "$485", diff: "+$35", up: true },
        { player: "🥉 Short stack (20%)", chop: "$300", icm: "$397", diff: "+$97", up: true },
      ],
      summary: {
        text: "Chip chop membagi berdasarkan persentase chip dan {b1}; ICM deal mencerminkan peluang finis tiap pemain dan {b2}. Di atas, short stack mendapat $300 dengan chip chop tetapi sekitar $397 dengan ICM deal — {b3}. Minta ICM deal saat Anda short; usulkan chip chop saat Anda chip leader.",
        b1: "menguntungkan chip leader",
        b2: "lebih adil bagi short stack",
        b3: "$97 lebih banyak",
      },
    },
  },

  guide: {
    badge: "Alat",
    h2: "Cara memakai 8 kalkulator Hold'em",
    cards: [
      { title: "Kalkulator outs", body: "Menghitung persis peluang draw Anda jadi di flop atau turn. Lihat jalan pintas Aturan 4 dan 2 serta angka persisnya sekaligus." },
      { title: "Pot odds & implied odds", body: "Putuskan call atau fold dengan matematika. Saat lawan deep, tambahkan implied odds untuk keputusan yang lebih akurat." },
      { title: "Penilai hand", body: "Pilih kartu untuk mengecek urutan kartunya. Masukkan hingga 7 kartu dan kombinasi 5 kartu terbaik ditemukan otomatis." },
      { title: "Kekuatan starting hand", body: "Pilih dua kartu tertutup Anda untuk melihat termasuk yang mana dari 169 hand dan aksi yang disarankan per posisi." },
      { title: "SPR (Stack-to-Pot Ratio)", body: "Rasio stack terhadap pot memberi tahu seberapa kuat hand yang Anda butuhkan. Makin rendah SPR, makin layak commit dengan hand kuat." },
      { title: "Nilai M turnamen", body: "M Harrington mengukur tekanan pada stack turnamen Anda. Strategi Anda berubah total di zona hijau/kuning/oranye/merah/mati." },
      { title: "Kalkulator ICM", body: "Independent Chip Model mengubah chip turnamen menjadi nilai hadiah sebenarnya — wajib untuk keputusan call/fold dan negosiasi deal di bubble dan meja final." },
      { title: "Chart push/fold Nash", body: "Chart heads-up 13×13 yang dihitung dari keseimbangan Nash: hand mana yang di-open-shove dan hand mana yang di-call pada 1–25bb. Wajib punya untuk fase akhir turnamen." },
    ],
  },

  faq: {
    badge: "FAQ",
    h2: "FAQ kalkulator ICM & kalkulator Hold'em",
    q: "Q. {q}",
  },

  related: {
    badge: "Lebih dalam",
    h2: "Panduan untuk dibaca setelah matematikanya klik",
    links: [
      { slug: "holdem-tournament", title: "Cara Kerja Turnamen Poker", desc: "ICM, bubble, dan permainan meja final" },
      { slug: "holdem-equity", title: "Equity Poker Dijelaskan", desc: "Persen menang, fold equity, dan realisasi" },
      { slug: "holdem-pot-odds", title: "Cara Menghitung Pot Odds", desc: "Ubah spot call/fold menjadi matematika" },
      { slug: "holdem-outs", title: "Cara Menghitung Outs", desc: "Outs per jenis draw dan aturan 4 dan 2" },
      { slug: "holdem-probability", title: "Bagan Peluang & Probabilitas Poker", desc: "Angka inti di balik setiap hand" },
      { slug: "holdem-starting-hands-chart", title: "Chart Starting Hands", desc: "Hand mana yang dimainkan per posisi" },
    ],
  },
};
