// MS (Bahasa Melayu · Malaysia) calculator dictionary — every user-visible string of the shared tool.
// Terminology follows docs/keyword-bank/ms-posting-reference.md (정본) and how lib/posts-ms/*.ts already
// phrase the same concepts: outs · pot odds · implied odds · equity · draw · stack efektif · cip · tournament ·
// tangan permulaan · kedudukan tangan · kad komuniti stay as the corpus writes them. Hand names are the
// English forms used by lib/posts-ms/holdem-hand-rankings.ts (Pair, Two Pair, Three of a Kind …).
// Numbers: English-style separators (1,326 · 2.5 · 35%) — never the Indonesian inversion.
import type { CalcDict } from "@/components/calculator/dict";

export const CALC_DICT_MS: CalcDict = {
  numberLocale: "ms-MY",

  seo: {
    title: "Kalkulator Odds Poker — Outs, Pot Odds & ICM",
    description:
      "Kalkulator poker Texas Hold'em percuma: outs & peluang draw, pot odds, penilai tangan, tangan permulaan, SPR, nilai M, ICM dan carta push/fold Nash — 8 alat.",
    path: "/ms/calculator",
  },

  hero: {
    badges: ["Alat percuma", "Masa nyata"],
    h1: "Kalkulator Odds Poker",
    h1Sub: "Semua nombor Hold'em di satu tempat",
    lead: "Outs · pot odds · penilai tangan · kekuatan tangan permulaan · SPR · nilai M tournament · ICM · carta push/fold Nash — dapatkan pengiraan yang anda perlukan di meja, serta-merta.",
    chips: ["🎯 Outs", "💰 Pot Odds", "🃏 Kedudukan Tangan", "📊 Tangan Permulaan", "📐 SPR", "🏆 Nilai M", "📈 ICM", "⚡ Push/Fold"],
  },

  tabs: {
    outs: { label: "Outs", sub: "Peluang draw" },
    pot: { label: "Pot Odds", sub: "Call/fold" },
    hand: { label: "Kedudukan Tangan", sub: "Pilih kad" },
    starting: { label: "Tangan Permulaan", sub: "Kekuatan open" },
    spr: { label: "SPR", sub: "Nisbah stack/pot" },
    m: { label: "M Tournament", sub: "Nilai M" },
    icm: { label: "ICM", sub: "Equity hadiah" },
    pushfold: { label: "Push/Fold", sub: "Carta Nash" },
  },

  workspace: {
    chooseCalculator: "Pilih kalkulator",
    resetInputs: "Set semula input",
    resetAria: "Set semula {label}",
    resetMessage: "Input {label} telah diset semula.",
  },

  cardPicker: {
    clearAll: "Kosongkan semua",
  },

  outs: {
    drawType: "Jenis draw",
    presets: [
      { label: "Input tersuai" },
      { label: "Nut flush draw", desc: "4 kad satu suit → perlukan kad ke-5" },
      { label: "Open-ended straight draw (OESD)", desc: "cth. 5-6-7-8, perlukan 4 atau 9" },
      { label: "Kombo flush + gutshot", desc: "9 flush + 3 gutshot (pertindihan dibuang)" },
      { label: "Gutshot straight", desc: "cth. 5-6-8-9, perlukan 7 sahaja" },
      { label: "Dua overcard", desc: "2 rank tinggi yang tiada di board × 3 setiap satu" },
      { label: "Two pair → full house", desc: "cth. A-K pada board A-K-x → tinggal 2 ace + 2 king" },
      { label: "Pair → trips", desc: "tinggal 2 kad rank itu" },
      { label: "Flush + OESD (monster)", desc: "9 flush + 8 straight (2 bertindih)" },
    ],
    outsSuffix: " ({n} outs)",
    street: "Street",
    afterFlopBtn: "🃏 Selepas flop",
    afterTurnBtn: "🔄 Selepas turn",
    outsCount: "Bilangan outs: {v}",
    afterFlop: "Selepas flop",
    afterTurn: "Selepas turn",
    ruleOf4: "Peraturan 4",
    ruleOf2: "Peraturan 2",
    chanceFlop: "Peluang melengkapkan draw selepas flop",
    chanceTurn: "Peluang melengkapkan draw selepas turn",
    exact: " (tepat)",
    ruleMental: "Peraturan {n} (kira dalam kepala):",
    exactNote: "Nilai di atas ialah angka yang tepat",
    verdict: { great: "Hebat 🔥", good: "Bagus ✅", fair: "Sederhana ⚠️", poor: "Lemah ❌", veryPoor: "Sangat lemah 💀" },
  },

  pot: {
    potSize: "Saiz pot semasa",
    callAmount: "Jumlah call anda",
    potOddsCaption: "Pot odds (equity minimum yang diperlukan)",
    orHigher: "atau lebih tinggi menjadikan call menguntungkan",
    equityLabel: "Equity tangan anda: {v}",
    sliderGutshot: "Gutshot 8.7%",
    sliderFlush: "Flush 19%",
    impliedToggle: "Implied odds {toggle}",
    close: "Tutup ▲",
    add: "Tambah ▼",
    extraWinnings: "Jangkaan kemenangan tambahan (jika draw lengkap): {v}",
    none: "Tiada",
    impliedCaption: "Implied odds (dengan kemenangan tambahan)",
    impliedNote: "Equity minimum yang diperlukan, dikira dengan {n} tambahan",
    needImplied: "implied odds {n}%",
    needPot: "pot odds {n}%",
    verdict: {
      call: { title: "Call (menguntungkan)", body: "Equity anda {eq}% > {need} → untung dalam jangka panjang" },
      even: { title: "Pulang modal (EV 0)", body: "Equity anda {eq}% = {need} → call tidak untung dan tidak rugi. Putuskan berdasarkan faktor di luar pot odds, seperti posisi dan gaya lawan" },
      fold: { title: "Fold disyorkan", body: "Equity anda {eq}% < {need} → rugi dalam jangka panjang" },
    },
  },

  handEval: {
    pickerLabel: "Pilih kad (5–7)",
    emptyTitle: "Pilih 5 kad atau lebih untuk menilai tangan",
    emptyHint: "Dengan 7 kad, gabungan 5 kad terbaik dicari secara automatik",
    bestFrom: "Tangan terbaik daripada {n} kad",
    rankNames: [
      "High Card", "Pair", "Two Pair", "Three of a Kind", "Straight",
      "Flush", "Full House", "Four of a Kind", "Straight Flush", "Royal Flush",
    ],
    resultNames: [
      "High Card 🃏", "Pair 1️⃣", "Two Pair ✌️", "Three of a Kind 3️⃣", "Straight ➡️",
      "Flush 🌊", "Full House 🏠", "Four of a Kind 💎", "Straight Flush 🌟", "Royal Flush 👑",
    ],
    axis: ["High Card", "Pair", "Flush", "Quads", "Royal"],
  },

  starting: {
    pickerLabel: "Pilih 2 kad tangan anda",
    emptyPrompt: "Pilih 2 kad tangan anda",
    unknownDesc: "Tangan sangat lemah",
    unknownAction: "Biasanya fold",
    tierNames: ["🥇 Tier 1 — Premium", "🥈 Tier 2 — Kuat", "🥉 Tier 3 — Boleh dimainkan", "⚠️ Tier 4 — Marginal", "🚫 Tier 5 — Lemah"],
    recommendedAction: "Tindakan disyorkan:",
    axis: ["Premium", "Kuat", "Boleh dimainkan", "Marginal", "Lemah"],
    summaryTitle: "Ringkasan tier tangan",
    summary: [
      { hands: "AA KK QQ JJ 10-10 AKs AKo", action: "Sentiasa raise" },
      { hands: "AQs AJs A10s KQs KJs 99 88 AQo", action: "Raise dari kebanyakan posisi" },
      { hands: "AJo KQo K10s QJs J10s 10-9s 77 A9s", action: "Raise dari posisi lewat" },
      { hands: "66–55 A8s–A2s KJo QJo suited connector", action: "Pilih-pilih di posisi lewat" },
      { hands: "44–22 tangan offsuit yang lemah", action: "Biasanya fold" },
    ],
    hands: {
      AA: { desc: "Tangan terbaik. Raise dalam setiap spot", action: "Sentiasa raise/re-raise (3-bet)" },
      KK: { desc: "Hanya perlu berjaga-jaga dengan ace di flop", action: "Sentiasa raise/re-raise" },
      QQ: { desc: "Lebih kuat daripada JJ, tetapi jangan terlebih nilai", action: "Sentiasa raise; berhati-hati apabila deep" },
      JJ: { desc: "Berjaga-jaga dengan overcard di flop", action: "Raise dari mana-mana posisi" },
      "1010": { desc: "Hilang nilai apabila overcard muncul di flop", action: "Raise di posisi tengah/lewat, pertimbangkan call di posisi awal" },
      AKs: { desc: "Tangan drawing terbaik. Besarkan pot", action: "Sentiasa raise/re-raise" },
      AKo: { desc: "Lebih lemah daripada AKs tetapi masih premium", action: "Sentiasa raise; boleh call re-raise" },
      AQs: { desc: "Tangan kuat; lebih bernilai dalam posisi", action: "Raise dari kebanyakan posisi" },
      AJs: { desc: "Hebat di BTN/CO, lemah dari UTG", action: "Raise di posisi tengah/lewat, pertimbangkan call di posisi awal" },
      A10s: { desc: "Antara suited ace teratas", action: "Raise di posisi lewat, call di posisi awal" },
      KQs: { desc: "Potensi flush tinggi + straight draw", action: "Raise dari kebanyakan posisi" },
      KJs: { desc: "Tangan drawing yang kuat", action: "Raise di posisi lewat, call di posisi awal" },
      "99": { desc: "Pair sederhana, berjaga-jaga dengan flop overcard", action: "Raise dari kebanyakan posisi; berhati-hati apabila deep" },
      "88": { desc: "Pocket pair dengan potensi set yang baik", action: "Raise di posisi lewat, pertimbangkan call di posisi awal" },
      AQo: { desc: "Offsuit lebih lemah; posisi penting", action: "Raise di posisi tengah/lewat" },
      AJo: { desc: "Lemah di posisi awal, kuat di posisi lewat", action: "Raise di CO/BTN, berhati-hati di posisi awal" },
      KQo: { desc: "Connector offsuit teratas", action: "Raise di posisi lewat, call/fold di posisi awal" },
      K10s: { desc: "Suited king, kuat di posisi lewat", action: "Raise di posisi lewat, fold di posisi awal" },
      QJs: { desc: "Draw dua hala yang kuat", action: "Raise di posisi lewat, lebih bernilai apabila deep" },
      J10s: { desc: "Antara suited connector terbaik", action: "Raise di posisi lewat, call di posisi awal ikut pot odds" },
      "109s": { desc: "Suited connector yang kuat", action: "Raise/call di posisi lewat" },
      "77": { desc: "Tangan untuk cari set, berjaga-jaga dengan overcard", action: "Raise di posisi lewat, call di posisi awal" },
      A9s: { desc: "Suited ace dengan potensi flush", action: "Raise di posisi lewat" },
      "66": { desc: "Cari set; perlukan pot odds", action: "Call/raise di posisi lewat, paling bagus multiway" },
      "55": { desc: "Kurang nilai tanpa set", action: "Call di posisi lewat, pot single-raised" },
      A8s: { desc: "Suited ace sederhana", action: "Main di posisi lewat, fold di posisi awal" },
      A7s: { desc: "Suited ace sederhana", action: "Main di posisi lewat sahaja" },
      A6s: { desc: "Suited ace sederhana", action: "Main di posisi lewat sahaja" },
      A5s: { desc: "Nilai wheel + ace-blocker; bluff 3-bet kegemaran", action: "Posisi lewat sahaja; implied odds penting" },
      A4s: { desc: "Suited ace dengan wheel draw", action: "Posisi lewat sahaja" },
      A3s: { desc: "Paling bawah antara suited ace", action: "BTN/SB sahaja" },
      A2s: { desc: "Wheel + nut flush, tetapi lemah", action: "BTN sahaja" },
      KJo: { desc: "Risiko didominasi; posisi lewat sahaja", action: "Raise di CO/BTN, fold jika di-re-raise" },
      QJo: { desc: "Sambungan sederhana; perlukan posisi", action: "Posisi lewat sahaja" },
      "98s": { desc: "Suited connector yang kuat", action: "Call/raise di posisi lewat" },
      "87s": { desc: "Suited connector yang baik", action: "Call di posisi lewat" },
      "76s": { desc: "Suited connector", action: "Call di posisi lewat ikut pot odds" },
      "44": { desc: "Hampir tiada nilai tanpa set", action: "Call hanya jika pot odds rendah" },
      "33": { desc: "Perlu cari set; spekulatif", action: "Pot multiway, call murah sahaja" },
      "22": { desc: "Pocket pair paling rendah", action: "Pot multiway, call murah sahaja" },
      K10o: { desc: "K-10 offsuit, lemah", action: "Sekali-sekala dari BTN" },
      Q10o: { desc: "Offsuit dengan sambungan rendah", action: "BTN sahaja" },
      J10o: { desc: "Offsuit yang boleh tahan tetapi mudah diserang", action: "Sekali-sekala dari BTN" },
      Q10s: { desc: "Suited broadway yang kuat, bagus dimainkan dalam posisi", action: "Raise di posisi lewat, call di posisi awal ikut pot odds" },
      A10o: { desc: "Ace offsuit marginal, mudah didominasi", action: "Posisi lewat sahaja" },
      "65s": { desc: "Suited connector; mahukan multiway/implied odds", action: "Call di posisi lewat" },
      "54s": { desc: "Suited connector rendah; spekulatif", action: "Call di posisi lewat, pot multiway yang murah" },
    },
  },

  spr: {
    effectiveStack: "Stack efektif (anda)",
    potSize: "Saiz pot semasa",
    caption: "SPR (Stack-to-Pot Ratio)",
    stackDivPot: "stack ÷ pot",
    zones: {
      low: {
        label: "SPR rendah (komited)",
        desc: "Sebahagian besar pot sudah masuk. Dengan top pair top kicker atau lebih baik, pertimbangkan all-in — fold di sini boleh menjadi kesilapan.",
        actions: [["TPTK+", "Pertimbangkan all-in"], ["Draw", "Pot odds wajib dikira"], ["Tangan lemah", "Fold dengan berhati-hati"]],
      },
      mid: {
        label: "SPR sederhana (fleksibel)",
        desc: "Ini zon untuk bermain tangan kuat seperti two pair atau lebih baik. Melindungi stack anda menjadi penting.",
        actions: [["Two pair+", "Value bet"], ["Satu pair", "Main ikut bacaan"], ["Draw", "Timbang risiko lawan ganjaran"]],
      },
      high: {
        label: "SPR tinggi (semakin deep)",
        desc: "Stack semakin deep. Draw dan made hand yang kuat naik nilai relatifnya.",
        actions: [["Set+", "Main dengan kuat"], ["Draw", "Implied odds meningkat"], ["Satu pair/TPTK", "Teruskan dengan berhati-hati"]],
      },
      deep: {
        label: "SPR sangat tinggi (deep)",
        desc: "Ini permainan deep stack. Posisi, potensi draw dan pembacaan range lawan sangat penting.",
        actions: [["Tangan nut", "Boleh bet besar"], ["Draw", "Implied odds sangat tinggi"], ["Made hand lemah", "Hati-hati, mudah di-bluff"]],
      },
    },
    legend: ["Komited", "Fleksibel", "Semakin deep", "Deep"],
  },

  m: {
    inputs: { stack: "Stack anda", bb: "Big blind", sb: "Small blind", ante: "Ante" },
    players: "Pemain di meja: {v}",
    headsUp: "2 (heads-up)",
    orbitCaption: "Kos satu pusingan (blind setiap pusingan meja)",
    orbitFormula: "BB {bb} + SB {sb} + ante {ante}×{players}",
    mCaption: "Nilai M (M Harrington)",
    zones: {
      dead: { name: "💀 Zon mati", desc: "Anda perlu all-in serta-merta. Tiada ruang untuk menunggu tangan yang lebih baik — shove tangan terbaik yang anda ada.", action: "All-in sekarang" },
      red: { name: "🔴 Zon merah", desc: "Anda perlu double up segera. Gunakan strategi push/fold — shove tangan yang bagus, fold selebihnya.", action: "Push/fold" },
      orange: { name: "🟠 Zon oren", desc: "Stack anda semakin susut. Ketatkan range kepada tangan kuat sahaja dan cari peluang untuk open-shove.", action: "Range ketat" },
      yellow: { name: "🟡 Zon kuning", desc: "Tekanan sudah terasa. Anda perlu aktif mengumpul cip — main agresif apabila spot yang baik muncul.", action: "Main agresif" },
      green: { name: "🟢 Zon hijau", desc: "Stack anda selesa. Gunakan strategi sepenuhnya — besarkan stack dengan permainan posisi dan bluff.", action: "Strategi penuh" },
    },
  },

  icm: {
    introStrong: "ICM (Independent Chip Model)",
    introRest: " ialah cara mengira nilai wang sebenar cip tournament anda. Nilai ICM chip leader sekalipun lebih rendah daripada bahagian cipnya, manakala short stack bernilai lebih daripada bahagian cipnya. Gunakannya untuk keputusan call/fold di final table dan di bubble.",
    numPlayers: "Bilangan pemain",
    paidPlaces: "Kedudukan yang dibayar",
    stacksTitle: "Stack cip pemain",
    total: "jumlah {n}",
    decStack: "Kurangkan stack pemain {n}",
    stackInput: "Stack cip pemain {n}",
    incStack: "Tambah stack pemain {n}",
    prizesTitle: "Hadiah",
    decPrize: "Kurangkan hadiah tempat ke-{n}",
    prizeInput: "Hadiah tempat ke-{n}",
    incPrize: "Tambah hadiah tempat ke-{n}",
    currencyNote: "Masukkan jumlah hadiah dalam mana-mana unit mata wang.",
    resultTitle: "Hasil ICM",
    th: { player: "Pemain", chips: "Cip", chipPct: "Cip %", icmValue: "Nilai ICM", icmPct: "ICM %", diff: "Beza" },
    playerCell: "{medal} P{n}",
    diffPlus: "+beza",
    diffPlusNote: "Nilai ICM melebihi bahagian cip → zon perlindungan short stack, elakkan coin flip",
    diffMinus: "−beza",
    diffMinusNote: "Nilai ICM di bawah bahagian cip → tekanan agresif chip leader lebih berbaloi",
    empty: "Tetapkan stack dan hadiah melebihi sifar untuk melihat hasil ICM.",
  },

  pushfold: {
    ante: "Ante",
    noAnte: "Tiada ante",
    bbAnteOn: "BB ante ON",
    table: "Meja",
    headsUp: "Heads-Up",
    sixMax: "6-max",
    nineMax: "9-max",
    scenario: "Senario",
    sbShove: "SB: shove atau fold",
    bbCall: "BB: call shove",
    position: "Posisi {hint}",
    firstInHint: "(first-in — semua fold kepada anda)",
    effectiveStack: "Stack efektif: {v}",
    captionHuPush: "Tangan yang SB shove pada {stack}bb",
    captionHuCall: "Tangan yang BB call shove pada {stack}bb",
    captionMw: "Shove first-in dari {pos} di meja {table}-max, {stack}bb",
    withAnte: " (dengan ante)",
    combosSuffix: " / {total} kombo",
    legendPush: "Push (all-in)",
    legendCall: "Call",
    legendFold: "Fold",
    note: {
      strong1: "Pepenjuru = pair · kanan atas = suited · kiri bawah = offsuit",
      p1: "Grid disusun mengikut ",
      strong2: "rank, bukan kekuatan",
      p2: ", jadi sel yang diserlahkan dan tidak diserlahkan berselang-seli dalam satu baris memang dijangka — AQo, KQo dan QQ bersebelahan tetapi bukan dalam susunan kekuatan. A5s masuk sedangkan A6s tidak juga betul: A5s membentuk",
      strong3: "wheel straight (A-2-3-4-5)",
      p3: ", yang mengatasi kicker yang lebih rendah.",
    },
    cellTitle: "{hand} — {action}",
    cell: { push: "push", call: "call", fold: "fold" },
    huNote: {
      strong: "Keseimbangan Nash, heads-up (SB lawan BB)",
      p1: ": SB diandaikan sama ada shove atau fold. Tetapan ante menambah 0.125bb setiap pemain (bersamaan big blind ante, ≈12.5%). Range melebar apabila stack semakin pendek — dan di bawah ~3-4bb, BB betul untuk call ",
      em: "lebih luas",
      p2: " daripada range shove SB, kerana pot odds.",
    },
    mwNote: {
      strong: "Carta shove first-in {table}-max",
      p1: ": semua pemain di hadapan sudah fold dan anda sama ada shove atau fold. Ia keseimbangan gaya Nash ",
      strong2: "chip-EV tulen",
      p2: " — range call pemain di belakang diselesaikan serentak — dengan anggaran standard bahawa pot yang di-call diselesaikan secara heads-up menentang caller pertama (pot dengan lebih daripada seorang caller diabaikan). Range melebar apabila makin sedikit pemain tinggal di belakang anda (UTG → BTN → SB), apabila stack semakin pendek, dan apabila ante ON (0.125bb setiap pemain). Kerana ia chip-EV tulen, range 10bb dari posisi awal (UTG/MP) keluar lebih ketat daripada peraturan umum yang popular (pair kecil fold) — sesuaikan dengan ICM dan lawan dalam permainan sebenar.",
    },
    readMore: "Untuk asas tekanan stack dan ICM dalam tournament, baca",
    shortStackLink: { slug: "holdem-tournament-vs-cash-game", text: "perbandingan tournament dan cash game kami" },
    readMoreEnd: ".",
  },

  icmGuide: {
    bubble: {
      badge: "Panduan ICM",
      h2: "Cara menggunakan kalkulator ICM — contoh bubble 3 minit",
      intro: "Katakan empat pemain tinggal dan tiga dibayar (bubble). Stack ialah 60,000 / 40,000 / 30,000 / 20,000 dan hadiahnya $500 / $300 / $200. Masukkan angka itu ke dalam kalkulator dan anda dapat bahagian cip setiap pemain berbanding nilai hadiah sebenar (ICM):",
      th: { player: "Pemain", chipPct: "Cip %", icmPct: "ICM %", diff: "Beza" },
      rows: [
        { player: "🥇 Chip leader", chip: "40.0%", icm: "33.3%", diff: "-6.7 mata", up: false },
        { player: "🥈 Ke-2", chip: "26.7%", icm: "27.2%", diff: "+0.6 mata", up: true },
        { player: "🥉 Ke-3", chip: "20.0%", icm: "22.9%", diff: "+2.9 mata", up: true },
        { player: "Ke-4 (short stack)", chip: "13.3%", icm: "16.6%", diff: "+3.3 mata", up: true },
      ],
      keyPoint: {
        text: "Perkara utama: {b1} sebanyak 6.7 mata. Kerana menang hanya membayar wang tempat pertama, chip leader mendapat nilai hadiah yang lebih kecil daripada satu coin flip berbanding yang dicadangkan oleh bilangan cipnya. Jadi di bubble, chip leader patut {b2}, manakala short stack (13.3% cip → 16.6% ICM) bernilai lebih daripada cipnya dan patut {b3} untuk melindungi nilai survival itu.",
        b1: "nilai ICM chip leader (33.3%) lebih rendah daripada bahagian cipnya (40%)",
        b2: "menekan short stack",
        b3: "mengelakkan call all-in yang tidak perlu",
      },
    },
    deal: {
      badge: "Pembahagian hadiah",
      h2: "Deal ICM lawan chip chop — membahagikan prize pool",
      intro: "Kini tiga pemain tinggal dan sedang berbincang tentang deal. Dengan stack 50% / 30% / 20% dan baki hadiah $1,500, dua kaedah ini membahagikannya dengan sangat berbeza:",
      th: { player: "Pemain", chop: "Chip chop", icm: "Deal ICM", diff: "Beza" },
      rows: [
        { player: "🥇 Chip leader (50%)", chop: "$750", icm: "$618", diff: "-$132", up: false },
        { player: "🥈 Ke-2 (30%)", chop: "$450", icm: "$485", diff: "+$35", up: true },
        { player: "🥉 Short stack (20%)", chop: "$300", icm: "$397", diff: "+$97", up: true },
      ],
      summary: {
        text: "Chip chop membahagi mengikut bahagian cip dan {b1}; deal ICM mencerminkan kebarangkalian kedudukan akhir dan {b2}. Di atas, short stack mendapat $300 dengan chip chop tetapi kira-kira $397 dengan deal ICM — {b3}. Minta deal ICM apabila anda short; cadangkan chip chop apabila anda chip leader.",
        b1: "memihak kepada chip leader",
        b2: "lebih adil kepada short stack",
        b3: "$97 lebih",
      },
    },
  },

  guide: {
    badge: "Alat",
    h2: "Cara menggunakan 8 kalkulator Hold'em",
    cards: [
      { title: "Kalkulator outs", body: "Mengira dengan tepat peluang draw anda lengkap pada flop atau turn. Lihat pintasan Peraturan 4 dan 2 serta angka yang tepat serentak." },
      { title: "Pot odds & implied odds", body: "Putuskan call atau fold dengan pengiraan. Apabila lawan deep, tambah implied odds untuk keputusan yang lebih tepat." },
      { title: "Penilai tangan", body: "Pilih kad untuk menyemak kedudukan tangan. Masukkan sehingga 7 kad dan ia mencari gabungan 5 kad terbaik secara automatik." },
      { title: "Kekuatan tangan permulaan", body: "Pilih dua kad tangan anda untuk melihat yang mana antara 169 tangan permulaan dan tindakan yang disyorkan mengikut posisi." },
      { title: "SPR (Stack-to-Pot Ratio)", body: "Nisbah stack kepada pot memberitahu sekuat mana tangan yang anda perlukan. Semakin rendah SPR, semakin wajar komited dengan tangan yang kuat." },
      { title: "Nilai M tournament", body: "M Harrington mengukur tekanan pada stack tournament anda. Strategi anda berubah sepenuhnya merentasi zon hijau/kuning/oren/merah/mati." },
      { title: "Kalkulator ICM", body: "Independent Chip Model menukar cip tournament kepada nilai hadiah wang sebenar — penting untuk keputusan call/fold dan perbincangan deal di bubble dan final table." },
      { title: "Carta push/fold Nash", body: "Carta heads-up 13×13 yang dikira daripada keseimbangan Nash: tangan mana untuk open-shove dan tangan mana untuk call pada 1–25bb. Wajib ada untuk peringkat akhir tournament." },
    ],
  },

  faq: {
    badge: "FAQ",
    h2: "FAQ — kalkulator ICM & kalkulator Hold'em",
    q: "Q. {q}",
  },

  related: {
    badge: "Baca seterusnya",
    h2: "Panduan untuk dibaca selepas pengiraannya sudah masuk akal",
    links: [
      { slug: "holdem-tournament-vs-cash-game", title: "Tournament atau Cash Game", desc: "Nilai cip, ICM dan tekanan bubble" },
      { slug: "a-high-board-cbet", title: "Equity dan EQR dalam Solver", desc: "Range check, equity dan realisasi equity pada A72" },
      { slug: "texas-holdem-rules-for-beginners", title: "Cara Main Texas Hold'em", desc: "Asas pot odds dan tangan permulaan untuk pemula" },
      { slug: "3bet-pot-bet-sizing", title: "Outs dan Harga Draw", desc: "40 kombo draw berbanding harga call dalam pot 3-bet" },
      { slug: "holdem-hand-rankings", title: "Susunan Tangan Poker", desc: "10 tangan dengan kebarangkalian dan kicker" },
      { slug: "holdem-game-order", title: "Urutan Permainan Hold'em", desc: "Preflop hingga showdown dan posisi di meja" },
    ],
  },
};
