// FR calculator dictionary — every user-visible string of `components/calculator/calculator-tool.tsx`.
//
// ★2026-09-17 신설(10로케일 일괄 개설 회차). 구조·플레이스홀더·배열 길이는 `CALC_DICT_EN`과 1:1.
// 용어 출처(우선순위 순): `docs/translation-terms-fr.md`(족보=quinte·couleur·brelan·carré·full·carte haute,
// 블라인드=petite/grosse blinde, 숫자=공백 천단위·쉼표 소수·% 앞 공백, $ 유지, register=tu) ·
// `docs/local-voice/fr-fr.md`(tirage·se coucher·paires servies·cote du pot·paliers·«mettre la pression») ·
// `lib/posts-fr/holdem-game-order.ts:309` «cotes du pot (pot odds)» · `lib/posts-fr/holdem-blind-meaning.ts:143`
// «27 % d'équité» · `lib/posts-fr/texas-holdem-rules-for-beginners.ts:410,444`(«169 types de mains de départ»,
// «AK assortis (suited)», «dépareillés (offsuit)», 앵커 «calculatrice de probabilités poker») ·
// `app/fr/solver/faq.ts`(equity·EV·range·«Equity (% victoire)»·«table finale»·«paliers de paiement»).
// 🔴 §13: 수치·핸드·공식은 EN과 동일. 구분자만 프랑스식(fr-FR toLocaleString + 문자열 내 «19,6 %»).
// 🪶 «equity»는 솔버 랜딩 관용(앱 fr 축어)을 따른다 — 블로그 코퍼스의 «équité»(1회)는 자연문 병기로만.
import type { CalcDict } from "@/components/calculator/dict";

export const CALC_DICT_FR: CalcDict = {
  numberLocale: "fr-FR",

  seo: {
    title: "Calculatrice de probabilités poker — Outs, cotes du pot, ICM",
    description: "Calculatrice poker gratuite (Texas Hold'em) : outs, cotes du pot, classement des mains, mains de départ, SPR, M de tournoi, ICM et push/fold — 8 outils en un.",
    path: "/fr/calculator",
  },

  hero: {
    badges: ["Outil gratuit", "En temps réel"],
    h1: "Calculatrice de probabilités poker",
    h1Sub: "Tous les chiffres du Hold'em au même endroit",
    lead: "Outs · cotes du pot · classement des mains · force des mains de départ · SPR · M de tournoi · ICM · tableau push/fold de Nash — les maths dont tu as besoin à table, tout de suite.",
    chips: ["🎯 Outs", "💰 Cotes du pot", "🃏 Classement", "📊 Main de départ", "📐 SPR", "🏆 Valeur M", "📈 ICM", "⚡ Push/Fold"],
  },

  tabs: {
    outs: { label: "Outs", sub: "Cote des tirages" },
    pot: { label: "Cotes du pot", sub: "Suivre / se coucher" },
    hand: { label: "Classement", sub: "Choisis tes cartes" },
    starting: { label: "Main de départ", sub: "Force à l'ouverture" },
    spr: { label: "SPR", sub: "Ratio tapis / pot" },
    m: { label: "M de tournoi", sub: "Valeur M" },
    icm: { label: "ICM", sub: "Equity en gains" },
    pushfold: { label: "Push/Fold", sub: "Tableau de Nash" },
  },

  workspace: {
    chooseCalculator: "Choisis un calculateur",
    resetInputs: "Réinitialiser",
    resetAria: "Réinitialiser {label}",
    resetMessage: "Champs de {label} réinitialisés.",
  },

  cardPicker: {
    clearAll: "Tout effacer",
  },

  outs: {
    drawType: "Type de tirage",
    presets: [
      { label: "Saisie libre" },
      { label: "Tirage couleur max (nut flush draw)", desc: "4 cartes de la même couleur → il te faut la 5e" },
      { label: "Tirage quinte par les deux bouts (OESD)", desc: "ex. 5-6-7-8, il te faut un 4 ou un 9" },
      { label: "Couleur + quinte ventrale (combo)", desc: "9 outs couleur + 3 outs ventrale (doublons retirés)" },
      { label: "Quinte ventrale (gutshot)", desc: "ex. 5-6-8-9, il te faut exactement un 7" },
      { label: "Deux overcards", desc: "2 hauteurs absentes du board × 3 chacune" },
      { label: "Double paire → full", desc: "ex. A-K sur un board A-K-x → 2 as + 2 rois restants" },
      { label: "Paire → brelan", desc: "il reste 2 cartes de cette hauteur" },
      { label: "Couleur + OESD (monstre)", desc: "9 outs couleur + 8 outs quinte (2 en double)" },
    ],
    outsSuffix: " ({n} outs)",
    street: "Street",
    afterFlopBtn: "🃏 Après le flop",
    afterTurnBtn: "🔄 Après le turn",
    outsCount: "Nombre d'outs : {v}",
    afterFlop: "Après le flop",
    afterTurn: "Après le turn",
    ruleOf4: "Règle du 4",
    ruleOf2: "Règle du 2",
    chanceFlop: "Chance de toucher après le flop",
    chanceTurn: "Chance de toucher après le turn",
    exact: " (exact)",
    ruleMental: "Règle du {n} (calcul mental) :",
    exactNote: "La valeur ci-dessus est le chiffre exact",
    verdict: { great: "Excellent 🔥", good: "Bon ✅", fair: "Moyen ⚠️", poor: "Faible ❌", veryPoor: "Très faible 💀" },
  },

  pot: {
    potSize: "Taille actuelle du pot",
    callAmount: "Montant à suivre",
    potOddsCaption: "Cotes du pot (equity minimale requise)",
    orHigher: "ou plus rend le call rentable",
    equityLabel: "Equity de ta main : {v}",
    sliderGutshot: "Ventrale 8,7 %",
    sliderFlush: "Couleur 19 %",
    impliedToggle: "Cotes implicites {toggle}",
    close: "Fermer ▲",
    add: "Ajouter ▼",
    extraWinnings: "Gains supplémentaires attendus (si tu touches) : {v}",
    none: "Aucun",
    impliedCaption: "Cotes implicites (gains supplémentaires inclus)",
    impliedNote: "Equity minimale requise, en comptant {n} de plus",
    needImplied: "les cotes implicites {n} %",
    needPot: "les cotes du pot {n} %",
    verdict: {
      call: { title: "Suivre (rentable)", body: "Ton equity {eq} % > {need} → rentable sur le long terme" },
      even: { title: "À l'équilibre (EV 0)", body: "Ton equity {eq} % = {need} → suivre ne gagne ni ne perd. Décide selon d'autres facteurs que les cotes du pot : la position, les tendances de l'adversaire" },
      fold: { title: "Se coucher (recommandé)", body: "Ton equity {eq} % < {need} → perdant sur le long terme" },
    },
  },

  handEval: {
    pickerLabel: "Choisis tes cartes (5 à 7)",
    emptyTitle: "Choisis au moins 5 cartes pour évaluer la main",
    emptyHint: "Avec 7 cartes, la meilleure combinaison de 5 cartes est trouvée automatiquement",
    bestFrom: "Meilleure main sur {n} cartes",
    rankNames: [
      "Carte haute", "Paire", "Double paire", "Brelan", "Quinte",
      "Couleur", "Full", "Carré", "Quinte flush", "Quinte flush royale",
    ],
    resultNames: [
      "Carte haute 🃏", "Paire 1️⃣", "Double paire ✌️", "Brelan 3️⃣", "Quinte ➡️",
      "Couleur 🌊", "Full 🏠", "Carré 💎", "Quinte flush 🌟", "Quinte flush royale 👑",
    ],
    axis: ["Carte haute", "Paire", "Couleur", "Carré", "Royale"],
  },

  starting: {
    pickerLabel: "Choisis tes 2 cartes fermées",
    emptyPrompt: "Choisis tes 2 cartes fermées",
    unknownDesc: "Main très faible",
    unknownAction: "Se coucher en général",
    tierNames: ["🥇 Tier 1 — Premium", "🥈 Tier 2 — Forte", "🥉 Tier 3 — Jouable", "⚠️ Tier 4 — Marginale", "🚫 Tier 5 — Faible"],
    recommendedAction: "Action recommandée :",
    axis: ["Premium", "Forte", "Jouable", "Marginale", "Faible"],
    summaryTitle: "Résumé des tiers de mains",
    summary: [
      { hands: "AA KK QQ JJ 10-10 AKs AKo", action: "Toujours relancer" },
      { hands: "AQs AJs A10s KQs KJs 99 88 AQo", action: "Relancer depuis la plupart des positions" },
      { hands: "AJo KQo K10s QJs J10s 10-9s 77 A9s", action: "Relancer en position tardive" },
      { hands: "66–55 A8s–A2s KJo QJo connecteurs assortis", action: "Sélectif en LP" },
      { hands: "44–22 mains dépareillées faibles", action: "Se coucher en général" },
    ],
    hands: {
      AA: { desc: "La meilleure main. Relance dans tous les spots", action: "Toujours relancer / sur-relancer (3-bet)" },
      KK: { desc: "Le seul danger : un as au flop", action: "Toujours relancer / sur-relancer" },
      QQ: { desc: "Plus forte que JJ, mais ne la surestime pas", action: "Toujours relancer ; prudence en tapis profond" },
      JJ: { desc: "Attention aux overcards au flop", action: "Relancer depuis toutes les positions" },
      "1010": { desc: "Perd de la valeur quand des overcards tombent au flop", action: "Relancer en mid/late, envisager de suivre en EP" },
      AKs: { desc: "La meilleure main à tirages. Fais grossir le pot", action: "Toujours relancer / sur-relancer" },
      AKo: { desc: "Moins forte qu'AKs mais toujours premium", action: "Toujours relancer ; peut suivre une sur-relance" },
      AQs: { desc: "Main forte ; vaut plus en position", action: "Relancer depuis la plupart des positions" },
      AJs: { desc: "Excellente au BTN/CO, faible depuis UTG", action: "Relancer en mid/late, envisager de suivre en EP" },
      A10s: { desc: "L'un des meilleurs as assortis", action: "Relancer en LP, suivre en EP" },
      KQs: { desc: "Potentiel couleur haute + quinte", action: "Relancer depuis la plupart des positions" },
      KJs: { desc: "Main à tirages solide", action: "Relancer en LP, suivre en EP" },
      "99": { desc: "Paire moyenne, attention aux flops avec overcards", action: "Relancer depuis la plupart des positions ; prudence en profond" },
      "88": { desc: "Paire servie avec un bon potentiel de brelan", action: "Relancer en LP, envisager de suivre en EP" },
      AQo: { desc: "Dépareillée, plus faible ; la position compte", action: "Relancer en position mid/late" },
      AJo: { desc: "Faible en EP, forte en LP", action: "Relancer au CO/BTN, prudence en EP" },
      KQo: { desc: "Le meilleur connecteur dépareillé", action: "Relancer en LP, suivre/se coucher en EP" },
      K10s: { desc: "Roi assorti, fort en LP", action: "Relancer en LP, se coucher en EP" },
      QJs: { desc: "Tirages solides dans les deux sens", action: "Relancer en LP, vaut plus en tapis profond" },
      J10s: { desc: "L'un des meilleurs connecteurs assortis", action: "Relancer en LP, suivre en EP selon les cotes du pot" },
      "109s": { desc: "Connecteur assorti solide", action: "Relancer/suivre en LP" },
      "77": { desc: "Main à chercher le brelan, attention aux overcards", action: "Relancer en LP, suivre en EP" },
      A9s: { desc: "As assorti avec potentiel couleur", action: "Relancer en LP" },
      "66": { desc: "Chercher le brelan ; il faut les cotes du pot", action: "Suivre/relancer en LP, idéale en multiway" },
      "55": { desc: "Peu de valeur sans brelan", action: "Suivre en LP, pots relancés une seule fois" },
      A8s: { desc: "As assorti moyen", action: "Jouer en LP, se coucher en EP" },
      A7s: { desc: "As assorti moyen", action: "Jouer en LP uniquement" },
      A6s: { desc: "As assorti moyen", action: "Jouer en LP uniquement" },
      A5s: { desc: "Roue + bloqueur à l'as ; un 3-bet bluff favori", action: "LP uniquement ; les cotes implicites comptent" },
      A4s: { desc: "As assorti avec tirage à la roue", action: "LP uniquement" },
      A3s: { desc: "Le bas des as assortis", action: "BTN/SB uniquement" },
      A2s: { desc: "Roue + couleur max, mais faible", action: "BTN uniquement" },
      KJo: { desc: "Risque de domination ; LP uniquement", action: "Relancer au CO/BTN, se coucher face à une sur-relance" },
      QJo: { desc: "Connectivité moyenne ; il faut la position", action: "LP uniquement" },
      "98s": { desc: "Connecteur assorti solide", action: "Suivre/relancer en LP" },
      "87s": { desc: "Bon connecteur assorti", action: "Suivre en LP" },
      "76s": { desc: "Connecteur assorti", action: "Suivre en LP selon les cotes du pot" },
      "44": { desc: "Presque aucune valeur sans brelan", action: "Suivre seulement à petites cotes du pot" },
      "33": { desc: "Doit toucher le brelan ; spéculative", action: "Pots multiway, calls pas chers uniquement" },
      "22": { desc: "La plus petite paire servie", action: "Pots multiway, calls pas chers uniquement" },
      K10o: { desc: "K-10 dépareillé, faible", action: "Parfois depuis le BTN" },
      Q10o: { desc: "Dépareillée, peu connectée", action: "BTN uniquement" },
      J10o: { desc: "Dépareillée correcte mais vulnérable", action: "Parfois depuis le BTN" },
      Q10s: { desc: "Broadway assorti solide, se joue bien en position", action: "Relancer en LP, suivre en EP selon les cotes du pot" },
      A10o: { desc: "As dépareillé marginal, souvent dominé", action: "LP uniquement" },
      "65s": { desc: "Connecteur assorti ; veut du multiway et des cotes implicites", action: "Suivre en LP" },
      "54s": { desc: "Petit connecteur assorti ; spéculatif", action: "Suivre en LP, pots multiway pas chers" },
    },
  },

  spr: {
    effectiveStack: "Tapis effectif (le tien)",
    potSize: "Taille actuelle du pot",
    caption: "SPR (ratio tapis / pot)",
    stackDivPot: "tapis ÷ pot",
    zones: {
      low: {
        label: "SPR bas (engagé)",
        desc: "Une grosse part du pot est déjà au milieu. Avec top paire top kicker ou mieux, envisage de faire tapis — se coucher ici peut être une erreur.",
        actions: [["TPTK+", "Envisager le tapis"], ["Tirages", "Cotes du pot obligatoires"], ["Mains faibles", "Se coucher avec prudence"]],
      },
      mid: {
        label: "SPR moyen (flexible)",
        desc: "C'est la zone où jouer les mains fortes, double paire ou mieux. Protéger ton tapis devient important.",
        actions: [["Double paire+", "Miser pour valeur"], ["Une paire", "Au feeling"], ["Tirages", "Peser le risque et le gain"]],
      },
      high: {
        label: "SPR élevé (ça devient profond)",
        desc: "Les tapis deviennent profonds. Les tirages et les mains faites fortes gagnent en valeur relative.",
        actions: [["Brelan+", "Jouer fort"], ["Tirages", "Les cotes implicites montent"], ["Une paire / TPTK", "Avancer avec prudence"]],
      },
      deep: {
        label: "SPR très élevé (profond)",
        desc: "C'est une partie en tapis profonds. La position, le potentiel des tirages et la lecture des ranges adverses comptent énormément.",
        actions: [["Mains max (nuts)", "Peut miser gros"], ["Tirages", "Cotes implicites très élevées"], ["Mains faites faibles", "Prudence, vulnérables aux bluffs"]],
      },
    },
    legend: ["Engagé", "Flexible", "Ça devient profond", "Profond"],
  },

  m: {
    inputs: { stack: "Ton tapis", bb: "Grosse blinde", sb: "Petite blinde", ante: "Ante" },
    players: "Joueurs à table : {v}",
    headsUp: "2 (heads-up)",
    orbitCaption: "Coût d'un tour (blindes par orbite)",
    orbitFormula: "BB {bb} + SB {sb} + ante {ante}×{players}",
    mCaption: "Valeur M (le M de Harrington)",
    zones: {
      dead: { name: "💀 Zone morte", desc: "Tu dois faire tapis tout de suite. Plus le temps d'attendre une meilleure main — pousse la meilleure main disponible.", action: "Tapis maintenant" },
      red: { name: "🔴 Zone rouge", desc: "Tu dois doubler vite. Joue en push/fold — fais tapis avec tes bonnes mains, couche le reste.", action: "Push/fold" },
      orange: { name: "🟠 Zone orange", desc: "Ton tapis fond. Resserre ta range aux mains fortes uniquement et cherche l'open-shove.", action: "Range serrée" },
      yellow: { name: "🟡 Zone jaune", desc: "La pression monte. Tu dois activement récupérer des jetons — joue agressif quand les bons spots se présentent.", action: "Jouer agressif" },
      green: { name: "🟢 Zone verte", desc: "Tu as un tapis confortable. Utilise toute la palette stratégique — fais grossir ton tapis avec la position et les bluffs.", action: "Stratégie complète" },
    },
  },

  icm: {
    introStrong: "L'ICM (Independent Chip Model)",
    introRest: " est une méthode pour calculer la valeur réelle, en argent, de tes jetons de tournoi. Même le chip leader a une valeur ICM inférieure à sa part de jetons, alors que les petits tapis valent plus que la leur. Sers-t'en pour tes décisions suivre / se coucher en table finale et à la bulle.",
    numPlayers: "Nombre de joueurs",
    paidPlaces: "Places payées",
    stacksTitle: "Tapis des joueurs",
    total: "total {n}",
    decStack: "Diminuer le tapis du joueur {n}",
    stackInput: "Tapis du joueur {n}",
    incStack: "Augmenter le tapis du joueur {n}",
    prizesTitle: "Gains",
    decPrize: "Diminuer le gain de la place {n}",
    prizeInput: "Gain de la place {n}",
    incPrize: "Augmenter le gain de la place {n}",
    currencyNote: "Saisis les gains dans n'importe quelle devise.",
    resultTitle: "Résultat ICM",
    th: { player: "Joueur", chips: "Jetons", chipPct: "% jetons", icmValue: "Valeur ICM", icmPct: "% ICM", diff: "Écart" },
    playerCell: "{medal} J{n}",
    diffPlus: "+écart",
    diffPlusNote: "Valeur ICM au-dessus de la part de jetons → zone de protection du petit tapis, évite les coin flips",
    diffMinus: "−écart",
    diffMinusNote: "Valeur ICM en dessous de la part de jetons → l'agression du chip leader rapporte davantage",
    empty: "Renseigne des tapis et des gains supérieurs à zéro pour voir le résultat ICM.",
  },

  pushfold: {
    ante: "Ante",
    noAnte: "Sans ante",
    bbAnteOn: "BB ante ON",
    table: "Table",
    headsUp: "Heads-up",
    sixMax: "6-max",
    nineMax: "9-max",
    scenario: "Scénario",
    sbShove: "SB : tapis ou fold",
    bbCall: "BB : payer un tapis",
    position: "Position {hint}",
    firstInHint: "(first-in — tout le monde s'est couché avant toi)",
    effectiveStack: "Tapis effectif : {v}",
    captionHuPush: "Mains avec lesquelles la SB fait tapis à {stack}bb",
    captionHuCall: "Mains avec lesquelles la BB paie un tapis à {stack}bb",
    captionMw: "Tapis first-in depuis {pos} à une table {table}-max, {stack}bb",
    withAnte: " (avec ante)",
    combosSuffix: " / {total} combos",
    legendPush: "Push (tapis)",
    legendCall: "Call",
    legendFold: "Fold",
    note: {
      strong1: "Diagonale = paires · en haut à droite = assorties · en bas à gauche = dépareillées",
      p1: "La grille est classée par ",
      strong2: "hauteur, pas par force",
      p2: ", donc voir des cases colorées et non colorées alterner sur une même ligne est normal — AQo, KQo et QQ sont côte à côte sans être dans l'ordre de force. Que A5s soit dedans alors qu'A6s est dehors est correct aussi : A5s fait la ",
      strong3: "quinte à la roue (A-2-3-4-5)",
      p3: ", ce qui pèse plus lourd que le kicker inférieur.",
    },
    cellTitle: "{hand} — {action}",
    cell: { push: "push", call: "call", fold: "fold" },
    huNote: {
      strong: "Équilibre de Nash, heads-up (SB contre BB)",
      p1: " : on suppose que la SB fait tapis ou se couche. Le réglage ante ajoute 0,125bb par joueur (l'équivalent d'un big blind ante, ≈12,5 %). Les ranges s'élargissent quand les tapis raccourcissent — et sous ~3-4bb, la BB paie correctement ",
      em: "plus large",
      p2: " que la SB ne pousse, à cause des cotes du pot.",
    },
    mwNote: {
      strong: "Tableau de tapis first-in {table}-max",
      p1: " : tout le monde s'est couché devant toi et tu fais tapis ou tu te couches. C'est un équilibre de type Nash en ",
      strong2: "pur EV jetons",
      p2: " — les ranges de call des joueurs derrière sont résolues simultanément — avec l'approximation standard qu'un tapis payé se joue en heads-up contre le premier caller (les pots à plusieurs callers sont ignorés). Les ranges s'élargissent quand il reste moins de joueurs derrière toi (UTG → BTN → SB), quand les tapis raccourcissent et avec les antes ON (0,125bb par joueur). Comme c'est du pur EV jetons, les ranges 10bb en position précoce (UTG/MP) ressortent plus serrées que les règles empiriques courantes (les petites paires se couchent) — en pratique, ajuste selon l'ICM et tes adversaires.",
    },
    readMore: "Pour les règles du tapis et des side pots, lis notre",
    shortStackLink: { slug: "holdem-all-in-rules", text: "guide des règles du tapis (all-in)" },
    readMoreEnd: ".",
  },

  icmGuide: {
    bubble: {
      badge: "Guide ICM",
      h2: "Comment utiliser le calculateur ICM — un exemple de bulle en 3 minutes",
      intro: "Imaginons qu'il reste quatre joueurs et que trois sont payés (la bulle). Les tapis sont 60 000 / 40 000 / 30 000 / 20 000 et les gains $500 / $300 / $200. Saisis ça dans le calculateur et tu obtiens, pour chaque joueur, sa part de jetons face à sa valeur réelle en gains (ICM) :",
      th: { player: "Joueur", chipPct: "% jetons", icmPct: "% ICM", diff: "Écart" },
      rows: [
        { player: "🥇 Chip leader", chip: "40,0 %", icm: "33,3 %", diff: "-6,7 pts", up: false },
        { player: "🥈 2e", chip: "26,7 %", icm: "27,2 %", diff: "+0,6 pt", up: true },
        { player: "🥉 3e", chip: "20,0 %", icm: "22,9 %", diff: "+2,9 pts", up: true },
        { player: "4e (petit tapis)", chip: "13,3 %", icm: "16,6 %", diff: "+3,3 pts", up: true },
      ],
      keyPoint: {
        text: "Le point clé : {b1} de 6,7 points. Comme gagner ne rapporte que le prix de la 1re place, le leader gagne moins de valeur en gains sur un coin flip que ne le suggère son nombre de jetons. À la bulle, le leader doit donc {b2}, tandis que le petit tapis (13,3 % des jetons → 16,6 % ICM) vaut plus que ses jetons et doit {b3} pour protéger cette valeur de survie.",
        b1: "la valeur ICM du chip leader (33,3 %) est inférieure à sa part de jetons (40 %)",
        b2: "mettre la pression sur les petits tapis",
        b3: "éviter les calls à tapis inutiles",
      },
    },
    deal: {
      badge: "Partage des gains",
      h2: "Deal ICM contre chip chop — se partager le prize pool",
      intro: "Il reste maintenant trois joueurs, qui discutent d'un deal. Avec des tapis de 50 % / 30 % / 20 % et $1 500 de gains restants, les deux méthodes donnent des partages très différents :",
      th: { player: "Joueur", chop: "Chip chop", icm: "Deal ICM", diff: "Écart" },
      rows: [
        { player: "🥇 Chip leader (50 %)", chop: "$750", icm: "$618", diff: "-$132", up: false },
        { player: "🥈 2e (30 %)", chop: "$450", icm: "$485", diff: "+$35", up: true },
        { player: "🥉 Petit tapis (20 %)", chop: "$300", icm: "$397", diff: "+$97", up: true },
      ],
      summary: {
        text: "Un chip chop partage au prorata des jetons et {b1} ; un deal ICM reflète les probabilités de classement final et est {b2}. Ci-dessus, le petit tapis touche $300 avec un chip chop mais environ $397 avec un deal ICM — {b3}. Demande un deal ICM quand tu es court ; propose un chip chop quand tu es chip leader.",
        b1: "avantage le chip leader",
        b2: "plus juste pour les petits tapis",
        b3: "$97 de plus",
      },
    },
  },

  guide: {
    badge: "Outils",
    h2: "Comment utiliser les 8 calculateurs Hold'em",
    cards: [
      { title: "Calculateur d'outs", body: "Calcule précisément la chance que ton tirage rentre au flop ou au turn. Tu vois d'un coup le raccourci de la règle du 4 et du 2 et le chiffre exact." },
      { title: "Cotes du pot et cotes implicites", body: "Décide de suivre ou de te coucher avec les maths. Quand l'adversaire est profond, ajoute les cotes implicites pour une décision plus précise." },
      { title: "Évaluateur de main", body: "Choisis des cartes pour connaître le rang de la main. Saisis jusqu'à 7 cartes et il trouve automatiquement la meilleure combinaison de 5 cartes." },
      { title: "Force des mains de départ", body: "Choisis tes deux cartes fermées pour voir laquelle des 169 mains c'est, et l'action recommandée selon la position." },
      { title: "SPR (ratio tapis / pot)", body: "Le ratio tapis / pot te dit de quelle force de main tu as besoin. Plus le SPR est bas, plus il est favorable de s'engager avec une main forte." },
      { title: "M de tournoi", body: "Le M de Harrington mesure la pression sur ton tapis de tournoi. Ta stratégie change du tout au tout entre les zones verte / jaune / orange / rouge / morte." },
      { title: "Calculateur ICM", body: "L'Independent Chip Model convertit les jetons de tournoi en valeur réelle en gains — indispensable pour les décisions suivre / se coucher et les négociations de deal à la bulle et en table finale." },
      { title: "Tableau push/fold de Nash", body: "Un tableau heads-up 13×13 calculé à partir de l'équilibre de Nash : quelles mains open-shove et lesquelles payer de 1 à 25bb. Incontournable en fin de tournoi." },
    ],
  },

  faq: {
    badge: "FAQ",
    h2: "FAQ — calculateur ICM et calculatrice Hold'em",
    q: "Q. {q}",
  },

  // 🔴 fr 코퍼스는 규칙 클러스터 6편뿐(EN의 tournament·equity·pot-odds·outs·probability·chart가 없다).
  //    링크는 실존 6편으로만 — 카드 desc는 각 글의 title/seoTitle 축어 범위 안에서만 썼다(창작 금지).
  related: {
    badge: "Pour aller plus loin",
    h2: "Les guides à lire une fois que les maths sont claires",
    links: [
      { slug: "texas-holdem-rules-for-beginners", title: "Règles du Texas Hold'em pour débutants", desc: "Jouer pas à pas : jetons, mains et première stratégie" },
      { slug: "holdem-blind-meaning", title: "Les blindes au poker", desc: "Petite et grosse blinde, expliquées simplement" },
      { slug: "holdem-betting-actions", title: "Les actions au Texas Hold'em", desc: "Checker, suivre, relancer, se coucher" },
      { slug: "holdem-all-in-rules", title: "Règles du tapis (all-in)", desc: "Side pots, relances et abattage" },
      { slug: "holdem-game-order", title: "L'ordre du jeu au Texas Hold'em", desc: "Quand miser, à qui de parler — des blindes à l'abattage" },
      { slug: "holdem-showdown-rules", title: "Règles de l'abattage", desc: "Qui montre en premier, jeter ses cartes et le slow roll" },
    ],
  },
};
