import type { CalcDict } from "@/components/calculator/dict";

/**
 * `/zh/calculator` 사전 — 공용 `CalculatorTool`이 이 객체 하나로 화면 전체를 그린다.
 * ★2026-09-17 신설(10개 로케일 동시 개설). 원문 = `components/calculator/dict.ts`(CALC_DICT_EN).
 *
 * 용어 출처(우선순위 순): `docs/translation-terms-zh.md` → `lib/posts-zh/holdem-glossary.ts` →
 *   코퍼스 실제 표기(`holdem-outs`·`holdem-pot-odds`·`holdem-icm`·`holdem-short-stack`·
 *   `holdem-hand-rankings`·`holdem-starting-hands-chart`·`holdem-drawing-odds`).
 * 판단 셋 —
 *   ① outs = «补牌（outs）» 병기(코퍼스 정본 · 신마 독자 영어 夹用) · OESD = «两头顺» · gutshot = «卡顺».
 *   ② push/fold·first-in·ante·chip chop·ICM deal·Nash 均衡은 코퍼스가 라틴 그대로 쓰므로 유지하고
 *      첫 등장에만 중문 괄호(«前注»·«推或弃»)를 단다. M值는 붙여 쓴다(코퍼스 7:1).
 *   ③ 인용부호는 zh 정본 “ ”만(check:hygiene) · 숫자 구분자는 코퍼스와 같은 3,000 / $1,500.
 */
export const CALC_DICT_ZH: CalcDict = {
  numberLocale: "zh-CN",

  seo: {
    title: "免费德州扑克概率计算器 — 胜率、补牌、底池赔率、ICM 一次算清",
    description:
      "免费的德州扑克概率计算器，打开浏览器就能算：补牌（outs）与听牌胜率、底池赔率和隐含赔率、牌型大小、起手牌强度、SPR、锦标赛 M值、ICM 分钱，还有 push/fold Nash 图表——8 个工具一页搞定。",
    path: "/zh/calculator",
  },

  hero: {
    badges: ["免费工具", "即时计算"],
    h1: "德州扑克概率计算器",
    h1Sub: "胜率、补牌、底池赔率即时计算",
    lead: "补牌 · 底池赔率 · 牌型大小 · 起手牌强度 · SPR · 锦标赛 M值 · ICM · Nash push/fold 图表——牌桌上要用的数字，这里一秒算出来。",
    chips: ["🎯 补牌", "💰 底池赔率", "🃏 牌型大小", "📊 起手牌", "📐 SPR", "🏆 M值", "📈 ICM", "⚡ Push/Fold"],
  },

  tabs: {
    outs: { label: "补牌", sub: "听牌胜率" },
    pot: { label: "底池赔率", sub: "跟还是弃" },
    hand: { label: "牌型大小", sub: "选牌判定" },
    starting: { label: "起手牌", sub: "开池强度" },
    spr: { label: "SPR", sub: "筹码底池比" },
    m: { label: "锦标赛 M", sub: "M值" },
    icm: { label: "ICM", sub: "奖金权益" },
    pushfold: { label: "Push/Fold", sub: "Nash 图表" },
  },

  workspace: {
    chooseCalculator: "选择计算器",
    resetInputs: "重置输入",
    resetAria: "重置{label}",
    resetMessage: "{label}的输入已重置。",
  },

  cardPicker: {
    clearAll: "全部清除",
  },

  outs: {
    drawType: "听牌类型",
    presets: [
      { label: "自定义输入" },
      { label: "坚果同花听牌", desc: "已有 4 张同花色 → 还差第 5 张" },
      { label: "两头顺听牌（OESD）", desc: "例：5-6-7-8，来一张 4 或 9 都成" },
      { label: "同花 + 卡顺组合听牌", desc: "9 张同花 + 3 张卡顺（已去掉重叠）" },
      { label: "卡顺听牌", desc: "例：5-6-8-9，只差一张 7" },
      { label: "两张高张", desc: "牌面上没有的 2 个高点数 × 各 3 张" },
      { label: "两对 → 葫芦", desc: "例：A-K 在 A-K-x 牌面 → 还剩 2 张 A + 2 张 K" },
      { label: "一对 → 三条", desc: "该点数还剩 2 张" },
      { label: "同花 + 两头顺（怪兽听牌）", desc: "9 张同花 + 8 张顺子（重叠 2 张）" },
    ],
    outsSuffix: "（{n} 张补牌）",
    street: "所在街",
    afterFlopBtn: "🃏 翻牌后",
    afterTurnBtn: "🔄 转牌后",
    outsCount: "补牌数：{v}",
    afterFlop: "翻牌后",
    afterTurn: "转牌后",
    ruleOf4: "×4 速算",
    ruleOf2: "×2 速算",
    chanceFlop: "翻牌后到河牌的成牌概率",
    chanceTurn: "转牌后到河牌的成牌概率",
    exact: "（精确值）",
    ruleMental: "×{n} 速算（心算）：",
    exactNote: "上方数值为精确计算结果",
    verdict: { great: "很好 🔥", good: "不错 ✅", fair: "一般 ⚠️", poor: "偏低 ❌", veryPoor: "很差 💀" },
  },

  pot: {
    potSize: "当前底池大小",
    callAmount: "你要跟注的金额",
    potOddsCaption: "底池赔率（跟注所需的最低胜率）",
    orHigher: "或更高，这次跟注就有利可图",
    equityLabel: "你的牌胜率：{v}",
    sliderGutshot: "卡顺 8.7%",
    sliderFlush: "同花听牌 19%",
    impliedToggle: "隐含赔率 {toggle}",
    close: "收起 ▲",
    add: "加上 ▼",
    extraWinnings: "命中后预计还能多赢：{v}",
    none: "无",
    impliedCaption: "隐含赔率（算上额外赢利）",
    impliedNote: "算上额外的 {n} 之后所需的最低胜率",
    needImplied: "隐含赔率 {n}%",
    needPot: "底池赔率 {n}%",
    verdict: {
      call: { title: "跟注（有利可图）", body: "你的胜率 {eq}% > {need} → 长期是赚的" },
      even: { title: "盈亏平衡（EV 为 0）", body: "你的胜率 {eq}% = {need} → 跟注不赚也不亏。看底池赔率之外的因素来决定，比如位置和对手的打法习惯" },
      fold: { title: "建议弃牌", body: "你的胜率 {eq}% < {need} → 长期是亏的" },
    },
  },

  handEval: {
    pickerLabel: "选择牌（5–7 张）",
    emptyTitle: "选 5 张或更多牌，判定牌型",
    emptyHint: "输入 7 张时，自动从中挑出最强的 5 张组合",
    bestFrom: "{n} 张里的最强牌型",
    rankNames: [
      "高牌", "一对", "两对", "三条", "顺子",
      "同花", "葫芦", "四条", "同花顺", "皇家同花顺",
    ],
    resultNames: [
      "高牌 🃏", "一对 1️⃣", "两对 ✌️", "三条 3️⃣", "顺子 ➡️",
      "同花 🌊", "葫芦 🏠", "四条 💎", "同花顺 🌟", "皇家同花顺 👑",
    ],
    axis: ["高牌", "一对", "同花", "四条", "皇家"],
  },

  starting: {
    pickerLabel: "选择你的 2 张底牌",
    emptyPrompt: "先选出你的 2 张底牌",
    unknownDesc: "很弱的一手牌",
    unknownAction: "通常弃牌",
    tierNames: ["🥇 第 1 层 — 顶级", "🥈 第 2 层 — 强牌", "🥉 第 3 层 — 可打", "⚠️ 第 4 层 — 边缘", "🚫 第 5 层 — 弱牌"],
    recommendedAction: "建议动作：",
    axis: ["顶级", "强牌", "可打", "边缘", "弱牌"],
    summaryTitle: "起手牌分层一览",
    summary: [
      { hands: "AA KK QQ JJ 10-10 AKs AKo", action: "任何位置都加注" },
      { hands: "AQs AJs A10s KQs KJs 99 88 AQo", action: "大多数位置加注" },
      { hands: "AJo KQo K10s QJs J10s 10-9s 77 A9s", action: "后位加注" },
      { hands: "66–55 A8s–A2s KJo QJo 同花连张", action: "后位择机进池" },
      { hands: "44–22 弱的非同花杂牌", action: "通常弃牌" },
    ],
    hands: {
      AA: { desc: "最强的起手牌。任何局面都加注", action: "永远加注 / 再加注（3bet）" },
      KK: { desc: "只需提防翻牌出 A", action: "永远加注 / 再加注" },
      QQ: { desc: "比 JJ 强，但别高估", action: "永远加注；深码时小心" },
      JJ: { desc: "提防翻牌出高张", action: "任何位置都加注" },
      "1010": { desc: "翻牌出高张时价值下降", action: "中后位加注，前位考虑跟注" },
      AKs: { desc: "最强的听牌型起手牌。把底池做大", action: "永远加注 / 再加注" },
      AKo: { desc: "比 AKs 弱，但仍是顶级牌", action: "永远加注；可以跟一次再加注" },
      AQs: { desc: "强牌；有位置时更值钱", action: "大多数位置加注" },
      AJs: { desc: "在 BTN/CO 很好，在 UTG 偏弱", action: "中后位加注，前位考虑跟注" },
      A10s: { desc: "顶级同花 A 之一", action: "后位加注，前位跟注" },
      KQs: { desc: "高同花 + 顺子听牌潜力", action: "大多数位置加注" },
      KJs: { desc: "强力的听牌型起手牌", action: "后位加注，前位跟注" },
      "99": { desc: "中对，提防出高张的翻牌", action: "大多数位置加注；深码时小心" },
      "88": { desc: "口袋对子，挖暗三条的潜力不错", action: "后位加注，前位考虑跟注" },
      AQo: { desc: "偏弱的非同花牌；位置很关键", action: "中后位加注" },
      AJo: { desc: "前位弱，后位强", action: "CO/BTN 加注，前位小心" },
      KQo: { desc: "最强的非同花连张", action: "后位加注，前位跟注或弃牌" },
      K10s: { desc: "同花 K，后位有力", action: "后位加注，前位弃牌" },
      QJs: { desc: "两头都能听的强听牌", action: "后位加注，深码时更值钱" },
      J10s: { desc: "最好的同花连张之一", action: "后位加注，前位看底池赔率跟注" },
      "109s": { desc: "强力同花连张", action: "后位加注 / 跟注" },
      "77": { desc: "挖暗三条的牌，提防高张", action: "后位加注，前位跟注" },
      A9s: { desc: "带同花潜力的同花 A", action: "后位加注" },
      "66": { desc: "挖暗三条；需要底池赔率", action: "后位跟注 / 加注，多人底池最好" },
      "55": { desc: "不中暗三条就没什么价值", action: "后位跟注，只进单次加注的底池" },
      A8s: { desc: "中等同花 A", action: "后位可打，前位弃牌" },
      A7s: { desc: "中等同花 A", action: "只在后位打" },
      A6s: { desc: "中等同花 A", action: "只在后位打" },
      A5s: { desc: "轮子顺 + A 阻断牌价值；最受欢迎的 3bet 诈唬牌", action: "只在后位打；隐含赔率是关键" },
      A4s: { desc: "带轮子顺听牌的同花 A", action: "只在后位打" },
      A3s: { desc: "同花 A 里垫底的一手", action: "只在 BTN/SB 打" },
      A2s: { desc: "轮子顺 + 坚果同花，但整体偏弱", action: "只在 BTN 打" },
      KJo: { desc: "有被压制的风险；只在后位打", action: "CO/BTN 加注，遇到再加注就弃" },
      QJo: { desc: "连接性一般；需要位置", action: "只在后位打" },
      "98s": { desc: "强力同花连张", action: "后位跟注 / 加注" },
      "87s": { desc: "不错的同花连张", action: "后位跟注" },
      "76s": { desc: "同花连张", action: "后位看底池赔率跟注" },
      "44": { desc: "不中暗三条几乎没价值", action: "只在底池赔率便宜时跟注" },
      "33": { desc: "只能挖暗三条；投机牌", action: "多人底池、便宜时才跟" },
      "22": { desc: "最小的口袋对子", action: "多人底池、便宜时才跟" },
      K10o: { desc: "非同花 K-10，偏弱", action: "偶尔从 BTN 打" },
      Q10o: { desc: "连接性差的非同花牌", action: "只在 BTN 打" },
      J10o: { desc: "非同花里还算可以，但容易被压制", action: "偶尔从 BTN 打" },
      Q10s: { desc: "强力的同花百老汇牌，有位置时打得好", action: "后位加注，前位看底池赔率跟注" },
      A10o: { desc: "边缘的非同花 A，容易被压制", action: "只在后位打" },
      "65s": { desc: "同花连张；要多人底池 / 隐含赔率", action: "后位跟注" },
      "54s": { desc: "小同花连张；投机牌", action: "后位跟注，便宜的多人底池" },
    },
  },

  spr: {
    effectiveStack: "有效筹码（你的）",
    potSize: "当前底池大小",
    caption: "SPR（筹码底池比）",
    stackDivPot: "筹码 ÷ 底池",
    zones: {
      low: {
        label: "低 SPR（已投入）",
        desc: "底池里已经有很大一部分筹码了。拿着顶对顶踢脚或更好的牌，可以考虑全下——在这里弃牌可能是错误。",
        actions: [["TPTK+", "考虑全下"], ["听牌", "必须看底池赔率"], ["弱牌", "谨慎弃牌"]],
      },
      mid: {
        label: "中 SPR（灵活）",
        desc: "这个区间适合打两对或更好的强牌。保护自己的筹码开始变得重要。",
        actions: [["两对+", "价值下注"], ["一对", "凭读牌判断"], ["听牌", "权衡风险和回报"]],
      },
      high: {
        label: "高 SPR（开始变深）",
        desc: "筹码开始变深。听牌和强的成手牌相对价值上升。",
        actions: [["暗三条+", "强势打"], ["听牌", "隐含赔率上升"], ["一对 / TPTK", "小心推进"]],
      },
      deep: {
        label: "极高 SPR（深码）",
        desc: "这是深码局。位置、听牌潜力和读懂对手范围的能力都非常重要。",
        actions: [["坚果牌", "可以下大注"], ["听牌", "隐含赔率极高"], ["弱的成手牌", "小心，容易被诈唬"]],
      },
    },
    legend: ["已投入", "灵活", "开始变深", "深码"],
  },

  m: {
    inputs: { stack: "你的筹码", bb: "大盲注", sb: "小盲注", ante: "前注（ante）" },
    players: "桌上人数：{v}",
    headsUp: "2（单挑）",
    orbitCaption: "一圈的成本（每轮盲注）",
    orbitFormula: "大盲 {bb} + 小盲 {sb} + 前注 {ante}×{players}",
    mCaption: "M值（Harrington 的 M）",
    zones: {
      dead: { name: "💀 死区", desc: "你必须立刻全下。已经没有等一手好牌的余地——拿到能打的最好的牌就推。", action: "现在就全下" },
      red: { name: "🔴 红区", desc: "你得尽快翻倍。用 push/fold 策略——好牌就推，其余弃掉。", action: "Push/fold" },
      orange: { name: "🟠 橙区", desc: "你的筹码在缩水。把范围收紧到只剩强牌，找机会 first-in 全下。", action: "收紧范围" },
      yellow: { name: "🟡 黄区", desc: "压力来了。你需要主动去积累筹码——好机会出现时打得激进一点。", action: "打得激进" },
      green: { name: "🟢 绿区", desc: "你的筹码很舒服。整套策略都能用——靠位置打法和诈唬把筹码做大。", action: "全套策略" },
    },
  },

  icm: {
    introStrong: "ICM（独立筹码模型，Independent Chip Model）",
    introRest: " 是一套把你锦标赛筹码换算成真实奖金价值的算法。就连 chip leader 的 ICM 价值也低于他的筹码占比，而短码的价值反而高于筹码占比。在决赛桌和钱圈（bubble）上做跟注 / 弃牌决定时，就用它。",
    numPlayers: "玩家人数",
    paidPlaces: "进钱名次",
    stacksTitle: "各玩家筹码量",
    total: "合计 {n}",
    decStack: "减少玩家 {n} 的筹码",
    stackInput: "玩家 {n} 的筹码量",
    incStack: "增加玩家 {n} 的筹码",
    prizesTitle: "奖金",
    decPrize: "减少第 {n} 名奖金",
    prizeInput: "第 {n} 名奖金",
    incPrize: "增加第 {n} 名奖金",
    currencyNote: "奖金用任何货币单位填都可以。",
    resultTitle: "ICM 结果",
    th: { player: "玩家", chips: "筹码", chipPct: "筹码 %", icmValue: "ICM 价值", icmPct: "ICM %", diff: "差额" },
    playerCell: "{medal} P{n}",
    diffPlus: "+差额",
    diffPlusNote: "ICM 价值高于筹码占比 → 短码保护区，避开掷硬币局面",
    diffMinus: "−差额",
    diffMinusNote: "ICM 价值低于筹码占比 → chip leader 的施压更划算",
    empty: "把筹码和奖金都设成大于零，就能看到 ICM 结果。",
  },

  pushfold: {
    ante: "前注（ante）",
    noAnte: "无前注",
    bbAnteOn: "大盲前注 开",
    table: "桌型",
    headsUp: "单挑",
    sixMax: "6 人桌",
    nineMax: "9 人桌",
    scenario: "局面",
    sbShove: "小盲位：推还是弃",
    bbCall: "大盲位：跟不跟全下",
    position: "位置 {hint}",
    firstInHint: "（first-in——前面全弃到你）",
    effectiveStack: "有效筹码：{v}",
    captionHuPush: "{stack}bb 时小盲位该推的牌",
    captionHuCall: "{stack}bb 时大盲位该跟全下的牌",
    captionMw: "{table} 人桌、{stack}bb，从 {pos} first-in 全下的范围",
    withAnte: "（含前注）",
    combosSuffix: " / {total} 个组合",
    legendPush: "推（全下）",
    legendCall: "跟注",
    legendFold: "弃牌",
    note: {
      strong1: "对角线 = 对子 · 右上 = 同花 · 左下 = 非同花",
      p1: "这张表按",
      strong2: "点数排序，不按牌力排序",
      p2: "，所以同一行里亮起和没亮的格子交替出现是正常的——AQo、KQo 和 QQ 挨在一起，却不是按强弱排的。A5s 在范围里而 A6s 不在，也是对的：A5s 能凑成",
      strong3: "轮子顺（A-2-3-4-5）",
      p3: "，这比踢脚小一点更值钱。",
    },
    cellTitle: "{hand} — {action}",
    cell: { push: "推", call: "跟注", fold: "弃牌" },
    huNote: {
      strong: "Nash 均衡，单挑（小盲位 vs 大盲位）",
      p1: "：假设小盲位只有推或弃两个选择。前注设置会给每位玩家加 0.125bb（相当于大盲前注，≈12.5%）。筹码越短范围越宽——而在约 3–4bb 以下，大盲位的正确跟注范围会",
      em: "宽于",
      p2: "小盲位的推注范围，原因是底池赔率。",
    },
    mwNote: {
      strong: "{table} 人桌 first-in 全下表",
      p1: "：前面的人全弃了，你要么推要么弃。这是一个",
      strong2: "纯 chip EV",
      p2: " 的 Nash 式均衡——身后玩家的跟注范围是同时求解的——并采用标准近似：被跟注的底池按与第一个跟注者单挑来结算（多人跟注的底池忽略不计）。身后剩的人越少（UTG → BTN → SB）、筹码越短、前注开启（每人 0.125bb）时，范围越宽。因为它是纯 chip EV，前位（UTG/MP）10bb 的范围会比常见的经验法则更紧（小对子弃掉）——实战中要按 ICM 和对手情况调整。",
    },
    readMore: "短码打法的基本功，请读我们的",
    shortStackLink: { slug: "holdem-short-stack", text: "短码策略指南" },
    readMoreEnd: "。",
  },

  icmGuide: {
    bubble: {
      badge: "ICM 指南",
      h2: "ICM 计算器怎么用——3 分钟看懂一个钱圈例子",
      intro: "假设桌上剩 4 个人，3 个进钱（正在钱圈上）。筹码分别是 60,000 / 40,000 / 30,000 / 20,000，奖金是 $500 / $300 / $200。把这些填进计算器，就能看到每个人的筹码占比和真实奖金价值（ICM）的对比：",
      th: { player: "玩家", chipPct: "筹码 %", icmPct: "ICM %", diff: "差额" },
      rows: [
        { player: "🥇 Chip leader", chip: "40.0%", icm: "33.3%", diff: "-6.7 个点", up: false },
        { player: "🥈 第 2", chip: "26.7%", icm: "27.2%", diff: "+0.6 个点", up: true },
        { player: "🥉 第 3", chip: "20.0%", icm: "22.9%", diff: "+2.9 个点", up: true },
        { player: "第 4（短码）", chip: "13.3%", icm: "16.6%", diff: "+3.3 个点", up: true },
      ],
      keyPoint: {
        text: "关键在这里：{b1}，差了 6.7 个点。因为赢下来也只拿冠军那一份钱，chip leader 从一次掷硬币里得到的奖金价值，比筹码数量看起来的要少。所以在钱圈上，leader 应该{b2}；而短码（13.3% 筹码 → 16.6% ICM）的价值高于他的筹码，应该{b3}，保住这份活下去的价值。",
        b1: "chip leader 的 ICM 价值（33.3%）低于他的筹码占比（40%）",
        b2: "对短码施压",
        b3: "避免不必要的全下跟注",
      },
    },
    deal: {
      badge: "分钱",
      h2: "ICM deal vs chip chop——剩下的奖池怎么分",
      intro: "现在剩 3 个人，正在谈分钱。筹码是 50% / 30% / 20%，剩余奖池 $1,500，两种分法差得很远：",
      th: { player: "玩家", chop: "Chip chop", icm: "ICM deal", diff: "差额" },
      rows: [
        { player: "🥇 Chip leader（50%）", chop: "$750", icm: "$618", diff: "-$132", up: false },
        { player: "🥈 第 2（30%）", chop: "$450", icm: "$485", diff: "+$35", up: true },
        { player: "🥉 短码（20%）", chop: "$300", icm: "$397", diff: "+$97", up: true },
      ],
      summary: {
        text: "chip chop 按筹码占比分钱，{b1}；ICM deal 反映的是每个人拿到各名次的概率，{b2}。上面这个例子里，短码按 chip chop 拿 $300，按 ICM deal 却能拿约 $397——{b3}。你是短码就要求 ICM deal；你是 leader 就提议 chip chop。",
        b1: "偏袒 chip leader",
        b2: "对短码更公平",
        b3: "多拿 $97",
      },
    },
  },

  guide: {
    badge: "工具",
    h2: "8 个德州扑克计算器怎么用",
    cards: [
      { title: "补牌计算器", body: "精确算出你的听牌在翻牌或转牌后成牌的概率。二四法则的速算值和精确值同时显示。" },
      { title: "底池赔率与隐含赔率", body: "用数学决定跟注还是弃牌。对手筹码深时，加上隐含赔率，判断会更准。" },
      { title: "牌型大小判定", body: "选牌就能看牌型。最多输入 7 张，自动挑出最强的 5 张组合。" },
      { title: "起手牌强度", body: "选出你的两张底牌，看它在 169 种起手牌里属于哪一层，以及按位置的建议动作。" },
      { title: "SPR（筹码底池比）", body: "筹码和底池的比值告诉你需要多强的牌。SPR 越低，越适合拿强牌把筹码投进去。" },
      { title: "锦标赛 M值", body: "Harrington 的 M 衡量你锦标赛筹码承受的压力。绿 / 黄 / 橙 / 红 / 死五个区，策略完全不同。" },
      { title: "ICM 计算器", body: "独立筹码模型把锦标赛筹码换算成真实的奖金价值——钱圈和决赛桌上的跟注 / 弃牌决定和分钱谈判都离不开它。" },
      { title: "Nash push/fold 图表", body: "按 Nash 均衡算出的 13×13 单挑图表：1–25bb 时哪些牌该 first-in 全下、哪些牌该跟。锦标赛后期必备。" },
    ],
  },

  faq: {
    badge: "常见问题",
    h2: "ICM 计算器和德州扑克计算器常见问题",
    q: "Q. {q}",
  },

  related: {
    badge: "深入学习",
    h2: "算明白之后，接着读这些指南",
    links: [
      { slug: "holdem-tournament", title: "锦标赛怎么运作", desc: "买入、赛制与 Day 1 全流程" },
      { slug: "holdem-equity", title: "扑克胜率 equity 详解", desc: "胜率、弃牌率与兑现率" },
      { slug: "holdem-pot-odds", title: "底池赔率怎么算", desc: "把跟注 / 弃牌变成一道算术题" },
      { slug: "holdem-outs", title: "补牌怎么数", desc: "各种听牌的补牌数和二四法则" },
      { slug: "holdem-probability", title: "德州扑克概率表", desc: "每一手牌背后的核心数字" },
      { slug: "holdem-starting-hands-chart", title: "起手牌表", desc: "按位置该打哪些牌" },
    ],
  },
};
